CREATE OR REPLACE FORCE EDITIONABLE VIEW "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" ("KEY_VALUE", "FIRST_NAME", "MIDDLE_NAME", "LAST_NAME", "DATE_OF_BIRTH", "PLACE_OF_BIRTH", "PERSON") AS 
  SELECT key_value
        ,first_name
        ,middle_name
        ,last_name
        ,date_of_birth
        ,place_of_birth
        ,person
    FROM dl_bordercontrol.fellow_passenger
;
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "JASPER_REPORTING";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSUPPORT";
  GRANT DELETE ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT MERGE VIEW ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."REP_VOA_FELLOW_PASSENGER_PREVIEW" TO "PORNRUKSA_S";
