CREATE MATERIALIZED VIEW "PIBICSDM2"."FW_USER_PIBICS" ("USER_ID", "USERNAME", "PASSWORD", "INITIALDATE", "EXPIREDATE", "EMAIL", "DISABLE", "USER_LEVEL", "USER_FLAG", "DEP_CODE", "UPD_USERID", "PERSON_ID", "LASTUPDATE", "TEL", "CHGPWDDATE", "PWDRPT", "MOBILE", "REMARK")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PIBICSDM" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_PIBICSDM" 
  REFRESH COMPLETE ON DEMAND NEXT null
  WITH PRIMARY KEY USING DEFAULT LOCAL ROLLBACK SEGMENT
  USING ENFORCED CONSTRAINTS DISABLE ON QUERY COMPUTATION DISABLE QUERY REWRITE
  AS SELECT "FW_USER"."USER_ID" "USER_ID","FW_USER"."USERNAME" "USERNAME","FW_USER"."PASSWORD" "PASSWORD","FW_USER"."INITIALDATE" "INITIALDATE","FW_USER"."EXPIREDATE" "EXPIREDATE","FW_USER"."EMAIL" "EMAIL","FW_USER"."DISABLE" "DISABLE","FW_USER"."USER_LEVEL" "USER_LEVEL","FW_USER"."USER_FLAG" "USER_FLAG","FW_USER"."DEP_CODE" "DEP_CODE","FW_USER"."UPD_USERID" "UPD_USERID","FW_USER"."PERSON_ID" "PERSON_ID","FW_USER"."LASTUPDATE" "LASTUPDATE","FW_USER"."TEL" "TEL","FW_USER"."CHGPWDDATE" "CHGPWDDATE","FW_USER"."PWDRPT" "PWDRPT","FW_USER"."MOBILE" "MOBILE","FW_USER"."REMARK" "REMARK" FROM "PIBICS"."FW_USER"@"PIBICS_PROD" "FW_USER";
   COMMENT ON MATERIALIZED VIEW "PIBICSDM2"."FW_USER_PIBICS"  IS 'snapshot table for snapshot PIBICSDM2.FW_USER_PIBICS';
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_C_SNAP$_221XPKFW_USER" ON "PIBICSDM2"."FW_USER_PIBICS" ("USER_ID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FW_USER_PIBICS" TO "BIOSAADM";
