CREATE TABLE "PIBICSDM2"."ACTIONLOG" 
   (	"ACTLOG_SEQNO" NUMBER, 
	"ACTLOG_SYSTEM" VARCHAR2(5 CHAR), 
	"ACTPGM_ID" VARCHAR2(100 CHAR), 
	"ACTPGM_TYPE" CHAR(1 CHAR), 
	"ACTPGM_LINK" VARCHAR2(250 CHAR), 
	"ACTPGM_NM" VARCHAR2(250 CHAR), 
	"ACTLOG_PARENT" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ACTIONLOG" ADD CONSTRAINT "ACTIONLOG_PK" PRIMARY KEY ("ACTPGM_ID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ACTIONLOG_PK" ON "PIBICSDM2"."ACTIONLOG" ("ACTPGM_ID") 
  ;
