CREATE TABLE "PIBICSDM2"."ADDRESS" 
   (	"ADDRESS_SEQNO" NUMBER, 
	"ADR" VARCHAR2(200 CHAR), 
	"ADRNO" VARCHAR2(20 CHAR), 
	"MOO" VARCHAR2(20 CHAR), 
	"SOI" VARCHAR2(200 CHAR), 
	"ROAD" VARCHAR2(200 CHAR), 
	"TMB_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"ZIPCODE" CHAR(5 CHAR), 
	"TELNO" VARCHAR2(60 CHAR), 
	"FAXNO" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ADDRESS_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ADDRESS_PK" ON "PIBICSDM2"."ADDRESS" ("ADDRESS_SEQNO") 
  ;
