CREATE TABLE "PIBICSDM2"."ALG_GENUSERID" 
   (	"NUMBER_CHAR" CHAR(2 CHAR), 
	"MONTH_CHARACTER" CHAR(1 CHAR), 
	"DAY_CHARACTER" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ALG_GENUSERID" ADD CONSTRAINT "ALG_GENUSERID_PK" PRIMARY KEY ("NUMBER_CHAR")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ALG_GENUSERID_PK" ON "PIBICSDM2"."ALG_GENUSERID" ("NUMBER_CHAR") 
  ;
