CREATE TABLE "PIBICSDM2"."ANU" 
   (	"ANU_SEQNO" NUMBER(5,0), 
	"SECTIONID" NUMBER(5,0), 
	"ANUNM" VARCHAR2(100 CHAR), 
	"ANUDESC" VARCHAR2(250 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"ANUTYPE" VARCHAR2(5 CHAR), 
	"ANU_NO" CHAR(2 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ANU" ADD CONSTRAINT "ANU_PK" PRIMARY KEY ("ANU_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ANU_PK" ON "PIBICSDM2"."ANU" ("ANU_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "DL_STAGING" WITH GRANT OPTION;
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ANU" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ANU" TO "BIOSAADM";
