CREATE TABLE "PIBICSDM2"."ANU_LOG" 
   (	"ANU_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"ANU_SEQNO" NUMBER(5,0), 
	"SECTIONID" NUMBER(5,0), 
	"ANUNM" VARCHAR2(50 CHAR), 
	"ANUDESC" VARCHAR2(250 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"ANUTYPE" VARCHAR2(5 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ANU_LOG" ADD CONSTRAINT "ANU_LOG_PK" PRIMARY KEY ("ANU_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ANU_LOG_PK" ON "PIBICSDM2"."ANU_LOG" ("ANU_LOG_SEQNO") 
  ;
