CREATE TABLE "PIBICSDM2"."ARRESTPRO" 
   (	"ART_SEQNO" NUMBER, 
	"DPT_SEQNO" NUMBER, 
	"OFD_SEQNO" NUMBER, 
	"PRODTE" DATE, 
	"PROUSRID" VARCHAR2(60 CHAR), 
	"CHARGE" VARCHAR2(200 CHAR), 
	"EVIDENCE" VARCHAR2(250 CHAR), 
	"DEPTNM" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO" ADD CONSTRAINT "ARRESTPRO_PK" PRIMARY KEY ("ART_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO" ADD FOREIGN KEY ("DPT_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPORTEE" ("DPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO" ADD FOREIGN KEY ("OFD_SEQNO")
	  REFERENCES "PIBICSDM2"."OFFENDER" ("OFD_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARRESTPRO_PK" ON "PIBICSDM2"."ARRESTPRO" ("ART_SEQNO") 
  ;
