CREATE TABLE "PIBICSDM2"."ARRESTPRO_LOG" 
   (	"ART_SEQNO" NUMBER, 
	"DPT_SEQNO" NUMBER, 
	"OFD_SEQNO" NUMBER, 
	"PRODTE" DATE, 
	"PROUSRID" VARCHAR2(60 CHAR), 
	"CHARGE" VARCHAR2(200 CHAR), 
	"EVIDENCE" VARCHAR2(250 CHAR), 
	"DEPTNM" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ART_LOG_SEQNO" NUMBER, 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"DPT_LOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO_LOG" ADD CONSTRAINT "ARRESTPRO_LOG_PK" PRIMARY KEY ("ART_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO_LOG" ADD FOREIGN KEY ("DPT_LOG_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPORTEE_LOG" ("DPT_LOG_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO_LOG" ADD FOREIGN KEY ("DPT_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPORTEE" ("DPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARRESTPRO_LOG" ADD FOREIGN KEY ("OFD_SEQNO")
	  REFERENCES "PIBICSDM2"."OFFENDER" ("OFD_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARRESTPRO_LOG_PK" ON "PIBICSDM2"."ARRESTPRO_LOG" ("ART_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ARRESTPRO_LOG" TO "BIOSAADM";
