CREATE TABLE "PIBICSDM2"."ARS_MASTERSTATISTIC" 
   (	"ID_CODE" VARCHAR2(20 CHAR), 
	"NAME" VARCHAR2(50 CHAR), 
	"ID_SEQ" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ARS_MASTERSTATISTIC" ADD CONSTRAINT "ARS_MASTERSTATISTIC_PK" PRIMARY KEY ("ID_CODE")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARS_MASTERSTATISTIC_PK" ON "PIBICSDM2"."ARS_MASTERSTATISTIC" ("ID_CODE") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ARS_MASTERSTATISTIC" TO "BIOSAADM";
