CREATE TABLE "PIBICSDM2"."ARS_TMP" 
   (	"ID" VARCHAR2(50 CHAR), 
	"FNAME" VARCHAR2(250 CHAR), 
	"LNAME" VARCHAR2(250 CHAR), 
	"DOCNO" VARCHAR2(50 CHAR), 
	"YEARDATA" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" VARCHAR2(5 CHAR), 
	"ACPLS_SEQNO" VARCHAR2(10 CHAR), 
	"ACBH_SEQNO" VARCHAR2(10 CHAR), 
	"ACPV_SEQNO" VARCHAR2(10 CHAR), 
	"DETACHEDDOCASPLS_SEQNO" VARCHAR2(10 CHAR), 
	"HEAD_AMP_OLD" VARCHAR2(250 CHAR), 
	"AMP_SEQNO" VARCHAR2(10 CHAR), 
	"HEAD_PV_OLD" VARCHAR2(250 CHAR), 
	"PV_SEQNO" VARCHAR2(5 CHAR), 
	"FILENAME_PATH1" VARCHAR2(250 CHAR), 
	"FILENAME_PATH2" VARCHAR2(250 CHAR), 
	"FILENAME_BLOB1" BLOB, 
	"FILENAME_BLOB2" BLOB, 
	"FILENAME_DUMMY1" VARCHAR2(250 CHAR), 
	"FILENAME_DUMMY2" VARCHAR2(250 CHAR), 
	"FLAG" CHAR(1 CHAR)
   ) ;
  ;
  ;
