CREATE TABLE "PIBICSDM2"."ARS_LEAVEPLACE_LOG" 
   (	"LEAVEPLACELOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LEAVEPLACE_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"LEAVEPLACE_DESC" VARCHAR2(2500 CHAR), 
	"LEAVECONV_SEQNO" NUMBER, 
	"LEAVEFLIGHTNO" VARCHAR2(15 CHAR), 
	"LEAVE_DATE" DATE, 
	"NOTICEPLS_SEQNO" NUMBER, 
	"NOTICEPLS_NO" VARCHAR2(20 CHAR), 
	"NOTICEPLS_DATE" DATE, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NPOLISBH_SEQNO" NUMBER, 
	"NPOLISPV_SEQNO" NUMBER, 
	"FLAG" CHAR(1 CHAR), 
	"ALIENCERTLOG_SEQNO" NUMBER, 
	"LETTERFORM" VARCHAR2(2500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ARS_LEAVEPLACE_LOG" ADD CONSTRAINT "ARS_LEAVEPLACE_LOG_PK" PRIMARY KEY ("LEAVEPLACELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_LEAVEPLACE_LOG" ADD CONSTRAINT "ARS_LEAVEPLACE_LOG_R02" FOREIGN KEY ("LEAVECONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_LEAVEPLACE_LOG" ADD CONSTRAINT "ARS_LEAVEPLACE_LOG_R01" FOREIGN KEY ("ALIENCERT_SEQNO")
	  REFERENCES "PIBICSDM2"."ARS_ALIENCERT" ("ALIENCERT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARS_LEAVEPLACE_LOG_PK" ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" ("LEAVEPLACELOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ARS_LEAVEPLACE_LOG" TO "BIOSAADM";
