CREATE TABLE "PIBICSDM2"."ARS_RENEWALCERT" 
   (	"RENEWALCERT_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"RENEWTYPE" VARCHAR2(50 CHAR), 
	"RENEW_DATE" DATE, 
	"RENEWEXP_DATE" DATE, 
	"NPOLIS_SEQNO" NUMBER, 
	"REPT_DATE" DATE, 
	"REPTNO" VARCHAR2(20 CHAR), 
	"REPTBOOKNO" VARCHAR2(15 CHAR), 
	"AMP_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NPOLISPV_SEQNO" NUMBER, 
	"NPOLISBH_SEQNO" NUMBER, 
	"FLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT" ADD CONSTRAINT "ARS_RENEWALCERT_PK" PRIMARY KEY ("RENEWALCERT_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT" ADD FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT" ADD FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT" ADD FOREIGN KEY ("ALIENCERT_SEQNO")
	  REFERENCES "PIBICSDM2"."ARS_ALIENCERT" ("ALIENCERT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARS_RENEWALCERT_PK" ON "PIBICSDM2"."ARS_RENEWALCERT" ("RENEWALCERT_SEQNO") 
  ;
