CREATE TABLE "PIBICSDM2"."ARS_CHGCITIZEN_LOG" 
   (	"CHGCITIZENLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"CHGCITIZEN_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"GAZETIENO" VARCHAR2(100 CHAR), 
	"GAZETIEBOOKNO" VARCHAR2(100 CHAR), 
	"GAZETIEAS" VARCHAR2(1500 CHAR), 
	"GAZETIE_DATE" DATE, 
	"NOTICEPLS_SEQNO" NUMBER, 
	"NOTICEPLS_DATE" DATE, 
	"NOTICEPLS_NO" VARCHAR2(1500 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NPOLISBH_SEQNO" NUMBER, 
	"NPOLISPV_SEQNO" NUMBER, 
	"FLAG" CHAR(1 CHAR), 
	"ALIENCERTLOG_SEQNO" NUMBER, 
	"CITIZENTYPE" CHAR(1 CHAR), 
	"GAINTYPE" CHAR(1 CHAR), 
	"GAINTYPEO_DESC" VARCHAR2(1000 CHAR), 
	"COPYRIGHTNO" VARCHAR2(100 CHAR), 
	"COPYRIGHT_DATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."ARS_CHGCITIZEN_LOG" ADD CONSTRAINT "ARS_CHGCITIZENLOG_PK" PRIMARY KEY ("CHGCITIZENLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_CHGCITIZEN_LOG" ADD CONSTRAINT "ARS_CHGCITIZENLOG_R01" FOREIGN KEY ("ALIENCERT_SEQNO")
	  REFERENCES "PIBICSDM2"."ARS_ALIENCERT" ("ALIENCERT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARS_CHGCITIZENLOG_PK" ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" ("CHGCITIZENLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ARS_CHGCITIZEN_LOG" TO "BIOSAADM";
