CREATE TABLE "PIBICSDM2"."ARS_RENEWALCERT_LOG" 
   (	"RENEWALCERTLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"RENEWALCERT_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"RENEWTYPE" VARCHAR2(50 CHAR), 
	"RENEW_DATE" DATE, 
	"RENEWEXP_DATE" DATE, 
	"NPOLIS_SEQNO" NUMBER, 
	"REPT_DATE" DATE, 
	"REPTNO" VARCHAR2(20 CHAR), 
	"REPTBOOKNO" VARCHAR2(15 CHAR), 
	"AMP_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NPOLISPV_SEQNO" NUMBER, 
	"NPOLISBH_SEQNO" NUMBER, 
	"FLAG" CHAR(1 CHAR), 
	"ALIENCERTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT_LOG" ADD CONSTRAINT "ARS_RENEWALCERT_LOG_PK" PRIMARY KEY ("RENEWALCERTLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT_LOG" ADD FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT_LOG" ADD FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."ARS_RENEWALCERT_LOG" ADD FOREIGN KEY ("ALIENCERT_SEQNO")
	  REFERENCES "PIBICSDM2"."ARS_ALIENCERT" ("ALIENCERT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ARS_RENEWALCERT_LOG_PK" ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" ("RENEWALCERTLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ARS_RENEWALCERT_LOG" TO "BIOSAADM";
