CREATE TABLE "PIBICSDM2"."ATTACHDLY" 
   (	"ATTACHDLY_SEQNO" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"IODATE" TIMESTAMP (6), 
	"FLIGHTNO" VARCHAR2(20 CHAR), 
	"AIRLINENM" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NUMREC" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ATTACHDLY" ADD CONSTRAINT "ATTACHDLY_PK" PRIMARY KEY ("ATTACHDLY_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ATTACHDLY_PK" ON "PIBICSDM2"."ATTACHDLY" ("ATTACHDLY_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ATTACHDLY" TO "BIOSAADM";
