CREATE TABLE "PIBICSDM2"."ATTACHDLYLOG" 
   (	"ATTACHDLYLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"ATTACHDLY_SEQNO" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"IODATE" TIMESTAMP (6), 
	"FLIGHTNO" VARCHAR2(20 CHAR), 
	"AIRLINENM" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NUMREC" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."ATTACHDLYLOG" ADD CONSTRAINT "ATTACHDLYLOG_PK" PRIMARY KEY ("ATTACHDLYLOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ATTACHDLYLOG_PK" ON "PIBICSDM2"."ATTACHDLYLOG" ("ATTACHDLYLOG_SEQNO") 
  ;
