CREATE TABLE "PIBICSDM2"."BAD_ROWS" 
   (	"ROW_ID" ROWID, 
	"ORACLE_ERROR_CODE" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BAD_ROWS" TO "BIOSAADM";
