CREATE TABLE "PIBICSDM2"."BANK" 
   (	"BANK_CODE" VARCHAR2(2 CHAR), 
	"BANK_NAME" VARCHAR2(50 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"BANK_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BANK" ADD CONSTRAINT "BANK_PK" PRIMARY KEY ("BANK_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BANK" ADD CONSTRAINT "BANK_U01" UNIQUE ("BANK_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BANK" ADD CONSTRAINT "BANK_U02" UNIQUE ("BANK_NAME")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."BANK_PK" ON "PIBICSDM2"."BANK" ("BANK_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BANK_U01" ON "PIBICSDM2"."BANK" ("BANK_CODE") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BANK_U02" ON "PIBICSDM2"."BANK" ("BANK_NAME") 
  ;
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BANK" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BANK" TO "BIOSAADM";
