CREATE TABLE "PIBICSDM2"."BATCHLOG$REORG" 
   (	"BATCHLOGNO" NUMBER, 
	"BATCH_SRC" VARCHAR2(8), 
	"FILE_TYPE" VARCHAR2(8), 
	"FILE_NAME" VARCHAR2(50), 
	"FILE_SIZE" NUMBER, 
	"TOTALROW" NUMBER, 
	"PRROW" NUMBER, 
	"ERRROW" NUMBER, 
	"STARTPROCESS" TIMESTAMP (6), 
	"ENDPROCESS" TIMESTAMP (6), 
	"STATUS" CHAR(1), 
	"CREUSR" VARCHAR2(32), 
	"CREDTE" DATE, 
	"TFSTATUS" CHAR(1), 
	"TOTALINS" NUMBER, 
	"TOTALUPD" NUMBER, 
	"TOTALDEL" NUMBER, 
	"NOTE" VARCHAR2(250), 
	"DATAFILEERROR" VARCHAR2(250), 
	"TRANSFERDTE" DATE
   ) ;
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BATCHLOG$REORG" TO "BIOSAADM";
