CREATE TABLE "PIBICSDM2"."BATCH_LOG" 
   (	"BATCH_LOGNO" NUMBER, 
	"BATCH_SRC" VARCHAR2(8 CHAR), 
	"FILE_TYPE" VARCHAR2(8 CHAR), 
	"FILE_NAME" VARCHAR2(50 CHAR), 
	"FILE_SIZE" NUMBER, 
	"TOTALROW" NUMBER, 
	"PRROW" NUMBER, 
	"ERRROW" NUMBER, 
	"STARTPROCESS" DATE, 
	"ENDPROCESS" DATE, 
	"STATUS" CHAR(1 CHAR), 
	"CREUSR" VARCHAR2(32 CHAR), 
	"CREDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."BATCH_LOG" ADD CONSTRAINT "PK_BATCH_LOG" PRIMARY KEY ("BATCH_LOGNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_BATCH_LOG" ON "PIBICSDM2"."BATCH_LOG" ("BATCH_LOGNO") 
  ;
