CREATE TABLE "PIBICSDM2"."BKLMESSAGE" 
   (	"MSEQNO" NUMBER, 
	"MESSAGEDESC" VARCHAR2(400 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."WLMESSAGE_PK" ON "PIBICSDM2"."BKLMESSAGE" ("MSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BKLMESSAGE" TO "BIOSAADM";
