CREATE TABLE "PIBICSDM2"."BLIMPREASON" 
   (	"REASON_SEQNO" NUMBER, 
	"REASONCD" CHAR(4 CHAR), 
	"REASONTNM" VARCHAR2(60 CHAR), 
	"REASONENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"OVERSTAY_BEGIN_AMT" NUMBER, 
	"OVERSTAY_BEGIN_UNIT" VARCHAR2(1 CHAR), 
	"PROHIBIT_AMT" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BLIMPREASON" ADD CONSTRAINT "BLIMPREASON_PK" PRIMARY KEY ("REASON_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."BLIMPREASON_PK" ON "PIBICSDM2"."BLIMPREASON" ("REASON_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BLIMPREASON_U01" ON "PIBICSDM2"."BLIMPREASON" ("REASONCD") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BLIMPREASON_U02" ON "PIBICSDM2"."BLIMPREASON" ("REASONTNM") 
  ;
