CREATE TABLE "PIBICSDM2"."BOICOUNTRY" 
   (	"COUNTRY_ID" VARCHAR2(50 CHAR), 
	"CONTINENT_ID" VARCHAR2(50 CHAR), 
	"ZONE_ID" VARCHAR2(50 CHAR), 
	"COUNTRY_NAME" VARCHAR2(200 CHAR), 
	"LEAST_INCOME" VARCHAR2(50 CHAR), 
	"CODE90" VARCHAR2(50 CHAR), 
	"NAME90" VARCHAR2(200 CHAR), 
	"SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BOICOUNTRY" TO "BIOSAADM";
