CREATE TABLE "PIBICSDM2"."BPDEPTDEFAULTLOG" 
   (	"BPDLOGSEQNO" NUMBER, 
	"BPDSEQNO" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"BPDOCSEQNO" NUMBER, 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"CHKHISTCARD" CHAR(1 CHAR), 
	"CHKDETEN" CHAR(1 CHAR), 
	"CHKTHAIBL" CHAR(1 CHAR), 
	"CHKIMGSTS" CHAR(1 CHAR), 
	"CHKFGPSTS" CHAR(1 CHAR), 
	"CHKFGPCARDSTS" CHAR(1 CHAR), 
	"CHKONESTOP" CHAR(1 CHAR), 
	"CHKADDCARD" CHAR(1 CHAR), 
	"BPTYPECARD" VARCHAR2(19 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDATE" TIMESTAMP (6), 
	"LOGUSER" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BPDEPTDEFAULTLOG" ADD CONSTRAINT "BPDEPTDEFAULTLOG_PK" PRIMARY KEY ("BPDLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BPDEPTDEFAULTLOG" ADD CONSTRAINT "BPDEPTDEFAULTLOG_R03" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPDEPTDEFAULTLOG" ADD CONSTRAINT "BPDEPTDEFAULTLOG_R04" FOREIGN KEY ("BPDOCSEQNO")
	  REFERENCES "PIBICSDM2"."BPDOCTYPE" ("BPDOCSEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."BPDEPTDEFAULTLOG_PK" ON "PIBICSDM2"."BPDEPTDEFAULTLOG" ("BPDLOGSEQNO") 
  ;
