CREATE TABLE "PIBICSDM2"."BPDEPTBYNATION" 
   (	"BPDNSEQNO" NUMBER, 
	"BPDSEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"BPDOCSEQNO" NUMBER, 
	"TYPEPERMIT" CHAR(1 CHAR), 
	"PERMITDAYS" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BPDEPTBYNATION" ADD CONSTRAINT "BPDEPTBYNATION_PK" PRIMARY KEY ("BPDNSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BPDEPTBYNATION" ADD CONSTRAINT "BPDEPTBYNATION_R01" FOREIGN KEY ("BPDSEQNO")
	  REFERENCES "PIBICSDM2"."BPDEPTDEFAULT" ("BPDSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPDEPTBYNATION" ADD CONSTRAINT "BPDEPTBYNATION_R02" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPDEPTBYNATION" ADD CONSTRAINT "BPDEPTBYNATION_R03" FOREIGN KEY ("BPDOCSEQNO")
	  REFERENCES "PIBICSDM2"."BPDOCTYPE" ("BPDOCSEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."BPDEPTBYNATION_PK" ON "PIBICSDM2"."BPDEPTBYNATION" ("BPDNSEQNO") 
  ;
