CREATE TABLE "PIBICSDM2"."BPFINGERPRINT" 
   (	"BPFGPSEQNO" NUMBER, 
	"BPCARDSEQNO" NUMBER, 
	"FGPTYPESEQNO" NUMBER, 
	"FGPSTS" CHAR(1 CHAR), 
	"FGPLOCATION" VARCHAR2(50 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BPFINGERPRINT" ADD CONSTRAINT "BPFINGERPRINT_PK" PRIMARY KEY ("BPFGPSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BPFINGERPRINT" ADD CONSTRAINT "BPFINGERPRINT_R02" FOREIGN KEY ("FGPTYPESEQNO")
	  REFERENCES "PIBICSDM2"."FINGERPRINTTYPE" ("FGPTYPESEQNO") ENABLE;
  CREATE INDEX "PIBICSDM2"."BPFG_BPCARDSEQNO_IDX" ON "PIBICSDM2"."BPFINGERPRINT" ("BPCARDSEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BPFINGERPRINT_PK" ON "PIBICSDM2"."BPFINGERPRINT" ("BPFGPSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BPFINGERPRINT" TO "BIOSAADM";
