CREATE TABLE "PIBICSDM2"."BPFINGERPRINTLOG" 
   (	"BPFGPLOGSEQNO" NUMBER, 
	"BPCARDLOGSEQNO" NUMBER, 
	"BPFGPSEQNO" NUMBER, 
	"BPCARDSEQNO" NUMBER, 
	"FGPTYPESEQNO" NUMBER, 
	"FGPSTS" CHAR(1 CHAR), 
	"FGPLOCATION" VARCHAR2(50 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDATE" TIMESTAMP (6), 
	"LOGUSER" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BPFINGERPRINTLOG" ADD CONSTRAINT "BPFINGERPRINTLOG_PK" PRIMARY KEY ("BPFGPLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BPFINGERPRINTLOG" ADD CONSTRAINT "BPFINGERPRINTLOG_R02" FOREIGN KEY ("FGPTYPESEQNO")
	  REFERENCES "PIBICSDM2"."FINGERPRINTTYPE" ("FGPTYPESEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."BPFINGERPRINTLOG_PK" ON "PIBICSDM2"."BPFINGERPRINTLOG" ("BPFGPLOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BPFINGERPRINTLOG" TO "BIOSAADM";
