CREATE TABLE "PIBICSDM2"."BPINOUT" 
   (	"BPINOUTSEQNO" NUMBER, 
	"BPPERSONSEQNO" NUMBER, 
	"BPCARDSEQNO" NUMBER, 
	"BPCARDPERSONSEQNO" NUMBER, 
	"BPCD" VARCHAR2(30 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"INOUTDTE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"BPDOCSEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"TFAMILYNM" VARCHAR2(100 CHAR), 
	"TFIRSTNM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"PERMITDTE" DATE, 
	"ISUCARDDTE" DATE, 
	"EXPCARDDTE" DATE, 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"IMGSTS" CHAR(1 CHAR), 
	"IMGINOUT" BLOB, 
	"FGPSTS" CHAR(1 CHAR), 
	"FGPLOCATION" VARCHAR2(100 CHAR), 
	"INTYPE" CHAR(1 CHAR), 
	"SAVETYPE" CHAR(1 CHAR), 
	"CHKHISTCARD" CHAR(1 CHAR), 
	"RESULTHISTCARD" CHAR(1 CHAR), 
	"CHKDETEN" CHAR(1 CHAR), 
	"RESULTDETEN" CHAR(1 CHAR), 
	"DETENPERSON" VARCHAR2(20 CHAR), 
	"CHKTHAIBL" CHAR(1 CHAR), 
	"RESULTTHAIBL" CHAR(1 CHAR), 
	"THAIBLPERSON" VARCHAR2(20 CHAR), 
	"CHKWLCD" CHAR(1 CHAR), 
	"WLCD" VARCHAR2(20 CHAR), 
	"FLAGFINES" CHAR(1 CHAR), 
	"FINES_SEQNO" NUMBER, 
	"REMARK" VARCHAR2(1000 CHAR), 
	"AGE" NUMBER, 
	"HEIGHT" NUMBER, 
	"CONVREGNO" VARCHAR2(100 CHAR), 
	"ELSNDXNM" VARCHAR2(100 CHAR), 
	"EFSNDXNM" VARCHAR2(100 CHAR), 
	"EMSNDXNM" VARCHAR2(100 CHAR), 
	"TLSNDXNM" VARCHAR2(100 CHAR), 
	"TFSNDXNM" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUTSEQNO_PK" PRIMARY KEY ("BPINOUTSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUT_R01" FOREIGN KEY ("BPPERSONSEQNO")
	  REFERENCES "PIBICSDM2"."BPPERSON" ("BPPERSONSEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUT_R02" FOREIGN KEY ("BPCARDSEQNO")
	  REFERENCES "PIBICSDM2"."BPCARD" ("BPCARDSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUT_R04" FOREIGN KEY ("BPDOCSEQNO")
	  REFERENCES "PIBICSDM2"."BPDOCTYPE" ("BPDOCSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUT_R05" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."BPINOUT" ADD CONSTRAINT "BPINOUT_R06" FOREIGN KEY ("FINES_SEQNO")
	  REFERENCES "PIBICSDM2"."FS_FINES" ("FINES_SEQNO") ENABLE;
  CREATE INDEX "PIBICSDM2"."BPINOUT_BIRTHDTE_IDX" ON "PIBICSDM2"."BPINOUT" ("BIRTHDTE") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_BPCARDSEQNO_IDX" ON "PIBICSDM2"."BPINOUT" ("BPCARDSEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_BPCD_IDX" ON "PIBICSDM2"."BPINOUT" ("BPCD") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_BRPERSONSEQNO_IDX" ON "PIBICSDM2"."BPINOUT" ("BPPERSONSEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_CARDTYPE_IDX" ON "PIBICSDM2"."BPINOUT" ("CARDTYPE") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_COUNT_SEQNO_IDX" ON "PIBICSDM2"."BPINOUT" ("COUNT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_CREATE_BY_IDX" ON "PIBICSDM2"."BPINOUT" ("CREATE_BY") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_CREATE_DATE_IDX" ON "PIBICSDM2"."BPINOUT" (TO_CHAR("CREATE_DATE",'YYYYMMDD')) 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_DEPT_SEQNO_IDX" ON "PIBICSDM2"."BPINOUT" ("DEPT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_EFAMILYNM_IDX" ON "PIBICSDM2"."BPINOUT" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_EFIRSTNM_IDX" ON "PIBICSDM2"."BPINOUT" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_EMIDDLENM_IDX" ON "PIBICSDM2"."BPINOUT" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_INOUTDTE_IDX" ON "PIBICSDM2"."BPINOUT" (TO_CHAR("INOUTDTE",'YYYYMMDD')) 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_PERMITDTE_IDX" ON "PIBICSDM2"."BPINOUT" (TO_CHAR("PERMITDTE",'YYYYMMDD')) 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_TFAMILYNM_IDX" ON "PIBICSDM2"."BPINOUT" ("TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."BPINOUT_TFIRSTNM_IDX" ON "PIBICSDM2"."BPINOUT" ("TFIRSTNM") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."BPINOUTSEQNO_PK" ON "PIBICSDM2"."BPINOUT" ("BPINOUTSEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000300844C00023$$" ON "PIBICSDM2"."BPINOUT" (
  ;
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."BPINOUT" TO "BIOSAADM";
