CREATE TABLE "PIBICSDM2"."CARDTYPE_LOG" 
   (	"CARDTYPE_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"CARDTYPE_SEQNO" NUMBER, 
	"CARDTYPE" VARCHAR2(60 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."CARDTYPE_LOG" ADD CONSTRAINT "CARDTYPE_LOG_PK" PRIMARY KEY ("CARDTYPE_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CARDTYPE_LOG_PK" ON "PIBICSDM2"."CARDTYPE_LOG" ("CARDTYPE_LOG_SEQNO") 
  ;
