CREATE TABLE "PIBICSDM2"."CARKIND" 
   (	"KINDCODE" CHAR(2 CHAR), 
	"KINDDESC" VARCHAR2(40 CHAR), 
	"UPDUSR" VARCHAR2(10 CHAR), 
	"UPDDTE" DATE, 
	"SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."CARKIND_PK" ON "PIBICSDM2"."CARKIND" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CARKIND" TO "BIOSAADM";
