CREATE TABLE "PIBICSDM2"."CARKIND" 
   (	"KINDCODE" CHAR(2 CHAR), 
	"KINDDESC" VARCHAR2(40 CHAR), 
	"UPDUSR" VARCHAR2(10 CHAR), 
	"UPDDTE" DATE, 
	"SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."CARKIND_PK" ON "PIBICSDM2"."CARKIND" ("SEQNO") 
  ;
