CREATE TABLE "PIBICSDM2"."CARPROVINCE" 
   (	"PROVINCECD" CHAR(3 CHAR), 
	"PROVINCETNM" VARCHAR2(60 CHAR), 
	"PROVINCEENM" VARCHAR2(60 CHAR), 
	"REGCD" CHAR(2 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE, 
	"SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."CARPROVINCE" ADD CONSTRAINT "CARPROVINCE_PK" PRIMARY KEY ("PROVINCECD")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CARPROVINCE_PK" ON "PIBICSDM2"."CARPROVINCE" ("PROVINCECD") 
  ;
