CREATE TABLE "PIBICSDM2"."CARTYPE" 
   (	"TYPECODE" CHAR(2 CHAR), 
	"TYPEDESC" VARCHAR2(85 CHAR), 
	"UPDUSR" VARCHAR2(10 CHAR), 
	"UPDDTE" DATE, 
	"SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."CARTYPE_PK" ON "PIBICSDM2"."CARTYPE" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CARTYPE" TO "BIOSAADM";
