CREATE TABLE "PIBICSDM2"."CHNGVISA_REASONDYN" 
   (	"SEQNO" NUMBER, 
	"REASON_SEQNO" NUMBER, 
	"DOC_SEQNO" NUMBER, 
	"CHKDOC" CHAR(1 CHAR), 
	"LAW_SEQNO" NUMBER, 
	"CHKLAW" CHAR(1 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"DOC_ORDER" NUMBER, 
	"LAW_ORDER" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."CHNGVISA_REASONDYN_PK" ON "PIBICSDM2"."CHNGVISA_REASONDYN" ("SEQNO") 
  ;
