CREATE TABLE "PIBICSDM2"."CITY" 
   (	"STATECD" CHAR(2 CHAR), 
	"CITYCD" CHAR(3 CHAR), 
	"CITYTNM" VARCHAR2(60 CHAR), 
	"CITYENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE, 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."CITY" ADD CONSTRAINT "CITYCD_STATECD_PK" PRIMARY KEY ("CITYCD", "STATECD")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."CITY" ADD CONSTRAINT "STATECD_FK" FOREIGN KEY ("STATECD")
	  REFERENCES "PIBICSDM2"."STATE" ("STATECD") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CITYCD_STATECD_PK" ON "PIBICSDM2"."CITY" ("CITYCD", "STATECD") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CITY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CITY" TO "BIOSAADM";
