CREATE TABLE "PIBICSDM2"."CITYLOG" 
   (	"CITYLOGID" NUMBER(*,0), 
	"ACTFLAG" VARCHAR2(255 CHAR), 
	"CHKPOINTNO" VARCHAR2(255 CHAR), 
	"CITYCD" VARCHAR2(255 CHAR), 
	"CITYENM" VARCHAR2(255 CHAR), 
	"CITYTNM" VARCHAR2(255 CHAR), 
	"LOGDTE" DATE, 
	"LOGFLAG" VARCHAR2(255 CHAR), 
	"LOGUSERID" VARCHAR2(255 CHAR), 
	"STATECD" VARCHAR2(255 CHAR), 
	"UPDDTE" DATE, 
	"UPDUSR" VARCHAR2(255 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."CITYLOG" ADD PRIMARY KEY ("CITYLOGID")
  USING INDEX  ENABLE;
  ;
