CREATE TABLE "PIBICSDM2"."CJT_UWANT" 
   (	"CARD_ID" VARCHAR2(9 CHAR), 
	"UWANT_NO" VARCHAR2(25 CHAR), 
	"UWANT_D" DATE, 
	"UWANT_OFF" VARCHAR2(5 CHAR), 
	"POLICE" VARCHAR2(50 CHAR), 
	"POSITION" VARCHAR2(70 CHAR), 
	"UN_CAUSE" VARCHAR2(2 CHAR), 
	"UPROC_NO" VARCHAR2(20 CHAR), 
	"UPROC_Y" VARCHAR2(4 CHAR), 
	"UPROC_OFF" VARCHAR2(5 CHAR), 
	"UPROC_D" DATE, 
	"UPD_ID" VARCHAR2(13 CHAR), 
	"UPD_DATE" DATE, 
	"CREUSR" CHAR(6 CHAR), 
	"CREDTE" DATE, 
	"CJTUSEQNO" NUMBER, 
	"CJTUPROCESS" CHAR(1 CHAR)
   ) ;
  CREATE INDEX "PIBICSDM2"."CJTU_CARD_ID_IDX" ON "PIBICSDM2"."CJT_UWANT" ("CARD_ID") 
  ;
CREATE INDEX "PIBICSDM2"."CJTU_CJTUPROCESS_IDX" ON "PIBICSDM2"."CJT_UWANT" ("CJTUPROCESS") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."CJTUSEQNO_PK" ON "PIBICSDM2"."CJT_UWANT" ("CJTUSEQNO") 
  ;
