CREATE TABLE "PIBICSDM2"."CJTTRANSFER" 
   (	"CJTSEQNO" NUMBER, 
	"TRANSFERDTE" DATE, 
	"CJTTIMES" NUMBER, 
	"TRANSFERLOGDTE" DATE, 
	"CJTTYPE" CHAR(1 CHAR), 
	"CJTADD" NUMBER DEFAULT 0, 
	"CJTUPD" NUMBER DEFAULT 0, 
	"CJTDEL" NUMBER DEFAULT 0, 
	"CJTFAIL" NUMBER DEFAULT 0, 
	"CJTTOTAL" NUMBER DEFAULT 0
   ) ;
  ALTER TABLE "PIBICSDM2"."CJTTRANSFER" ADD CONSTRAINT "CJTTRANSFER_PK" PRIMARY KEY ("CJTSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CJTTRANSFER_PK" ON "PIBICSDM2"."CJTTRANSFER" ("CJTSEQNO") 
  ;
