CREATE TABLE "PIBICSDM2"."CONVFORDEPT" 
   (	"CFDSEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."CONVFORDEPT" ADD CONSTRAINT "CONVFORDEPT_PK" PRIMARY KEY ("CFDSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CONVFORDEPT_PK" ON "PIBICSDM2"."CONVFORDEPT" ("CFDSEQNO") 
  ;
