CREATE TABLE "PIBICSDM2"."CONVEYANCELOG" 
   (	"TRAVCD" CHAR(4 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVTNM" VARCHAR2(60 CHAR), 
	"CONVENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"CONVEYANCELOGID" NUMBER(5,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."CONVEYANCELOG" ADD CONSTRAINT "CONVEYANCELOG_PK" PRIMARY KEY ("CONVEYANCELOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CONVEYANCELOG_PK" ON "PIBICSDM2"."CONVEYANCELOG" ("CONVEYANCELOGID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CONVEYANCELOG" TO "BIOSAADM";
