CREATE TABLE "PIBICSDM2"."CONVFORDEPT" 
   (	"CFDSEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."CONVFORDEPT" ADD CONSTRAINT "CONVFORDEPT_PK" PRIMARY KEY ("CFDSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CONVFORDEPT_PK" ON "PIBICSDM2"."CONVFORDEPT" ("CFDSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CONVFORDEPT" TO "BIOSAADM";
