CREATE TABLE "PIBICSDM2"."CORONA_VIRUS" 
   (	"DATE_OF_ENTRY" DATE, 
	"DEPARTMENT_NAME" VARCHAR2(200), 
	"NATION" VARCHAR2(50), 
	"FLIGHT_NO" VARCHAR2(50), 
	"PROVINCE" VARCHAR2(100), 
	"IN_NUM" NUMBER, 
	"OUT_NUM" NUMBER, 
	"LOAD_DATE" DATE, 
	"AREA" VARCHAR2(50)
   ) ;
