CREATE TABLE "PIBICSDM2"."COUNTRYLOG" 
   (	"COUNTCD" CHAR(3 CHAR), 
	"COUNTTNM" VARCHAR2(60 CHAR), 
	"COUNTENM" VARCHAR2(60 CHAR), 
	"NATIONTNM" VARCHAR2(60 CHAR), 
	"NATIONENM" VARCHAR2(60 CHAR), 
	"CONTINENTCD" CHAR(2 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"ABBCOUNT" VARCHAR2(3 CHAR), 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"COUNTRYLOGID" NUMBER(5,0), 
	"VISAFLAG" VARCHAR2(1 CHAR), 
	"HEALTHCTL" VARCHAR2(1 CHAR), 
	"SALARY" NUMBER, 
	"COUNTCHNNM" NVARCHAR2(60)
   ) ;
  ALTER TABLE "PIBICSDM2"."COUNTRYLOG" ADD CONSTRAINT "COUNTRYLOG_PK" PRIMARY KEY ("COUNTRYLOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."COUNTRYLOG_PK" ON "PIBICSDM2"."COUNTRYLOG" ("COUNTRYLOGID") 
  ;
