CREATE TABLE "PIBICSDM2"."COUNTRY_HISTORY" 
   (	"COUNTCD" CHAR(3 CHAR), 
	"COUNTTNM" VARCHAR2(60 CHAR), 
	"COUNTENM" VARCHAR2(60 CHAR), 
	"NATIONTNM" VARCHAR2(60 CHAR), 
	"NATIONENM" VARCHAR2(60 CHAR), 
	"CONTINENTCD" CHAR(2 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"ABBCOUNT" VARCHAR2(3 CHAR), 
	"VISAFLAG" VARCHAR2(1 CHAR), 
	"HEALTHCTL" VARCHAR2(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."COUNTRY_HISTORY" ADD CONSTRAINT "COUNTCD_PK" PRIMARY KEY ("COUNTCD")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."COUNTRY_HISTORY" ADD CONSTRAINT "CONTINENTCD_FK" FOREIGN KEY ("CONTINENTCD")
	  REFERENCES "PIBICSDM2"."CONTINENT" ("CONTINENTCD") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."COUNTCD_PK" ON "PIBICSDM2"."COUNTRY_HISTORY" ("COUNTCD") 
  ;
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."COUNTRY_HISTORY" TO "BIOSAADM";
