CREATE TABLE "PIBICSDM2"."CREW_MEMBER_CONTRL" 
   (	"SEQNO" NUMBER, 
	"MEMBER_SEQNO" NUMBER, 
	"DEPT_SEQNO" VARCHAR2(40 CHAR), 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT NULL
   ) ;
  ALTER TABLE "PIBICSDM2"."CREW_MEMBER_CONTRL" ADD CONSTRAINT "CREW_MEMBER_CONTRL_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CREW_MEMBER_CONTRL_PK" ON "PIBICSDM2"."CREW_MEMBER_CONTRL" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CREW_MEMBER_CONTRL" TO "BIOSAADM";
