CREATE TABLE "PIBICSDM2"."CREW_MEMBER" 
   (	"SEQNO" NUMBER, 
	"USER_ID" VARCHAR2(20 CHAR), 
	"PWD" VARCHAR2(20 CHAR), 
	"CONV_SEQNO" VARCHAR2(20 CHAR), 
	"COMPANYNM" VARCHAR2(50 CHAR), 
	"ADDR" VARCHAR2(200 CHAR), 
	"ROAD" VARCHAR2(50 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"POSTCODE" VARCHAR2(5 CHAR), 
	"TEL" VARCHAR2(20 CHAR), 
	"FAX" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(50 CHAR), 
	"CONTROL_SEQNO" NUMBER, 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT NULL, 
	"MEMBERNM" VARCHAR2(250 CHAR), 
	"NOTE" VARCHAR2(500 CHAR), 
	"CDEPT_SEQNO" NUMBER, 
	"PWDMD5" VARCHAR2(100 CHAR), 
	"REGIST_DATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."CREW_MEMBER" ADD CONSTRAINT "CREW_MEMBER_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CREW_MEMBER_PK" ON "PIBICSDM2"."CREW_MEMBER" ("SEQNO") 
  ;
