CREATE TABLE "PIBICSDM2"."CRS_PROCESSINGISSUE" 
   (	"PROCESSINGISSUE_SEQNO" NUMBER, 
	"PROCESSINGNO" VARCHAR2(20 CHAR), 
	"PROCESSING_DATE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"PROCESSNM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"PROCESSING_DETAIL" CLOB, 
	"ISSUE_FLAG" CHAR(1 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"OTHERNM" VARCHAR2(100 CHAR), 
	"AGE" NUMBER, 
	"RESCERTTYPE_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."CRS_PROCESSINGISSUE" ADD CONSTRAINT "CRS_PROCESSINGISSUE_PK" PRIMARY KEY ("PROCESSINGISSUE_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_PROCESSINGISSUE" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CRS_PROCESSINGISSUE_PK" ON "PIBICSDM2"."CRS_PROCESSINGISSUE" ("PROCESSINGISSUE_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000300969C00017$$" ON "PIBICSDM2"."CRS_PROCESSINGISSUE" (
  ;
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."CRS_PROCESSINGISSUE" TO "BIOSAADM";
