CREATE TABLE "PIBICSDM2"."CRS_TM18LOG" 
   (	"TM18_SEQNO" NUMBER, 
	"TM18NO" VARCHAR2(20 CHAR), 
	"RESCERTTYPE_SEQNO" NUMBER, 
	"DOC_DATE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"ARSNO" VARCHAR2(10 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"OTHERNM" VARCHAR2(100 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"BTH_TAMBON" VARCHAR2(50 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"AGE" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"HEIGHT" NUMBER, 
	"MARK" VARCHAR2(60 CHAR), 
	"HOMETOWN_STATE" VARCHAR2(60 CHAR), 
	"HOMETOWNCOUNT_SEQNO" NUMBER, 
	"TADDRNO" VARCHAR2(20 CHAR), 
	"TROAD" VARCHAR2(100 CHAR), 
	"TTMB_SEQNO" NUMBER, 
	"TAMP_SEQNO" NUMBER, 
	"TPV_SEQNO" NUMBER, 
	"TZIPCODE" VARCHAR2(5 CHAR), 
	"VISATYPE_SEQNO" NUMBER, 
	"IN_DATE" DATE, 
	"CONV_SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PASSPORT_DATE" DATE, 
	"PASSPORTISSUE" VARCHAR2(60 CHAR), 
	"VISABYEMBASSY" VARCHAR2(60 CHAR), 
	"VISANO" VARCHAR2(20 CHAR), 
	"VISA_DATE" DATE, 
	"APPVSTS" CHAR(1 CHAR), 
	"APPOINT_DATE" DATE, 
	"REMARK" VARCHAR2(100 CHAR), 
	"CERTOFRESIDENCE_SEQNO" NUMBER, 
	"PROCESSINGISSUE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"BTH_AMPUR" VARCHAR2(50 CHAR), 
	"BTH_PROVICE" VARCHAR2(50 CHAR), 
	"BTH_COUNTRY" NUMBER, 
	"RACE_SEQNO" NUMBER, 
	"PASSPORTEXP_DATE" DATE, 
	"TM18LOG_SEQNO" NUMBER, 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"LOG_FLAG" VARCHAR2(1 CHAR), 
	"LOG_DATE" DATE, 
	"OCC_DETAIL" VARCHAR2(60 CHAR), 
	"RACEOTHER" VARCHAR2(200 CHAR), 
	"IMGTM18" BLOB, 
	"IMGSTS" CHAR(1 CHAR), 
	"FGPTM18" VARCHAR2(100 CHAR), 
	"FGPSTS" CHAR(1 CHAR), 
	"FGPREMARK" VARCHAR2(1000 CHAR), 
	"TEL" VARCHAR2(100 CHAR), 
	"CHKRUNNO" CHAR(1 CHAR), 
	"TM18RUNNO" NUMBER, 
	"TM18YEAR" CHAR(4 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_PK" PRIMARY KEY ("TM18LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_TAMBON_FK1" FOREIGN KEY ("TTMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_OCCUPATION_FK1" FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_PROVINCE_FK1" FOREIGN KEY ("TPV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_VISATYPE_FK1" FOREIGN KEY ("VISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_CONVEYANCE_FK1" FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_COUNTRY_FK2" FOREIGN KEY ("HOMETOWNCOUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_COUNTRY_FK1" FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_COUNTRY_FK3" FOREIGN KEY ("RACE_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_COUNTRY_FK4" FOREIGN KEY ("BTH_COUNTRY")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_CRS_CERTOFRES_FK1" FOREIGN KEY ("CERTOFRESIDENCE_SEQNO")
	  REFERENCES "PIBICSDM2"."CRS_CERTOFRESIDENCE" ("CERTOFRESIDENCE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."CRS_TM18LOG" ADD CONSTRAINT "CRS_TM18LOG_AMPUR_FK1" FOREIGN KEY ("TAMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CRS_TM18LOG_PK" ON "PIBICSDM2"."CRS_TM18LOG" ("TM18LOG_SEQNO") 
  ;
  ;
