CREATE TABLE "PIBICSDM2"."CRS_PETTIONLOG" 
   (	"PETTION_SEQNO" NUMBER, 
	"PETTION_DATE" DATE, 
	"PETTION_NO" VARCHAR2(20 CHAR), 
	"CREATE_BY" VARCHAR2(60 CHAR), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(60 CHAR), 
	"UPDATE_DATE" DATE, 
	"VERSION" NUMBER, 
	"PETTIONLOG_SEQNO" NUMBER, 
	"LOG_FLAG" VARCHAR2(1 CHAR), 
	"LOG_DATE" DATE, 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"PETTION_DETAIL" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."CRS_PETTIONLOG" ADD CONSTRAINT "CRS_PETITIONLOG_PK" PRIMARY KEY ("PETTIONLOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."CRS_PETITIONLOG_PK" ON "PIBICSDM2"."CRS_PETTIONLOG" ("PETTIONLOG_SEQNO") 
  ;
