CREATE TABLE "PIBICSDM2"."DATAUSED" 
   (	"PERSONID" VARCHAR2(20 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."DATAUSED_PK" ON "PIBICSDM2"."DATAUSED" ("PERSONID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DATAUSED" TO "BIOSAADM";
