CREATE TABLE "PIBICSDM2"."DELAY" 
   (	"DELAY_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVNM" VARCHAR2(250 CHAR), 
	"NATIONCD" NUMBER, 
	"CONVREGNO" VARCHAR2(50 CHAR), 
	"CONVOWNER" VARCHAR2(250 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"INDTE" TIMESTAMP (6), 
	"INAMOUNT_S" NUMBER, 
	"INAMOUNT_T" NUMBER, 
	"OUTDTE" TIMESTAMP (6), 
	"OUTAMOUNT_S" NUMBER, 
	"OUTAMOUNT_T" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD CONSTRAINT "DELAY_PK" PRIMARY KEY ("DELAY_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD FOREIGN KEY ("NATIONCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."DELAY_PK" ON "PIBICSDM2"."DELAY" ("DELAY_SEQNO") 
  ;
