CREATE TABLE "PIBICSDM2"."DELAY" 
   (	"DELAY_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVNM" VARCHAR2(250 CHAR), 
	"NATIONCD" NUMBER, 
	"CONVREGNO" VARCHAR2(50 CHAR), 
	"CONVOWNER" VARCHAR2(250 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"INDTE" TIMESTAMP (6), 
	"INAMOUNT_S" NUMBER, 
	"INAMOUNT_T" NUMBER, 
	"OUTDTE" TIMESTAMP (6), 
	"OUTAMOUNT_S" NUMBER, 
	"OUTAMOUNT_T" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD CONSTRAINT "DELAY_PK" PRIMARY KEY ("DELAY_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DELAY" ADD FOREIGN KEY ("NATIONCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."DELAY_PK" ON "PIBICSDM2"."DELAY" ("DELAY_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DELAY" TO "BIOSAADM";
