CREATE TABLE "PIBICSDM2"."DEPARTMENT_LOG" 
   (	"DEPT_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"DEPT_SEQNO" NUMBER, 
	"DEPTCD" CHAR(5 CHAR), 
	"DEPTLEVEL" CHAR(1 CHAR), 
	"DEPTENM" VARCHAR2(60 CHAR), 
	"DEPTTNM" VARCHAR2(60 CHAR), 
	"ADDR" VARCHAR2(250 CHAR), 
	"ADDNO" VARCHAR2(60 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"ZIPCODE" CHAR(5 CHAR), 
	"TELNO" VARCHAR2(60 CHAR), 
	"FAX" VARCHAR2(60 CHAR), 
	"EMAIL" VARCHAR2(2000 CHAR), 
	"URLDEPT" VARCHAR2(100 CHAR), 
	"ADEPTTYPE" CHAR(1 CHAR), 
	"CONV_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"CONVCD" CHAR(4 CHAR), 
	"ABBRNM" VARCHAR2(50 CHAR), 
	"REL_CODE" NUMBER, 
	"ORG_CODE" VARCHAR2(8 CHAR), 
	"DETAINEE_FLAG" CHAR(1 CHAR), 
	"CHECKPOINT" CHAR(1 CHAR), 
	"CASINO_FLAG" CHAR(1 CHAR), 
	"FIELD_DEFAULT" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."DEPARTMENT_LOG" ADD CONSTRAINT "DEPARTMENT_LOG_PK" PRIMARY KEY ("DEPT_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPARTMENT_LOG" ADD CONSTRAINT "DEPARTMENT_LOG_R03" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPARTMENT_LOG" ADD CONSTRAINT "DEPARTMENT_LOG_R02" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPARTMENT_LOG" ADD CONSTRAINT "DEPARTMENT_LOG_R01" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPARTMENT_LOG" ADD CONSTRAINT "DEPARTMENT_LOG_R04" FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."DEPARTMENT_LOG_PK" ON "PIBICSDM2"."DEPARTMENT_LOG" ("DEPT_LOG_SEQNO") 
  ;
