CREATE TABLE "PIBICSDM2"."DEPARTMENT_BK" 
   (	"DEPT_SEQNO" NUMBER, 
	"DEPTCD" CHAR(5 CHAR), 
	"DEPTLEVEL" CHAR(1 CHAR), 
	"DEPTENM" VARCHAR2(60 CHAR), 
	"DEPTTNM" VARCHAR2(60 CHAR), 
	"ADDR" VARCHAR2(250 CHAR), 
	"ADDNO" VARCHAR2(60 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"ZIPCODE" CHAR(5 CHAR), 
	"TELNO" VARCHAR2(60 CHAR), 
	"FAX" VARCHAR2(60 CHAR), 
	"EMAIL" VARCHAR2(60 CHAR), 
	"URLDEPT" VARCHAR2(100 CHAR), 
	"ADEPTTYPE" CHAR(1 CHAR), 
	"CONV_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"CONVCD" CHAR(4 CHAR), 
	"ABBRNM" VARCHAR2(50 CHAR), 
	"REL_CODE" NUMBER, 
	"ORG_CODE" VARCHAR2(8 CHAR), 
	"DETAINEE_FLAG" CHAR(1 CHAR), 
	"OLD_DEPTCD" CHAR(5 CHAR), 
	"OLD_DEPTENM" VARCHAR2(60 CHAR), 
	"OLD_DEPTTNM" VARCHAR2(60 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DEPARTMENT_BK" TO "BIOSAADM";
