CREATE TABLE "PIBICSDM2"."DEPARTMENT_MAPPING_FN" 
   (	"SEQ_ORA" NUMBER, 
	"SEQ_SQLSERVER" NUMBER, 
	"NAME_SQLSERVER" VARCHAR2(200 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."DEPARTMENT_MAPPING_FN_PK" ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" ("SEQ_SQLSERVER") 
  ;
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DEPARTMENT_MAPPING_FN" TO "BIOSAADM";
