CREATE TABLE "PIBICSDM2"."DEPORTEE_LOG" 
   (	"DPT_SEQNO" NUMBER, 
	"DPTNO" VARCHAR2(15 CHAR), 
	"DPTDTE" DATE, 
	"DPTUSRID" VARCHAR2(60 CHAR), 
	"DOCID" NUMBER(5,0), 
	"DOCNO" VARCHAR2(20 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(30 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" NUMBER, 
	"ISSDTE" DATE, 
	"ISSPLACE" VARCHAR2(100 CHAR), 
	"EXPDTE" DATE, 
	"DEPTDPT_SEQNO" NUMBER, 
	"DEPTFWDNOTE" VARCHAR2(250 CHAR), 
	"REASONDPT_SEQNO" NUMBER, 
	"DPTREASONNOTE" VARCHAR2(250 CHAR), 
	"DEPTPER" VARCHAR2(60 CHAR), 
	"DEPTDOCNO" VARCHAR2(20 CHAR), 
	"DEPTDOCDTE" DATE, 
	"BEHAVIOR" VARCHAR2(250 CHAR), 
	"METHOD" CHAR(1 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"INDTE" DATE, 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"COUNTCD" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"SECTION_SEQNO" NUMBER, 
	"TM6NO" CHAR(7 CHAR), 
	"CONV_SEQNO" NUMBER, 
	"IMGDPT" BLOB, 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"DPT_LOG_SEQNO" NUMBER, 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"INOUT_SEQNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISATYPE_SEQNO" NUMBER, 
	"VISAEXPDTE" DATE, 
	"PERMIT_SEQNO" NUMBER, 
	"PERMITDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD PRIMARY KEY ("DPT_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD CONSTRAINT "DEPORTEE_LOG_R01" FOREIGN KEY ("DEPTDPT_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPARTMENTDPT" ("DEPTDPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD FOREIGN KEY ("SECTION_SEQNO")
	  REFERENCES "PIBICSDM2"."SECTION" ("SECTION_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD CONSTRAINT "DEPORTEE_LOG_R02" FOREIGN KEY ("REASONDPT_SEQNO")
	  REFERENCES "PIBICSDM2"."REASONDPT" ("REASONDPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD FOREIGN KEY ("NATIONCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."DEPORTEE_LOG" ADD FOREIGN KEY ("COUNTCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_C00207450" ON "PIBICSDM2"."DEPORTEE_LOG" ("DPT_LOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301022C00038$$" ON "PIBICSDM2"."DEPORTEE_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DEPORTEE_LOG" TO "BIOSAADM";
