CREATE TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" 
   (	"RELEASEDETAINEE_SEQNO" NUMBER, 
	"RELEASE_SEQNO" NUMBER, 
	"DETENRECORD_SEQNO" NUMBER, 
	"RELEASETYPE_SEQNO" NUMBER, 
	"ISSUEDEPT_TO" NUMBER, 
	"FLIGHTNO" VARCHAR2(10 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"AIRLINENM" VARCHAR2(100 CHAR), 
	"PENALTYRATE" VARCHAR2(20 CHAR), 
	"REMARK" VARCHAR2(200 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"RELEASE_NO" VARCHAR2(50 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(50 CHAR), 
	"RELEASEDETAINEE_LOG_SEQNO" NUMBER, 
	"RELEASE_LOG_SEQNO" NUMBER, 
	"DETENRECORD_LOG_SEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(10 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(10 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD PRIMARY KEY ("RELEASEDETAINEE_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD FOREIGN KEY ("DETENRECORD_SEQNO")
	  REFERENCES "PIBICSDM2"."DRS_DETENRECORD" ("DETENRECORD_SEQNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD FOREIGN KEY ("RELEASETYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."DRS_RELEASETYPE" ("RELEASETYPE_SEQNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD FOREIGN KEY ("RELEASE_LOG_SEQNO")
	  REFERENCES "PIBICSDM2"."DRS_RELEASE_LOG" ("RELEASE_LOG_SEQNO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RELEASEDETAINEE_LOG" ADD FOREIGN KEY ("DETENRECORD_LOG_SEQNO")
	  REFERENCES "PIBICSDM2"."DRS_DETENRECORD_LOG" ("DETENRECORD_LOG_SEQNO") ON DELETE CASCADE ENABLE;
  ;
