CREATE TABLE "PIBICSDM2"."DRS_RECVTYPE" 
   (	"RECVTYPE_SEQNO" NUMBER, 
	"RECVTYPECD" CHAR(1 CHAR), 
	"RECVDESC" VARCHAR2(100 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."DRS_RECVTYPE" ADD PRIMARY KEY ("RECVTYPE_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RECVTYPE" ADD CONSTRAINT "DRS_RECVTYPE_U01" UNIQUE ("RECVDESC")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."DRS_RECVTYPE" ADD UNIQUE ("RECVTYPECD")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."DRS_RECVTYPE_U01" ON "PIBICSDM2"."DRS_RECVTYPE" ("RECVDESC") 
  ;
  ;
  ;
