CREATE TABLE "PIBICSDM2"."DRS_RECVTYPE_LOG" 
   (	"RECVTYPE_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"RECVTYPE_SEQNO" NUMBER, 
	"RECVTYPECD" CHAR(1 CHAR), 
	"RECVDESC" VARCHAR2(100 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."DRS_RECVTYPE_LOG" ADD CONSTRAINT "DRS_RECVTYPE_LOG_PK" PRIMARY KEY ("RECVTYPE_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."DRS_RECVTYPE_LOG_PK" ON "PIBICSDM2"."DRS_RECVTYPE_LOG" ("RECVTYPE_LOG_SEQNO") 
  ;
