CREATE TABLE "PIBICSDM2"."DW_DIM_NATION" 
   (	"COUNT_SEQNO" NUMBER, 
	"COUNTCD" CHAR(3 CHAR), 
	"COUNTTNM" VARCHAR2(60 CHAR), 
	"COUNTENM" VARCHAR2(60 CHAR), 
	"NATIONTNM" VARCHAR2(60 CHAR), 
	"NATIONENM" VARCHAR2(60 CHAR), 
	"CONTINENTCD" CHAR(2 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"ABBCOUNT" VARCHAR2(3 CHAR), 
	"VISAFLAG" VARCHAR2(1 CHAR), 
	"HEALTHCTL" VARCHAR2(1 CHAR), 
	"CONTINENT_SEQNO" NUMBER, 
	"RPT_SORT" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DW_DIM_NATION" TO "BIOSAADM";
