CREATE TABLE "PIBICSDM2"."DW_DIM_CONVEYANCE" 
   (	"CONV_SEQNO" NUMBER, 
	"CONVCD" CHAR(4 CHAR), 
	"TRAVCD" CHAR(4 CHAR), 
	"CONVTNM" VARCHAR2(60 CHAR), 
	"CONVENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."DW_DIM_CONVEYANCE" TO "BIOSAADM";
