CREATE TABLE "PIBICSDM2"."DW_FACT_INOUT_STAT" 
   (	"IO_SEQNO" NUMBER(*,0), 
	"INOUTDTE" VARCHAR2(10 CHAR), 
	"INOUT_D" NUMBER(*,0), 
	"MONTH_SEQNO" NUMBER(*,0), 
	"INOUT_Y" NUMBER(*,0), 
	"CARDTYPE" CHAR(1 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"COUNT_SEQNO" NUMBER(*,0), 
	"DEPT_SEQNO" NUMBER(*,0), 
	"DEPT1_SEQNO" NUMBER(*,0), 
	"DEPT2_SEQNO" NUMBER(*,0), 
	"DEPT3_SEQNO" NUMBER(*,0), 
	"CONV_SEQNO" NUMBER(*,0), 
	"VISATYPE_SEQNO" NUMBER(*,0), 
	"INOUT_STAT" NUMBER
   ) ;
