CREATE TABLE "PIBICSDM2"."EF_CHKTRAVEL" 
   (	"ICC_CARDNO" VARCHAR2(30 CHAR), 
	"BPASSTYPE" CHAR(1 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"DATEIO" TIMESTAMP (6), 
	"DEPTIO_SEQNO" NUMBER, 
	"TFIRSTNM" VARCHAR2(100 CHAR), 
	"TFAMILYNM" VARCHAR2(100 CHAR), 
	"TMIDDLENM" VARCHAR2(100 CHAR), 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"EF_CHKTRAVEL_HIST_SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."EF_TRAVEL_PK" ON "PIBICSDM2"."EF_CHKTRAVEL" ("ICC_CARDNO") 
  ;
