CREATE TABLE "PIBICSDM2"."EF_DETENPERSON" 
   (	"IDCNO" VARCHAR2(20 CHAR), 
	"DEPT_SEQNODTE" NUMBER, 
	"DTETYPE_SEQNO" VARCHAR2(5 CHAR), 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"TFIRSTNM" VARCHAR2(100 CHAR), 
	"TFAMILYNM" VARCHAR2(100 CHAR), 
	"TMIDDLENM" VARCHAR2(100 CHAR), 
	"GENDER" CHAR(1 CHAR), 
	"BIRTHDATE" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"ALLEGATION" NUMBER, 
	"SENDDEPT_SEQNO" NUMBER, 
	"EF_DETENPERSONHIST_SEQNO" NUMBER, 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EF_DETENPERSON" TO "BIOSAADM";
