CREATE TABLE "PIBICSDM2"."EF_TRC_LOSTLOG" 
   (	"LOG_DATE" TIMESTAMP (6), 
	"ORG_CODE" VARCHAR2(5 CHAR), 
	"ORG_NAME" VARCHAR2(200 CHAR), 
	"RECEIVE_DATE" VARCHAR2(8 CHAR), 
	"CAR_FLAG" CHAR(1 CHAR), 
	"RETURN_DATE" VARCHAR2(8 CHAR), 
	"TRC01_OFF_PROV" CHAR(3 CHAR), 
	"TRC01_OFF_BR" CHAR(2 CHAR), 
	"TRC01_PLATE" CHAR(6 CHAR), 
	"TRC01_PREV_OFF_PROV" CHAR(3 CHAR), 
	"TRC01_PREV_OFF_BR" CHAR(2 CHAR), 
	"TRC01_PREV_PLATE" CHAR(6 CHAR), 
	"TRC01_NUMBODY" VARCHAR2(30 CHAR), 
	"TRC01_OCC_NO" NUMBER, 
	"TRC01_OCC_YYYY" CHAR(4 CHAR), 
	"TRC01_OCC_MM" CHAR(2 CHAR), 
	"TRC01_OCC_DD" CHAR(2 CHAR), 
	"TRC01_OWN_PID" VARCHAR2(13 CHAR), 
	"TRC01_OWN_TITLE" CHAR(3 CHAR), 
	"TRC01_OWN_NAME" VARCHAR2(100 CHAR), 
	"TRC01_OWN_SNAME" VARCHAR2(100 CHAR), 
	"TRC01_OWN_ADDR" VARCHAR2(100 CHAR), 
	"TRC01_OWN_AUMP" CHAR(2 CHAR), 
	"TRC01_OWN_PROV" CHAR(3 CHAR), 
	"TRC01_OWN_ZIP" CHAR(5 CHAR), 
	"TRC01_OWN_DETAIL" VARCHAR2(100 CHAR), 
	"TRC01_REG_YYYY" CHAR(4 CHAR), 
	"TRC01_REG_MM" CHAR(2 CHAR), 
	"TRC01_REG_DD" CHAR(2 CHAR), 
	"TRC01_TAX_YYYY" CHAR(4 CHAR), 
	"TRC01_TAX_MM" CHAR(2 CHAR), 
	"TRC01_TAX_DD" CHAR(2 CHAR), 
	"TRC01_HOLD_ST" CHAR(1 CHAR), 
	"TRC01_NOTE_ST" CHAR(1 CHAR), 
	"TRC06_OFF_PROV_CHK" CHAR(3 CHAR), 
	"TRC06_ROUTE" CHAR(1 CHAR), 
	"TRC06_KIND" CHAR(2 CHAR), 
	"TRC06_TYPE_TRF" CHAR(1 CHAR), 
	"TRC06_SIZE" CHAR(1 CHAR), 
	"TRC06_WHEEL" CHAR(2 CHAR), 
	"TRC06_FUEL" CHAR(1 CHAR), 
	"TRC06_SEQ_NO" CHAR(3 CHAR), 
	"TRC06_OWN_ST" VARCHAR2(30 CHAR), 
	"TRC06_OFF_BR" CHAR(2 CHAR), 
	"TRC06_OFF_PROV_RCV" CHAR(3 CHAR), 
	"TRC06_OFF_BR_RCV" CHAR(2 CHAR), 
	"TRC06_PLATE" CHAR(6 CHAR), 
	"TRC06_SUB_KIND" CHAR(2 CHAR), 
	"TRC06_TYPE_TRC" CHAR(1 CHAR), 
	"TRC06_TYPE_MODE" CHAR(1 CHAR), 
	"TRC06_NUMENG" VARCHAR2(30 CHAR), 
	"TRC06_BRAND_CAR" CHAR(3 CHAR), 
	"TRC06_MODEL_CAR" VARCHAR2(30 CHAR), 
	"TRC06_NUMBODY" VARCHAR2(30 CHAR)
   ) ;
  CREATE INDEX "PIBICSDM2"."EFTRC_LOGDTE_IDX" ON "PIBICSDM2"."EF_TRC_LOSTLOG" (TO_CHAR("LOG_DATE",'yyyymmddhh24miss')) 
  ;
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EF_TRC_LOSTLOG" TO "BIOSAADM";
