CREATE TABLE "PIBICSDM2"."EVISA_PWD" 
   (	"USERID" VARCHAR2(90), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PWD" VARCHAR2(90), 
	"STATUS" CHAR(3), 
	"WARNING" VARCHAR2(750), 
	"AGENT_SEQNO" NUMBER
   ) ;
