CREATE TABLE "PIBICSDM2"."EXP_PIBICS" 
   (	"PP10PPNO" VARCHAR2(9 CHAR), 
	"PPTHFNM" VARCHAR2(100 CHAR), 
	"PPTHLNM" VARCHAR2(100 CHAR), 
	"PPENFNM" VARCHAR2(100 CHAR), 
	"PPENLNM" VARCHAR2(100 CHAR), 
	"PPNFID" VARCHAR2(13 CHAR), 
	"PPNFBHDT" VARCHAR2(8 CHAR), 
	"PPNFISDT" VARCHAR2(8 CHAR), 
	"PPNFEXDT" VARCHAR2(8 CHAR), 
	"PPSTATUS" VARCHAR2(4 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXP_PIBICS" TO "BIOSAADM";
