CREATE TABLE "PIBICSDM2"."EXT_PERSON" 
   (	"EXTPERSON_SEQNO" NUMBER, 
	"OPASSPORTNO" VARCHAR2(50 CHAR), 
	"CPASSPORTNO" VARCHAR2(50 CHAR), 
	"EXT_DATE" DATE, 
	"DOCNO" VARCHAR2(50 CHAR), 
	"TM6NO" VARCHAR2(50 CHAR), 
	"EFIRSTNM" VARCHAR2(150 CHAR), 
	"EMIDDLENM" VARCHAR2(150 CHAR), 
	"EFAMILYNM" VARCHAR2(150 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"BIRTH_PLACE" VARCHAR2(50 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"OPASSPORT_PLACE" VARCHAR2(50 CHAR), 
	"OPASSPORT_DATE" DATE, 
	"OPASSPORT_EXPDATE" DATE, 
	"CPASSPORT_PLACE" VARCHAR2(50 CHAR), 
	"CPASSPORT_EXPDATE" DATE, 
	"CPASSPORT_DATE" DATE, 
	"IN_DATE" DATE, 
	"CONV_SEQNO" NUMBER, 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"FROMCOUNT" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"VISA_EXPDATE" DATE, 
	"BUILDING" VARCHAR2(100 CHAR), 
	"ADDR" VARCHAR2(200 CHAR), 
	"ROAD" VARCHAR2(100 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"POSTCODE" VARCHAR2(5 CHAR), 
	"TEL" VARCHAR2(100 CHAR), 
	"REASON_SEQNO" NUMBER, 
	"REASON_DAY" NUMBER, 
	"APPROVE_STS" CHAR(1 CHAR), 
	"PERMIT_DATE" DATE, 
	"PERSON_STS" CHAR(1 CHAR), 
	"EXT_SEQNO" NUMBER, 
	"FEESLIP_SEQNO" NUMBER, 
	"SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"UDEPT_SEQNO" NUMBER, 
	"PASSPORT_PIC" BLOB, 
	"STATUSEXT" CHAR(1 CHAR), 
	"STATUSEXTDTE" DATE, 
	"RQS_STS" CHAR(1 CHAR), 
	"VISATYPESUB_SEQNO" NUMBER, 
	"SUFFIX_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PERSON" ADD CONSTRAINT "EXTPERSON_PK" PRIMARY KEY ("EXTPERSON_SEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."EXTP_APPROVE_STS_IDX" ON "PIBICSDM2"."EXT_PERSON" ("APPROVE_STS") 
  ;
CREATE INDEX "PIBICSDM2"."EXT_IN_DATE_IDX" ON "PIBICSDM2"."EXT_PERSON" (TO_CHAR("IN_DATE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."IDXEXTPERSON1" ON "PIBICSDM2"."EXT_PERSON" ("CPASSPORTNO", "NATION_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_EXTPERSON_OPASSPORT" ON "PIBICSDM2"."EXT_PERSON" ("OPASSPORTNO") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_EXTPERSON_UPDATE" ON "PIBICSDM2"."EXT_PERSON" (TO_CHAR("UPDATE_DATE",'yyyymmdd')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."EXTPERSON_PK" ON "PIBICSDM2"."EXT_PERSON" ("EXTPERSON_SEQNO") 
  ;
  ;
