CREATE TABLE "PIBICSDM2"."EXT_PRO_220" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"RELATIONSHIP" VARCHAR2(100 CHAR), 
	"OWNER_EXTLIST_SEQNO" NUMBER, 
	"OWNER_DOC_NO" VARCHAR2(50 CHAR), 
	"OWNERNM" VARCHAR2(100 CHAR), 
	"OWNER_NATION_SEQNO" NUMBER, 
	"OWNER_PERMIT_DATE" DATE, 
	"OWNER_FOR" VARCHAR2(150 CHAR), 
	"OTH" VARCHAR2(1500 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_220" ADD CONSTRAINT "EXT_PRO_220_PK" PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_220" ADD CONSTRAINT "EXT_PRO_220_R03" FOREIGN KEY ("OWNER_NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_220" ADD CONSTRAINT "EXT_PRO_220_R02" FOREIGN KEY ("OWNER_EXTLIST_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_EXTENSIONLIST" ("EXTLIST_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_220" ADD CONSTRAINT "EXT_PRO_220_R01" FOREIGN KEY ("PROC_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_PROCESS" ("PROC_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_PRO_220_PK" ON "PIBICSDM2"."EXT_PRO_220" ("PRO_SEQNO") 
  ;
