CREATE TABLE "PIBICSDM2"."EXT_PRO_25_2_LOG" 
   (	"PRO_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"DOCITEM1" CHAR(1 CHAR), 
	"IT1_BANKNM" VARCHAR2(100 CHAR), 
	"IT1_TRANSFER_DATE" DATE, 
	"IT1_SUMTOTAL" NUMBER(15,2), 
	"DOCITEM2" CHAR(1 CHAR), 
	"IT2_PROJECTNM" VARCHAR2(100 CHAR), 
	"IT2_OUTCOME" NUMBER(15,2), 
	"DOCITEM3" CHAR(1 CHAR), 
	"IT3_BANKNM" VARCHAR2(100 CHAR), 
	"IT3_SUMTOTAL" NUMBER(15,2), 
	"DOCITEM4" CHAR(1 CHAR), 
	"IT4_FROM" VARCHAR2(100 CHAR), 
	"IT4_SUMTOTAL" NUMBER(15,2), 
	"DOCITEM5" CHAR(1 CHAR), 
	"IT5_OTH" VARCHAR2(100 CHAR), 
	"IT5_SUMTOTAL" NUMBER(15,2), 
	"FACT1" CHAR(1 CHAR), 
	"FACT2" CHAR(1 CHAR), 
	"FACT3" CHAR(1 CHAR), 
	"FACT4" CHAR(1 CHAR), 
	"FACT5" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"PROC_LOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_25_2_LOG" ADD CONSTRAINT "EXT_PRO_25_2_LOG_PK" PRIMARY KEY ("PRO_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_PRO_25_2_LOG_PK" ON "PIBICSDM2"."EXT_PRO_25_2_LOG" ("PRO_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXT_PRO_25_2_LOG" TO "BIOSAADM";
