CREATE TABLE "PIBICSDM2"."EXT_REASON_LOG" 
   (	"REASON_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"REASON_SEQNO" NUMBER, 
	"REASONEXTABB" CHAR(1 CHAR), 
	"REASONEXTENM" VARCHAR2(4000 CHAR), 
	"REASONEXTTNM" VARCHAR2(300 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"PERMIT_DAY" NUMBER, 
	"DEPTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"REASONCD" VARCHAR2(4 CHAR), 
	"WAIT_DAY" NUMBER, 
	"LAWSET" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_REASON_LOG" ADD CONSTRAINT "EXT_REASON_LOG_PK" PRIMARY KEY ("REASON_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_REASON_LOG_PK" ON "PIBICSDM2"."EXT_REASON_LOG" ("REASON_LOG_SEQNO") 
  ;
