CREATE TABLE "PIBICSDM2"."EXT_BOI_SPLAW_LOG" 
   (	"PRO_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"FACTTYPE" CHAR(1 CHAR), 
	"DUE_YEAR" NUMBER(5,1), 
	"GUARANTY_NO" VARCHAR2(20 CHAR), 
	"GUARANTY_DATE" DATE, 
	"GUARANTY_YEAR" NUMBER(4,1), 
	"CONTINENT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"REMARK" VARCHAR2(500 CHAR), 
	"TERMINAL_DATE" DATE, 
	"CHGPASS_NAME" VARCHAR2(100 CHAR), 
	"CHGPASS_OPASS" VARCHAR2(100 CHAR), 
	"CHGPASS_NPASS" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"GUARANTY_NO2" VARCHAR2(20 CHAR), 
	"COMPANY_SEQNO" NUMBER, 
	"COMPANYNM" VARCHAR2(1000 CHAR), 
	"PROC_LOG_SEQNO" NUMBER, 
	"POSITION" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_SPLAW_LOG" ADD CONSTRAINT "EXT_BOI_SPLAW_LOG_PK" PRIMARY KEY ("PRO_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_BOI_SPLAW_LOG_PK" ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" ("PRO_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXT_BOI_SPLAW_LOG" TO "BIOSAADM";
