CREATE TABLE "PIBICSDM2"."EXT_BOI_FAMILY" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"RELATIONSHIP" VARCHAR2(100 CHAR), 
	"OWNER_EXTLIST_SEQNO" NUMBER, 
	"OWNER_DOC_NO" VARCHAR2(50 CHAR), 
	"OWNERNM" VARCHAR2(100 CHAR), 
	"OWNER_NATION_SEQNO" NUMBER, 
	"OWNER_PERMIT_DATE" DATE, 
	"OWNER_COMPANY_SEQNO" NUMBER, 
	"CONTINENT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"OWNER_COMPANYNM" VARCHAR2(2000 CHAR), 
	"OTH" VARCHAR2(300 CHAR), 
	"DUE_YEAR" NUMBER(5,1)
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_PK" PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R01" FOREIGN KEY ("PROC_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_PROCESS" ("PROC_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R03" FOREIGN KEY ("OWNER_NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R05" FOREIGN KEY ("CONTINENT_SEQNO")
	  REFERENCES "PIBICSDM2"."CONTINENT" ("CONTINENT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R06" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R04" FOREIGN KEY ("OWNER_COMPANY_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_COMPANY" ("COMPANY_SEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_FAMILY" ADD CONSTRAINT "EXT_BOI_FAMILY_R02" FOREIGN KEY ("OWNER_EXTLIST_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_EXTENSIONLIST" ("EXTLIST_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_BOI_FAMILY_PK" ON "PIBICSDM2"."EXT_BOI_FAMILY" ("PRO_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXT_BOI_FAMILY" TO "BIOSAADM";
