CREATE TABLE "PIBICSDM2"."EXT_PRO_29_LOG" 
   (	"PRO_LOG_SEQNO" NUMBER, 
	"PROC_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"DOCDATE" DATE, 
	"EXPEXT_DATE" DATE, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"AGENCY" VARCHAR2(50 CHAR), 
	"BOOK" VARCHAR2(200 CHAR), 
	"SEAL" VARCHAR2(100 CHAR), 
	"EXT_DATE" DATE, 
	"STUDY_PERIOD" VARCHAR2(100 CHAR), 
	"YEAR_EDUCATION" VARCHAR2(50 CHAR), 
	"COURSE_LEVEL" VARCHAR2(100 CHAR), 
	"RESULTS" VARCHAR2(200 CHAR), 
	"COURSE" VARCHAR2(200 CHAR), 
	"SCHEDULE" VARCHAR2(200 CHAR), 
	"SUPPORT_BOOK" VARCHAR2(2000 CHAR), 
	"FACT1" CHAR(1 CHAR), 
	"COMMAND_FROM" VARCHAR2(150 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_29_LOG" ADD CONSTRAINT "EXT_PRO_29_LOG_PK" PRIMARY KEY ("PRO_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_PRO_29_LOG_PK" ON "PIBICSDM2"."EXT_PRO_29_LOG" ("PRO_LOG_SEQNO") 
  ;
