CREATE TABLE "PIBICSDM2"."EXT_PRO_217" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"MINCOME" NUMBER(15,2), 
	"CONTACT_DATE" DATE, 
	"OTH" VARCHAR2(1500 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"COMPANYNM" VARCHAR2(200 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_217" ADD CONSTRAINT "EXT_PRO_217_PK" PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_217" ADD CONSTRAINT "EXT_PRO_217_R01" FOREIGN KEY ("PROC_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_PROCESS" ("PROC_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_PRO_217_PK" ON "PIBICSDM2"."EXT_PRO_217" ("PRO_SEQNO") 
  ;
