CREATE TABLE "PIBICSDM2"."EXT_COMMAND_LOG" 
   (	"COMMAND_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"COMMAND_SEQNO" NUMBER, 
	"COMMANDTNM" VARCHAR2(200 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"COMMANDENM" VARCHAR2(200 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_COMMAND_LOG" ADD CONSTRAINT "EXT_COMMAND_LOG_PK" PRIMARY KEY ("COMMAND_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_COMMAND_LOG_PK" ON "PIBICSDM2"."EXT_COMMAND_LOG" ("COMMAND_LOG_SEQNO") 
  ;
