CREATE TABLE "PIBICSDM2"."EXT_PRO_230" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"LOCATION" VARCHAR2(1000 CHAR), 
	"INCOME_PERSON" NUMBER(15,2), 
	"CONTRACT_DATE" DATE, 
	"CONTRACT" VARCHAR2(300 CHAR), 
	"OTHER" VARCHAR2(2000 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_230" ADD CONSTRAINT "EXT_PRO_230_PK" PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_PRO_230" ADD CONSTRAINT "EXT_PRO_230_R01" FOREIGN KEY ("PROC_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_PROCESS" ("PROC_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_PRO_230_PK" ON "PIBICSDM2"."EXT_PRO_230" ("PRO_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXT_PRO_230" TO "BIOSAADM";
