CREATE TABLE "PIBICSDM2"."EXT_COMMITTEE_LOG" 
   (	"COMMITEE_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"COMMITEE_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"CMEETING_NO" VARCHAR2(20 CHAR), 
	"CMEETING_DATE" DATE, 
	"CREMARK" VARCHAR2(1000 CHAR), 
	"CRESOLVE" CHAR(1 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"CR_DETAIL" VARCHAR2(200 CHAR), 
	"CDATE" DATE
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_COMMITEE_LOG_PK" ON "PIBICSDM2"."EXT_COMMITTEE_LOG" ("COMMITEE_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXT_COMMITTEE_LOG" TO "BIOSAADM";
