CREATE TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"DUE_YEAR" NUMBER(5,1), 
	"POSITION" VARCHAR2(2000 CHAR), 
	"COMPANY_SEQNO" NUMBER, 
	"COMPANYTYPENM" VARCHAR2(2000 CHAR), 
	"COMPANYNM" VARCHAR2(1000 CHAR), 
	"CAPITAL" NUMBER(15,2), 
	"CAPITALPAY" NUMBER(15,2), 
	"SHARES" NUMBER(15,2), 
	"SUMINCOME" NUMBER(15,2), 
	"ASSET" NUMBER(15,2), 
	"SUMOFFICER" NUMBER, 
	"THAIOFFICER" NUMBER, 
	"PERMANENCE" NUMBER, 
	"DAILY" NUMBER, 
	"ALIENOFFICER" NUMBER, 
	"ALIENINCOMEM" NUMBER(15,2), 
	"ALIENTAXM" NUMBER(15,2), 
	"ALIENINCOMEY" NUMBER(15,2), 
	"ALIENTAXY" NUMBER(15,2), 
	"OTH" VARCHAR2(300 CHAR), 
	"FACT1" CHAR(1 CHAR), 
	"FACT2" CHAR(1 CHAR), 
	"CONTINENT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"FACT_LESSINCOME" NUMBER(15,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"WPERMIT_DATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" ADD PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" ADD CONSTRAINT "EXT_BOI_BUSINESS_R01" FOREIGN KEY ("PROC_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_PROCESS" ("PROC_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" ADD CONSTRAINT "EXT_BOI_BUSINESS_R03" FOREIGN KEY ("CONTINENT_SEQNO")
	  REFERENCES "PIBICSDM2"."CONTINENT" ("CONTINENT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" ADD CONSTRAINT "EXT_BOI_BUSINESS_R04" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_BOI_BUSINESS" ADD CONSTRAINT "EXT_BOI_BUSINESS_R02" FOREIGN KEY ("COMPANY_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_COMPANY" ("COMPANY_SEQNO") DISABLE;
  ;
