CREATE TABLE "PIBICSDM2"."EXT_COMPANY_HIST" 
   (	"COMPANY_HIST_SEQNO" NUMBER, 
	"COMPANY_SEQNO" NUMBER, 
	"COMTYPE_SEQNO" NUMBER, 
	"CAPITAL" NUMBER(15,2), 
	"ASSET" NUMBER(15,2), 
	"SHARES" NUMBER(15,2), 
	"SUMINCOME" NUMBER(15,2), 
	"SUMOFFICER" NUMBER, 
	"THAIOFFICER" NUMBER, 
	"ALIENOFFICER" NUMBER, 
	"ALIENINCOMEM" NUMBER(15,2), 
	"ALIENTAXM" NUMBER(15,2), 
	"ALIENINCOMEY" NUMBER(15,2), 
	"ALIENTAXY" NUMBER(15,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"COMPANYNM" VARCHAR2(100 CHAR), 
	"COMPANYTYPENM" VARCHAR2(200 CHAR), 
	"CAPITALPAY" NUMBER(15,2), 
	"ASSET_BOI" NUMBER(15,2), 
	"PERMANENCE" NUMBER, 
	"DAILY" NUMBER, 
	"TRANSFER_DATE" DATE, 
	"TRANSFER_TO" DATE, 
	"TRANSFER_AMOUNT" NUMBER(15,2), 
	"DEPT_SEQNO" NUMBER, 
	"SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"SUMEND" NUMBER, 
	"MOVESTAMP_TYPE" CHAR(1 CHAR), 
	"STATALIENOFFICER" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."EXT_COMPANY_HIST" ADD CONSTRAINT "EXT_COMPANY_HIST_PK" PRIMARY KEY ("COMPANY_HIST_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."EXT_COMPANY_HIST" ADD CONSTRAINT "EXT_COMPANY_HIST_R01" FOREIGN KEY ("COMPANY_SEQNO")
	  REFERENCES "PIBICSDM2"."EXT_COMPANY" ("COMPANY_SEQNO") DISABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."EXT_COMPANY_HIST_PK" ON "PIBICSDM2"."EXT_COMPANY_HIST" ("COMPANY_HIST_SEQNO") 
  ;
