CREATE TABLE "PIBICSDM2"."EXTCOUNTRY_TMP" 
   (	"CODE" VARCHAR2(200 CHAR), 
	"DESCRIPTION" VARCHAR2(500 CHAR), 
	"IMM" VARCHAR2(50 CHAR), 
	"SEQNO" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXTCOUNTRY_TMP" TO "BIOSAADM";
