CREATE TABLE "PIBICSDM2"."EXTFSLIPLOG" 
   (	"EXTFSLIPLOGID" VARCHAR2(255 CHAR), 
	"IPADDRESS" VARCHAR2(255 CHAR), 
	"COUNTERNM" VARCHAR2(255 CHAR), 
	"SLIPNUM" VARCHAR2(255 CHAR), 
	"MAXSLIPNO" VARCHAR2(255 CHAR), 
	"MAXSLIPBOOKNO" VARCHAR2(255 CHAR), 
	"CREUSR" VARCHAR2(255 CHAR), 
	"CREDTE" DATE, 
	"UPDUSR" VARCHAR2(255 CHAR), 
	"UPDDTE" DATE, 
	"LOGUSERID" VARCHAR2(255 CHAR), 
	"LOGFLAG" VARCHAR2(255 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" VARCHAR2(255 CHAR), 
	"DEPTCD" VARCHAR2(255 CHAR), 
	"ORGCD" VARCHAR2(255 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."EXTFSLIPLOG" ADD PRIMARY KEY ("EXTFSLIPLOGID")
  USING INDEX  ENABLE;
  ;
