CREATE TABLE "PIBICSDM2"."EXTSLIP" 
   (	"EXTSLIPID" VARCHAR2(255 CHAR), 
	"SLIPNO" VARCHAR2(255 CHAR), 
	"SLIPBOOKNO" VARCHAR2(255 CHAR), 
	"EXTID" VARCHAR2(255 CHAR), 
	"SLIPDTE" DATE, 
	"FULLNM" VARCHAR2(255 CHAR), 
	"AMOUNT" NUMBER(*,0), 
	"PRINTFLAG" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"CREUSR" VARCHAR2(255 CHAR), 
	"CREDTE" DATE, 
	"UPDUSR" VARCHAR2(255 CHAR), 
	"UPDDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."EXTSLIP" ADD PRIMARY KEY ("EXTSLIPID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_C00207536" ON "PIBICSDM2"."EXTSLIP" ("EXTSLIPID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."EXTSLIP" TO "BIOSAADM";
