CREATE TABLE "PIBICSDM2"."FACT_ADDR24" 
   (	"ADDR24_SEQNO" NUMBER, 
	"CHECKINDTE" DATE, 
	"NATION_SEQNO" NUMBER, 
	"AGE" NUMBER, 
	"HOTEL_SEQNO" NUMBER, 
	"HTYPE_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"DEPT1_SEQNO" NUMBER, 
	"ADDR24_STAT" NUMBER, 
	"DW_INSDTE" TIMESTAMP (6), 
	"DW_UPDDTE" TIMESTAMP (6), 
	"DEPT2_SEQNO" NUMBER, 
	"DEPT3_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"DEPTSEQNOLEVEL1" NUMBER, 
	"DEPTSEQNOLEVEL2" NUMBER
   ) ;
  CREATE INDEX "PIBICSDM2"."FADDR24_CHECKINDTE_IDX" ON "PIBICSDM2"."FACT_ADDR24" (TO_CHAR("CHECKINDTE",'YYYYMMDD')) 
  ;
