CREATE TABLE "PIBICSDM2"."FILEDLYLOG" 
   (	"FILEDLYLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"FILEDLY_SEQNO" NUMBER, 
	"ATTACHDLY_SEQNO" NUMBER, 
	"FILEPATH" VARCHAR2(100 CHAR), 
	"FILEDESC" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ATTACHDLYLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FILEDLYLOG" ADD CONSTRAINT "FILEDLYLOG_PK" PRIMARY KEY ("FILEDLYLOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FILEDLYLOG_PK" ON "PIBICSDM2"."FILEDLYLOG" ("FILEDLYLOG_SEQNO") 
  ;
