CREATE TABLE "PIBICSDM2"."FILETYPE" 
   (	"SEQNO" NUMBER, 
	"FILE_TYPE" VARCHAR2(8 CHAR), 
	"FILE_DESC" VARCHAR2(250 CHAR), 
	"FILE_IO" CHAR(1 CHAR), 
	"AGENT_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FILETYPE" ADD CONSTRAINT "FILETYPE_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FILETYPE_PK" ON "PIBICSDM2"."FILETYPE" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FILETYPE" TO "BIOSAADM";
