CREATE TABLE "PIBICSDM2"."FILETYPE" 
   (	"SEQNO" NUMBER, 
	"FILE_TYPE" VARCHAR2(8 CHAR), 
	"FILE_DESC" VARCHAR2(250 CHAR), 
	"FILE_IO" CHAR(1 CHAR), 
	"AGENT_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FILETYPE" ADD CONSTRAINT "FILETYPE_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FILETYPE_PK" ON "PIBICSDM2"."FILETYPE" ("SEQNO") 
  ;
