CREATE TABLE "PIBICSDM2"."FLIGHTNUMBERS" 
   (	"FLIGHTSEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"ALLFLAG" CHAR(1 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"FLIGHTSTARTDTE" TIMESTAMP (6), 
	"FLIGHTENDDTE" TIMESTAMP (6), 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 0, 
	"FLIGHT_TYPE" VARCHAR2(1 CHAR), 
	"HEALTHFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FLIGHTNUMBERS" ADD CONSTRAINT "FLIGHTNUMBERS_PK" PRIMARY KEY ("FLIGHTSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FLIGHTNUMBERS_PK" ON "PIBICSDM2"."FLIGHTNUMBERS" ("FLIGHTSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FLIGHTNUMBERS" TO "BIOSAADM";
