CREATE TABLE "PIBICSDM2"."FLIGHTNUMBERS_LOG" 
   (	"FLIGHTSEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"ALLFLAG" CHAR(1 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"FLIGHTSTARTDTE" TIMESTAMP (6), 
	"FLIGHTENDDTE" TIMESTAMP (6), 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_USERID" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER DEFAULT 0, 
	"FLIGHTSEQNOLOG" NUMBER, 
	"FLIGHT_TYPE" VARCHAR2(1 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."FLIGHTNUMBERS_LOG_PK" ON "PIBICSDM2"."FLIGHTNUMBERS_LOG" ("FLIGHTSEQNOLOG") 
  ;
