CREATE TABLE "PIBICSDM2"."FN38PERDAY" 
   (	"DAYS" CHAR(2 CHAR), 
	"CARDIN" NUMBER, 
	"CHKINNOW" NUMBER, 
	"A1" NUMBER, 
	"A2" NUMBER, 
	"A3" NUMBER, 
	"A4" NUMBER, 
	"A5" NUMBER, 
	"A6" NUMBER, 
	"A7" NUMBER, 
	"A8" NUMBER, 
	"A9" NUMBER, 
	"A10" NUMBER, 
	"A11" NUMBER, 
	"A12" NUMBER, 
	"A13" NUMBER, 
	"A14" NUMBER, 
	"A15" NUMBER, 
	"A16" NUMBER, 
	"A17" NUMBER, 
	"A18" NUMBER, 
	"A19" NUMBER, 
	"A20" NUMBER, 
	"A21" NUMBER, 
	"A22" NUMBER, 
	"A23" NUMBER, 
	"A24" NUMBER, 
	"A25" NUMBER, 
	"A26" NUMBER, 
	"A27" NUMBER, 
	"A28" NUMBER, 
	"A29" NUMBER, 
	"A30" NUMBER, 
	"A31" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FN38PERDAY" TO "BIOSAADM";
