CREATE TABLE "PIBICSDM2"."FN_ALIENLIST" 
   (	"ALIEN_SEQNO" NUMBER, 
	"ADDRN_SEQNO" NUMBER, 
	"CHECKINDTE" TIMESTAMP (6), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"SEX" CHAR(1 CHAR), 
	"PASSPORTNO" VARCHAR2(21 CHAR), 
	"INDTE" TIMESTAMP (6), 
	"VISATYPE_SEQNO" NUMBER, 
	"DUEDATE" TIMESTAMP (6), 
	"DEPT_SEQNO" NUMBER, 
	"TM6NO" VARCHAR2(7 CHAR), 
	"PV_SEQNO" NUMBER, 
	"RELATIONSHIP" VARCHAR2(60 CHAR), 
	"FLAGWATCHLIST" CHAR(1 CHAR), 
	"FLAGFOUND" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"BIRTHDATE" VARCHAR2(10 CHAR), 
	"ALIENQ_SEQNO" NUMBER, 
	"ADDRNQ_SEQNO" NUMBER, 
	"DEPT_SEQNO_TEMP" NUMBER, 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"UIPADDRESS" VARCHAR2(20 CHAR), 
	"MARKUPD" CHAR(1 CHAR), 
	"EXCELFLAG" VARCHAR2(1 CHAR), 
	"FLAGITP" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FN_ALIENLIST" ADD CONSTRAINT "FN_ALIENLIST_PK" PRIMARY KEY ("ALIEN_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FN_ALIENLIST" ADD CONSTRAINT "FN_ALIENLIST_R03" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."FN_ALIENLIST" ADD CONSTRAINT "FN_ALIENLIST_R02" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."FN_ALIENLIST" ADD CONSTRAINT "FN_ALIENLIST_R04" FOREIGN KEY ("VISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") DISABLE;
  CREATE INDEX "PIBICSDM2"."FNALIEN_ADDRNSEQNO_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("ADDRN_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_BIRTHDATE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("BIRTHDATE") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_CHECKINDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("CHECKINDTE") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_CHECKINDTE_TOCHAR_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CHECKINDTE",'yyyy-mm-dd')) 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_CONCAT_CSEQNO_PPNO_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("COUNT_SEQNO", "PASSPORTNO") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_CREATE_DATE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CREATE_DATE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_DD_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CHECKINDTE",'dd')) 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_EFAMILYNM_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_EFIRSTNM_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_INDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("INDTE") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_MM_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CHECKINDTE",'mm')) 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_NAME_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("EFIRSTNM", "EMIDDLENM", "EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_PASSPORTNO_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("PASSPORTNO") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_SEX_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("SEX") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_TCHECKINDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TRUNC("CHECKINDTE")) 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_TM6NO_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("TM6NO") 
  ;
CREATE INDEX "PIBICSDM2"."FNALIEN_YYMM_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CHECKINDTE",'yyyymm')) 
  ;
CREATE INDEX "PIBICSDM2"."FN_ALIENLIST_CHECKINDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" (TO_CHAR("CHECKINDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."FN_ALIENLIST_IPADRR_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("IPADDRESS") 
  ;
CREATE INDEX "PIBICSDM2"."FN_ALIENT_CREDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("CREATE_DATE") 
  ;
CREATE INDEX "PIBICSDM2"."FN_ALIENT_UPDTE_IDX" ON "PIBICSDM2"."FN_ALIENLIST" ("UPDATE_DATE") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."FN_ALIENLIST_PK" ON "PIBICSDM2"."FN_ALIENLIST" ("ALIEN_SEQNO") 
  ;
