CREATE TABLE "PIBICSDM2"."FN_CHECKPASSFIRST" 
   (	"SEQNO" NUMBER, 
	"USER_ID" VARCHAR2(20 CHAR), 
	"PASSWORDMD5" VARCHAR2(150 CHAR), 
	"PASSWORD" VARCHAR2(20 CHAR), 
	"PV_SEQNO" NUMBER, 
	"CHGPWDDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FN_CHECKPASSFIRST" ADD CONSTRAINT "FN_CHECKPASSFIRST_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FN_CHECKPASSFIRST_PK" ON "PIBICSDM2"."FN_CHECKPASSFIRST" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FN_CHECKPASSFIRST" TO "BIOSAADM";
