CREATE TABLE "PIBICSDM2"."FN_HOTELTYPE" 
   (	"HTYPE_SEQNO" NUMBER, 
	"TYPENAME" VARCHAR2(50 CHAR), 
	"SHORTNESS" CHAR(1 CHAR), 
	"RUNNO" VARCHAR2(5 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"VERSION" NUMBER, 
	"SUBTYPE_FLAG" CHAR(1 CHAR), 
	"TYPE_NUM" VARCHAR2(2 CHAR), 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FN_HOTELTYPE" ADD CONSTRAINT "FN_HOTELTYPE_PK" PRIMARY KEY ("HTYPE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FN_HOTELTYPE_PK" ON "PIBICSDM2"."FN_HOTELTYPE" ("HTYPE_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FN_HOTELTYPE" TO "BIOSAADM";
