CREATE TABLE "PIBICSDM2"."FN_REGISTER_LOG" 
   (	"FN_REGISTER_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"REGIS_SEQNO" NUMBER, 
	"HOTEL_SEQNO" NUMBER, 
	"FIRSTNM" VARCHAR2(60 CHAR), 
	"FAMILYNAME" VARCHAR2(60 CHAR), 
	"POSITION" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"REGISDTE" TIMESTAMP (6), 
	"DOCSTATUS" CHAR(1 CHAR), 
	"APPRSTATUS" CHAR(1 CHAR), 
	"REASON" VARCHAR2(100 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"VERSION" NUMBER, 
	"FN_HOTEL_LOG_SEQNO" NUMBER, 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FN_REGISTER_LOG" ADD CONSTRAINT "FN_REGISTER_LOG_PK" PRIMARY KEY ("FN_REGISTER_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FN_REGISTER_LOG_PK" ON "PIBICSDM2"."FN_REGISTER_LOG" ("FN_REGISTER_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FN_REGISTER_LOG" TO "BIOSAADM";
