CREATE TABLE "PIBICSDM2"."FN_USER" 
   (	"USERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(300 CHAR), 
	"LASTNAME" VARCHAR2(300 CHAR), 
	"ADDRESS" VARCHAR2(500 CHAR), 
	"PHONE" VARCHAR2(50 CHAR), 
	"USERNAME" VARCHAR2(100 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"USERGROUP" NUMBER, 
	"DEPT_SEQNO" NUMBER
   ) ;
