CREATE TABLE "PIBICSDM2"."FN_USER" 
   (	"USERID" NUMBER, 
	"FIRSTNAME" VARCHAR2(300 CHAR), 
	"LASTNAME" VARCHAR2(300 CHAR), 
	"ADDRESS" VARCHAR2(500 CHAR), 
	"PHONE" VARCHAR2(50 CHAR), 
	"USERNAME" VARCHAR2(100 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"USERGROUP" NUMBER, 
	"DEPT_SEQNO" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FN_USER" TO "BIOSAADM";
