CREATE TABLE "PIBICSDM2"."FNSTATISTICMONTHPIBICS" 
   (	"FNMONTHSEQNO" NUMBER, 
	"MONTHTHAI" VARCHAR2(60 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"NET_HOTEL_Y" NUMBER, 
	"NET_HOTEL_N" NUMBER, 
	"OFFICE_HOTEL_Y" NUMBER, 
	"OFFICE_HOTEL_N" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."FNSTATISTICMONTHPIBICS_PK" ON "PIBICSDM2"."FNSTATISTICMONTHPIBICS" ("FNMONTHSEQNO") 
  ;
