CREATE TABLE "PIBICSDM2"."FOREIGNPRO_LOG" 
   (	"FOREIGN_SEQNO" NUMBER, 
	"DPT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"NOTE" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"FOREIGNPRO_LOG_SEQNO" NUMBER, 
	"DPT_LOG_SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."FOREIGNPRO_LOG_PK" ON "PIBICSDM2"."FOREIGNPRO_LOG" ("FOREIGNPRO_LOG_SEQNO") 
  ;
