CREATE TABLE "PIBICSDM2"."FOUNDWATCHLIST" 
   (	"SEQNO" VARCHAR2(29 CHAR), 
	"USERID" VARCHAR2(20 CHAR), 
	"MATCHDATE" DATE, 
	"ACTION" CHAR(1 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"DEPTCD" CHAR(5 CHAR), 
	"MSEQNO" NUMBER, 
	"WLCD" VARCHAR2(10 CHAR), 
	"USERSTAFF" VARCHAR2(20 CHAR), 
	"PROGRAM_ID" VARCHAR2(25 CHAR), 
	"INTERPOL" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FOUNDWATCHLIST" ADD CONSTRAINT "FOUNDWATCHLIST_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FOUNDWATCHLIST_PK" ON "PIBICSDM2"."FOUNDWATCHLIST" ("SEQNO") 
  ;
