CREATE TABLE "PIBICSDM2"."FOUNDWATCHLIST" 
   (	"SEQNO" VARCHAR2(29 CHAR), 
	"USERID" VARCHAR2(20 CHAR), 
	"MATCHDATE" DATE, 
	"ACTION" CHAR(1 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"DEPTCD" CHAR(5 CHAR), 
	"MSEQNO" NUMBER, 
	"WLCD" VARCHAR2(10 CHAR), 
	"USERSTAFF" VARCHAR2(20 CHAR), 
	"PROGRAM_ID" VARCHAR2(25 CHAR), 
	"INTERPOL" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FOUNDWATCHLIST" ADD CONSTRAINT "FOUNDWATCHLIST_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FOUNDWATCHLIST_PK" ON "PIBICSDM2"."FOUNDWATCHLIST" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FOUNDWATCHLIST" TO "BIOSAADM";
