CREATE TABLE "PIBICSDM2"."FS_FINESDUE" 
   (	"FSFDEUSEQNO" NUMBER, 
	"ESTIMATEYEAR" CHAR(4 CHAR), 
	"ESTIMATEMONTH" CHAR(2 CHAR), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CONFIRMUSER" VARCHAR2(20 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"FLAGCOMMANDER" CHAR(1 CHAR), 
	"REWARDFINE" NUMBER(10,2)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FINESDUE" ADD CONSTRAINT "FS_FINESDUE_PK" PRIMARY KEY ("FSFDEUSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_FINESDUE_PK" ON "PIBICSDM2"."FS_FINESDUE" ("FSFDEUSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FS_FINESDUE" TO "BIOSAADM";
