CREATE TABLE "PIBICSDM2"."FS_FINESDUE" 
   (	"FSFDEUSEQNO" NUMBER, 
	"ESTIMATEYEAR" CHAR(4 CHAR), 
	"ESTIMATEMONTH" CHAR(2 CHAR), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CONFIRMUSER" VARCHAR2(20 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"FLAGCOMMANDER" CHAR(1 CHAR), 
	"REWARDFINE" NUMBER(10,2)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FINESDUE" ADD CONSTRAINT "FS_FINESDUE_PK" PRIMARY KEY ("FSFDEUSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_FINESDUE_PK" ON "PIBICSDM2"."FS_FINESDUE" ("FSFDEUSEQNO") 
  ;
