CREATE TABLE "PIBICSDM2"."FS_FINESDETAIL" 
   (	"FINESDETAIL_SEQNO" NUMBER, 
	"FINES_SEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"FINESLIPAMOUNT" NUMBER(10,2), 
	"OVERSTAYDAY" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL" ADD CONSTRAINT "FINESDETAIL_PK" PRIMARY KEY ("FINESDETAIL_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL" ADD FOREIGN KEY ("FINES_SEQNO")
	  REFERENCES "PIBICSDM2"."FS_FINES" ("FINES_SEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL" ADD FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") DISABLE;
  CREATE INDEX "PIBICSDM2"."FD_FINES_SEQNO_IDX" ON "PIBICSDM2"."FS_FINESDETAIL" ("FINES_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."FINES_PRATE_SEQNO_IDX" ON "PIBICSDM2"."FS_FINESDETAIL" ("PRATE_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."FINESDETAIL_PK" ON "PIBICSDM2"."FS_FINESDETAIL" ("FINESDETAIL_SEQNO") 
  ;
