CREATE TABLE "PIBICSDM2"."FS_FEESDETAIL" 
   (	"FEESDETAIL_SEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"FEES_SEQNO" NUMBER, 
	"FEESLIPAMOUNT" NUMBER(10,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FEESDETAIL" ADD CONSTRAINT "FEESDETAIL_PK" PRIMARY KEY ("FEESDETAIL_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FEESDETAIL" ADD FOREIGN KEY ("FEES_SEQNO")
	  REFERENCES "PIBICSDM2"."FS_FEES" ("FEES_SEQNO") DISABLE;
  ALTER TABLE "PIBICSDM2"."FS_FEESDETAIL" ADD FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") DISABLE;
  CREATE INDEX "PIBICSDM2"."FD_FEES_SEQNO_IDX" ON "PIBICSDM2"."FS_FEESDETAIL" ("FEES_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."FD_PRATE_SEQNO_IDX" ON "PIBICSDM2"."FS_FEESDETAIL" ("PRATE_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."FEESDETAIL_PK" ON "PIBICSDM2"."FS_FEESDETAIL" ("FEESDETAIL_SEQNO") 
  ;
