CREATE TABLE "PIBICSDM2"."FS_FEES_LOG" 
   (	"FEESLOG_SEQNO" NUMBER, 
	"FEES_SEQNO" NUMBER, 
	"FEESNO" VARCHAR2(50 CHAR), 
	"FEESLIPNO" VARCHAR2(20 CHAR), 
	"FEESLIPBOOKNO" VARCHAR2(20 CHAR), 
	"FEESLIPDATE" TIMESTAMP (6), 
	"FEESLIPTOTAL" NUMBER(10,2), 
	"PRINTFLAG" CHAR(1 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(7 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"INDTE" DATE, 
	"VISATYPE_SEQNO" NUMBER, 
	"FEESSTATUS" VARCHAR2(10 CHAR), 
	"FEESREMARK" VARCHAR2(200 CHAR), 
	"FLAG_SYSTEM" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"SLIPTYPE" CHAR(1 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"APPROVE_BY" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FEES_LOG" ADD CONSTRAINT "FS_FEES_LOG_PK" PRIMARY KEY ("FEESLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FEES_LOG" ADD FOREIGN KEY ("VISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FEES_LOG" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FEES_LOG" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_FEES_LOG_PK" ON "PIBICSDM2"."FS_FEES_LOG" ("FEESLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FS_FEES_LOG" TO "BIOSAADM";
