CREATE TABLE "PIBICSDM2"."FS_FINESDETAIL_LOG" 
   (	"FID_LOG_SEQNO" NUMBER, 
	"FINESLOG_SEQNO" NUMBER, 
	"FINESDETAIL_SEQNO" NUMBER, 
	"FINES_SEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"FINESLIPAMOUNT" NUMBER(10,2), 
	"OVERSTAYDAY" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL_LOG" ADD CONSTRAINT "FS_FINESDETAIL_LOG_R01" PRIMARY KEY ("FID_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL_LOG" ADD CONSTRAINT "FS_FINESDETAIL_LOG_R02" FOREIGN KEY ("FINESLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."FS_FINES_LOG" ("FINESLOG_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_FINESDETAIL_LOG" ADD FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_FINESDETAIL_LOG_R01" ON "PIBICSDM2"."FS_FINESDETAIL_LOG" ("FID_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FS_FINESDETAIL_LOG" TO "BIOSAADM";
