CREATE TABLE "PIBICSDM2"."FS_NONAUTHPERSONLOG" 
   (	"NONAUTHPERSONLOGSEQNO" NUMBER, 
	"FSNONAUTHLOGSEQNO" NUMBER, 
	"NONAUTHPERSONSEQNO" NUMBER, 
	"FSNONAUTHSEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"REMARK" VARCHAR2(200 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_NONAUTHPERSONLOG" ADD CONSTRAINT "FS_NONAUTHPERSONLOG_PK" PRIMARY KEY ("NONAUTHPERSONLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_NONAUTHPERSONLOG" ADD CONSTRAINT "FS_NONAUTHPERSONLOG_R01" FOREIGN KEY ("FSNONAUTHLOGSEQNO")
	  REFERENCES "PIBICSDM2"."FS_NONAUTHORIZEDLOG" ("FSNONAUTHLOGSEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_NONAUTHPERSONLOG_PK" ON "PIBICSDM2"."FS_NONAUTHPERSONLOG" ("NONAUTHPERSONLOGSEQNO") 
  ;
