CREATE TABLE "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" 
   (	"FSETFEESLOG_SEQNO" NUMBER, 
	"IPADDRESS" VARCHAR2(15 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"COUNTERNM" VARCHAR2(50 CHAR), 
	"SLIPNUM" NUMBER(38,0), 
	"MAXSLIPNO" VARCHAR2(10 CHAR), 
	"MAXSLIPBOOKNO" VARCHAR2(10 CHAR), 
	"PRATE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER(10,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" ADD CONSTRAINT "FS_SETTINGFEESLIP_LOG_R01" PRIMARY KEY ("FSETFEESLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" ADD FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FS_SETTINGFEESLIP_LOG_R01" ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" ("FSETFEESLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FS_SETTINGFEESLIP_LOG" TO "BIOSAADM";
