CREATE TABLE "PIBICSDM2"."FS_SETTINGFEESLIP" 
   (	"IPADDRESS" VARCHAR2(15 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"COUNTERNM" VARCHAR2(50 CHAR), 
	"SLIPNUM" NUMBER(38,0), 
	"MAXSLIPNO" VARCHAR2(10 CHAR), 
	"MAXSLIPBOOKNO" VARCHAR2(10 CHAR), 
	"PRATE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER(10,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."FS_SETTINGFEESLIP" ADD PRIMARY KEY ("IPADDRESS")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FS_SETTINGFEESLIP" ADD FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  ;
