CREATE TABLE "PIBICSDM2"."FUNCTION" 
   (	"FUNCTIONCD" VARCHAR2(20 CHAR), 
	"APPCD" VARCHAR2(20 CHAR), 
	"FUNCTIONTYPE" CHAR(1 CHAR), 
	"FUNCTIONNM" VARCHAR2(100 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE, 
	"ORDER_NO" CHAR(8 CHAR), 
	"MENUNM" VARCHAR2(100 CHAR), 
	"URL" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FUNCTION" ADD CONSTRAINT "FUNCTIONCD_PK" PRIMARY KEY ("FUNCTIONCD")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FUNCTION" ADD CONSTRAINT "APPCD_FK" FOREIGN KEY ("APPCD")
	  REFERENCES "PIBICSDM2"."APPLICATION" ("APPCD") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FUNCTIONCD_PK" ON "PIBICSDM2"."FUNCTION" ("FUNCTIONCD") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FUNCTION" TO "BIOSAADM";
