CREATE TABLE "PIBICSDM2"."FUNCTION" 
   (	"FUNCTIONCD" VARCHAR2(20 CHAR), 
	"APPCD" VARCHAR2(20 CHAR), 
	"FUNCTIONTYPE" CHAR(1 CHAR), 
	"FUNCTIONNM" VARCHAR2(100 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE, 
	"ORDER_NO" CHAR(8 CHAR), 
	"MENUNM" VARCHAR2(100 CHAR), 
	"URL" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FUNCTION" ADD CONSTRAINT "FUNCTIONCD_PK" PRIMARY KEY ("FUNCTIONCD")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FUNCTION" ADD CONSTRAINT "APPCD_FK" FOREIGN KEY ("APPCD")
	  REFERENCES "PIBICSDM2"."APPLICATION" ("APPCD") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."FUNCTIONCD_PK" ON "PIBICSDM2"."FUNCTION" ("FUNCTIONCD") 
  ;
