CREATE TABLE "PIBICSDM2"."FW_FAVORITES" 
   (	"FAV_SEQ" NUMBER, 
	"USER_ID" VARCHAR2(20 CHAR), 
	"NODE_ID" NUMBER, 
	"PROGRAM_ID" VARCHAR2(25 CHAR), 
	"DESCRIPTION" VARCHAR2(100 CHAR), 
	"ROLE_ID" NUMBER, 
	"LINK" VARCHAR2(100 CHAR), 
	"START_PAGE" CHAR(1 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"LASTUPDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_FAVORITES" ADD CONSTRAINT "XPKFW_FAVORITES" PRIMARY KEY ("FAV_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_FAVORITES" ADD CONSTRAINT "R_51" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PIBICSDM2"."FW_ROLE" ("ROLE_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_FAVORITES" ADD CONSTRAINT "R_52" FOREIGN KEY ("USER_ID")
	  REFERENCES "PIBICSDM2"."FW_USER" ("USER_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_FAVORITES" ADD CONSTRAINT "R_50" FOREIGN KEY ("NODE_ID", "PROGRAM_ID")
	  REFERENCES "PIBICSDM2"."FW_MENU" ("NODE_ID", "PROGRAM_ID") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_FAVORITES" ON "PIBICSDM2"."FW_FAVORITES" ("FAV_SEQ") 
  ;
