CREATE TABLE "PIBICSDM2"."FW_GROUPUSER" 
   (	"GROUP_ID" NUMBER, 
	"SEQ" NUMBER, 
	"USER_ID" VARCHAR2(20 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"STATUS" CHAR(1 CHAR), 
	"LASTUPDATE" TIMESTAMP (6), 
	"START_DATE" TIMESTAMP (6), 
	"EXPIRE_DATE" TIMESTAMP (6), 
	"IS_ASSIGNDATE" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_GROUPUSER" ADD CONSTRAINT "XPKFW_GROUPUSER" PRIMARY KEY ("GROUP_ID", "SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_GROUPUSER" ADD CONSTRAINT "R_45" FOREIGN KEY ("USER_ID")
	  REFERENCES "PIBICSDM2"."FW_USER" ("USER_ID") DISABLE;
  ALTER TABLE "PIBICSDM2"."FW_GROUPUSER" ADD CONSTRAINT "R_16" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "PIBICSDM2"."FW_GROUP" ("GROUP_ID") DISABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_GROUPUSER" ON "PIBICSDM2"."FW_GROUPUSER" ("GROUP_ID", "SEQ") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FW_GROUPUSER" TO "BIOSAADM";
