CREATE TABLE "PIBICSDM2"."FW_GROUP" 
   (	"GROUP_ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(60 CHAR), 
	"DESCRIPTION" VARCHAR2(60 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"GROUP_TYPE" CHAR(1 CHAR), 
	"LASTUPDATE" TIMESTAMP (6), 
	"SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_GROUP" ADD CONSTRAINT "XPKFW_GROUP" PRIMARY KEY ("GROUP_ID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_GROUP" ON "PIBICSDM2"."FW_GROUP" ("GROUP_ID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FW_GROUP" TO "BIOSAADM";
