CREATE TABLE "PIBICSDM2"."FW_LOG_BACKUP" 
   (	"SESSIONID" VARCHAR2(200 CHAR), 
	"LOGINDATE" TIMESTAMP (6) DEFAULT NULL, 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"STATUS" VARCHAR2(1 CHAR), 
	"USER_TYPE" VARCHAR2(1 CHAR), 
	"SYSTEMMESSAGE" VARCHAR2(250 CHAR), 
	"ACTION" VARCHAR2(30 CHAR), 
	"USER_ID" VARCHAR2(50 CHAR), 
	"PROGRAM_ID" VARCHAR2(30 CHAR), 
	"LOGOUT_TYPE" CHAR(1 CHAR), 
	"LOGOUT_TIME" TIMESTAMP (6) DEFAULT NULL, 
	"IPSERVER" VARCHAR2(200 CHAR), 
	"TIMELINEDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_LOG_BACKUP" ADD CONSTRAINT "XPKFW_LOG" PRIMARY KEY ("SESSIONID")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."FWLOG_IPSERVER_IDX" ON "PIBICSDM2"."FW_LOG_BACKUP" ("IPSERVER") 
  ;
CREATE INDEX "PIBICSDM2"."FWLOG_LOGINDATE_HH_IDX" ON "PIBICSDM2"."FW_LOG_BACKUP" (TO_CHAR("LOGINDATE",'YYYYMMDDHH24MISS')) 
  ;
CREATE INDEX "PIBICSDM2"."FWLOG_LOGINDATE_IDX" ON "PIBICSDM2"."FW_LOG_BACKUP" (TO_CHAR("LOGINDATE",'YYYYMMDD')) 
  ;
CREATE INDEX "PIBICSDM2"."FWLOG_LOGOUTTIME_IDX" ON "PIBICSDM2"."FW_LOG_BACKUP" ("LOGOUT_TIME") 
  ;
CREATE INDEX "PIBICSDM2"."XPKFFW_ACTION" ON "PIBICSDM2"."FW_LOG_BACKUP" ("ACTION") 
  ;
CREATE INDEX "PIBICSDM2"."XPKFFW_IPADDRESS" ON "PIBICSDM2"."FW_LOG_BACKUP" ("IPADDRESS") 
  ;
CREATE INDEX "PIBICSDM2"."XPKFFW_LOGINDATE" ON "PIBICSDM2"."FW_LOG_BACKUP" ("LOGINDATE") 
  ;
CREATE INDEX "PIBICSDM2"."XPKFFW_USERID" ON "PIBICSDM2"."FW_LOG_BACKUP" ("USER_ID") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_LOG" ON "PIBICSDM2"."FW_LOG_BACKUP" ("SESSIONID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FW_LOG_BACKUP" TO "BIOSAADM";
