CREATE TABLE "PIBICSDM2"."FW_PERMITITEM" 
   (	"ITEM_SEQ" NUMBER, 
	"ITEM_NAME" VARCHAR2(50 CHAR), 
	"CREATEDATE" TIMESTAMP (6), 
	"ITEM_DESC" VARCHAR2(50 CHAR), 
	"CREATEUSERID" VARCHAR2(20 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"LASTUPDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_PERMITITEM" ADD CONSTRAINT "XPKFW_PERMITITEM" PRIMARY KEY ("ITEM_SEQ")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XAK1FW_PERMITITEM" ON "PIBICSDM2"."FW_PERMITITEM" ("ITEM_NAME") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_PERMITITEM" ON "PIBICSDM2"."FW_PERMITITEM" ("ITEM_SEQ") 
  ;
