CREATE TABLE "PIBICSDM2"."FW_PERMITSETITEM" 
   (	"MEMBER_SEQ" NUMBER, 
	"PERMISSION_ID" NUMBER(*,0), 
	"ITEM_SEQ" NUMBER, 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"LASTUPDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_PERMITSETITEM" ADD CONSTRAINT "XPKFW_PERMITSETITEM" PRIMARY KEY ("MEMBER_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PERMITSETITEM" ADD CONSTRAINT "R_60" FOREIGN KEY ("ITEM_SEQ")
	  REFERENCES "PIBICSDM2"."FW_PERMITITEM" ("ITEM_SEQ") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PERMITSETITEM" ADD CONSTRAINT "R_62" FOREIGN KEY ("PERMISSION_ID")
	  REFERENCES "PIBICSDM2"."FW_PERMITSET" ("PERMISSION_ID") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_PERMITSETITEM" ON "PIBICSDM2"."FW_PERMITSETITEM" ("MEMBER_SEQ") 
  ;
