CREATE TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" 
   (	"SEQUS" NUMBER, 
	"USER_ID" VARCHAR2(20 CHAR), 
	"ITEM_SEQ" NUMBER, 
	"ROLE_ID" NUMBER, 
	"GROUP_ID" NUMBER, 
	"NODE_ID" NUMBER, 
	"PROGRAM_ID" VARCHAR2(25 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"MEMBER_TYPE" CHAR(1 CHAR), 
	"DISABLE" CHAR(1 CHAR), 
	"LASTUPDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "XPKFW_PROGRAM_SPECIAL" PRIMARY KEY ("SEQUS")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_31" FOREIGN KEY ("USER_ID")
	  REFERENCES "PIBICSDM2"."FW_USER" ("USER_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_30" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "PIBICSDM2"."FW_GROUP" ("GROUP_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_38" FOREIGN KEY ("NODE_ID")
	  REFERENCES "PIBICSDM2"."FW_NODEMENU" ("NODE_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_66" FOREIGN KEY ("ITEM_SEQ")
	  REFERENCES "PIBICSDM2"."FW_PERMITITEM" ("ITEM_SEQ") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_28" FOREIGN KEY ("PROGRAM_ID")
	  REFERENCES "PIBICSDM2"."FW_PROGRAMLIST" ("PROGRAM_ID") ENABLE;
  ALTER TABLE "PIBICSDM2"."FW_PROGRAM_SPECIAL" ADD CONSTRAINT "R_44" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "PIBICSDM2"."FW_ROLE" ("ROLE_ID") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_PROGRAM_SPECIAL" ON "PIBICSDM2"."FW_PROGRAM_SPECIAL" ("SEQUS") 
  ;
