CREATE TABLE "PIBICSDM2"."FW_SITECONFIG" 
   (	"ITEM_NAME" VARCHAR2(20 CHAR), 
	"ITEM_VALUE" VARCHAR2(10 CHAR), 
	"UPD_USERID" VARCHAR2(20 CHAR), 
	"LASTUPDATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."FW_SITECONFIG" ADD CONSTRAINT "XPKFW_SITECONFIG" PRIMARY KEY ("ITEM_NAME")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."XPKFW_SITECONFIG" ON "PIBICSDM2"."FW_SITECONFIG" ("ITEM_NAME") 
  ;
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."FW_SITECONFIG" TO "BIOSAADM";
