CREATE TABLE "PIBICSDM2"."GUARTBANK" 
   (	"GUARTBANK_SEQNO" NUMBER, 
	"GUARTDEPT_SEQNO" NUMBER, 
	"BANKNM" VARCHAR2(250 CHAR), 
	"BANKDESC" VARCHAR2(250 CHAR), 
	"AMOUNT" NUMBER(38,0), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."GUARTBANK" ADD CONSTRAINT "GUARTBANK_PK" PRIMARY KEY ("GUARTBANK_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."GUARTBANK_PK" ON "PIBICSDM2"."GUARTBANK" ("GUARTBANK_SEQNO") 
  ;
