CREATE TABLE "PIBICSDM2"."GUNTYPE_LOG" 
   (	"GT_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"GT_SEQNO" NUMBER, 
	"GT_GUNTYPE" VARCHAR2(60 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."GUNTYPE_LOG" ADD CONSTRAINT "GUNTYPE_LOG_PK" PRIMARY KEY ("GT_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."GUNTYPE_LOG_PK" ON "PIBICSDM2"."GUNTYPE_LOG" ("GT_LOG_SEQNO") 
  ;
