CREATE TABLE "PIBICSDM2"."HEALTHCONTROLLOG" 
   (	"FLNO" CHAR(9 CHAR), 
	"COUNTCD" CHAR(3 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE, 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"SLIPZONELOGID" NUMBER(5,0)
   ) ;
