CREATE TABLE "PIBICSDM2"."HR_RELATIVE" 
   (	"RELATIVE_SEQNO" NUMBER, 
	"RELATIVE_NAME" VARCHAR2(25 CHAR), 
	"RELATIVE_SNAME" VARCHAR2(25 CHAR), 
	"RELATIVE_HEALTHSTATUS" CHAR(1 CHAR), 
	"RELATIVE_BIRTHDATE" DATE, 
	"RELATIVE_TYPE" CHAR(1 CHAR), 
	"RELATIVE_CARDID" CHAR(13 CHAR), 
	"PROFILE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"PID" VARCHAR2(13 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."HR_RELATIVE" ADD CONSTRAINT "HR_RELATIVE_PK" PRIMARY KEY ("RELATIVE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."HR_RELATIVE_PK" ON "PIBICSDM2"."HR_RELATIVE" ("RELATIVE_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."HR_RELATIVE" TO "BIOSAADM";
