CREATE TABLE "PIBICSDM2"."HRTMP" 
   (	"PID" VARCHAR2(200 CHAR), 
	"CARD_ID" VARCHAR2(200 CHAR), 
	"RANK_CODE" VARCHAR2(200 CHAR), 
	"NAME" VARCHAR2(200 CHAR), 
	"SNAME" VARCHAR2(200 CHAR), 
	"ORG_CODE" VARCHAR2(200 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."HRTMP" TO "BIOSAADM";
