CREATE TABLE "PIBICSDM2"."IMMOVERSTAY" 
   (	"IOVSEQNO" NUMBER, 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"TDTCD" VARCHAR2(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"PASSPORTDTE" DATE, 
	"PASSPORTEXPDTE" DATE, 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(30 CHAR), 
	"REMARK" VARCHAR2(1000 CHAR), 
	"STATUS" CHAR(1 CHAR) DEFAULT 0, 
	"TM5_SEQNO" NUMBER, 
	"TM2INOUT_SEQNO" NUMBER, 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(40 CHAR), 
	"SEQNO" VARCHAR2(20 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 0, 
	"CONV_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"PERMIT_SEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"DEPTCD" CHAR(5 CHAR), 
	"EXTPERSON_SEQNO" NUMBER, 
	"EXTPERMITDTE" DATE, 
	"EXTFLAG" CHAR(1 CHAR), 
	"CHNGPERSON_SEQNO" NUMBER, 
	"CHNGPERMITDTE" DATE, 
	"CHNGFLAG" CHAR(1 CHAR), 
	"RQSPERSON_SEQNO" NUMBER, 
	"RQSPERMITDTE" DATE, 
	"RQSFLAG" CHAR(1 CHAR), 
	"FNPERSON_SEQNO" NUMBER, 
	"ALIEN_SEQNO" NUMBER, 
	"PROCESSDTE" DATE, 
	"MATCH_NAME" CHAR(1 CHAR), 
	"MATCH_NAME_WLCD" VARCHAR2(20 CHAR), 
	"MATCH_TDTNO" CHAR(1 CHAR), 
	"MATCH_TDTNO_WLCD" VARCHAR2(20 CHAR), 
	"OVSDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."IMMOVERSTAY" ADD CONSTRAINT "IMMOVERSTAY_PK" PRIMARY KEY ("IOVSEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."IMMOVERSTAY_BIRTHDTE_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("BIRTHDTE") 
  ;
CREATE INDEX "PIBICSDM2"."IMMOVERSTAY_NATIONCD_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."IMMOVERSTAY_SEX_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("SEX") 
  ;
CREATE INDEX "PIBICSDM2"."IMMOVERSTAY_VISATYPE_SEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("VISATYPE_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_ALIENSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("ALIEN_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_CHNGPERSONSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("CHNGPERSON_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_COUNTSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("COUNT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_EXTPERSONSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("EXTPERSON_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_FNPERSONSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("FNPERSON_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_INOUTDTE_IDX" ON "PIBICSDM2"."IMMOVERSTAY" (TO_CHAR("INOUTDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."IOV_PERSONID_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("PERSONID") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_PROCESSDTE_IDX" ON "PIBICSDM2"."IMMOVERSTAY" (TO_CHAR("PROCESSDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."IOV_RQSPERSONSEQNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("RQSPERSON_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IOV_TDTNO_IDX" ON "PIBICSDM2"."IMMOVERSTAY" ("TDTNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."IMMOVERSTAY_PK" ON "PIBICSDM2"."IMMOVERSTAY" ("IOVSEQNO") 
  ;
