CREATE TABLE "PIBICSDM2"."IMPORT_TMINOUT_LOG" 
   (	"TABLE_NAME" VARCHAR2(30 CHAR), 
	"NUM_ROW" NUMBER, 
	"IMPDATE" DATE, 
	"STDATE" VARCHAR2(25 CHAR), 
	"ENDATE" VARCHAR2(25 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."IMPORT_TMINOUT_LOG" TO "BIOSAADM";
