CREATE TABLE "PIBICSDM2"."INDICATECARD" 
   (	"IDC_SEQNO" NUMBER, 
	"IDCCD" CHAR(4 CHAR), 
	"IDCTNM" VARCHAR2(60 CHAR), 
	"IDCENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"BK_IDCCD" VARCHAR2(4 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."INDICATECARD" ADD CONSTRAINT "INDICATECARD_PK" PRIMARY KEY ("IDC_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INDICATECARD_PK" ON "PIBICSDM2"."INDICATECARD" ("IDC_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."INDICATECARD_U01" ON "PIBICSDM2"."INDICATECARD" ("IDCCD") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."INDICATECARD_U02" ON "PIBICSDM2"."INDICATECARD" ("IDCTNM") 
  ;
