CREATE TABLE "PIBICSDM2"."INDICATECARD_LOG" 
   (	"IDC_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"IDC_SEQNO" NUMBER, 
	"IDCCD" CHAR(4 CHAR), 
	"IDCTNM" VARCHAR2(60 CHAR), 
	"IDCENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INDICATECARD_LOG" ADD CONSTRAINT "INDICATECARD_LOG_PK" PRIMARY KEY ("IDC_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INDICATECARD_LOG_PK" ON "PIBICSDM2"."INDICATECARD_LOG" ("IDC_LOG_SEQNO") 
  ;
