CREATE TABLE "PIBICSDM2"."INPRO" 
   (	"INPRO_SEQNO" NUMBER, 
	"OFD_SEQNO" NUMBER, 
	"DPT_SEQNO" NUMBER, 
	"PRODTE" DATE, 
	"PROUSRID" VARCHAR2(60 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"AUTHORISE" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INPRO" ADD CONSTRAINT "INPRO_PK" PRIMARY KEY ("INPRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INPRO" ADD FOREIGN KEY ("DPT_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPORTEE" ("DPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INPRO" ADD FOREIGN KEY ("OFD_SEQNO")
	  REFERENCES "PIBICSDM2"."OFFENDER" ("OFD_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INPRO_PK" ON "PIBICSDM2"."INPRO" ("INPRO_SEQNO") 
  ;
