CREATE TABLE "PIBICSDM2"."INPRO_LOG" 
   (	"INPRO_SEQNO" NUMBER, 
	"OFD_SEQNO" NUMBER, 
	"DPT_SEQNO" NUMBER, 
	"PRODTE" DATE, 
	"PROUSRID" VARCHAR2(60 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"AUTHORISE" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"INPRO_LOG_SEQNO" NUMBER, 
	"PHBLOG_SEQNO" NUMBER, 
	"DPT_LOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INPRO_LOG" ADD PRIMARY KEY ("INPRO_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INPRO_LOG" ADD CONSTRAINT "INPRO_LOG_R01" FOREIGN KEY ("PHBLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."PROHIBITLOG" ("PHBLOG_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INPRO_LOG" ADD FOREIGN KEY ("DPT_SEQNO")
	  REFERENCES "PIBICSDM2"."DEPORTEE" ("DPT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INPRO_LOG" ADD FOREIGN KEY ("OFD_SEQNO")
	  REFERENCES "PIBICSDM2"."OFFENDER" ("OFD_SEQNO") ENABLE;
  ;
