CREATE TABLE "PIBICSDM2"."INSBANK" 
   (	"INSBANK_SEQNO" NUMBER, 
	"TM5_SEQNO" NUMBER, 
	"BANKNM" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."INSBANK" ADD CONSTRAINT "INSBANK_PK" PRIMARY KEY ("INSBANK_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INSBANK" ADD CONSTRAINT "INSBANK_R01" FOREIGN KEY ("TM5_SEQNO")
	  REFERENCES "PIBICSDM2"."TM5" ("TM5_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INSBANK_PK" ON "PIBICSDM2"."INSBANK" ("INSBANK_SEQNO") 
  ;
