CREATE TABLE "PIBICSDM2"."INSCASH" 
   (	"INSCASH_SEQNO" NUMBER, 
	"TM5_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."INSCASH" ADD CONSTRAINT "INSCASH_PK" PRIMARY KEY ("INSCASH_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INSCASH" ADD CONSTRAINT "INSCASH_R01" FOREIGN KEY ("TM5_SEQNO")
	  REFERENCES "PIBICSDM2"."TM5" ("TM5_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INSCASH_PK" ON "PIBICSDM2"."INSCASH" ("INSCASH_SEQNO") 
  ;
