CREATE TABLE "PIBICSDM2"."INSDEPTLOG" 
   (	"INSDEPTLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"INSDEPT_SEQNO" NUMBER, 
	"TM5_SEQNO" NUMBER, 
	"GUART_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"TM5LOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INSDEPTLOG" ADD CONSTRAINT "INSDEPTLOG_PK" PRIMARY KEY ("INSDEPTLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INSDEPTLOG" ADD CONSTRAINT "INSDEPTLOG_R01" FOREIGN KEY ("TM5LOG_SEQNO")
	  REFERENCES "PIBICSDM2"."TM5LOG" ("TM5LOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INSDEPTLOG_PK" ON "PIBICSDM2"."INSDEPTLOG" ("INSDEPTLOG_SEQNO") 
  ;
