CREATE TABLE "PIBICSDM2"."INSPRO" 
   (	"INSPRO_SEQNO" NUMBER(10,0), 
	"PHB_SEQNO" NUMBER, 
	"PRODTE" TIMESTAMP (6), 
	"PROUSRID" VARCHAR2(20 CHAR), 
	"INSPERSON" VARCHAR2(60 CHAR), 
	"INSDEPT" VARCHAR2(60 CHAR), 
	"ADDR" VARCHAR2(200 CHAR), 
	"TELNO" VARCHAR2(30 CHAR), 
	"AUTHORISE" VARCHAR2(60 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INSPRO" ADD PRIMARY KEY ("INSPRO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INSPRO" ADD CONSTRAINT "INSPRO_R01" FOREIGN KEY ("PHB_SEQNO")
	  REFERENCES "PIBICSDM2"."PROHIBIT" ("PHB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INSPRO" ADD CONSTRAINT "INSPRO_R02" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INSPRO" ADD CONSTRAINT "INSPRO_R04" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INSPRO" ADD CONSTRAINT "INSPRO_R03" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_INSPRO" ON "PIBICSDM2"."INSPRO" ("INSPRO_SEQNO") 
  ;
