CREATE TABLE "PIBICSDM2"."INT_PLAINTIFF_LOG" 
   (	"PT_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PT_SEQNO" NUMBER, 
	"PT_NAME" VARCHAR2(50 CHAR), 
	"PT_SNAME" VARCHAR2(50 CHAR), 
	"PT_IDCARD" VARCHAR2(13 CHAR), 
	"PT_ADDRESS" VARCHAR2(200 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."INT_PLAINTIFF_LOG_PK" ON "PIBICSDM2"."INT_PLAINTIFF_LOG" ("PT_LOG_SEQNO") 
  ;
