CREATE TABLE "PIBICSDM2"."INT_PLAINTIFF" 
   (	"PT_SEQNO" NUMBER, 
	"PT_NAME" VARCHAR2(50 CHAR), 
	"PT_SNAME" VARCHAR2(50 CHAR), 
	"PT_IDCARD" VARCHAR2(13 CHAR), 
	"PT_ADDRESS" VARCHAR2(200 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INT_PLAINTIFF" ADD CONSTRAINT "INT_PLAINTIFF_R01" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INT_PLAINTIFF" ADD CONSTRAINT "INT_PLAINTIFF_R02" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INT_PLAINTIFF" ADD CONSTRAINT "INT_PLAINTIFF_R03" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INT_PLAINTIFF_PK" ON "PIBICSDM2"."INT_PLAINTIFF" ("PT_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INT_PLAINTIFF" TO "BIOSAADM";
