CREATE TABLE "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" 
   (	"SPP_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"SPP_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"PROFILE_SEQNO" NUMBER, 
	"SPPRIVATEINFOLOG_SEQNO" NUMBER, 
	"SPPRIVATEINFOLOG_DATE" TIMESTAMP (6), 
	"SPPRIVATEINFOLOG_FLAG" CHAR(1 CHAR), 
	"SPPRIVATEINFOLOG_USRUPD" VARCHAR2(20 CHAR), 
	"SPP_REMARK" CLOB, 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" ADD CONSTRAINT "INV_SPPRIVATEINFO_LOG_PK" PRIMARY KEY ("SPPRIVATEINFOLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" ADD CONSTRAINT "INV_SPPRIVATEINFO_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPPRIVATEINFO_LOG_PK" ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" ("SPPRIVATEINFOLOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301603C00015$$" ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_SPPRIVATEINFO_LOG" TO "BIOSAADM";
