CREATE TABLE "PIBICSDM2"."INV_SPVEHICLE_LOG" 
   (	"SPV_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"VHC_SEQNO" NUMBER, 
	"SPV_LICENSENO" VARCHAR2(30 CHAR), 
	"PV_SEQNO" NUMBER, 
	"SPV_BRAND" VARCHAR2(50 CHAR), 
	"SPV_MODEL" VARCHAR2(50 CHAR), 
	"SPV_COLOR" VARCHAR2(50 CHAR), 
	"SPV_REMARK" VARCHAR2(500 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPV_SECURITYLEVEL" NUMBER, 
	"SPVEHICLELOG_SEQNO" NUMBER, 
	"SPVEHICLELOG_DATE" TIMESTAMP (6), 
	"SPVEHICLELOG_FLAG" CHAR(1 CHAR), 
	"SPVEHICLELOG_USRUPD" VARCHAR2(20 CHAR), 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPVEHICLE_LOG" ADD CONSTRAINT "INV_SPVEHICLE_LOG_PK" PRIMARY KEY ("SPVEHICLELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPVEHICLE_LOG" ADD CONSTRAINT "INV_SPVEHICLE_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPVEHICLE_LOG" ADD CONSTRAINT "INV_SPVEHICLE_LOG_R02" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPVEHICLE_LOG" ADD CONSTRAINT "INV_SPVEHICLE_LOG_R03" FOREIGN KEY ("VHC_SEQNO")
	  REFERENCES "PIBICSDM2"."VEHICLETYPE" ("VHC_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPVEHICLE_LOG_PK" ON "PIBICSDM2"."INV_SPVEHICLE_LOG" ("SPVEHICLELOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_SPVEHICLE_LOG" TO "BIOSAADM";
