CREATE TABLE "PIBICSDM2"."INV_PLPRIVATEINFO" 
   (	"PLP_SEQNO" NUMBER, 
	"PL_SEQNO" NUMBER, 
	"PLP_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"PROFILE_SEQNO" NUMBER, 
	"PLP_REMARK" CLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_PLPRIVATEINFO" ADD CONSTRAINT "INV_PLPRIVATEINFO_PK" PRIMARY KEY ("PLP_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_PLPRIVATEINFO" ADD CONSTRAINT "INV_PLPRIVATEINFO_R01" FOREIGN KEY ("PL_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_PLACE" ("PL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_PLPRIVATEINFO_PK" ON "PIBICSDM2"."INV_PLPRIVATEINFO" ("PLP_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301546C00011$$" ON "PIBICSDM2"."INV_PLPRIVATEINFO" (
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_PLPRIVATEINFO" TO "BIOSAADM";
