CREATE TABLE "PIBICSDM2"."INV_PLCASEHISTORY" 
   (	"PLC_SEQNO" NUMBER, 
	"PL_SEQNO" NUMBER, 
	"PLC_CASENO" VARCHAR2(20 CHAR), 
	"PLC_CASEOWNER" VARCHAR2(100 CHAR), 
	"PLC_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PLC_REMARK" CLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_PLCASEHISTORY" ADD CONSTRAINT "INV_PLCASEHISTORY_PK" PRIMARY KEY ("PLC_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_PLCASEHISTORY" ADD CONSTRAINT "INV_PLCASEHISTORY_R01" FOREIGN KEY ("PL_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_PLACE" ("PL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_PLCASEHISTORY_PK" ON "PIBICSDM2"."INV_PLCASEHISTORY" ("PLC_SEQNO") 
  ;
  ;
