CREATE TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" 
   (	"SPC_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"SPC_CASEID" VARCHAR2(10 CHAR), 
	"SPC_CASEYEAR" CHAR(4 CHAR), 
	"SPC_CASEOWNER" VARCHAR2(60 CHAR), 
	"SPC_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPCRIMINALHISLOG_SEQNO" NUMBER, 
	"SPCRIMINALHISLOG_DATE" TIMESTAMP (6), 
	"SPCRIMINALHISLOG_FLAG" CHAR(1 CHAR), 
	"SPCRIMINALHISLOG_USRUPD" VARCHAR2(20 CHAR), 
	"SPC_REMARK" CLOB, 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ADD CONSTRAINT "INV_SPCRIMINALHIS_LOG_PK" PRIMARY KEY ("SPCRIMINALHISLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ADD CONSTRAINT "INV_SPCRIMINALHIS_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPCRIMINALHIS_LOG_PK" ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ("SPCRIMINALHISLOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301569C00017$$" ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" TO "BIOSAADM";
