CREATE TABLE "PIBICSDM2"."INV_SPEXPERIENCE_LOG" 
   (	"SPEX_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"CR_SEQNO" NUMBER, 
	"SPEX_POSITION" VARCHAR2(100 CHAR), 
	"SPEX_COMPANYADDR" VARCHAR2(200 CHAR), 
	"SPEX_COMPANY" VARCHAR2(100 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"SPEX_STARTYEAR" CHAR(4 CHAR), 
	"SPEX_ENDYEAR" CHAR(4 CHAR), 
	"SPEX_REMARK" VARCHAR2(500 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPEX_SECURITYLEVEL" NUMBER, 
	"SPEXPERIENCELOG_SEQNO" NUMBER, 
	"SPEXPERIENCELOG_DATE" TIMESTAMP (6), 
	"SPEXPERIENCELOG_FLAG" CHAR(1 CHAR), 
	"SPEXPERIENCELOG_USRUPD" VARCHAR2(20 CHAR), 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPEXPERIENCE_LOG" ADD CONSTRAINT "INV_SPEXPERIENCE_LOG_PK" PRIMARY KEY ("SPEXPERIENCELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPEXPERIENCE_LOG" ADD CONSTRAINT "INV_SPEXPERIENCE_LOG_R03" FOREIGN KEY ("CR_SEQNO")
	  REFERENCES "PIBICSDM2"."CAREER" ("CR_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPEXPERIENCE_LOG" ADD CONSTRAINT "INV_SPEXPERIENCE_LOG_R02" FOREIGN KEY ("COUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPEXPERIENCE_LOG" ADD CONSTRAINT "INV_SPEXPERIENCE_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPEXPERIENCE_LOG_PK" ON "PIBICSDM2"."INV_SPEXPERIENCE_LOG" ("SPEXPERIENCELOG_SEQNO") 
  ;
