CREATE TABLE "PIBICSDM2"."INV_SPBEHAVIOR_LOG" 
   (	"SPB_SEQNO" NUMBER DEFAULT 1, 
	"SP_SEQNO" NUMBER, 
	"SPB_DATE" DATE, 
	"SPB_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPBEHAVIORLOG_SEQNO" NUMBER, 
	"SPBEHAVIORLOG_DATE" TIMESTAMP (6), 
	"SPBEHAVIORLOG_FLAG" CHAR(1 CHAR), 
	"SPBEHAVIORLOG_USRUPD" VARCHAR2(20 CHAR), 
	"SPB_BEHAVIOR" CLOB, 
	"SPB_REMARK" CLOB, 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPBEHAVIOR_LOG" ADD CONSTRAINT "INV_SPBEHAVIOR_LOG_PK" PRIMARY KEY ("SPBEHAVIORLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPBEHAVIOR_LOG" ADD CONSTRAINT "INV_SPBEHAVIOR_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPBEHAVIOR_LOG_PK" ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" ("SPBEHAVIORLOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301561C00015$$" ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301561C00016$$" ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_SPBEHAVIOR_LOG" TO "BIOSAADM";
