CREATE TABLE "PIBICSDM2"."INV_MTATTACHFILE_LOG" 
   (	"MTA_SEQNO" NUMBER, 
	"MT_SEQNO" NUMBER, 
	"MTA_FILENAME" VARCHAR2(60 CHAR), 
	"MTA_FILEPATH" VARCHAR2(60 CHAR), 
	"MTA_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"MTATTACHFILELOG_SEQNO" NUMBER, 
	"MTATTACHFILELOG_DATE" TIMESTAMP (6), 
	"MTATTACHFILELOG_FLAG" CHAR(1 CHAR), 
	"MTATTACHFILELOG_USRUPD" VARCHAR2(20 CHAR), 
	"MASTERFILELOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_MTATTACHFILE_LOG" ADD CONSTRAINT "INV_MTATTACHFILE_LOG_PK" PRIMARY KEY ("MTATTACHFILELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_MTATTACHFILE_LOG" ADD CONSTRAINT "INV_MTATTACHFILE_LOG_R01" FOREIGN KEY ("MASTERFILELOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_MASTERFILE_LOG" ("MASTERFILELOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_MTATTACHFILE_LOG_PK" ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" ("MTATTACHFILELOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."INV_MTATTACHFILE_LOG" TO "BIOSAADM";
