CREATE TABLE "PIBICSDM2"."INV_SPPLACE" 
   (	"SPP_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"SPP_PLACENAME" VARCHAR2(300 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPP_SECURITYLEVEL" NUMBER, 
	"SPP_REMARK" CLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPPLACE" ADD CONSTRAINT "INV_SPPLACE_PK" PRIMARY KEY ("SPP_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPPLACE" ADD CONSTRAINT "INV_SPPLACE_R04" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPPLACE" ADD CONSTRAINT "INV_SPPLACE_R03" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPPLACE" ADD CONSTRAINT "INV_SPPLACE_R01" FOREIGN KEY ("SP_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT" ("SP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPPLACE" ADD CONSTRAINT "INV_SPPLACE_R02" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPPLACE_PK" ON "PIBICSDM2"."INV_SPPLACE" ("SPP_SEQNO") 
  ;
  ;
