CREATE TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" 
   (	"SPC_SEQNO" NUMBER, 
	"SP_SEQNO" NUMBER, 
	"SPC_CASEID" VARCHAR2(10 CHAR), 
	"SPC_CASEYEAR" CHAR(4 CHAR), 
	"SPC_CASEOWNER" VARCHAR2(60 CHAR), 
	"SPC_SECURITYLEVEL" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"SPCRIMINALHISLOG_SEQNO" NUMBER, 
	"SPCRIMINALHISLOG_DATE" TIMESTAMP (6), 
	"SPCRIMINALHISLOG_FLAG" CHAR(1 CHAR), 
	"SPCRIMINALHISLOG_USRUPD" VARCHAR2(20 CHAR), 
	"SPC_REMARK" CLOB, 
	"SUSPECTLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ADD CONSTRAINT "INV_SPCRIMINALHIS_LOG_PK" PRIMARY KEY ("SPCRIMINALHISLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ADD CONSTRAINT "INV_SPCRIMINALHIS_LOG_R01" FOREIGN KEY ("SUSPECTLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."INV_SUSPECT_LOG" ("SUSPECTLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."INV_SPCRIMINALHIS_LOG_PK" ON "PIBICSDM2"."INV_SPCRIMINALHIS_LOG" ("SPCRIMINALHISLOG_SEQNO") 
  ;
  ;
