CREATE TABLE "PIBICSDM2"."IPSGT_PREMISES" 
   (	"CODE" VARCHAR2(10 CHAR), 
	"EN" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."IPSGT_PREMISES" ADD CONSTRAINT "IPSGT_PREMISES_PK" PRIMARY KEY ("CODE")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."IPSGT_PREMISES_PK" ON "PIBICSDM2"."IPSGT_PREMISES" ("CODE") 
  ;
