CREATE TABLE "PIBICSDM2"."JOEY" 
   (	"SEQNO" VARCHAR2(50 CHAR), 
	"CITIZENID" VARCHAR2(20 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PPS_SEQNO" VARCHAR2(4 CHAR), 
	"PASS_SEQNO" VARCHAR2(4 CHAR), 
	"TYPEDPASSPORT" VARCHAR2(4 CHAR), 
	"PASSPORTSTS" VARCHAR2(4 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."JOEY_PK" ON "PIBICSDM2"."JOEY" ("SEQNO") 
  ;
