CREATE TABLE "PIBICSDM2"."LA_EXTEND_LOG" 
   (	"EXTEND_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"EXTEND_SEQNO" NUMBER, 
	"PERSON_SEQNO" NUMBER, 
	"EXTEND_DATE" DATE, 
	"IMGPERSON" BLOB, 
	"IMGPASS" BLOB, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PASSPORT_EXPDATE" DATE, 
	"CPASSPORT_EXPDATE" DATE, 
	"VISANO" VARCHAR2(50 CHAR), 
	"VISA_EXPDATE" DATE, 
	"CVISA_EXPDATE" DATE, 
	"NOTE" VARCHAR2(500 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" CHAR(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"IPCREATE" VARCHAR2(20 CHAR), 
	"IPUPDATE" VARCHAR2(20 CHAR), 
	"UDEPT_SEQNO" NUMBER, 
	"CDEPT_SEQNO" NUMBER, 
	"UZONE_SEQNO" NUMBER, 
	"CZONE_SEQNO" NUMBER, 
	"FLAG_SEQNO" VARCHAR2(5 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."LA_EXTEND_LOG_PK" ON "PIBICSDM2"."LA_EXTEND_LOG" ("EXTEND_LOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301645C00008$$" ON "PIBICSDM2"."LA_EXTEND_LOG" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301645C00009$$" ON "PIBICSDM2"."LA_EXTEND_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."LA_EXTEND_LOG" TO "BIOSAADM";
