CREATE TABLE "PIBICSDM2"."LA_MOVESTAMP_LOG" 
   (	"MOVESTAMP_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"MOVESTAMP_SEQNO" NUMBER, 
	"PERSON_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"VISANO" VARCHAR2(50 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"BIRTHDATE" VARCHAR2(10 CHAR), 
	"BIRTHPLACE" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"OCC_SEQNO" NUMBER, 
	"OPASSPORTNO" VARCHAR2(20 CHAR), 
	"OPASSPORT_ISSUEDATE" DATE, 
	"OPASSPORT_ISSUEAT" VARCHAR2(60 CHAR), 
	"OPASSPORT_EXPDATE" DATE, 
	"NPASSPORTNO" VARCHAR2(20 CHAR), 
	"NPASSPORT_ISSUEDATE" DATE, 
	"NPASSPORT_ISSUEAT" VARCHAR2(60 CHAR), 
	"NPASSPORT_EXPDATE" DATE, 
	"ARRIVED_BY" NUMBER, 
	"ARRIVED_DATE" DATE, 
	"ARRIVED_DEPT" NUMBER, 
	"TM6NO" VARCHAR2(20 CHAR), 
	"VISA_SEQNO" NUMBER, 
	"REASONDESC" VARCHAR2(500 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"FLIGHTNO" VARCHAR2(30 CHAR), 
	"VISA_DATE" DATE, 
	"MOVESTAMP_DATE" DATE, 
	"IPCREATE" VARCHAR2(20 CHAR), 
	"IPUPDATE" VARCHAR2(20 CHAR), 
	"CDEPT_SEQNO" NUMBER, 
	"UDEPT_SEQNO" NUMBER, 
	"CZONE_SEQNO" NUMBER, 
	"UZONE_SEQNO" NUMBER, 
	"VISA_EXPDATE" DATE, 
	"REMARK" VARCHAR2(500 CHAR), 
	"REMARKTYPE" CHAR(1 CHAR), 
	"TL38" VARCHAR2(20 CHAR), 
	"NIMGPASS" BLOB, 
	"OIMGPASS" BLOB
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."LA_MOVESTAMP_LOG_PK" ON "PIBICSDM2"."LA_MOVESTAMP_LOG" ("MOVESTAMP_LOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301661C00050$$" ON "PIBICSDM2"."LA_MOVESTAMP_LOG" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301661C00051$$" ON "PIBICSDM2"."LA_MOVESTAMP_LOG" (
  ;
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."LA_MOVESTAMP_LOG" TO "BIOSAADM";
