CREATE TABLE "PIBICSDM2"."LA_VISANO_LOG" 
   (	"VISANO_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"FMT_DEPT" VARCHAR2(20 CHAR), 
	"FMT_RUNNING" NUMBER, 
	"FMT_CODE_MMR" VARCHAR2(5 CHAR), 
	"ACTFLAG" CHAR(1 CHAR) DEFAULT 'Y', 
	"FMT_CODE_LAO" VARCHAR2(5 CHAR), 
	"FMT_CODE_KHM" VARCHAR2(5 CHAR), 
	"YEAR" VARCHAR2(4 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."LA_VISANO_LOG_R01" ON "PIBICSDM2"."LA_VISANO_LOG" ("VISANO_LOG_SEQNO") 
  ;
