CREATE TABLE "PIBICSDM2"."LOGIN_NOTIFICATION" 
   (	"PAGE" VARCHAR2(20 CHAR), 
	"MESSAGE" CLOB
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."LOGIN_NOTIFICATION_PK" ON "PIBICSDM2"."LOGIN_NOTIFICATION" ("PAGE") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301680C00002$$" ON "PIBICSDM2"."LOGIN_NOTIFICATION" (
  ;
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."LOGIN_NOTIFICATION" TO "BIOSAADM";
