CREATE TABLE "PIBICSDM2"."LOGSAPI" 
   (	"LOGSAPI_SEQNO" NUMBER, 
	"API_SEQNO" NUMBER, 
	"PARAM" VARCHAR2(2000 CHAR), 
	"AGENT_SEQNO" NUMBER, 
	"PERSONID" VARCHAR2(13 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"FLAGBWL" CHAR(1 CHAR), 
	"METHOD" VARCHAR2(50 CHAR), 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"NOTE" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."LOGSAPI" ADD CONSTRAINT "LOGSAPI_PK" PRIMARY KEY ("LOGSAPI_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."LOGSAPI" ADD FOREIGN KEY ("API_SEQNO")
	  REFERENCES "PIBICSDM2"."API" ("API_SEQNO") ENABLE;
  CREATE INDEX "PIBICSDM2"."IDX_CREATEDATE" ON "PIBICSDM2"."LOGSAPI" (TO_CHAR("CREATE_DATE",'yyyyMMdd')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."LOGSAPI_PK" ON "PIBICSDM2"."LOGSAPI" ("LOGSAPI_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."LOGSAPI" TO "BIOSAADM";
