CREATE TABLE "PIBICSDM2"."MAIN_T" 
   (	"MF_SEQNO" NUMBER, 
	"MFNO1" VARCHAR2(15 CHAR), 
	"MFNAME" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."MAIN_T" ADD CONSTRAINT "MAIN_T_PK" PRIMARY KEY ("MF_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."MAIN_T_PK" ON "PIBICSDM2"."MAIN_T" ("MF_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."MAIN_T" TO "BIOSAADM";
