CREATE TABLE "PIBICSDM2"."MAIN_T" 
   (	"MF_SEQNO" NUMBER, 
	"MFNO1" VARCHAR2(15 CHAR), 
	"MFNAME" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."MAIN_T" ADD CONSTRAINT "MAIN_T_PK" PRIMARY KEY ("MF_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."MAIN_T_PK" ON "PIBICSDM2"."MAIN_T" ("MF_SEQNO") 
  ;
