CREATE TABLE "PIBICSDM2"."MAP_TAMBON" 
   (	"MTMB_SEQNO" NUMBER, 
	"MTMB_ENGNAME" VARCHAR2(500 CHAR), 
	"MTMB_THANAME" VARCHAR2(500 CHAR), 
	"MTMB_COORDINATE" CLOB, 
	"TMB_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"MAMP_CODE" NUMBER, 
	"MTMB_CODE" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."MAP_TAMBON_PK" ON "PIBICSDM2"."MAP_TAMBON" ("MTMB_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301708C00004$$" ON "PIBICSDM2"."MAP_TAMBON" (
  ;
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."MAP_TAMBON" TO "BIOSAADM";
