CREATE TABLE "PIBICSDM2"."MB_MENU_ADMIN" 
   (	"USER_ID" VARCHAR2(20 CHAR), 
	"STATUS" VARCHAR2(1 CHAR), 
	"PROGRAM_ID" VARCHAR2(25 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."MB_MENU_ADMIN" ADD CHECK ("USER_ID" IS NOT NULL) ENABLE;
  ALTER TABLE "PIBICSDM2"."MB_MENU_ADMIN" ADD CHECK ("PROGRAM_ID" IS NOT NULL) ENABLE;
  ALTER TABLE "PIBICSDM2"."MB_MENU_ADMIN" ADD PRIMARY KEY ("USER_ID", "PROGRAM_ID")
  USING INDEX  ENABLE;
  ;
