CREATE TABLE "PIBICSDM2"."MBT_ADD_C" 
   (	"ADD_CODE" VARCHAR2(3 CHAR), 
	"ADD_DESC" VARCHAR2(50 CHAR), 
	"ADD_TYPE" VARCHAR2(1 CHAR), 
	"ADD_ABBR" VARCHAR2(15 CHAR), 
	"UPD_ID" VARCHAR2(13 CHAR), 
	"UPD_ORG" CHAR(5 CHAR), 
	"UPD_DATE" TIMESTAMP (6)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."MBT_ADD_C" TO "BIOSAADM";
