CREATE TABLE "PIBICSDM2"."NTM2INOUT" 
   (	"SEQNO" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"INOUTDATE" TIMESTAMP (6), 
	"CONV_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"TM2NO" VARCHAR2(20 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"DOCTYPE" NUMBER, 
	"DOCNAT" NUMBER, 
	"DOCNO" VARCHAR2(20 CHAR), 
	"DOCISSUEDATE" TIMESTAMP (6), 
	"DOCEXPDATE" TIMESTAMP (6), 
	"PERMITDATE" TIMESTAMP (6), 
	"PERMITEXPDATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"NTM2CAR_SEQNO" NUMBER, 
	"BARCODE" VARCHAR2(20 CHAR), 
	"CARCOLOR" NUMBER, 
	"CARKIND" NUMBER, 
	"CARBRAND" NUMBER, 
	"CARTYPE" NUMBER, 
	"REMARK" VARCHAR2(500 CHAR), 
	"PROVDLT" NUMBER, 
	"WLREMARK" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."NTM2INOUT" ADD CONSTRAINT "NTM2INOUT_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."NTM2INOUT_PK" ON "PIBICSDM2"."NTM2INOUT" ("SEQNO") 
  ;
