CREATE TABLE "PIBICSDM2"."NTM2REF" 
   (	"NTM2INOUT_SEQNO" NUMBER, 
	"FWD_PAGE" VARCHAR2(3 CHAR), 
	"RELATION_CAR" CHAR(1 CHAR), 
	"INOUT_SEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."NTM2REF_PK" ON "PIBICSDM2"."NTM2REF" ("FWD_PAGE", "INOUT_SEQNO") 
  ;
