CREATE TABLE "PIBICSDM2"."OCCUPATIONLOG" 
   (	"OCCCD" CHAR(4 CHAR), 
	"OCCTNM" VARCHAR2(60 CHAR), 
	"OCCENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"OCCUPATIONLOGID" NUMBER(5,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."OCCUPATIONLOG" ADD CONSTRAINT "OCCUPATIONLOG_PK" PRIMARY KEY ("OCCUPATIONLOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OCCUPATIONLOG_PK" ON "PIBICSDM2"."OCCUPATIONLOG" ("OCCUPATIONLOGID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OCCUPATIONLOG" TO "BIOSAADM";
