CREATE TABLE "PIBICSDM2"."OCCUPATION" 
   (	"OCC_SEQNO" NUMBER, 
	"OCCCD" CHAR(4 CHAR), 
	"OCCTNM" VARCHAR2(60 CHAR), 
	"OCCENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OCCUPATION" ADD CONSTRAINT "OCCUPATION_PK" PRIMARY KEY ("OCC_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OCCUPATION" ADD CONSTRAINT "OCCUPATION_U01" UNIQUE ("OCCCD")
  USING INDEX (CREATE UNIQUE INDEX "PIBICSDM2"."OCCCD_PK" ON "PIBICSDM2"."OCCUPATION" ("OCCCD") 
  )  ENABLE;
  ALTER TABLE "PIBICSDM2"."OCCUPATION" ADD UNIQUE ("OCCCD", "OCCTNM")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OCCCD_PK" ON "PIBICSDM2"."OCCUPATION" ("OCCCD") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."OCCUPATION_PK" ON "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") 
  ;
  ;
