CREATE TABLE "PIBICSDM2"."ON_DUTY" 
   (	"PD_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"DEPT2_SEQNO" NUMBER, 
	"DEPT3_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."ON_DUTY" ADD CONSTRAINT "ON_DUTY_PK" PRIMARY KEY ("PD_SEQNO", "PROFILE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."ON_DUTY_PK" ON "PIBICSDM2"."ON_DUTY" ("PD_SEQNO", "PROFILE_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."ON_DUTY" TO "BIOSAADM";
