CREATE TABLE "PIBICSDM2"."OPERATIONREF" 
   (	"OPER_SEQNO" NUMBER, 
	"OPERCD" CHAR(2 CHAR), 
	"OPERREF" VARCHAR2(60 CHAR), 
	"OPERFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OPERATIONREF" ADD CONSTRAINT "OPERATIONREF_PK" PRIMARY KEY ("OPER_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OPERATIONREF" ADD CONSTRAINT "OPERATIONREF_U01" UNIQUE ("OPERCD")
  USING INDEX (CREATE UNIQUE INDEX "PIBICSDM2"."PK_OPERATIONREF" ON "PIBICSDM2"."OPERATIONREF" ("OPERCD") 
  )  ENABLE;
  ALTER TABLE "PIBICSDM2"."OPERATIONREF" ADD CONSTRAINT "OPERATIONREF_U02" UNIQUE ("OPERREF")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OPERATIONREF_PK" ON "PIBICSDM2"."OPERATIONREF" ("OPER_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."OPERATIONREF_U02" ON "PIBICSDM2"."OPERATIONREF" ("OPERREF") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PK_OPERATIONREF" ON "PIBICSDM2"."OPERATIONREF" ("OPERCD") 
  ;
