CREATE TABLE "PIBICSDM2"."OT_NONAUTHORIZEDLOG" 
   (	"OTNONAUTHLOGSEQNO" NUMBER, 
	"OTNONAUTHSEQNO" NUMBER, 
	"ESTIMATEYEAR" CHAR(4 CHAR), 
	"ESTIMATEMONTH" CHAR(2 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USERID" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_NONAUTHORIZEDLOG" ADD CONSTRAINT "OT_NONAUTHORIZEDLOG_PK" PRIMARY KEY ("OTNONAUTHLOGSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_NONAUTHORIZEDLOG_PK" ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" ("OTNONAUTHLOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_NONAUTHORIZEDLOG" TO "BIOSAADM";
