CREATE TABLE "PIBICSDM2"."OT_NONAUTHORIZED" 
   (	"OTNONAUTHSEQNO" NUMBER, 
	"ESTIMATEYEAR" CHAR(4 CHAR), 
	"ESTIMATEMONTH" CHAR(2 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_NONAUTHORIZED" ADD CONSTRAINT "OT_NONAUTHORIZED_PK" PRIMARY KEY ("OTNONAUTHSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_NONAUTHORIZED" ADD CONSTRAINT "OT_NONAUTHORIZED_U01" UNIQUE ("DEPT_SEQNO", "ESTIMATEMONTH", "ESTIMATEYEAR")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_NONAUTHORIZED_PK" ON "PIBICSDM2"."OT_NONAUTHORIZED" ("OTNONAUTHSEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."OT_NONAUTHORIZED_U01" ON "PIBICSDM2"."OT_NONAUTHORIZED" ("DEPT_SEQNO", "ESTIMATEMONTH", "ESTIMATEYEAR") 
  ;
