CREATE TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" 
   (	"OTSLIPDETAILLOGSEQNO" NUMBER, 
	"OTSLIPLOGSEQNO" NUMBER, 
	"OTSLIPDETAILSEQNO" NUMBER, 
	"OTSLIPSEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"OTDETAILDESC" VARCHAR2(400 CHAR), 
	"OTSLIPAMOUNT" NUMBER(10,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USERID" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_PK" PRIMARY KEY ("OTSLIPDETAILLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_R01" FOREIGN KEY ("OTSLIPLOGSEQNO")
	  REFERENCES "PIBICSDM2"."OT_OTSLIPLOG" ("OTSLIPLOGSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_R02" FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_OTSLIPDETAILLOG_PK" ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" ("OTSLIPDETAILLOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" TO "BIOSAADM";
