CREATE TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" 
   (	"OTSLIPDETAILLOGSEQNO" NUMBER, 
	"OTSLIPLOGSEQNO" NUMBER, 
	"OTSLIPDETAILSEQNO" NUMBER, 
	"OTSLIPSEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"OTDETAILDESC" VARCHAR2(400 CHAR), 
	"OTSLIPAMOUNT" NUMBER(10,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USERID" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_PK" PRIMARY KEY ("OTSLIPDETAILLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_R01" FOREIGN KEY ("OTSLIPLOGSEQNO")
	  REFERENCES "PIBICSDM2"."OT_OTSLIPLOG" ("OTSLIPLOGSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAILLOG" ADD CONSTRAINT "OT_OTSLIPDETAILLOG_R02" FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_OTSLIPDETAILLOG_PK" ON "PIBICSDM2"."OT_OTSLIPDETAILLOG" ("OTSLIPDETAILLOGSEQNO") 
  ;
