CREATE TABLE "PIBICSDM2"."OT_OTSLIPDETAIL" 
   (	"OTSLIPDETAILSEQNO" NUMBER, 
	"OTSLIPSEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"OTDETAILDESC" VARCHAR2(400 CHAR), 
	"OTSLIPAMOUNT" NUMBER(10,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAIL" ADD CONSTRAINT "OT_OTSLIPDETAIL_PK" PRIMARY KEY ("OTSLIPDETAILSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAIL" ADD CONSTRAINT "OT_OTSLIPDETAIL_R01" FOREIGN KEY ("OTSLIPSEQNO")
	  REFERENCES "PIBICSDM2"."OT_OTSLIP" ("OTSLIPSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_OTSLIPDETAIL" ADD CONSTRAINT "OT_OTSLIPDETAIL_R02" FOREIGN KEY ("PRATE_SEQNO")
	  REFERENCES "PIBICSDM2"."PAYMENTRATE" ("PRATE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_OTSLIPDETAIL_PK" ON "PIBICSDM2"."OT_OTSLIPDETAIL" ("OTSLIPDETAILSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_OTSLIPDETAIL" TO "BIOSAADM";
