CREATE TABLE "PIBICSDM2"."OT_POSCHANGEPERSONLOG" 
   (	"OTPOSPERSONLOGSEQNO" NUMBER, 
	"OTPOSCHANGELOGSEQNO" NUMBER, 
	"OTPOSCHANGESEQNO" NUMBER, 
	"OTPOSPERSONSEQNO" NUMBER, 
	"RANK_SEQNO" VARCHAR2(3 CHAR), 
	"PROFILE_SEQNO" NUMBER, 
	"POSDATE" DATE, 
	"ORGDEPT_SEQNO" NUMBER, 
	"ORGPOSLEVEL_SEQNO" NUMBER, 
	"ORGPOSNUMDAYS" NUMBER, 
	"ORGOTRATE" NUMBER(3,2), 
	"ORGOTRECEIVE" NUMBER(7,2), 
	"TOCORG" NUMBER, 
	"NEWDEPT_SEQNO" NUMBER, 
	"NEWPOSLEVEL_SEQNO" NUMBER, 
	"NEWPOSNUMDAYS" NUMBER, 
	"NEWOTRATE" NUMBER(3,2), 
	"NEWOTRECEIVE" NUMBER(7,2), 
	"TOCNEW" NUMBER, 
	"SECOTRATE" NUMBER(3,2), 
	"ACTORG" CHAR(1 CHAR), 
	"ACTNEW" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USERID" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_POSCHANGEPERSONLOG" ADD CONSTRAINT "OT_POSCHANGEPERSONLOG_PK" PRIMARY KEY ("OTPOSPERSONLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_POSCHANGEPERSONLOG" ADD CONSTRAINT "OT_POSCHANGEPERSONLOG_R01" FOREIGN KEY ("OTPOSCHANGELOGSEQNO")
	  REFERENCES "PIBICSDM2"."OT_POSCHANGELOG" ("OTPOSCHANGELOGSEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_POSCHANGEPERSONLOG" ADD CONSTRAINT "OT_POSCHANGEPERSONLOG_R06" FOREIGN KEY ("NEWPOSLEVEL_SEQNO")
	  REFERENCES "PIBICSDM2"."POSLEVEL" ("POSLEVEL_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_POSCHANGEPERSONLOG" ADD CONSTRAINT "OT_POSCHANGEPERSONLOG_R04" FOREIGN KEY ("ORGPOSLEVEL_SEQNO")
	  REFERENCES "PIBICSDM2"."POSLEVEL" ("POSLEVEL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_POSCHANGEPERSONLOG_PK" ON "PIBICSDM2"."OT_POSCHANGEPERSONLOG" ("OTPOSPERSONLOGSEQNO") 
  ;
