CREATE TABLE "PIBICSDM2"."OT_RATELOG" 
   (	"OTRATELOGSEQNO" NUMBER, 
	"OTRATESEQNO" NUMBER, 
	"POSLEVEL_SEQNO" NUMBER, 
	"OTRATE" NUMBER(3,2), 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_RATELOG" ADD CONSTRAINT "OT_RATELOG_PK" PRIMARY KEY ("OTRATELOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_RATELOG" ADD CONSTRAINT "OT_RATELOG_R01" FOREIGN KEY ("POSLEVEL_SEQNO")
	  REFERENCES "PIBICSDM2"."POSLEVEL" ("POSLEVEL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_RATELOG_PK" ON "PIBICSDM2"."OT_RATELOG" ("OTRATELOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_RATELOG" TO "BIOSAADM";
