CREATE TABLE "PIBICSDM2"."OT_RATELOG" 
   (	"OTRATELOGSEQNO" NUMBER, 
	"OTRATESEQNO" NUMBER, 
	"POSLEVEL_SEQNO" NUMBER, 
	"OTRATE" NUMBER(3,2), 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_RATELOG" ADD CONSTRAINT "OT_RATELOG_PK" PRIMARY KEY ("OTRATELOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_RATELOG" ADD CONSTRAINT "OT_RATELOG_R01" FOREIGN KEY ("POSLEVEL_SEQNO")
	  REFERENCES "PIBICSDM2"."POSLEVEL" ("POSLEVEL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_RATELOG_PK" ON "PIBICSDM2"."OT_RATELOG" ("OTRATELOGSEQNO") 
  ;
