CREATE TABLE "PIBICSDM2"."OT_SETTINGDUE" 
   (	"OSDSEQNO" NUMBER, 
	"COMMISSIONFUND" NUMBER, 
	"WARRANTFUND" NUMBER, 
	"EMPLOYEEFUND" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_SETTINGDUE_PK" ON "PIBICSDM2"."OT_SETTINGDUE" ("OSDSEQNO") 
  ;
