CREATE TABLE "PIBICSDM2"."OT_TAXLOG" 
   (	"TAXLOGSEQNO" NUMBER, 
	"TAXSEQNO" NUMBER, 
	"POSLEVEL_SEQNO" NUMBER, 
	"TAXRATE" NUMBER, 
	"ACTFLAG" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(10 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_TAXLOG" ADD CONSTRAINT "OT_TAXLOG_PK" PRIMARY KEY ("TAXLOGSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_TAXLOG" ADD CONSTRAINT "OT_TAXLOG_R01" FOREIGN KEY ("POSLEVEL_SEQNO")
	  REFERENCES "PIBICSDM2"."POSLEVEL" ("POSLEVEL_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_TAXLOG_PK" ON "PIBICSDM2"."OT_TAXLOG" ("TAXLOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_TAXLOG" TO "BIOSAADM";
