CREATE TABLE "PIBICSDM2"."OT_UNPROCESS" 
   (	"UNPSEQNO" NUMBER, 
	"ESTIMATEYEAR" CHAR(4 CHAR), 
	"ESTIMATEMONTH" CHAR(2 CHAR), 
	"PROFILE_SEQNO" NUMBER, 
	"UNWF_WATER" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."OT_UNPROCESS" ADD CONSTRAINT "OT_UNPROCESS_PK" PRIMARY KEY ("UNPSEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."OT_UNPROCESS" ADD CONSTRAINT "OT_UNPROCESS_R01" FOREIGN KEY ("PROFILE_SEQNO")
	  REFERENCES "PIBICSDM2"."HR_PROFILE" ("PROFILE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."OT_UNPROCESS_PK" ON "PIBICSDM2"."OT_UNPROCESS" ("UNPSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."OT_UNPROCESS" TO "BIOSAADM";
