CREATE TABLE "PIBICSDM2"."OVERSTAY" 
   (	"SEQNO" VARCHAR2(20 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"STATUS" CHAR(10 CHAR), 
	"CREUSR" CHAR(6 CHAR), 
	"CREDTE" DATE, 
	"VISATYPECD" CHAR(4 CHAR), 
	"PERMITCD" CHAR(4 CHAR), 
	"PERMITDTE" DATE, 
	"INDTE" DATE, 
	"OUTDTE" DATE, 
	"VISAEXPDTE" DATE, 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"TRAVCD" CHAR(4 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"OVERSTAYDAY" VARCHAR2(5 CHAR), 
	"PASSPORTEXPDTE" DATE, 
	"VISABYRIGHTS" CHAR(1 CHAR), 
	"TARGETNO" CHAR(6 CHAR), 
	"INTYPE" CHAR(1 CHAR), 
	"DEPTCD" CHAR(5 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"EXTID" NUMBER(20,0), 
	"MATCH_NAME" CHAR(1 CHAR), 
	"MATCH_NAME_WLCD" CHAR(1 CHAR), 
	"WLCD" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."OVERSTAY" ADD CONSTRAINT "SEQNO_PK1" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SEQNO_PK1" ON "PIBICSDM2"."OVERSTAY" ("SEQNO") 
  ;
