CREATE TABLE "PIBICSDM2"."PASSPORTTYPE" 
   (	"PASS_SEQNO" NUMBER, 
	"PASSNO" CHAR(4 CHAR), 
	"PASSTNM" VARCHAR2(60 CHAR), 
	"PASSENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."PASSPORTTYPE" ADD CONSTRAINT "PASSPORTTYPE_PK" PRIMARY KEY ("PASS_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_PK" ON "PIBICSDM2"."PASSPORTTYPE" ("PASS_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_U01" ON "PIBICSDM2"."PASSPORTTYPE" ("PASSNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_U02" ON "PIBICSDM2"."PASSPORTTYPE" ("PASSTNM") 
  ;
