CREATE TABLE "PIBICSDM2"."PASSPORTTYPE" 
   (	"PASS_SEQNO" NUMBER, 
	"PASSNO" CHAR(4 CHAR), 
	"PASSTNM" VARCHAR2(60 CHAR), 
	"PASSENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."PASSPORTTYPE" ADD CONSTRAINT "PASSPORTTYPE_PK" PRIMARY KEY ("PASS_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_PK" ON "PIBICSDM2"."PASSPORTTYPE" ("PASS_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_U01" ON "PIBICSDM2"."PASSPORTTYPE" ("PASSNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_U02" ON "PIBICSDM2"."PASSPORTTYPE" ("PASSTNM") 
  ;
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."PASSPORTTYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."PASSPORTTYPE" TO "APPSUSR";
