CREATE TABLE "PIBICSDM2"."PASSPORTSTATUS_LOG" 
   (	"PPS_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PPS_SEQNO" NUMBER, 
	"PPS_CODE" CHAR(1 CHAR), 
	"PPS_DESC" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PASSPORTSTATUS_LOG" ADD CONSTRAINT "PASSPORTSTATUS_LOG_PK" PRIMARY KEY ("PPS_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTSTATUS_LOG_PK" ON "PIBICSDM2"."PASSPORTSTATUS_LOG" ("PPS_LOG_SEQNO") 
  ;
