CREATE TABLE "PIBICSDM2"."PASSPORTTYPE_LOG" 
   (	"PASS_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PASS_SEQNO" NUMBER, 
	"PASSNO" CHAR(4 CHAR), 
	"PASSTNM" VARCHAR2(60 CHAR), 
	"PASSENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."PASSPORTTYPE_LOG" ADD CONSTRAINT "PASSPORTTYPE_LOG_PK" PRIMARY KEY ("PASS_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PASSPORTTYPE_LOG_PK" ON "PIBICSDM2"."PASSPORTTYPE_LOG" ("PASS_LOG_SEQNO") 
  ;
