CREATE TABLE "PIBICSDM2"."PAYMENTRATE2" 
   (	"PAYMENTRATEID" NUMBER(*,0), 
	"RATE" NUMBER(*,0) DEFAULT 0, 
	"TYPE" VARCHAR2(3 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."PAYMENTRATE2" ADD CONSTRAINT "PK_PAYMENTRATE" PRIMARY KEY ("PAYMENTRATEID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_PAYMENTRATE" ON "PIBICSDM2"."PAYMENTRATE2" ("PAYMENTRATEID") 
  ;
