CREATE TABLE "PIBICSDM2"."PERIOD_DUTY_LOG" 
   (	"PD_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PD_SEQNO" NUMBER, 
	"PD_NAME" VARCHAR2(100 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"REMARK" VARCHAR2(1000 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PERIOD_DUTY_LOG" ADD CONSTRAINT "PERIOD_DUTY_LOG_PK" PRIMARY KEY ("PD_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PERIOD_DUTY_LOG_PK" ON "PIBICSDM2"."PERIOD_DUTY_LOG" ("PD_LOG_SEQNO") 
  ;
