CREATE TABLE "PIBICSDM2"."PISCESBATCHTMP_ORG" 
   (	"BATCHLOGNO" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."PISCESBATCHTMP_ORG" TO "BIOSAADM";
