CREATE TABLE "PIBICSDM2"."PISCESIMGBKL" 
   (	"PISIMGSEQNO" NUMBER, 
	"TMRUNNO" VARCHAR2(20 CHAR), 
	"IMAGE_ID" VARCHAR2(50 CHAR), 
	"FLAGBKL" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"FILENAME" VARCHAR2(20 CHAR), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"PERSONID" VARCHAR2(50 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PISCESIMGBKL" ADD CONSTRAINT "PISCESIMGBKL_PK" PRIMARY KEY ("PISIMGSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PISCESIMGBKL_PK" ON "PIBICSDM2"."PISCESIMGBKL" ("PISIMGSEQNO") 
  ;
