CREATE TABLE "PIBICSDM2"."PISCESIMGBKL" 
   (	"PISIMGSEQNO" NUMBER, 
	"TMRUNNO" VARCHAR2(20 CHAR), 
	"IMAGE_ID" VARCHAR2(50 CHAR), 
	"FLAGBKL" CHAR(1 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"FILENAME" VARCHAR2(20 CHAR), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"PERSONID" VARCHAR2(50 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PISCESIMGBKL" ADD CONSTRAINT "PISCESIMGBKL_PK" PRIMARY KEY ("PISIMGSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PISCESIMGBKL_PK" ON "PIBICSDM2"."PISCESIMGBKL" ("PISIMGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."PISCESIMGBKL" TO "BIOSAADM";
