CREATE TABLE "PIBICSDM2"."PLACE_PERMITTYPE_LOG" 
   (	"PP_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PP_SEQNO" NUMBER, 
	"PP_PERMITNAME" VARCHAR2(100 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"PP_PERMITCODE" VARCHAR2(5 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PLACE_PERMITTYPE_LOG" ADD CONSTRAINT "PLACE_PERMITTYPE_LOG_PK" PRIMARY KEY ("PP_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PLACE_PERMITTYPE_LOG_PK" ON "PIBICSDM2"."PLACE_PERMITTYPE_LOG" ("PP_LOG_SEQNO") 
  ;
