CREATE TABLE "PIBICSDM2"."PLACE_SUBTYPE" 
   (	"PS_SEQNO" NUMBER, 
	"PS_CODE" VARCHAR2(5 CHAR), 
	"PS_NAME" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PT_CODE" VARCHAR2(5 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."PLACE_SUBTYPE" ADD CONSTRAINT "PLACE_SUBTYPE_PK" PRIMARY KEY ("PS_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PLACE_SUBTYPE_PK" ON "PIBICSDM2"."PLACE_SUBTYPE" ("PS_SEQNO") 
  ;
