CREATE TABLE "PIBICSDM2"."POLICELOCALITY" 
   (	"PL_SEQNO" NUMBER, 
	"PLTNM" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."POLICELOCALITY_PK" ON "PIBICSDM2"."POLICELOCALITY" ("PL_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."POLICELOCALITY" TO "BIOSAADM";
