CREATE TABLE "PIBICSDM2"."POLICORGANIZE_LOG" 
   (	"ORG_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"ORG_SEQNO" NUMBER, 
	"ORGCD" CHAR(4 CHAR), 
	"ORGNM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"EXTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1
   ) ;
  ALTER TABLE "PIBICSDM2"."POLICORGANIZE_LOG" ADD CONSTRAINT "POLICORGANIZE_LOG_PK" PRIMARY KEY ("ORG_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."POLICORGANIZE_LOG_PK" ON "PIBICSDM2"."POLICORGANIZE_LOG" ("ORG_LOG_SEQNO") 
  ;
