CREATE TABLE "PIBICSDM2"."POSLEVELLOG" 
   (	"POSLEVELID" CHAR(2 CHAR), 
	"POSLEVELABVNM" VARCHAR2(60 CHAR), 
	"POSLEVELFULLNM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDUSER" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"POSLEVELLOGID" NUMBER(5,0), 
	"POSLEVELENM" VARCHAR2(60 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."POSLEVELLOG" ADD CONSTRAINT "POSLEVELLOG_PK" PRIMARY KEY ("POSLEVELLOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."POSLEVELLOG_PK" ON "PIBICSDM2"."POSLEVELLOG" ("POSLEVELLOGID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."POSLEVELLOG" TO "BIOSAADM";
