CREATE TABLE "PIBICSDM2"."PROVINCE_ORN" 
   (	"PV_SEQNO" NUMBER, 
	"REG_SEQNO" NUMBER, 
	"PVCD" CHAR(2 CHAR), 
	"PV_DESC" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"NUM_HOTEL" NUMBER DEFAULT 0, 
	"PV_DESC_EN" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"PL_SEQNO" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."PROVINCE_ORN" TO "BIOSAADM";
