CREATE TABLE "PIBICSDM2"."QUE_SETUP" 
   (	"SETUP_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SETUP_YYYYMM" CHAR(6 CHAR), 
	"SYSTEM_CODE" VARCHAR2(20 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1
   ) ;
  ALTER TABLE "PIBICSDM2"."QUE_SETUP" ADD CONSTRAINT "QUE_SETUP_R02" FOREIGN KEY ("ZONE_SEQNO")
	  REFERENCES "PIBICSDM2"."ZONE" ("ZONE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."QUE_SETUP_PK" ON "PIBICSDM2"."QUE_SETUP" ("SETUP_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."QUE_SETUP" TO "BIOSAADM";
