CREATE TABLE "PIBICSDM2"."QUE_APPOINTMENT" 
   (	"APPOINTMENT_SEQNO" NUMBER, 
	"SETUP_DAYS_SEQNO" NUMBER, 
	"TIME_START" VARCHAR2(5 CHAR), 
	"TIME_END" VARCHAR2(5 CHAR), 
	"NUM_AVAILABLE" NUMBER, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."QUE_SETUP_TIMES_PK" ON "PIBICSDM2"."QUE_APPOINTMENT" ("APPOINTMENT_SEQNO") 
  ;
