CREATE TABLE "PIBICSDM2"."QUE_SETUP" 
   (	"SETUP_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SETUP_YYYYMM" CHAR(6 CHAR), 
	"SYSTEM_CODE" VARCHAR2(20 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1
   ) ;
  ALTER TABLE "PIBICSDM2"."QUE_SETUP" ADD CONSTRAINT "QUE_SETUP_R02" FOREIGN KEY ("ZONE_SEQNO")
	  REFERENCES "PIBICSDM2"."ZONE" ("ZONE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."QUE_SETUP_PK" ON "PIBICSDM2"."QUE_SETUP" ("SETUP_SEQNO") 
  ;
