CREATE TABLE "PIBICSDM2"."QUE_SETUP_LOG" 
   (	"QSETUP_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"SETUP_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SETUP_YYYYMM" CHAR(6 CHAR), 
	"SYSTEM_CODE" VARCHAR2(20 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."QUE_SETUP_LOG_PK" ON "PIBICSDM2"."QUE_SETUP_LOG" ("QSETUP_LOG_SEQNO") 
  ;
