CREATE TABLE "PIBICSDM2"."QUE_IDENTIFIED" 
   (	"IDENTIFIED_SEQNO" NUMBER, 
	"REQ_PASSPORTNO" VARCHAR2(20 CHAR), 
	"REQ_NATION_SEQNO" NUMBER, 
	"REQ_SEX" CHAR(1 CHAR), 
	"REQ_BIRTHDTE" VARCHAR2(10 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"REQ_NUM" NUMBER, 
	"REQ_TYPE" VARCHAR2(5 CHAR), 
	"VERIFY_INOUT" CHAR(1 CHAR), 
	"VERIFY_BLACKLIST" CHAR(1 CHAR), 
	"REQ_IPADDRESS" VARCHAR2(20 CHAR), 
	"REQ_IDENT_CLIENT" VARCHAR2(250 CHAR), 
	"REQ_TM6NO" VARCHAR2(20 CHAR), 
	"REQ_EFIRSTNM" VARCHAR2(60 CHAR), 
	"REQ_EFAMILYNM" VARCHAR2(60 CHAR), 
	"REQ_EMIDDLENM" VARCHAR2(60 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."QUE_IDENTIFIED" ADD CONSTRAINT "QUE_IDENTIFIED_R01" FOREIGN KEY ("REQ_NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."QUE_IDENTIFIED_PK" ON "PIBICSDM2"."QUE_IDENTIFIED" ("IDENTIFIED_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."QUE_IDENTIFIED" TO "BIOSAADM";
