CREATE TABLE "PIBICSDM2"."REASONDPT_LOG" 
   (	"REASONDPT_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"REASONDPT_SEQNO" NUMBER, 
	"REASONDPTNM" VARCHAR2(100 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."REASONDPT_LOG" ADD CONSTRAINT "REASONDPT_LOG_PK" PRIMARY KEY ("REASONDPT_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."REASONDPT_LOG_PK" ON "PIBICSDM2"."REASONDPT_LOG" ("REASONDPT_LOG_SEQNO") 
  ;
