CREATE TABLE "PIBICSDM2"."RECVTYPE" 
   (	"RECVTYPE_SEQNO" NUMBER, 
	"RECVTYPECD" CHAR(1 CHAR), 
	"RECVDESC" VARCHAR2(100 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."RECVTYPE" ADD CONSTRAINT "RECVTYPE_PK" PRIMARY KEY ("RECVTYPE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."RECVTYPE_PK" ON "PIBICSDM2"."RECVTYPE" ("RECVTYPE_SEQNO") 
  ;
