CREATE TABLE "PIBICSDM2"."REPORTBOI_FORYEAR" 
   (	"COM_SEQNO" NUMBER, 
	"COMPANYNM" VARCHAR2(1000 CHAR), 
	"EXTCOUNT" NUMBER, 
	"NAME" VARCHAR2(600 CHAR), 
	"REASONNM" VARCHAR2(2000 CHAR), 
	"NATIONSBY" VARCHAR2(60 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"EXT_DATE" DATE, 
	"PERMIT_DATE" DATE, 
	"COMPANYNM_CHECK" VARCHAR2(1000 CHAR), 
	"COMSEQNO_CHECK" NUMBER, 
	"EXTLIST_SEQNO" NUMBER, 
	"RUNNO" NUMBER, 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"AGE" VARCHAR2(3 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."REPORTBOI_FORYEAR" ADD CONSTRAINT "REPORTBOI_FORYEAR_PK" PRIMARY KEY ("EXTLIST_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."REPORTBOI_FORYEAR_PK" ON "PIBICSDM2"."REPORTBOI_FORYEAR" ("EXTLIST_SEQNO") 
  ;
