CREATE TABLE "PIBICSDM2"."REPS_PERSON_TMP" 
   (	"REPSPERSON_SEQNO" NUMBER, 
	"FAMILYNM" VARCHAR2(100 CHAR), 
	"FIRSTNM" VARCHAR2(100 CHAR), 
	"MIDDLENM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"NATIONAL_SEQNO" NUMBER, 
	"OPASSPORTNO" VARCHAR2(20 CHAR), 
	"OPASSPORT_DATE" DATE, 
	"OPASSPORTEXP_DATE" DATE, 
	"CPASSPORTNO" VARCHAR2(20 CHAR), 
	"CPASSPORT_DATE" DATE, 
	"CPASSPORTEXP_DATE" DATE, 
	"PERMIT_SEQNO" NUMBER, 
	"PERMIT_DATE" DATE, 
	"TM8_SEQNO" NUMBER, 
	"TM8NO" NUMBER, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"TM8CHILD_SEQNO" NUMBER, 
	"APPVSTS" CHAR(1 CHAR), 
	"DOCTYPE" CHAR(1 CHAR), 
	"YEAR" CHAR(4 CHAR), 
	"PERSONFLAG" CHAR(1 CHAR), 
	"VISA_SEQNO" NUMBER, 
	"VISAEND_DATE" DATE, 
	"STATUSENTRY" CHAR(1 CHAR), 
	"STATUSENTRYDTE" DATE
   ) ;
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."REPS_PERSON_TMP" TO "BIOSAADM";
