CREATE TABLE "PIBICSDM2"."REPS_TM8_LOG" 
   (	"TM8_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"TM8_SEQNO" NUMBER, 
	"TM8NO" NUMBER, 
	"YEAR" CHAR(4 CHAR), 
	"FEES_SEQNO" NUMBER, 
	"WRITTEN" NVARCHAR2(20), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"FAMILYNM" VARCHAR2(100 CHAR), 
	"FIRSTNM" VARCHAR2(100 CHAR), 
	"MIDDLENM" VARCHAR2(100 CHAR), 
	"NATIONAL_SEQNO" NUMBER, 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"AGE" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"BIRTH_PLACE" VARCHAR2(2000 CHAR), 
	"BIRTHCOUNT_SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PASSPORT_DATE" DATE, 
	"PASSPORTEXP_DATE" DATE, 
	"PASSPORTISSUEBY" VARCHAR2(2000 CHAR), 
	"CHILDNO" NUMBER(*,0), 
	"ADDR" VARCHAR2(2500 CHAR), 
	"ROAD" VARCHAR2(2500 CHAR), 
	"TMB_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"VISANO" VARCHAR2(20 CHAR), 
	"TDT_SEQNO" NUMBER, 
	"VISAISSUE" VARCHAR2(2500 CHAR), 
	"VISA_DATE" DATE, 
	"OPERMIT_SEQNO" NUMBER, 
	"ARRIVE_DATE" DATE, 
	"OPERMIT_DATE" DATE, 
	"DOCTYPE" CHAR(1 CHAR), 
	"PURPOSECOUNT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"LEAVE_DATE" DATE, 
	"RETURN_DATE" DATE, 
	"PURPOSE" VARCHAR2(2500 CHAR), 
	"APPVSTS" CHAR(1 CHAR), 
	"DOC_DATE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"PERMIT_STATUS" CHAR(1 CHAR), 
	"NEWPERMIT_DATE" DATE, 
	"REASON_SEQNO" NUMBER, 
	"REASONDESC" VARCHAR2(2500 CHAR), 
	"TM6_SEQNO" NUMBER, 
	"ENDPERMIT_DATE" DATE, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"OVISATYPE_SEQNO" NUMBER, 
	"TODAY_DATE" DATE, 
	"IMGINOUT" BLOB, 
	"TM6NO" VARCHAR2(7 CHAR), 
	"APPVSTSBYDATE" DATE, 
	"APPVSTSBYDEPT_SEQNO" NUMBER, 
	"FLAG_BOI" CHAR(1 CHAR), 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"UIPADDRESS" VARCHAR2(20 CHAR), 
	"ZONE_SEQNO" NUMBER, 
	"SUFFIX_SEQNO" NUMBER, 
	"EXTLIST_SEQNO" NUMBER, 
	"MANUALTM8" VARCHAR2(1 CHAR), 
	"REPSPERSON_SEQNO" NUMBER, 
	"TELEPHONE" VARCHAR2(500 CHAR), 
	"IMG_PERSON" BLOB, 
	"FLAG_QUEONLINE" CHAR(1 CHAR), 
	"PD_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_PK" PRIMARY KEY ("TM8_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R07" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R14" FOREIGN KEY ("OVISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R05" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R11" FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R02" FOREIGN KEY ("NATIONAL_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R04" FOREIGN KEY ("BIRTHCOUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R10" FOREIGN KEY ("PURPOSECOUNT_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R06" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R03" FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_TM8_LOG" ADD CONSTRAINT "REPS_TM8_LOG_R09" FOREIGN KEY ("OPERMIT_SEQNO")
	  REFERENCES "PIBICSDM2"."PERMITTYPE" ("PERMIT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."REPS_TM8_LOG_PK" ON "PIBICSDM2"."REPS_TM8_LOG" ("TM8_LOG_SEQNO") 
  ;
  ;
  ;
