CREATE TABLE "PIBICSDM2"."REPS_MOVESTAMP" 
   (	"MOVESTAMP_SEQNO" NUMBER, 
	"REPSPERSON_SEQNO" NUMBER, 
	"FLAGMOVE" CHAR(1 CHAR), 
	"YEAR" CHAR(4 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"BIRTH_PLACE" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"AGE" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"OPASSPORTNO" VARCHAR2(20 CHAR), 
	"OPASSPORT_PIC" VARCHAR2(50 CHAR), 
	"OPASSPORTISSUE_DATE" DATE, 
	"OPASSPORTISSUE_BY" VARCHAR2(60 CHAR), 
	"OPASSPORTEXP_DATE" DATE, 
	"NPASSPORTNO" VARCHAR2(20 CHAR), 
	"NPASSPORT_PIC" VARCHAR2(50 CHAR), 
	"NPASSPORTISSUE_DATE" DATE, 
	"NPASSPORTISSUE_BY" VARCHAR2(60 CHAR), 
	"NPASSPORTEXP_DATE" DATE, 
	"CONV_SEQNO" NUMBER, 
	"IN_DATE" DATE, 
	"PORTOFARRV_DEPT" NUMBER, 
	"TM6NO" VARCHAR2(20 CHAR), 
	"VISATYPE_SEQNO" NUMBER, 
	"REASONDESC" VARCHAR2(1000 CHAR), 
	"PERMIT_DATE" DATE, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"FLIGHTNO" VARCHAR2(30 CHAR), 
	"VISA_DATE" DATE, 
	"TM8NO" NUMBER, 
	"DOCDATE" DATE, 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"UIPADDRESS" VARCHAR2(20 CHAR), 
	"DEPT_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."REPS_MOVESTAMP" ADD CONSTRAINT "REPS_MOVESTAMP_PK" PRIMARY KEY ("MOVESTAMP_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_MOVESTAMP" ADD FOREIGN KEY ("VISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_MOVESTAMP" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_MOVESTAMP" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."REPS_MOVESTAMP" ADD FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."REPS_MOVESTAMP_PK" ON "PIBICSDM2"."REPS_MOVESTAMP" ("MOVESTAMP_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."REPS_MOVESTAMP" TO "BIOSAADM";
