CREATE TABLE "PIBICSDM2"."RESIDENTCERT" 
   (	"RES_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"RESCERTTYPE" VARCHAR2(2 CHAR), 
	"RESPVCD" VARCHAR2(3 CHAR), 
	"RESNO" VARCHAR2(20 CHAR), 
	"RESYEAR" VARCHAR2(4 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFIRSTNM" VARCHAR2(100 CHAR), 
	"TMIDDLENM" VARCHAR2(100 CHAR), 
	"TFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"NATIONCD" VARCHAR2(3 CHAR), 
	"PASSPORTNO" VARCHAR2(60 CHAR), 
	"PASSPORTEXPDTE" DATE, 
	"CRECUSR" VARCHAR2(20 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(20 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(20 CHAR), 
	"RESIMG" BLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."RESIDENTCERT" ADD PRIMARY KEY ("RES_SEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."RES_NATIONCD_IDX" ON "PIBICSDM2"."RESIDENTCERT" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."RES_NATION_SEQNO_IDX" ON "PIBICSDM2"."RESIDENTCERT" ("NATION_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."RES_PASSPORTNO_IDX" ON "PIBICSDM2"."RESIDENTCERT" ("PASSPORTNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_C00207887" ON "PIBICSDM2"."RESIDENTCERT" ("RES_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000301905C00026$$" ON "PIBICSDM2"."RESIDENTCERT" (
  ;
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."RESIDENTCERT" TO "BIOSAADM";
