CREATE TABLE "PIBICSDM2"."RQS_NONQUOTALIST" 
   (	"NONQUOTALIST_SEQNO" NUMBER, 
	"NONQUOTASTTL_SEQNO" NUMBER, 
	"NONQUOTANO" NUMBER, 
	"NONQUOTAYEAR" CHAR(4 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"AGE" NUMBER, 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"MOICODE" VARCHAR2(15 CHAR), 
	"PV_OFFICE" VARCHAR2(60 CHAR), 
	"IDNO" VARCHAR2(30 CHAR), 
	"FATHERNM" VARCHAR2(60 CHAR), 
	"MOTHERNM" VARCHAR2(60 CHAR), 
	"ADD_NO" VARCHAR2(60 CHAR), 
	"ADD_ROAD" VARCHAR2(60 CHAR), 
	"ADD_TMB" VARCHAR2(60 CHAR), 
	"ADD_AMP" VARCHAR2(60 CHAR), 
	"IN_DB" CHAR(1 CHAR), 
	"ATTDOCCHK" CHAR(1 CHAR), 
	"CRIMNALCHK" CHAR(1 CHAR), 
	"DRUGCHK" CHAR(1 CHAR), 
	"NATION" NUMBER, 
	"REMARK" VARCHAR2(2000 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."RQS_NONQUOTALIST" ADD CONSTRAINT "RQS_NONQUOTALIST_PK" PRIMARY KEY ("NONQUOTALIST_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."RQS_NONQUOTALIST_PK" ON "PIBICSDM2"."RQS_NONQUOTALIST" ("NONQUOTALIST_SEQNO") 
  ;
