CREATE TABLE "PIBICSDM2"."RQS_COMMITEE" 
   (	"COMMITEE_SEQNO" NUMBER, 
	"TMTYPE" CHAR(1 CHAR), 
	"TM_SEQNO" NUMBER, 
	"CMEETING_NO" VARCHAR2(20 CHAR), 
	"CMEETING_DATE" DATE, 
	"CREMARK" VARCHAR2(1000 CHAR), 
	"CRESOLVE" CHAR(2 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"CR_DETAIL" VARCHAR2(200 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."RQS_COMMITEE" ADD CONSTRAINT "RQS_COMMITEE_PK" PRIMARY KEY ("COMMITEE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."RQS_COMMITEE_PK" ON "PIBICSDM2"."RQS_COMMITEE" ("COMMITEE_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."RQS_COMMITEE" TO "BIOSAADM";
