CREATE TABLE "PIBICSDM2"."RQS_NONQUOTASTTL" 
   (	"NONQUOTASTTL_SEQNO" NUMBER, 
	"DOCNO" VARCHAR2(15 CHAR), 
	"DOC_DATE" DATE, 
	"STATELESS_DESC" VARCHAR2(500 CHAR), 
	"MOIDOCNO" VARCHAR2(15 CHAR), 
	"MOIDOC_DATE" DATE, 
	"PVAREA" NUMBER, 
	"AMPURAREA" NUMBER, 
	"APPVSTSTELESS_YEAR" CHAR(4 CHAR), 
	"CABINET_DATE" DATE, 
	"FEESBYREGULATION" NUMBER, 
	"FEES_DATE" DATE, 
	"INTERIORMINISTER" VARCHAR2(100 CHAR), 
	"ORDERAPPV_DATE" DATE, 
	"CIRBORDER" VARCHAR2(100 CHAR), 
	"SENTNO" VARCHAR2(15 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"STATLESS_AMOUNT" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."RQS_NONQUOTASTTL" ADD CONSTRAINT "RQS_NONQUOTASTTL_PK" PRIMARY KEY ("NONQUOTASTTL_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."RQS_NONQUOTASTTL_PK" ON "PIBICSDM2"."RQS_NONQUOTASTTL" ("NONQUOTASTTL_SEQNO") 
  ;
