CREATE TABLE "PIBICSDM2"."SEARCHWATCHLIST" 
   (	"SEQNO" VARCHAR2(20 CHAR), 
	"USERID" VARCHAR2(20 CHAR), 
	"SEARCHDTE" DATE, 
	"WLCD" VARCHAR2(7 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."SEARCHWATCHLIST" ADD CONSTRAINT "SEARCHWATCHLIST_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SEARCHWATCHLIST_PK" ON "PIBICSDM2"."SEARCHWATCHLIST" ("SEQNO") 
  ;
