CREATE TABLE "PIBICSDM2"."SEARCHLOG" 
   (	"FLAG_SEQNO" NUMBER, 
	"FLAG" CHAR(1 CHAR), 
	"USERID" VARCHAR2(20 CHAR), 
	"SEARCH_DATE" TIMESTAMP (6), 
	"PROGRAM_ID" VARCHAR2(60 CHAR), 
	"CONDITION" VARCHAR2(2000 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."SEARCHLOG" ADD CONSTRAINT "SEARCHLOG_PK" PRIMARY KEY ("FLAG_SEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."SEARCHLOG_PROGRAM_ID_IDX" ON "PIBICSDM2"."SEARCHLOG" ("PROGRAM_ID") 
  ;
CREATE INDEX "PIBICSDM2"."SL_CONDITION_IDX" ON "PIBICSDM2"."SEARCHLOG" ("CONDITION") 
  ;
CREATE INDEX "PIBICSDM2"."SL_SEARCH_DATE_IDX" ON "PIBICSDM2"."SEARCHLOG" ("SEARCH_DATE") 
  ;
CREATE INDEX "PIBICSDM2"."SL_USERID_IDX" ON "PIBICSDM2"."SEARCHLOG" ("USERID") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SEARCHLOG_PK" ON "PIBICSDM2"."SEARCHLOG" ("FLAG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SEARCHLOG" TO "BIOSAADM";
