CREATE TABLE "PIBICSDM2"."SECRETLEVEL_LOG" 
   (	"SECRET_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"SECRET_SEQNO" NUMBER, 
	"SECRETCD" VARCHAR2(2 CHAR), 
	"SECRETNM" VARCHAR2(60 CHAR), 
	"SECRETFLAG" CHAR(1 CHAR), 
	"SECRETDESC" VARCHAR2(100 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SECRETLEVEL_LOG" ADD CONSTRAINT "SECRETLEVEL_LOG_PK" PRIMARY KEY ("SECRET_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SECRETLEVEL_LOG_PK" ON "PIBICSDM2"."SECRETLEVEL_LOG" ("SECRET_LOG_SEQNO") 
  ;
