CREATE TABLE "PIBICSDM2"."SERVERINSTANCES" 
   (	"INSTANCENUMBER" NUMBER, 
	"R3PORT" VARCHAR2(4 CHAR), 
	"R2PORT" VARCHAR2(4 CHAR), 
	"STATUS" VARCHAR2(10 CHAR), 
	"TESTFLAG" CHAR(1 CHAR), 
	"URLSERV" VARCHAR2(200 CHAR), 
	"CONTEXTROOT" VARCHAR2(50 CHAR), 
	"MAIL_CONFIG" VARCHAR2(20 CHAR), 
	"MAIL_VALUE" VARCHAR2(200 CHAR), 
	"COUNT_VISIT" NUMBER, 
	"COUNT_REGIS" NUMBER, 
	"CHKRSIZE" NUMBER(6,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."SERVERINSTANCES" ADD CONSTRAINT "SERVERINSTANCES_PK" PRIMARY KEY ("INSTANCENUMBER")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SERVERINSTANCES_PK" ON "PIBICSDM2"."SERVERINSTANCES" ("INSTANCENUMBER") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SERVERINSTANCES" TO "BIOSAADM";
