CREATE TABLE "PIBICSDM2"."SETTINGWL" 
   (	"SEQNO" NUMBER, 
	"AGCPHONE" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."SETTINGWL" ADD CONSTRAINT "SETTINGWL_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SETTINGWL_PK" ON "PIBICSDM2"."SETTINGWL" ("SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SETTINGWL" TO "BIOSAADM";
