CREATE TABLE "PIBICSDM2"."SHARE_DETAIL" 
   (	"SD_SEQNO" NUMBER, 
	"SD_NAME" CHAR(60 CHAR), 
	"COUNTCD" CHAR(3 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SHARE_DETAIL" ADD CONSTRAINT "SHARE_DETAIL_PK" PRIMARY KEY ("SD_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SHARE_DETAIL_PK" ON "PIBICSDM2"."SHARE_DETAIL" ("SD_SEQNO") 
  ;
