CREATE TABLE "PIBICSDM2"."SHARE_MAIN" 
   (	"SH_SEQNO" NUMBER(20,0), 
	"MF_SEQNO" NUMBER, 
	"MFNAME" VARCHAR2(255 CHAR), 
	"HOLD_SEQNO" NUMBER, 
	"SHNUM" NUMBER, 
	"SHRECDATE" DATE, 
	"REMARK" VARCHAR2(400 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SHARE_MAIN" ADD CONSTRAINT "SHARE_MAIN_PK" PRIMARY KEY ("SH_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."SHARE_MAIN" ADD CONSTRAINT "SHARE_MAIN_R01" FOREIGN KEY ("MF_SEQNO")
	  REFERENCES "PIBICSDM2"."MAIN_T" ("MF_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."SHARE_MAIN" ADD CONSTRAINT "SHARE_MAIN_R02" FOREIGN KEY ("HOLD_SEQNO")
	  REFERENCES "PIBICSDM2"."HOLDER_TYPE_R" ("HOLD_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SHARE_MAIN_PK" ON "PIBICSDM2"."SHARE_MAIN" ("SH_SEQNO") 
  ;
