CREATE TABLE "PIBICSDM2"."SHORTDPT" 
   (	"URNO" NUMBER(10,0), 
	"FLNO" CHAR(9 CHAR), 
	"STOD" DATE, 
	"ETOD" DATE, 
	"DES3" CHAR(5 CHAR), 
	"OFBL" DATE, 
	"ACT5" CHAR(5 CHAR), 
	"REGN" CHAR(12 CHAR), 
	"VIAL" CHAR(18 CHAR), 
	"AIRB" DATE, 
	"PSTD" CHAR(6 CHAR), 
	"PAXT" CHAR(3 CHAR), 
	"FTYP" CHAR(1 CHAR), 
	"FLTI" CHAR(1 CHAR), 
	"GTD1" CHAR(5 CHAR), 
	"GD1B" CHAR(14 CHAR), 
	"GD1E" CHAR(14 CHAR), 
	"GD1X" CHAR(14 CHAR), 
	"GD1Y" CHAR(14 CHAR), 
	"GTD2" CHAR(5 CHAR), 
	"GD2B" CHAR(14 CHAR), 
	"GD2E" CHAR(14 CHAR), 
	"GD2X" CHAR(14 CHAR), 
	"GD2Y" CHAR(14 CHAR), 
	"VIAL1" CHAR(3 CHAR), 
	"VIAL2" CHAR(3 CHAR), 
	"VIAL3" CHAR(3 CHAR), 
	"VIAL4" CHAR(3 CHAR), 
	"VIAL5" CHAR(3 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."SHORTDPT" ADD CONSTRAINT "PK_SHORTDPT" PRIMARY KEY ("URNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_SHORTDPT" ON "PIBICSDM2"."SHORTDPT" ("URNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SHORTDPT" TO "BIOSAADM";
