CREATE TABLE "PIBICSDM2"."SPK_STATISTIC" 
   (	"SPKSEQNO" NUMBER, 
	"STAT_TYPE" VARCHAR2(200 CHAR), 
	"STAT_NATNAME_NO1" VARCHAR2(100 CHAR), 
	"STAT_NATNAME_NO2" VARCHAR2(100 CHAR), 
	"STAT_NATNAME_NO3" VARCHAR2(100 CHAR), 
	"STAT_NATNAME_NO4" VARCHAR2(100 CHAR), 
	"STAT_NATNAME_NO5" VARCHAR2(100 CHAR), 
	"STAT_NATAMOUNT_NO1" NUMBER DEFAULT 0, 
	"STAT_NATAMOUNT_NO2" NUMBER DEFAULT 0, 
	"STAT_NATAMOUNT_NO3" NUMBER DEFAULT 0, 
	"STAT_NATAMOUNT_NO4" NUMBER DEFAULT 0, 
	"STAT_NATAMOUNT_NO5" NUMBER DEFAULT 0, 
	"TOTAL" NUMBER DEFAULT 0, 
	"TOTALDAY" NUMBER DEFAULT 0, 
	"SPK_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."SPK_STATISTIC" ADD CONSTRAINT "SPK_STATISTIC_PK" PRIMARY KEY ("SPKSEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."SPK_SPK_DATE_IDX" ON "PIBICSDM2"."SPK_STATISTIC" (TO_CHAR("SPK_DATE",'dd/mm/yyyy')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SPK_STATISTIC_PK" ON "PIBICSDM2"."SPK_STATISTIC" ("SPKSEQNO") 
  ;
