CREATE TABLE "PIBICSDM2"."STATNATOVERSTAY" 
   (	"COUNT_SEQNO" NUMBER, 
	"IMMCARD1" NUMBER, 
	"M3_0020_M" NUMBER, 
	"M3_0020_F" NUMBER, 
	"M3_2030_M" NUMBER, 
	"M3_2030_F" NUMBER, 
	"M3_3140_M" NUMBER, 
	"M3_3140_F" NUMBER, 
	"M3_4150_M" NUMBER, 
	"M3_4150_F" NUMBER, 
	"M3_5000_M" NUMBER, 
	"M3_5000_F" NUMBER, 
	"Y1_0020_M" NUMBER, 
	"Y1_0020_F" NUMBER, 
	"Y1_2030_M" NUMBER, 
	"Y1_2030_F" NUMBER, 
	"Y1_3140_M" NUMBER, 
	"Y1_3140_F" NUMBER, 
	"Y1_4150_M" NUMBER, 
	"Y1_4150_F" NUMBER, 
	"Y1_5000_M" NUMBER, 
	"Y1_5000_F" NUMBER, 
	"Y3_0020_M" NUMBER, 
	"Y3_0020_F" NUMBER, 
	"Y3_2030_M" NUMBER, 
	"Y3_2030_F" NUMBER, 
	"Y3_3140_M" NUMBER, 
	"Y3_3140_F" NUMBER, 
	"Y3_4150_M" NUMBER, 
	"Y3_4150_F" NUMBER, 
	"Y3_5000_M" NUMBER, 
	"Y3_5000_F" NUMBER, 
	"Y5_0020_M" NUMBER, 
	"Y5_0020_F" NUMBER, 
	"Y5_2030_M" NUMBER, 
	"Y5_2030_F" NUMBER, 
	"Y5_3140_M" NUMBER, 
	"Y5_3140_F" NUMBER, 
	"Y5_4150_M" NUMBER, 
	"Y5_4150_F" NUMBER, 
	"Y5_5000_M" NUMBER, 
	"Y5_5000_F" NUMBER, 
	"MORE_0020_M" NUMBER, 
	"MORE_0020_F" NUMBER, 
	"MORE_2030_M" NUMBER, 
	"MORE_2030_F" NUMBER, 
	"MORE_3140_M" NUMBER, 
	"MORE_3140_F" NUMBER, 
	"MORE_4150_M" NUMBER, 
	"MORE_4150_F" NUMBER, 
	"MORE_5000_M" NUMBER, 
	"MORE_5000_F" NUMBER, 
	"PROCESSDTE" DATE, 
	"REMARK" VARCHAR2(1000 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."STATNATOVERSTAY" ADD CONSTRAINT "STATNATOVERSTAY_PK" PRIMARY KEY ("COUNT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."STATNATOVERSTAY_PK" ON "PIBICSDM2"."STATNATOVERSTAY" ("COUNT_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."STATNATOVERSTAY" TO "BIOSAADM";
