CREATE TABLE "PIBICSDM2"."SUPERVISORUNLOCKED" 
   (	"SPVULSEQNO" NUMBER, 
	"SUPERVISOR" VARCHAR2(20 CHAR), 
	"USERID" VARCHAR2(20 CHAR), 
	"UNLOCKEDDATE" DATE, 
	"WLCD" VARCHAR2(10 CHAR), 
	"TM6NO" VARCHAR2(10 CHAR), 
	"TDTNO" VARCHAR2(40 CHAR), 
	"INOUTDTE" DATE, 
	"CREUSR" VARCHAR2(40 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(20 CHAR), 
	"DEPT_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SUPERVISORUNLOCKED" ADD CONSTRAINT "SUPERVISORUNLOCKED_PK" PRIMARY KEY ("SPVULSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SUPERVISORUNLOCKED_PK" ON "PIBICSDM2"."SUPERVISORUNLOCKED" ("SPVULSEQNO") 
  ;
