CREATE TABLE "PIBICSDM2"."SUPERSESSION_LOG" 
   (	"SHIFT_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"SHIFT_SEQNO" NUMBER, 
	"SHIFT_NAME" VARCHAR2(50 CHAR), 
	"START_TIME" VARCHAR2(5 CHAR), 
	"STOP_TIME" VARCHAR2(5 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SUPERSESSION_LOG" ADD CONSTRAINT "SUPERSESSION_LOG_PK" PRIMARY KEY ("SHIFT_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SUPERSESSION_LOG_PK" ON "PIBICSDM2"."SUPERSESSION_LOG" ("SHIFT_LOG_SEQNO") 
  ;
