CREATE TABLE "PIBICSDM2"."SUPERSESSION" 
   (	"SHIFT_SEQNO" NUMBER, 
	"SHIFT_NAME" VARCHAR2(50 CHAR), 
	"START_TIME" VARCHAR2(5 CHAR), 
	"STOP_TIME" VARCHAR2(5 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."SUPERSESSION" ADD CONSTRAINT "SUPERSESSION_PK" PRIMARY KEY ("SHIFT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SUPERSESSION_PK" ON "PIBICSDM2"."SUPERSESSION" ("SHIFT_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SUPERSESSION" TO "BIOSAADM";
