CREATE TABLE "PIBICSDM2"."SW_EXT_PERSON_DOC_LOG" 
   (	"SW_EXT_PERSON_DOC_LOG_SEQNO" NUMBER, 
	"SW_EXT_PERSON_LOG_SEQNO" NUMBER, 
	"DOC_NAME" VARCHAR2(200 CHAR), 
	"DOC_TYPE" VARCHAR2(1 CHAR), 
	"DOC_DATE" VARCHAR2(10 CHAR), 
	"DOC_PATH" VARCHAR2(150 CHAR), 
	"VERSION" NUMBER, 
	"DOC_TYPE_SW" NUMBER, 
	"LOCAL_PATH" VARCHAR2(150 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."SW_EXT_PERSON_DOC_LOG" ADD CONSTRAINT "SW_EXT_PERSON_DOC_LOG_CK1" CHECK ( DOC_TYPE  IN ('1','2','3')) ENABLE;
  CREATE INDEX "PIBICSDM2"."SW_EXT_PERSON_LOG_SEQNO_IDX" ON "PIBICSDM2"."SW_EXT_PERSON_DOC_LOG" ("SW_EXT_PERSON_LOG_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SW_EXT_PERSON_DOC_LOG_PK" ON "PIBICSDM2"."SW_EXT_PERSON_DOC_LOG" ("SW_EXT_PERSON_DOC_LOG_SEQNO") 
  ;
