CREATE TABLE "PIBICSDM2"."SW_UPD_BOILETTER_LOG" 
   (	"SW_UPD_BOILETTER_LOG_SEQNO" NUMBER, 
	"PORT" VARCHAR2(6 CHAR), 
	"REQ_NO" VARCHAR2(20 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"FIRST_NAME" VARCHAR2(60 CHAR), 
	"MIDDLE_NAME" VARCHAR2(60 CHAR), 
	"LAST_NAME" VARCHAR2(60 CHAR), 
	"PASSPORT_NO" VARCHAR2(20 CHAR), 
	"NATIONALITY" VARCHAR2(3 CHAR), 
	"CALLBY_PROGRAM_ID" VARCHAR2(25 CHAR), 
	"CALLBY_USER" VARCHAR2(20 CHAR), 
	"CALLBY_IPADDRESS" VARCHAR2(20 CHAR), 
	"CALL_DATE" TIMESTAMP (6)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."SW_UPD_BOILETTER_LOG_PK" ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" ("SW_UPD_BOILETTER_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."SW_UPD_BOILETTER_LOG" TO "BIOSAADM";
