CREATE TABLE "PIBICSDM2"."T_ONLINE_PWD" 
   (	"USERID" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PWD" VARCHAR2(20 CHAR), 
	"STATUS" CHAR(1 CHAR), 
	"WARNING" VARCHAR2(250 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."T_ONLINE_PWD_PK" ON "PIBICSDM2"."T_ONLINE_PWD" ("USERID") 
  ;
