CREATE TABLE "PIBICSDM2"."TEMPDOCSTMINOUT" 
   (	"DOCSEQNO" NUMBER, 
	"SEQNO" VARCHAR2(100 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"TDTCD" VARCHAR2(4 CHAR), 
	"TDTNO" VARCHAR2(60 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"IMGDOC" BLOB, 
	"REMARK" VARCHAR2(1000 CHAR), 
	"CREUSR" VARCHAR2(30 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(20 CHAR), 
	"UPDUSR" VARCHAR2(30 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TEMPDOCSTMINOUT" ADD CONSTRAINT "TEMPDOCSTMINOUT_PK" PRIMARY KEY ("DOCSEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."TMPDTM_CREUSR_IDX" ON "PIBICSDM2"."TEMPDOCSTMINOUT" ("CREUSR") 
  ;
CREATE INDEX "PIBICSDM2"."TMPDTM_SEQNO_IDX" ON "PIBICSDM2"."TEMPDOCSTMINOUT" ("SEQNO") 
  ;
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TEMPDOCSTMINOUT_PK" ON "PIBICSDM2"."TEMPDOCSTMINOUT" ("DOCSEQNO") 
  ;
