CREATE TABLE "PIBICSDM2"."TESTWLCD" 
   (	"WLCD" VARCHAR2(50 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TESTWLCD" TO "BIOSAADM";
