CREATE TABLE "PIBICSDM2"."THAIPASSPORTHIST" 
   (	"CITIZENID" CHAR(13 CHAR), 
	"SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(12 CHAR), 
	"PASSNO" CHAR(4 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"MICROROLLNO" VARCHAR2(4 CHAR), 
	"MICROPICNO" VARCHAR2(10 CHAR), 
	"MICROPICNOL" VARCHAR2(4 CHAR), 
	"PASSPORTDTE" DATE, 
	"PASSPORTEXPDTE" DATE, 
	"PASSPORTSTS" CHAR(1 CHAR)
   ) ;
  CREATE INDEX "PIBICSDM2"."THAIPASSPORTHIST1_IDX1" ON "PIBICSDM2"."THAIPASSPORTHIST" ("CITIZENID", "PASSNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PK_THAIPASSPORTHIST1" ON "PIBICSDM2"."THAIPASSPORTHIST" ("CITIZENID", "SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."THAIPASSPORTHIST" TO "BIOSAADM";
