CREATE TABLE "PIBICSDM2"."TM1BLCHK" 
   (	"TDTNO" VARCHAR2(30 CHAR), 
	"NATIONTNM" VARCHAR2(50 CHAR), 
	"COUNTCD" VARCHAR2(10 CHAR), 
	"CHECKEXT" CHAR(1 CHAR), 
	"CHECKCHNGVISA" CHAR(1 CHAR), 
	"CHECKFN90" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"ABBCOUNT" VARCHAR2(10 CHAR), 
	"EXT_DEPT" NUMBER, 
	"CHNGVISA_DEPT" NUMBER, 
	"FN90_DEPT" NUMBER, 
	"ID" NUMBER, 
	"MONTH" NUMBER, 
	"CHECKIN" CHAR(1 CHAR), 
	"INDTE" DATE, 
	"CHECKOUT" CHAR(1 CHAR), 
	"OUTDTE" DATE
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM1BLCHK_PK" ON "PIBICSDM2"."TM1BLCHK" ("ID", "MONTH") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TM1BLCHK" TO "BIOSAADM";
