CREATE TABLE "PIBICSDM2"."TM2CAR" 
   (	"TM2CAR_SEQNO" NUMBER, 
	"TM2_SEQNO" NUMBER, 
	"KIND" VARCHAR2(250 CHAR), 
	"COLOR" VARCHAR2(250 CHAR), 
	"BAND" VARCHAR2(250 CHAR), 
	"PLATENO" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TM2CAR" TO "BIOSAADM";
