CREATE TABLE "PIBICSDM2"."TM2LOG" 
   (	"TM2LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"TM2_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"IODTE" TIMESTAMP (6), 
	"CARDTYPE" CHAR(1 CHAR), 
	"CONVNM" VARCHAR2(250 CHAR), 
	"CONVNATIONCD" NUMBER, 
	"CONVREGNO" VARCHAR2(50 CHAR), 
	"CONVOWNER" VARCHAR2(250 CHAR), 
	"TM2DEPT" NUMBER, 
	"IOCOUNTCD" NUMBER, 
	"IOPORTNM" VARCHAR2(250 CHAR), 
	"TM5_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"TM2NO" VARCHAR2(20 CHAR), 
	"TM2DTE" DATE, 
	"TM2USR" VARCHAR2(250 CHAR), 
	"FLIGHTNO" VARCHAR2(25 CHAR), 
	"CONVCODE" VARCHAR2(20 CHAR), 
	"IONOTE" VARCHAR2(250 CHAR), 
	"IODEPT" NUMBER, 
	"IODEPTTH" NUMBER, 
	"AMOUNT_CRW" NUMBER, 
	"AMOUNT_PSG" NUMBER, 
	"AMOUNT_IO" NUMBER, 
	"AMOUNT_T" NUMBER, 
	"AMOUNT_S" NUMBER, 
	"CONVTYPE_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"TM2MAIN_SEQNO" NUMBER, 
	"NOTE" VARCHAR2(500 CHAR), 
	"CREATE_IP" VARCHAR2(25 CHAR), 
	"UPDATE_IP" VARCHAR2(25 CHAR), 
	"SHIFT_SEQNO" NUMBER, 
	"PD_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TM2LOG" ADD CONSTRAINT "TM2LOG_PK" PRIMARY KEY ("TM2LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TM2LOG" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TM2LOG" ADD FOREIGN KEY ("CONVNATIONCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TM2LOG" ADD FOREIGN KEY ("IOCOUNTCD")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TM2LOG" ADD CONSTRAINT "TM2LOG_R01" FOREIGN KEY ("CONVTYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVTYPE" ("CONVTYPE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM2LOG_PK" ON "PIBICSDM2"."TM2LOG" ("TM2LOG_SEQNO") 
  ;
