CREATE TABLE "PIBICSDM2"."TM2MAINLOG" 
   (	"TM2MAINLOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"TM2MAIN_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVNATIONCD" NUMBER, 
	"CONVREGNO" VARCHAR2(50 CHAR), 
	"TM2_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"DEPT_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TM2MAINLOG" ADD CONSTRAINT "TM2MAINLOG_PK" PRIMARY KEY ("TM2MAINLOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM2MAINLOG_PK" ON "PIBICSDM2"."TM2MAINLOG" ("TM2MAINLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TM2MAINLOG" TO "BIOSAADM";
