CREATE TABLE "PIBICSDM2"."TM5LOG" 
   (	"TM5LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"TM5_SEQNO" NUMBER, 
	"INDEPT_SEQNO" NUMBER, 
	"INSTYPE" CHAR(1 CHAR), 
	"INSSTATUS" CHAR(1 CHAR), 
	"FLAG" CHAR(1 CHAR), 
	"AMOUNT" NUMBER, 
	"TM2_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CHKDEPT_SEQNO" NUMBER, 
	"NOTE" VARCHAR2(250 CHAR), 
	"GUARANTOR" VARCHAR2(250 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TM5LOG" ADD CONSTRAINT "TM5LOG_PK" PRIMARY KEY ("TM5LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TM5LOG" ADD FOREIGN KEY ("TM2_SEQNO")
	  REFERENCES "PIBICSDM2"."TM2" ("TM2_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM5LOG_PK" ON "PIBICSDM2"."TM5LOG" ("TM5LOG_SEQNO") 
  ;
