CREATE TABLE "PIBICSDM2"."TM5LOG" 
   (	"TM5LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"TM5_SEQNO" NUMBER, 
	"INDEPT_SEQNO" NUMBER, 
	"INSTYPE" CHAR(1 CHAR), 
	"INSSTATUS" CHAR(1 CHAR), 
	"FLAG" CHAR(1 CHAR), 
	"AMOUNT" NUMBER, 
	"TM2_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 1, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CHKDEPT_SEQNO" NUMBER, 
	"NOTE" VARCHAR2(250 CHAR), 
	"GUARANTOR" VARCHAR2(250 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TM5LOG" ADD CONSTRAINT "TM5LOG_PK" PRIMARY KEY ("TM5LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TM5LOG" ADD FOREIGN KEY ("TM2_SEQNO")
	  REFERENCES "PIBICSDM2"."TM2" ("TM2_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM5LOG_PK" ON "PIBICSDM2"."TM5LOG" ("TM5LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TM5LOG" TO "BIOSAADM";
