CREATE TABLE "PIBICSDM2"."TM61_TRANSFER_ROUNDTIME" 
   (	"ROUNDNO" NUMBER, 
	"STARTTIME" VARCHAR2(18 CHAR), 
	"ENDTIME" VARCHAR2(18 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM61_TRANSFER_ROUNDTIME_PK" ON "PIBICSDM2"."TM61_TRANSFER_ROUNDTIME" ("ROUNDNO") 
  ;
