CREATE TABLE "PIBICSDM2"."TM6_PIC" 
   (	"TM6_SEQNO" NUMBER, 
	"TRAV_SEQNO" NUMBER, 
	"TM6NO" VARCHAR2(20 CHAR), 
	"IMGTM6" BLOB, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TM6_PIC" ADD CONSTRAINT "TM6_PIC_PK" PRIMARY KEY ("TM6_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302081C00004$$" ON "PIBICSDM2"."TM6_PIC" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TM6_PIC_PK" ON "PIBICSDM2"."TM6_PIC" ("TM6_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TM6_PIC" TO "BIOSAADM";
