CREATE TABLE "PIBICSDM2"."TM_PUBFILE_LOG" 
   (	"PF_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(20 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"PF_SEQNO" NUMBER(*,0), 
	"PF_FILENAME" VARCHAR2(500 CHAR), 
	"PF_FILEDETAIL" VARCHAR2(2000 CHAR), 
	"PF_STATUS" CHAR(1 CHAR), 
	"PF_FILEPATH" VARCHAR2(1000 CHAR), 
	"PF_OWNER" VARCHAR2(1000 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PF_FILESIZE" VARCHAR2(10 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TM_PUBFILE_LOG" ADD CONSTRAINT "TM_PUBLICFILE_LOG_PK" PRIMARY KEY ("PF_LOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TM_PUBLICFILE_LOG_PK" ON "PIBICSDM2"."TM_PUBFILE_LOG" ("PF_LOG_SEQNO") 
  ;
