CREATE TABLE "PIBICSDM2"."TMINOUTJOINPASS" 
   (	"SEQNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"DEPTCD" VARCHAR2(5 CHAR), 
	"TRAVCD" CHAR(4 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"TDTCD" CHAR(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"PERMITCD" CHAR(4 CHAR), 
	"NEWPERMIT" DATE, 
	"PASSPORTDTE" DATE, 
	"PASSPORTISU" VARCHAR2(60 CHAR), 
	"PASSPORTEXPDTE" DATE, 
	"TARGETNO" VARCHAR2(7 CHAR), 
	"INTYPE" CHAR(1 CHAR), 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"CREUSR" VARCHAR2(20 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(30 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(30 CHAR), 
	"ISPROCESS" CHAR(1 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"REMARK" VARCHAR2(1500 CHAR), 
	"RESCERTNO" VARCHAR2(20 CHAR), 
	"IMGINOUT" BLOB, 
	"FLAGTM6NO" VARCHAR2(20 CHAR), 
	"FLAGOVERSTAY" VARCHAR2(20 CHAR), 
	"FLAGWATCHLIST" VARCHAR2(20 CHAR), 
	"REASONCD" CHAR(4 CHAR), 
	"EXTID" NUMBER(20,0), 
	"PM_RE_ENTRY" VARCHAR2(20 CHAR), 
	"PM_REEXPDTE" DATE, 
	"PM_EXTENSION" VARCHAR2(20 CHAR), 
	"PM_EXEXPDTE" DATE, 
	"PM_NON_QUOTA" VARCHAR2(20 CHAR), 
	"PM_NONEXPDTE" DATE, 
	"STATUS" CHAR(1 CHAR), 
	"TM5_SEQNO" NUMBER, 
	"TM2INOUT_SEQNO" NUMBER, 
	"IMGPASS" BLOB, 
	"FLAGPASS" NUMBER, 
	"ACTIONCAPTUREPASS" VARCHAR2(15 CHAR), 
	"MOVEIMM2IMMHIST" CHAR(1 CHAR), 
	"RPJSEQNO" NUMBER, 
	"FLAGUPDATEREENTRY" VARCHAR2(12 CHAR), 
	"REPSPERSON_SEQNO" NUMBER, 
	"FLAGUPDATEEXTENSION" VARCHAR2(12 CHAR), 
	"EXTPERSON_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"PERMIT_SEQNO" NUMBER, 
	"FLAGUPDATERQS" VARCHAR2(12 CHAR), 
	"RQSPERSON_SEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"FLAGJOINPASS" CHAR(1 CHAR), 
	"FLAGFINES" CHAR(1 CHAR), 
	"PERMITDAY" VARCHAR2(10 CHAR), 
	"FLAGUPDATECHNG" VARCHAR2(12 CHAR), 
	"CHNGPERSON_SEQNO" NUMBER, 
	"FLAGVISARUN" CHAR(1 CHAR), 
	"ACTIONVISARUN" CHAR(1 CHAR), 
	"VSRPERSONSEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"PD_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SHIFT_SEQNO" NUMBER, 
	"NEWPERSON" CHAR(1 CHAR), 
	"FLAGUPDATEIMAGEPASS" CHAR(1 CHAR), 
	"VOAL_SEQNO" NUMBER, 
	"VOA_PERSON" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMINOUTJOINPASS" ADD CONSTRAINT "TMINOUTJOINPASS2_PK" PRIMARY KEY ("SEQNO", "CREUSR")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302102C00046$$" ON "PIBICSDM2"."TMINOUTJOINPASS" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302102C00061$$" ON "PIBICSDM2"."TMINOUTJOINPASS" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TMINOUTJOINPASS2_PK" ON "PIBICSDM2"."TMINOUTJOINPASS" ("SEQNO", "CREUSR") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMINOUTJOINPASS" TO "BIOSAADM";
