CREATE TABLE "PIBICSDM2"."TMINOUT" 
   (	"SEQNO" VARCHAR2(100 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"DEPTCD" VARCHAR2(5 CHAR), 
	"TRAVCD" CHAR(4 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"TDTCD" VARCHAR2(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"PASSPORTDTE" DATE, 
	"PASSPORTISU" VARCHAR2(60 CHAR), 
	"PASSPORTEXPDTE" DATE, 
	"TARGETNO" VARCHAR2(7 CHAR), 
	"INTYPE" CHAR(1 CHAR), 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"CREUSR" VARCHAR2(20 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(30 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(30 CHAR), 
	"ISPROCESS" CHAR(1 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"REMARK" VARCHAR2(1500 CHAR), 
	"RESCERTNO" VARCHAR2(20 CHAR), 
	"IMGINOUT" BLOB, 
	"PM_RE_ENTRY" VARCHAR2(20 CHAR), 
	"PM_REEXPDTE" DATE, 
	"PM_EXTENSION" VARCHAR2(20 CHAR), 
	"PM_EXEXPDTE" DATE, 
	"PM_NON_QUOTA" VARCHAR2(20 CHAR), 
	"PM_NONEXPDTE" DATE, 
	"STATUS" CHAR(1 CHAR), 
	"TM5_SEQNO" NUMBER, 
	"TM2INOUT_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 0, 
	"RPJSEQNO" NUMBER, 
	"PERMITCD" CHAR(4 CHAR), 
	"NEWPERMIT" DATE, 
	"CONV_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"PERMIT_SEQNO" NUMBER, 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"PASS_SEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"TYPEDATA" VARCHAR2(20 CHAR), 
	"DEPTCDORG" CHAR(5 CHAR), 
	"FLAGJOINPASS" CHAR(1 CHAR), 
	"FLAGFINES" CHAR(1 CHAR), 
	"RESCERTTYPE" VARCHAR2(4 CHAR), 
	"RESPVCD" VARCHAR2(3 CHAR), 
	"RESNOYEAR" VARCHAR2(20 CHAR), 
	"PV_SEQNO" NUMBER, 
	"PD_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SHIFT_SEQNO" NUMBER
   ) ;
  CREATE INDEX "PIBICSDM2"."IDX$$_297B90001" ON "PIBICSDM2"."TMINOUT" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."IDX$$_297B90002" ON "PIBICSDM2"."TMINOUT" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."IDX$$_297B90003" ON "PIBICSDM2"."TMINOUT" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_COMPOSITE_IDX1" ON "PIBICSDM2"."TMINOUT" ("NATIONCD", "BIRTHDTE", "SEX") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_COMPOSITE_IDX2" ON "PIBICSDM2"."TMINOUT" ("NATIONCD", "BIRTHDTE", "SEX", "TDTNO", "EFAMILYNM", "EFIRSTNM", "EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX1" ON "PIBICSDM2"."TMINOUT" (TRIM("TFIRSTNM"), TRIM("TFAMILYNM")) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX10" ON "PIBICSDM2"."TMINOUT" (REPLACE("EFAMILYNM"||"EFIRSTNM"||"EMIDDLENM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX11" ON "PIBICSDM2"."TMINOUT" (REPLACE("EFAMILYNM"||"EMIDDLENM"||"EFIRSTNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX12" ON "PIBICSDM2"."TMINOUT" (REPLACE("EMIDDLENM"||"EFIRSTNM"||"EFAMILYNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX13" ON "PIBICSDM2"."TMINOUT" (REPLACE("EMIDDLENM"||"EFAMILYNM"||"EFIRSTNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX14" ON "PIBICSDM2"."TMINOUT" (REPLACE("TFIRSTNM"||"TFAMILYNM"||"TMIDDLENM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX15" ON "PIBICSDM2"."TMINOUT" (REPLACE("TFIRSTNM"||"TMIDDLENM"||"TFAMILYNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX16" ON "PIBICSDM2"."TMINOUT" (REPLACE("TFAMILYNM"||"TFIRSTNM"||"TMIDDLENM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX17" ON "PIBICSDM2"."TMINOUT" (REPLACE("TFAMILYNM"||"TMIDDLENM"||"TFIRSTNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX18" ON "PIBICSDM2"."TMINOUT" (REPLACE("TMIDDLENM"||"TFIRSTNM"||"TFAMILYNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX19" ON "PIBICSDM2"."TMINOUT" (REPLACE("TMIDDLENM"||"TFAMILYNM"||"TFIRSTNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX2" ON "PIBICSDM2"."TMINOUT" (TRIM("EFIRSTNM"), TRIM("EFAMILYNM")) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX3" ON "PIBICSDM2"."TMINOUT" ("TFAMILYNM", "TFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX4" ON "PIBICSDM2"."TMINOUT" ("FLIGHTPREFIX"||"FLIGHTNUMBER", "INOUTDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX5" ON "PIBICSDM2"."TMINOUT" ("TFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX6" ON "PIBICSDM2"."TMINOUT" ("TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX7" ON "PIBICSDM2"."TMINOUT" (SUBSTR("BIRTHDTE",-4,4)) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX8" ON "PIBICSDM2"."TMINOUT" (REPLACE("EFIRSTNM"||"EFAMILYNM"||"EMIDDLENM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_IDX9" ON "PIBICSDM2"."TMINOUT" (REPLACE("EFIRSTNM"||"EMIDDLENM"||"EFAMILYNM",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_PASSPORTNO_IDX" ON "PIBICSDM2"."TMINOUT" ("TDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMINOUT_PERSONID_IDX2" ON "PIBICSDM2"."TMINOUT" ("PERSONID") 
  ;
CREATE INDEX "PIBICSDM2"."TM_BIRHTDTE_IDX" ON "PIBICSDM2"."TMINOUT" ("BIRTHDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TM_CITIZENID_IDX" ON "PIBICSDM2"."TMINOUT" ("CITIZENID") 
  ;
CREATE INDEX "PIBICSDM2"."TM_CONVREGNO_IDX" ON "PIBICSDM2"."TMINOUT" ("CONVREGNO") 
  ;
CREATE INDEX "PIBICSDM2"."TM_CREDTEDATE_IDX" ON "PIBICSDM2"."TMINOUT" ("CREATE_DATE") 
  ;
CREATE INDEX "PIBICSDM2"."TM_CREDTE_IDX" ON "PIBICSDM2"."TMINOUT" ("CREDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TM_CREDTE_IDX1" ON "PIBICSDM2"."TMINOUT" (TO_CHAR("CREDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TM_CREUSR_IDX" ON "PIBICSDM2"."TMINOUT" ("CREUSR") 
  ;
CREATE INDEX "PIBICSDM2"."TM_DEPTCD_IDX" ON "PIBICSDM2"."TMINOUT" ("DEPTCD") 
  ;
CREATE INDEX "PIBICSDM2"."TM_DEPT_SEQNO_IDX" ON "PIBICSDM2"."TMINOUT" ("DEPT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TM_INOUTDTE_IDX" ON "PIBICSDM2"."TMINOUT" ("INOUTDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TM_INOUTDTE_IDX1" ON "PIBICSDM2"."TMINOUT" (TO_CHAR("INOUTDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TM_NATIONCD_IDX" ON "PIBICSDM2"."TMINOUT" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."TM_TM6NO_IDX" ON "PIBICSDM2"."TMINOUT" ("TM6NO") 
  ;
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TMINOUT_MA_PK" ON "PIBICSDM2"."TMINOUT" ("SEQNO") 
  ;
