CREATE TABLE "PIBICSDM2"."TMINFORMDEADLOG" 
   (	"TMINFDEADLOGSEQNO" NUMBER, 
	"TMINFDEADSEQNO" NUMBER, 
	"TMRUNNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"DEPTCD" VARCHAR2(5 CHAR), 
	"TRAVCD" CHAR(4 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"TDTCD" CHAR(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"PASSPORTDTE" DATE, 
	"PASSPORTEXPDTE" DATE, 
	"INTYPE" CHAR(1 CHAR), 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"CREUSR" VARCHAR2(20 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(30 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(30 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"REMARK" VARCHAR2(1000 CHAR), 
	"RESCERTNO" VARCHAR2(20 CHAR), 
	"IMGINOUT" BLOB, 
	"PERMITCD" CHAR(4 CHAR), 
	"PERMITDTE" DATE, 
	"CONV_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"PERMIT_SEQNO" NUMBER, 
	"LOGUSERID" VARCHAR2(20 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"TMDEPT_SEQNO" NUMBER, 
	"DATEOFDEATH" DATE, 
	"REASONOFDEATH" VARCHAR2(1000 CHAR), 
	"CERTIFICATEOFDEATH" VARCHAR2(20 CHAR), 
	"OFFICEOFREGIS" VARCHAR2(400 CHAR), 
	"INFORMOFDEATH" VARCHAR2(150 CHAR), 
	"INFORMOFID13" VARCHAR2(13 CHAR), 
	"INFORMOFRELATION" VARCHAR2(150 CHAR), 
	"DELREMARK" VARCHAR2(1000 CHAR), 
	"INFORMPV_SEQNO" NUMBER, 
	"FORMBASE" VARCHAR2(20 CHAR), 
	"PV_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMINFORMDEADLOG" ADD CONSTRAINT "TMINFORMDEADLOG_PK" PRIMARY KEY ("TMINFDEADLOGSEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_BIRTHDTE_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("BIRTHDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_CARDTYPE_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("CARDTYPE") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_CREDTE_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" (TO_NUMBER(TO_CHAR("CREDTE",'YYYYMMDD'))) 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_CREUSR_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("CREUSR") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_EFAMILYNM_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_EFIRSTNM_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_EMIDDLENM_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_NATIONCD_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_RESCERTNO_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("RESCERTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_SEX_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("SEX") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_TDTNO_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("TDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_TFAMILYNM_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_TFIRSTNM_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("TFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMINFORMDEADLOG_TM6NO_IDX" ON "PIBICSDM2"."TMINFORMDEADLOG" ("TM6NO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302090C00043$$" ON "PIBICSDM2"."TMINFORMDEADLOG" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TMINFORMDEADLOG_PK" ON "PIBICSDM2"."TMINFORMDEADLOG" ("TMINFDEADLOGSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMINFORMDEADLOG" TO "BIOSAADM";
