CREATE TABLE "PIBICSDM2"."TMMAIN_PIS" 
   (	"TMRUNNO" VARCHAR2(20 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"INSEQNO" VARCHAR2(20 CHAR), 
	"INDTE" DATE, 
	"INDEPTCD" CHAR(5 CHAR), 
	"INTRAVCD" CHAR(4 CHAR), 
	"INCONVCD" CHAR(4 CHAR), 
	"INCONVREGNO" VARCHAR2(20 CHAR), 
	"INTDTCD" CHAR(4 CHAR), 
	"INTDTNO" VARCHAR2(20 CHAR), 
	"INTM6NO" VARCHAR2(20 CHAR), 
	"INVISATYPECD" CHAR(4 CHAR), 
	"INPERMITCD" CHAR(4 CHAR), 
	"INPERMITDTE" DATE, 
	"INPASSPORTDTE" DATE, 
	"INPASSPORTISU" VARCHAR2(60 CHAR), 
	"INPASSPORTEXPDTE" DATE, 
	"VISANO" VARCHAR2(20 CHAR), 
	"VISAISSUE" VARCHAR2(60 CHAR), 
	"VISADTE" DATE, 
	"VISABYRIGHTS" CHAR(1 CHAR), 
	"INCHKPOINTNO" VARCHAR2(10 CHAR), 
	"INCREUSR" CHAR(6 CHAR), 
	"INCREDTE" DATE, 
	"INCREDTERM" VARCHAR2(30 CHAR), 
	"INUPDUSR" CHAR(6 CHAR), 
	"INUPDDTE" DATE, 
	"INUPDTERM" VARCHAR2(30 CHAR), 
	"INPROCESSUSR" VARCHAR2(30 CHAR), 
	"INPROCESSDTE" DATE, 
	"INPROCESSTERM" VARCHAR2(30 CHAR), 
	"XTNDEPTCD" CHAR(5 CHAR), 
	"XTNADDRESS" VARCHAR2(60 CHAR), 
	"XTNTYPE" CHAR(2 CHAR), 
	"INPUTXTNDEPTCD" CHAR(5 CHAR), 
	"APPDTE" DATE, 
	"OUTSEQNO" VARCHAR2(20 CHAR), 
	"OUTDTE" DATE, 
	"OUTDEPTCD" CHAR(5 CHAR), 
	"OUTTRAVCD" CHAR(4 CHAR), 
	"OUTCONVCD" CHAR(4 CHAR), 
	"OUTCONVREGNO" VARCHAR2(20 CHAR), 
	"OUTTDTCD" CHAR(4 CHAR), 
	"OUTTDTNO" VARCHAR2(20 CHAR), 
	"OUTTM6NO" VARCHAR2(20 CHAR), 
	"OUTVISATYPECD" CHAR(4 CHAR), 
	"OUTPERMITCD" CHAR(4 CHAR), 
	"OUTPERMITDTE" DATE, 
	"OUTPASSPORTDTE" DATE, 
	"OUTPASSPORTISU" VARCHAR2(60 CHAR), 
	"OUTPASSPORTEXPDTE" DATE, 
	"OUTCHKPOINTNO" VARCHAR2(10 CHAR), 
	"OUTCREUSR" CHAR(6 CHAR), 
	"OUTCREDTE" DATE, 
	"OUTCREDTERM" VARCHAR2(30 CHAR), 
	"OUTUPDUSR" CHAR(6 CHAR), 
	"OUTUPDDTE" DATE, 
	"OUTUPDTERM" VARCHAR2(30 CHAR), 
	"OUTPROCESSUSR" VARCHAR2(30 CHAR), 
	"OUTPROCESSDTE" DATE, 
	"OUTPROCESSTERM" VARCHAR2(30 CHAR), 
	"MATCHPROCESSUSR" VARCHAR2(30 CHAR), 
	"MATCHPROCESSDTE" DATE, 
	"MATCHPROCESSTERM" VARCHAR2(30 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"INVISAEXPDTE" DATE, 
	"OUTVISAEXPDTE" DATE, 
	"ININTYPE" CHAR(1 CHAR), 
	"OUTINTYPE" CHAR(1 CHAR), 
	"INTARGETNO" CHAR(6 CHAR), 
	"OUTTARGETNO" CHAR(6 CHAR), 
	"INREMARK" VARCHAR2(1000 CHAR), 
	"OUTREMARK" VARCHAR2(1000 CHAR), 
	"FLAGMATCH" CHAR(1 CHAR), 
	"INRESCERTNO" VARCHAR2(20 CHAR), 
	"OUTRESCERTNO" VARCHAR2(20 CHAR), 
	"INIMG" BLOB, 
	"OUTIMG" BLOB, 
	"EXTID" NUMBER(20,0), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"FLAGPROCESDTE" DATE, 
	"INVISATYPECDORG" CHAR(4 CHAR), 
	"OUTVISATYPECDORG" CHAR(4 CHAR), 
	"INDEPTCDORG" CHAR(5 CHAR), 
	"OUTDEPTCDORG" CHAR(5 CHAR), 
	"TYPEDATA" VARCHAR2(20 CHAR)
   ) ;
  CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_EFAMILYNM_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_EFIRSTNM_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_EMIDDLENM_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_INDEPTCD_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("INDEPTCD") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_INDTE_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("INDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_INDTE_IDX2" ON "PIBICSDM2"."TMMAIN_PIS" (TO_CHAR("INDTE",'mmyyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_INTDTNO_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("INTDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_INTM6NO_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("INTM6NO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_NATIONCD_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_OUTDEPTCD_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("OUTDEPTCD") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_OUTDTE_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("OUTDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_OUTDTE_IDX2" ON "PIBICSDM2"."TMMAIN_PIS" (TO_CHAR("OUTDTE",'mmyyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_OUTTDTNO_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("OUTTDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_OUTTM6NO_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("OUTTM6NO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_PERSONID_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("PERSONID") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_TFAMILYNM_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PIS_TFIRSTNM_IDX" ON "PIBICSDM2"."TMMAIN_PIS" ("TFIRSTNM") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302147C00091$$" ON "PIBICSDM2"."TMMAIN_PIS" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302147C00092$$" ON "PIBICSDM2"."TMMAIN_PIS" (
  ;
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMMAIN_PIS" TO "BIOSAADM";
