CREATE TABLE "PIBICSDM2"."TMMAINLAST" 
   (	"TMSEQNO" NUMBER, 
	"TMRUNNO" VARCHAR2(20 CHAR), 
	"IMMPERSONID" VARCHAR2(20 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"INOUTDTE" TIMESTAMP (6), 
	"TM6NO" VARCHAR2(10 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"TDTCD" VARCHAR2(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"PASSPORTDTE" DATE, 
	"PASSPORTEXPDTE" DATE, 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"DEPTCD" CHAR(5 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"IMGINOUT" BLOB, 
	"FLAGPROCESS" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMMAINLAST" ADD CONSTRAINT "TMMAINLAST_PK" PRIMARY KEY ("TMSEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."TMLAST_BIRTHDTE_IDX" ON "PIBICSDM2"."TMMAINLAST" ("BIRTHDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_EFAMILYNM_IDX" ON "PIBICSDM2"."TMMAINLAST" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_EFIRSTNM_IDX" ON "PIBICSDM2"."TMMAINLAST" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_EMIDDLENM_IDX" ON "PIBICSDM2"."TMMAINLAST" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_INOUTDTE_IDX" ON "PIBICSDM2"."TMMAINLAST" (TO_NUMBER(TO_CHAR("INOUTDTE",'YYYYMMDDHH24MISS'))) 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_NATIONCD_IDX" ON "PIBICSDM2"."TMMAINLAST" ("NATIONCD") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_SEX_IDX" ON "PIBICSDM2"."TMMAINLAST" ("SEX") 
  ;
CREATE INDEX "PIBICSDM2"."TMLAST_TMRUNNO_IDX" ON "PIBICSDM2"."TMMAINLAST" ("TMRUNNO") 
  ;
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TMMAINLAST_PK" ON "PIBICSDM2"."TMMAINLAST" ("TMSEQNO") 
  ;
