CREATE TABLE "PIBICSDM2"."TMMAIN_IMM61" 
   (	"TMRUNNO" VARCHAR2(100 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"INSEQNO" VARCHAR2(100 CHAR), 
	"INDTE" DATE, 
	"INDEPTCD" CHAR(5 CHAR), 
	"INTRAVCD" CHAR(4 CHAR), 
	"INCONVCD" CHAR(4 CHAR), 
	"INCONVREGNO" VARCHAR2(20 CHAR), 
	"INTDTCD" VARCHAR2(4 CHAR), 
	"INTDTNO" VARCHAR2(20 CHAR), 
	"INTM6NO" VARCHAR2(20 CHAR), 
	"INVISATYPECDORG" CHAR(4 CHAR), 
	"INPERMITCD" CHAR(4 CHAR), 
	"INPERMITDTE" DATE, 
	"INPASSPORTDTE" DATE, 
	"INPASSPORTISU" VARCHAR2(60 CHAR), 
	"INPASSPORTEXPDTE" DATE, 
	"VISANO" VARCHAR2(20 CHAR), 
	"VISAISSUE" VARCHAR2(60 CHAR), 
	"VISADTE" DATE, 
	"VISABYRIGHTS" CHAR(1 CHAR), 
	"INCHKPOINTNO" VARCHAR2(10 CHAR), 
	"INCREUSR" VARCHAR2(20 CHAR), 
	"INCREDTE" DATE, 
	"INCREDTERM" VARCHAR2(30 CHAR), 
	"INUPDUSR" VARCHAR2(20 CHAR), 
	"INUPDDTE" DATE, 
	"INUPDTERM" VARCHAR2(30 CHAR), 
	"INPROCESSUSR" VARCHAR2(30 CHAR), 
	"INPROCESSDTE" DATE, 
	"INPROCESSTERM" VARCHAR2(30 CHAR), 
	"XTNDEPTCD" CHAR(5 CHAR), 
	"XTNADDRESS" VARCHAR2(60 CHAR), 
	"XTNTYPE" CHAR(2 CHAR), 
	"INPUTXTNDEPTCD" CHAR(5 CHAR), 
	"APPDTE" DATE, 
	"OUTSEQNO" VARCHAR2(100 CHAR), 
	"OUTDTE" DATE, 
	"OUTDEPTCD" CHAR(5 CHAR), 
	"OUTTRAVCD" CHAR(4 CHAR), 
	"OUTCONVCD" CHAR(4 CHAR), 
	"OUTCONVREGNO" VARCHAR2(20 CHAR), 
	"OUTTDTCD" VARCHAR2(4 CHAR), 
	"OUTTDTNO" VARCHAR2(20 CHAR), 
	"OUTTM6NO" VARCHAR2(20 CHAR), 
	"OUTVISATYPECDORG" CHAR(4 CHAR), 
	"OUTPERMITCD" CHAR(4 CHAR), 
	"OUTPERMITDTE" DATE, 
	"OUTPASSPORTDTE" DATE, 
	"OUTPASSPORTISU" VARCHAR2(60 CHAR), 
	"OUTPASSPORTEXPDTE" DATE, 
	"OUTCHKPOINTNO" VARCHAR2(10 CHAR), 
	"OUTCREUSR" VARCHAR2(20 CHAR), 
	"OUTCREDTE" DATE, 
	"OUTCREDTERM" VARCHAR2(30 CHAR), 
	"OUTUPDUSR" VARCHAR2(20 CHAR), 
	"OUTUPDDTE" DATE, 
	"OUTUPDTERM" VARCHAR2(30 CHAR), 
	"OUTPROCESSUSR" VARCHAR2(30 CHAR), 
	"OUTPROCESSDTE" DATE, 
	"OUTPROCESSTERM" VARCHAR2(30 CHAR), 
	"MATCHPROCESSUSR" VARCHAR2(30 CHAR), 
	"MATCHPROCESSDTE" DATE, 
	"MATCHPROCESSTERM" VARCHAR2(30 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"INVISAEXPDTE" DATE, 
	"OUTVISAEXPDTE" DATE, 
	"ININTYPE" CHAR(1 CHAR), 
	"OUTINTYPE" CHAR(1 CHAR), 
	"INTARGETNO" CHAR(6 CHAR), 
	"OUTTARGETNO" CHAR(6 CHAR), 
	"INREMARK" VARCHAR2(1500 CHAR), 
	"OUTREMARK" VARCHAR2(1500 CHAR), 
	"FLAGMATCH" CHAR(1 CHAR), 
	"INRESCERTNO" VARCHAR2(20 CHAR), 
	"OUTRESCERTNO" VARCHAR2(20 CHAR), 
	"INIMG" BLOB, 
	"OUTIMG" BLOB, 
	"EXTID" NUMBER(20,0), 
	"INPM_RE_ENTRY" VARCHAR2(20 CHAR), 
	"INPM_REEXPDTE" DATE, 
	"INPM_EXTENSION" VARCHAR2(20 CHAR), 
	"INPM_EXEXPDTE" DATE, 
	"INPM_NON_QUOTA" VARCHAR2(20 CHAR), 
	"INPM_NONEXPDTE" DATE, 
	"INSTATUS" CHAR(1 CHAR), 
	"INTM5_SEQNO" NUMBER, 
	"INTM2INOUT_SEQNO" NUMBER, 
	"OUTPM_RE_ENTRY" VARCHAR2(20 CHAR), 
	"OUTPM_REEXPDTE" DATE, 
	"OUTPM_EXTENSION" VARCHAR2(20 CHAR), 
	"OUTPM_EXEXPDTE" DATE, 
	"OUTPM_NON_QUOTA" VARCHAR2(20 CHAR), 
	"OUTPM_NONEXPDTE" DATE, 
	"OUTSTATUS" CHAR(1 CHAR), 
	"OUTTM5_SEQNO" NUMBER, 
	"OUTTM2INOUT_SEQNO" NUMBER, 
	"INCONV_SEQNO" NUMBER, 
	"INVISATYPE_SEQNO" NUMBER, 
	"INDEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"INPERMIT_SEQNO" NUMBER, 
	"OUTCONV_SEQNO" NUMBER, 
	"OUTVISATYPE_SEQNO" NUMBER, 
	"OUTDEPT_SEQNO" NUMBER, 
	"OUTPERMIT_SEQNO" NUMBER, 
	"INFLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"INFLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"OUTFLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"OUTFLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"PASS_SEQNO" NUMBER, 
	"INRPJSEQNO" NUMBER, 
	"OUTRPJSEQNO" NUMBER, 
	"INDEPTCDORG" CHAR(5 CHAR), 
	"OUTDEPTCDORG" CHAR(5 CHAR), 
	"TYPEDATA" VARCHAR2(20 CHAR), 
	"FLAGJOINPASS" CHAR(1 CHAR), 
	"FLAGFINES" CHAR(1 CHAR), 
	"INVISATYPECD" CHAR(4 CHAR), 
	"OUTVISATYPECD" CHAR(4 CHAR), 
	"SEND_FLAG" VARCHAR2(1 CHAR), 
	"VISARUNDAY" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"INPD_SEQNO" NUMBER, 
	"INZONE_SEQNO" NUMBER, 
	"OUTPD_SEQNO" NUMBER, 
	"OUTZONE_SEQNO" NUMBER, 
	"INSHIFT_SEQNO" NUMBER, 
	"OUTSHIFT_SEQNO" NUMBER
   ) ;
  CREATE BITMAP INDEX "PIBICSDM2"."TM_INDEPTCD_BITMAP_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("INDEPTCD") 
  ;
CREATE BITMAP INDEX "PIBICSDM2"."TM_NATIONCD_BITMAP_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("NATIONCD") 
  ;
CREATE BITMAP INDEX "PIBICSDM2"."TM_OUTDEPTCD_BITMAP_IDX44" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTDEPTCD") 
  ;
CREATE BITMAP INDEX "PIBICSDM2"."TM_SEX_BITMAP_IDX44" ON "PIBICSDM2"."TMMAIN_IMM61" ("SEX") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_IMM61_INSEQNO" ON "PIBICSDM2"."TMMAIN_IMM61" ("INSEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_IMM61_OUTSEQNO" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTSEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_IMM61_TMMAIN" ON "PIBICSDM2"."TMMAIN_IMM61" ("TFIRSTNM", "TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."IDX_IMM61_TMMAIN_509" ON "PIBICSDM2"."TMMAIN_IMM61" ("SEX", "TFIRSTNM", "TFAMILYNM", "EMIDDLENM", "EFIRSTNM", "EFAMILYNM", "INTM6NO", "INTDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_BD_NTN_SEX_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("BIRTHDTE", "NATIONCD", "SEX") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_COUNTSEQNO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("COUNT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_EFAMILYNM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("EFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_EFIRSTNM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("EFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_EFSNDXNM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("EFSNDXNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_ELSNDXNM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("ELSNDXNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_EMIDDLENM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("EMIDDLENM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_EMSNDXNM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("EMSNDXNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREDTE1_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INCREDTE",'hh24mi')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREDTE2_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INCREDTE",'yyyymmddhh24mi')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREDTERM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INCREDTERM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREDTE_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INCREDTE",'yyyymm')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREDTE_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INCREDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INCREUSR_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INCREUSR") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDEPT_SEQNO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INDEPT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDTETIME_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'YYYYMMDDHH24MI')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDTETIME_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'YYYYMMDDHH24MISS')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDTE_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'mmyyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDTE_IDX3_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'dd/mm/yyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INDTE_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INTDTNO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INTDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INTM6NO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INTM6NO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INVISATYPE_SEQNO_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INVISATYPE_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_INZONE_SEQNO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("INZONE_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREDTE1_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTCREDTE",'hh24mi')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREDTE2_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTCREDTE",'yyyymmddhh24mi')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREDTERM_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTCREDTERM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREDTE_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTCREDTE",'yyyymm')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREDTE_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTCREDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTCREUSR_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTCREUSR") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDEPT_SEQNO_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTDEPT_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDTETIME_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'YYYYMMDDHH24MI')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDTETIME_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'YYYYMMDDHH24MISS')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDTE_IDX2_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'mmyyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDTE_IDX3_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'dd/mm/yyyy')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTDTE_IDX_IMM61" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTDTE") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTPM_EXTENSION_IDX4" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTPM_EXTENSION") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTTDTNO_IDX4" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTTDTNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTTM6NO_IDX4" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTTM6NO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTVISATYPE_SEQNO3" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTVISATYPE_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_OUTZONE_SEQNO_IDX3" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTZONE_SEQNO") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_PERSONID_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("PERSONID") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_RPT_INDTE_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_RPT_OUTDTE_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_TFIRSTNM_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("TFIRSTNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_TFSNDXNM_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("TFSNDXNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_TLSNDXNM_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("TLSNDXNM") 
  ;
CREATE INDEX "PIBICSDM2"."TMMAIN_TYPEDATA_IDX333" ON "PIBICSDM2"."TMMAIN_IMM61" ("TYPEDATA") 
  ;
CREATE INDEX "PIBICSDM2"."TMMIAN_TFAMILYNM_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" ("TFAMILYNM") 
  ;
CREATE INDEX "PIBICSDM2"."TM_INCONVREGNO_IDX44" ON "PIBICSDM2"."TMMAIN_IMM61" ("INCONVREGNO") 
  ;
CREATE INDEX "PIBICSDM2"."TM_INDTE_IDX33" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("INDTE",'YYYYMM')) 
  ;
CREATE INDEX "PIBICSDM2"."TM_OUTCONVREGNO_IDX44" ON "PIBICSDM2"."TMMAIN_IMM61" ("OUTCONVREGNO") 
  ;
CREATE INDEX "PIBICSDM2"."TM_OUTDTE_IDX44" ON "PIBICSDM2"."TMMAIN_IMM61" (TO_CHAR("OUTDTE",'YYYYMM')) 
  ;
  ;
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TMMAIN_IMM61_PK" ON "PIBICSDM2"."TMMAIN_IMM61" ("TMRUNNO") 
  ;
