CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_EXT_WAITCOMMENT" 
   (	"WAITCOMMENT_SEQNO" NUMBER, 
	"WAITCOMMENTTNM" VARCHAR2(200 CHAR), 
	"WAITCOMMENTENM" VARCHAR2(200 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_EXT_WAITCOMMENT" ADD CONSTRAINT "TMP_SYNC_MAS_EXT_WAITCOMMENT_PK" PRIMARY KEY ("WAITCOMMENT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_EXT_WAITCOMMENT_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_EXT_WAITCOMMENT" ("WAITCOMMENT_SEQNO") 
  ;
