CREATE TABLE "PIBICSDM2"."TMP_BACKUP_MAS_PRECINCT" 
   (	"PRECINCT_SEQNO" NUMBER, 
	"PRECINCTCD" CHAR(4 CHAR), 
	"PRECINCTTNM" VARCHAR2(60 CHAR), 
	"PRECINCTENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
