CREATE TABLE "PIBICSDM2"."TMP_SYNC_TRAN_FN_ADDRESSNOTIFY" 
   (	"ADDRN_SEQNO" NUMBER, 
	"HOTEL_SEQNO" NUMBER, 
	"NOTIFYTYPE" CHAR(1 CHAR), 
	"ADDRNDTE" TIMESTAMP (6), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"VERSION" NUMBER, 
	"ADDRNQ_SEQNO" NUMBER, 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"UIPADDRESS" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_TRAN_FN_ADDRESSNOTIFY" ADD CONSTRAINT "TMP_SYNC_TRAN_FN_ADDRESSNOTIFY_PK" PRIMARY KEY ("ADDRN_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_TRAN_FN_ADDRESSNOTIFY_PK" ON "PIBICSDM2"."TMP_SYNC_TRAN_FN_ADDRESSNOTIFY" ("ADDRN_SEQNO") 
  ;
