CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_PRECINCT" 
   (	"PRECINCT_SEQNO" NUMBER, 
	"PRECINCTCD" CHAR(4 CHAR), 
	"PRECINCTTNM" VARCHAR2(60 CHAR), 
	"PRECINCTENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_PRECINCT" ADD CONSTRAINT "TMP_SYNC_MAS_PRECINCT_PK" PRIMARY KEY ("PRECINCT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_PRECINCT_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_PRECINCT" ("PRECINCT_SEQNO") 
  ;
