CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_SUFFIX" 
   (	"SUFFIX_SEQNO" NUMBER, 
	"SUFFIX_DESC" VARCHAR2(50 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"SUFFIX_TYPE" CHAR(1 CHAR), 
	"SUFFIXORDER" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_SUFFIX" ADD CONSTRAINT "TMP_SYNC_MAS_SUFFIX_PK" PRIMARY KEY ("SUFFIX_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_SUFFIX_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_SUFFIX" ("SUFFIX_SEQNO") 
  ;
