CREATE TABLE "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" 
   (	"ALIENATTSCAN_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"SCAN_DATE" DATE, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ATTSCAN" VARCHAR2(200 CHAR), 
	"FLAGSCAN" CHAR(1 CHAR), 
	"MASTER_FLAG" CHAR(1 CHAR)
   ) ;
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" TO "BIOSAADM";
