CREATE TABLE "PIBICSDM2"."TMP_BACKUP_MAS_PASSPORTSTATUS" 
   (	"PPS_SEQNO" NUMBER, 
	"PPS_CODE" CHAR(1 CHAR), 
	"PPS_DESC" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
