CREATE TABLE "PIBICSDM2"."TMP_BACKUP_MAS_ARS_ALIENATTSCAN" 
   (	"ALIENATTSCAN_SEQNO" NUMBER, 
	"ALIENCERT_SEQNO" NUMBER, 
	"SCAN_DATE" DATE, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ATTSCAN" VARCHAR2(200 CHAR), 
	"FLAGSCAN" CHAR(1 CHAR), 
	"MASTER_FLAG" CHAR(1 CHAR)
   ) ;
