CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_DRS_DETAINROOM" 
   (	"DETAINROOM_SEQNO" NUMBER, 
	"DETAINROOMID" VARCHAR2(10 CHAR), 
	"DETAINROOM_NAME" VARCHAR2(20 CHAR), 
	"LOCATEDEPT_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"REMARK" VARCHAR2(150 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_DRS_DETAINROOM" ADD CONSTRAINT "TMP_SYNC_MAS_DRS_DETAINROOM_PK" PRIMARY KEY ("DETAINROOM_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_DRS_DETAINROOM_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_DRS_DETAINROOM" ("DETAINROOM_SEQNO") 
  ;
