CREATE TABLE "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" 
   (	"DATE_CHECK" VARCHAR2(20), 
	"AMOUNT" NUMBER, 
	"TYPE_CHECK" NUMBER
   ) ;
   COMMENT ON COLUMN "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP"."DATE_CHECK" IS 'ชื่อตาราง';
   COMMENT ON COLUMN "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP"."AMOUNT" IS 'ชื่อเงื่อนไข';
   COMMENT ON COLUMN "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP"."TYPE_CHECK" IS 'ประเภทการตรวจสอบ 1-Source/ 2-Destination';
  GRANT SELECT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMP_SYNC_CHECK_TABLE_AMOUNT_TMP" TO "BIOSAADM";
