CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_CHNGVISA_LAW" 
   (	"LAW_SEQNO" NUMBER, 
	"LAWNO" NUMBER, 
	"LAWNM" VARCHAR2(250 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"NOTE" VARCHAR2(200 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_CHNGVISA_LAW" ADD CONSTRAINT "TMP_SYNC_MAS_CHNGVISA_LAW_PK" PRIMARY KEY ("LAW_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_CHNGVISA_LAW_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_CHNGVISA_LAW" ("LAW_SEQNO") 
  ;
