CREATE TABLE "PIBICSDM2"."TMP_SYNC_TRAN_EXT_PROCESSLIST" 
   (	"PROCLIST_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"EXTLIST_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_TRAN_EXT_PROCESSLIST" ADD CONSTRAINT "TMP_SYNC_TRAN_EXT_PROCESSLIST_PK" PRIMARY KEY ("PROCLIST_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_TRAN_EXT_PROCESSLIST_PK" ON "PIBICSDM2"."TMP_SYNC_TRAN_EXT_PROCESSLIST" ("PROCLIST_SEQNO") 
  ;
