CREATE TABLE "PIBICSDM2"."TMP_BACKUP_MAS_BLIMPREASON" 
   (	"REASON_SEQNO" NUMBER, 
	"REASONCD" CHAR(4 CHAR), 
	"REASONTNM" VARCHAR2(60 CHAR), 
	"REASONENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"OVERSTAY_BEGIN_AMT" NUMBER, 
	"OVERSTAY_BEGIN_UNIT" VARCHAR2(1 CHAR), 
	"PROHIBIT_AMT" NUMBER
   ) ;
