CREATE TABLE "PIBICSDM2"."TMP_SYNC_MAS_DRS_RELEASE" 
   (	"RELEASE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"DOCNO" VARCHAR2(100 CHAR), 
	"DOC_DATE" DATE, 
	"ISSUEDEPT_SEQNO" NUMBER, 
	"ISSUE_DATE" DATE, 
	"ISSUENM" VARCHAR2(100 CHAR), 
	"NOTE" VARCHAR2(200 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"DETAIN_NO" NUMBER, 
	"RELEASETYPE_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMP_SYNC_MAS_DRS_RELEASE" ADD CONSTRAINT "TMP_SYNC_MAS_DRS_RELEASE_PK" PRIMARY KEY ("RELEASE_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMP_SYNC_MAS_DRS_RELEASE_PK" ON "PIBICSDM2"."TMP_SYNC_MAS_DRS_RELEASE" ("RELEASE_SEQNO") 
  ;
