CREATE TABLE "PIBICSDM2"."TMPERSONTOWV15" 
   (	"TMSEQNO" NUMBER, 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"AMOUNT" NUMBER, 
	"INOUTDTE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"TM6NO" VARCHAR2(10 CHAR), 
	"CHKCAPTURE" CHAR(1 CHAR), 
	"FN38" VARCHAR2(1500 CHAR), 
	"CARDTYPE" CHAR(1 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMPERSONTOWV15_PK" ON "PIBICSDM2"."TMPERSONTOWV15" ("TMSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMPERSONTOWV15" TO "BIOSAADM";
