CREATE TABLE "PIBICSDM2"."TMPERSONEX3090" 
   (	"TMSEQNO" NUMBER, 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"AMOUNT" NUMBER, 
	"INOUTDTE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"TM6NO" VARCHAR2(10 CHAR), 
	"CHKCAPTURE" CHAR(1 CHAR), 
	"FN38" VARCHAR2(1500 CHAR), 
	"CARDTYPE" CHAR(1 CHAR), 
	"VISATYPE_SEQNO" NUMBER, 
	"CREDTE" DATE, 
	"FLAGPROCESS" VARCHAR2(50 CHAR), 
	"FLAGVISARUN" CHAR(1 CHAR), 
	"VISARUNDAYS" NUMBER, 
	"FLAGOUT" CHAR(1 CHAR), 
	"FLAGDIFF" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TMPERSONEX3090" ADD CONSTRAINT "TMPERSONEX3090_PK" PRIMARY KEY ("TMSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMPERSONEX3090_PK" ON "PIBICSDM2"."TMPERSONEX3090" ("TMSEQNO") 
  ;
