CREATE TABLE "PIBICSDM2"."TMRUNNOIMM" 
   (	"TMRUNNO" VARCHAR2(20 CHAR), 
	"TYPEDATA" VARCHAR2(10 CHAR), 
	"INDTE" TIMESTAMP (6), 
	"OUTDTE" TIMESTAMP (6), 
	"MONTH" VARCHAR2(10 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMRUNNOIMM" ADD CONSTRAINT "TMRUNNOIMM_PK" PRIMARY KEY ("TMRUNNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMRUNNOIMM_PK" ON "PIBICSDM2"."TMRUNNOIMM" ("TMRUNNO") 
  ;
