CREATE TABLE "PIBICSDM2"."TMVISARUN" 
   (	"VISARUNSEQNO" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TM6NO" VARCHAR2(10 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"EFAMILYNM" VARCHAR2(100 CHAR), 
	"EFIRSTNM" VARCHAR2(100 CHAR), 
	"EMIDDLENM" VARCHAR2(100 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" CHAR(3 CHAR), 
	"AMOUNT" NUMBER, 
	"INOUTDTE" DATE, 
	"DEPT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"VISAEXPDTE" DATE, 
	"CHKCAPTURE" CHAR(1 CHAR), 
	"FLAGVISARUN" CHAR(1 CHAR), 
	"VISARUNDAYS" NUMBER, 
	"INTYPE" CHAR(1 CHAR), 
	"TYPEDATA" VARCHAR2(40 CHAR), 
	"CREUSR" VARCHAR2(40 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(40 CHAR), 
	"REMARK" VARCHAR2(2000 CHAR), 
	"TMRUNNO" VARCHAR2(20 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"FLAGPROCESS" CHAR(1 CHAR), 
	"FLAGVISA" VARCHAR2(10 CHAR), 
	"FLAGDIFF" NUMBER, 
	"UPDDTE" DATE, 
	"VISAPROCESSDTE" DATE, 
	"PCSREASION" VARCHAR2(1000 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TMVISARUN" ADD CONSTRAINT "TMVISARUN_PK" PRIMARY KEY ("VISARUNSEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TMVISARUN_PK" ON "PIBICSDM2"."TMVISARUN" ("VISARUNSEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TMVISARUN" TO "BIOSAADM";
