CREATE TABLE "PIBICSDM2"."TRAIN_EVA_INS_LOG" 
   (	"EVAI_SEQNO" NUMBER, 
	"EVA_SEQNO" NUMBER, 
	"INS_SEQNO" NUMBER, 
	"EVA_2_3_1" CHAR(1 CHAR), 
	"EVA_2_3_1_REMARK" VARCHAR2(100 CHAR), 
	"EVA_2_3_2" CHAR(1 CHAR), 
	"EVA_2_3_2_REMARK" VARCHAR2(100 CHAR), 
	"EVA_2_3_3" CHAR(1 CHAR), 
	"EVA_2_3_3_REMARK" VARCHAR2(100 CHAR), 
	"EVA_2_3_4" CHAR(1 CHAR), 
	"EVA_2_3_4_REMARK" VARCHAR2(100 CHAR), 
	"EVA_2_3_5" CHAR(1 CHAR), 
	"EVA_2_3_5_REMARK" VARCHAR2(100 CHAR), 
	"VERSION" NUMBER, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"EVA_INSLOG_SEQNO" NUMBER, 
	"EVA_INSLOG_DATE" TIMESTAMP (6), 
	"EVA_INSLOG_FLAG" CHAR(1 CHAR), 
	"EVA_INSLOG_USRUPD" VARCHAR2(20 CHAR), 
	"EVALUATIONLOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_EVA_INS_LOG" ADD CONSTRAINT "TRAIN_EVA_INS_LOG_PK" PRIMARY KEY ("EVA_INSLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_EVA_INS_LOG" ADD CONSTRAINT "TRAIN_EVA_INS_LOG_R01" FOREIGN KEY ("EVALUATIONLOG_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_EVALUATION_LOG" ("EVALUATIONLOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_EVA_INS_LOG_PK" ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" ("EVA_INSLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_EVA_INS_LOG" TO "BIOSAADM";
