CREATE TABLE "PIBICSDM2"."TRAIN_SCHEDULE_LOG" 
   (	"SCH_SEQNO" NUMBER, 
	"SCH_TOPIC" VARCHAR2(100 CHAR), 
	"SCH_STARTDATE" DATE, 
	"SCH_STARTTIME" CHAR(5 CHAR), 
	"SCH_ENDDATE" DATE, 
	"SCH_ENDTIME" CHAR(5 CHAR), 
	"SCH_PLACEDETAIL" VARCHAR2(100 CHAR), 
	"INS_SEQNO" NUMBER, 
	"COURSE_SEQNO" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"SCHEDULELOG_SEQNO" NUMBER, 
	"SCHEDULELOG_DATE" TIMESTAMP (6), 
	"SCHEDULELOG_FLAG" CHAR(1 CHAR), 
	"SCHEDULELOG_USRUPD" VARCHAR2(20 CHAR), 
	"COURSELOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_SCHEDULE_LOG" ADD CONSTRAINT "TRAIN_SCHEDULE_LOG_PK" PRIMARY KEY ("SCHEDULELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_SCHEDULE_LOG" ADD CONSTRAINT "TRAIN_SCHEDULE_LOG_R01" FOREIGN KEY ("COURSELOG_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_COURSE_LOG" ("COURSELOG_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_SCHEDULE_LOG" ADD CONSTRAINT "TRAIN_SCHEDULE_LOG_R02" FOREIGN KEY ("INS_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_INSTRUCTOR" ("INS_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_SCHEDULE_LOG_PK" ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" ("SCHEDULELOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_SCHEDULE_LOG" TO "BIOSAADM";
