CREATE TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP_LOG" 
   (	"WG_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"COURSE_SEQNO" NUMBER, 
	"WG_JOBDESC" VARCHAR2(200 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"WORKINGGROUPLOG_SEQNO" NUMBER, 
	"WORKINGGROUPLOG_DATE" TIMESTAMP (6), 
	"WORKINGGROUPLOG_FLAG" CHAR(1 CHAR), 
	"WORKINGGROUPLOG_USRUPD" VARCHAR2(20 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"RANK_SEQNO" VARCHAR2(3 CHAR), 
	"POS_CODE" VARCHAR2(8 CHAR), 
	"NAME" VARCHAR2(25 CHAR), 
	"SNAME" VARCHAR2(25 CHAR), 
	"COURSELOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP_LOG" ADD CONSTRAINT "TRAIN_WORKINGGROUP_LOG_PK" PRIMARY KEY ("WORKINGGROUPLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP_LOG" ADD CONSTRAINT "TRAIN_WORKINGGROUP_LOG_R01" FOREIGN KEY ("COURSELOG_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_COURSE_LOG" ("COURSELOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_WORKINGGROUP_LOG_PK" ON "PIBICSDM2"."TRAIN_WORKINGGROUP_LOG" ("WORKINGGROUPLOG_SEQNO") 
  ;
