CREATE TABLE "PIBICSDM2"."TRAIN_COSRUNNO" 
   (	"COSRUNNO_SEQNO" NUMBER, 
	"COSRUNNO_CODE" CHAR(4 CHAR), 
	"COSRUNNO_YEAR" CHAR(4 CHAR), 
	"CREATE_BY" VARCHAR2(60 CHAR), 
	"CREATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(60 CHAR), 
	"UPDATE_DATE" DATE, 
	"VERSION" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_COSRUNNO_PK" ON "PIBICSDM2"."TRAIN_COSRUNNO" ("COSRUNNO_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_COSRUNNO" TO "BIOSAADM";
