CREATE TABLE "PIBICSDM2"."TRAIN_INSPROFILE" 
   (	"INSPROFILE_SEQNO" NUMBER, 
	"INS_SEQNO" NUMBER, 
	"INSPROFILE_TOPIC" VARCHAR2(500 CHAR), 
	"INSPROFILE_ATTENDEE" VARCHAR2(500 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"INSPROFILE_FROMDATE" DATE, 
	"INSPROFILE_TODATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSPROFILE" ADD CONSTRAINT "TRAIN_INSPROFILE_PK" PRIMARY KEY ("INSPROFILE_SEQNO")
  USING INDEX (CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_INSTPROFILE_PK" ON "PIBICSDM2"."TRAIN_INSPROFILE" ("INSPROFILE_SEQNO") 
  )  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSPROFILE" ADD CONSTRAINT "TRAIN_INSPROFILE_R01" FOREIGN KEY ("INS_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_INSTRUCTOR" ("INS_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_INSTPROFILE_PK" ON "PIBICSDM2"."TRAIN_INSPROFILE" ("INSPROFILE_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_INSPROFILE" TO "BIOSAADM";
