CREATE TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP" 
   (	"WG_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"COURSE_SEQNO" NUMBER, 
	"WG_JOBDESC" VARCHAR2(200 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"RANK_SEQNO" VARCHAR2(3 CHAR), 
	"POS_CODE" VARCHAR2(8 CHAR), 
	"NAME" VARCHAR2(25 CHAR), 
	"SNAME" VARCHAR2(25 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP" ADD CONSTRAINT "TRAIN_WORKINGGROUP_PK" PRIMARY KEY ("WG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP" ADD CONSTRAINT "TRAIN_WORKINGGROUP_R02" FOREIGN KEY ("PROFILE_SEQNO")
	  REFERENCES "PIBICSDM2"."HR_PROFILE" ("PROFILE_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_WORKINGGROUP" ADD CONSTRAINT "TRAIN_WORKINGGROUP_R01" FOREIGN KEY ("COURSE_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_COURSE" ("COURSE_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_WORKINGGROUP_PK" ON "PIBICSDM2"."TRAIN_WORKINGGROUP" ("WG_SEQNO") 
  ;
