CREATE TABLE "PIBICSDM2"."TRAIN_BUDGET_LOG" 
   (	"BG_SEQNO" NUMBER, 
	"COURSE_SEQNO" NUMBER, 
	"BG_DETAIL" VARCHAR2(100 CHAR), 
	"BG_AMOUNT" NUMBER, 
	"VERSION" NUMBER DEFAULT 1, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"BUDGETLOG_SEQNO" NUMBER, 
	"BUDGETLOG_DATE" TIMESTAMP (6), 
	"BUDGETLOG_FLAG" CHAR(1 CHAR), 
	"BUDGETLOG_USRUPD" VARCHAR2(20 CHAR), 
	"COURSELOG_SEQNO" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_BUDGET_LOG" ADD CONSTRAINT "TRAIN_BUDGET_LOG_PK" PRIMARY KEY ("BUDGETLOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_BUDGET_LOG" ADD CONSTRAINT "TRAIN_BUDGET_LOG_R01" FOREIGN KEY ("COURSELOG_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_COURSE_LOG" ("COURSELOG_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_BUDGET_LOG_PK" ON "PIBICSDM2"."TRAIN_BUDGET_LOG" ("BUDGETLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_BUDGET_LOG" TO "BIOSAADM";
