CREATE TABLE "PIBICSDM2"."TRAIN_INSEDUCATION" 
   (	"EDU_SEQNO" NUMBER, 
	"INS_SEQNO" NUMBER, 
	"EDU_DEGREE" VARCHAR2(60 CHAR), 
	"EDU_INSTITUTE" VARCHAR2(100 CHAR), 
	"EDU_FINISHEDYEAR" VARCHAR2(4 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"EDU_FACULTY" VARCHAR2(100 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSEDUCATION" ADD CONSTRAINT "TRAIN_EDUCATION_PK" PRIMARY KEY ("EDU_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSEDUCATION" ADD CONSTRAINT "TRAIN_INSEDUCATION_R01" FOREIGN KEY ("INS_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_INSTRUCTOR" ("INS_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_EDUCATION_PK" ON "PIBICSDM2"."TRAIN_INSEDUCATION" ("EDU_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_INSEDUCATION" TO "BIOSAADM";
