CREATE TABLE "PIBICSDM2"."TRAIN_INSPROFILE" 
   (	"INSPROFILE_SEQNO" NUMBER, 
	"INS_SEQNO" NUMBER, 
	"INSPROFILE_TOPIC" VARCHAR2(500 CHAR), 
	"INSPROFILE_ATTENDEE" VARCHAR2(500 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"INSPROFILE_FROMDATE" DATE, 
	"INSPROFILE_TODATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSPROFILE" ADD CONSTRAINT "TRAIN_INSPROFILE_PK" PRIMARY KEY ("INSPROFILE_SEQNO")
  USING INDEX (CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_INSTPROFILE_PK" ON "PIBICSDM2"."TRAIN_INSPROFILE" ("INSPROFILE_SEQNO") 
  )  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_INSPROFILE" ADD CONSTRAINT "TRAIN_INSPROFILE_R01" FOREIGN KEY ("INS_SEQNO")
	  REFERENCES "PIBICSDM2"."TRAIN_INSTRUCTOR" ("INS_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_INSTPROFILE_PK" ON "PIBICSDM2"."TRAIN_INSPROFILE" ("INSPROFILE_SEQNO") 
  ;
