CREATE TABLE "PIBICSDM2"."TRAIN_PLACE_LOG" 
   (	"PLACE_SEQNO" NUMBER, 
	"PLACE_NAME" VARCHAR2(60 CHAR), 
	"PLACE_NUMBER" VARCHAR2(10 CHAR), 
	"PLACE_ROAD" VARCHAR2(30 CHAR), 
	"TMB_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"PV_SEQNO" NUMBER, 
	"PLACE_POSTCODE" VARCHAR2(5 CHAR), 
	"PLACE_CONTACTNAME" VARCHAR2(30 CHAR), 
	"PLACE_PHONENO" VARCHAR2(20 CHAR), 
	"PLACE_FAXNO" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"PLACE_CONTACTNO" VARCHAR2(30 CHAR), 
	"PLACELOG_SEQNO" NUMBER, 
	"PLACELOG_DATE" TIMESTAMP (6), 
	"PLACELOG_FLAG" CHAR(1 CHAR), 
	"PLACELOG_USRUPD" VARCHAR2(20 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"PLACE_CONTACTEMAIL" VARCHAR2(40 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAIN_PLACE_LOG" ADD CONSTRAINT "TRAIN_PLACE_LOG_PK" PRIMARY KEY ("PLACELOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_PLACE_LOG" ADD CONSTRAINT "TRAIN_PLACE_LOG_R02" FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_PLACE_LOG" ADD CONSTRAINT "TRAIN_PLACE_LOG_R01" FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAIN_PLACE_LOG" ADD CONSTRAINT "TRAIN_PLACE_LOG_R03" FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAIN_PLACE_LOG_PK" ON "PIBICSDM2"."TRAIN_PLACE_LOG" ("PLACELOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAIN_PLACE_LOG" TO "BIOSAADM";
