CREATE TABLE "PIBICSDM2"."TRAVELTYPE" 
   (	"TRAV_SEQNO" NUMBER, 
	"TRAVCD" CHAR(4 CHAR), 
	"TRAVTNM" VARCHAR2(60 CHAR), 
	"TRAVENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAVELTYPE" ADD CONSTRAINT "TRAVELTYPE_PK" PRIMARY KEY ("TRAV_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAVELTYPE" ADD CONSTRAINT "TRAVELTYPE_U01" UNIQUE ("TRAVCD")
  USING INDEX (CREATE UNIQUE INDEX "PIBICSDM2"."TRAVCD_PK" ON "PIBICSDM2"."TRAVELTYPE" ("TRAVCD") 
  )  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."TRAVCD_PK" ON "PIBICSDM2"."TRAVELTYPE" ("TRAVCD") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TRAVELTYPE_PK" ON "PIBICSDM2"."TRAVELTYPE" ("TRAV_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."TRAVELTYPE" TO "BIOSAADM";
