CREATE TABLE "PIBICSDM2"."TRAVELDOCTYPE" 
   (	"TDT_SEQNO" NUMBER, 
	"TDTCD" CHAR(4 CHAR), 
	"TDTTNM" VARCHAR2(60 CHAR), 
	"TDTENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."TRAVELDOCTYPE" ADD CONSTRAINT "TRAVELDOCTYPE_PK" PRIMARY KEY ("TDT_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAVELDOCTYPE" ADD CONSTRAINT "TRAVELDOCTYPE_U01" UNIQUE ("TDTCD")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."TRAVELDOCTYPE" ADD CONSTRAINT "TRAVELDOCTYPE_U02" UNIQUE ("TDTTNM")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."IDX_TRAVELDOCTYPE_500" ON "PIBICSDM2"."TRAVELDOCTYPE" (TO_NUMBER("TDTCD")) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TRAVELDOCTYPE_PK" ON "PIBICSDM2"."TRAVELDOCTYPE" ("TDT_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TRAVELDOCTYPE_U01" ON "PIBICSDM2"."TRAVELDOCTYPE" ("TDTCD") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."TRAVELDOCTYPE_U02" ON "PIBICSDM2"."TRAVELDOCTYPE" ("TDTTNM") 
  ;
