CREATE TABLE "PIBICSDM2"."VOA_PERSON" 
   (	"PERSON_SEQNO" NUMBER, 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PASSPORT_ISSUEDATE" DATE, 
	"PASSPORT_EXPDATE" DATE, 
	"PASSPORT_PLACE" VARCHAR2(60 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"VISATYPE_SEQNO" NUMBER, 
	"PERMIT_DATE" DATE, 
	"FROMCOUNTRY" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVNO" VARCHAR2(20 CHAR), 
	"IN_DATE" DATE, 
	"PERADD" VARCHAR2(1500 CHAR), 
	"THAIREF" VARCHAR2(100 CHAR), 
	"BUILDING" VARCHAR2(100 CHAR), 
	"ADDR" VARCHAR2(1500 CHAR), 
	"ROAD" VARCHAR2(100 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"POSTCODE" VARCHAR2(20 CHAR), 
	"TEL" VARCHAR2(20 CHAR), 
	"APPROVE" CHAR(1 CHAR), 
	"REASON" VARCHAR2(2000 CHAR), 
	"VISANO" VARCHAR2(50 CHAR), 
	"STS" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"STATUSVOA" CHAR(1 CHAR), 
	"STATUSVOADTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD CONSTRAINT "VOA_PERSON_PK" PRIMARY KEY ("PERSON_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("CONV_SEQNO")
	  REFERENCES "PIBICSDM2"."CONVEYANCE" ("CONV_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("FROMCOUNTRY")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("AMP_SEQNO")
	  REFERENCES "PIBICSDM2"."AMPUR" ("AMP_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("PV_SEQNO")
	  REFERENCES "PIBICSDM2"."PROVINCE" ("PV_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("VISATYPE_SEQNO")
	  REFERENCES "PIBICSDM2"."VISATYPE" ("VISATYPE_SEQNO") ENABLE NOVALIDATE;
  ALTER TABLE "PIBICSDM2"."VOA_PERSON" ADD FOREIGN KEY ("TMB_SEQNO")
	  REFERENCES "PIBICSDM2"."TAMBON" ("TMB_SEQNO") ENABLE NOVALIDATE;
  CREATE UNIQUE INDEX "PIBICSDM2"."VOA_PERSON_PK" ON "PIBICSDM2"."VOA_PERSON" ("PERSON_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."VOA_PERSON" TO "BIOSAADM";
