CREATE TABLE "PIBICSDM2"."VOA_DOCS" 
   (	"DOCS_SEQNO" NUMBER, 
	"VOAL_SEQNO" NUMBER, 
	"TDT_SEQNO" NUMBER, 
	"PASSPORTNO" VARCHAR2(60 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"IMGDOC" VARCHAR2(100 CHAR), 
	"REMARK" VARCHAR2(1000 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_TERM" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_TERM" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."VOA_DOCS" ADD CONSTRAINT "VOA_DOCS_PK" PRIMARY KEY ("DOCS_SEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."DVOA_CREATEBY_IDX" ON "PIBICSDM2"."VOA_DOCS" ("CREATE_BY") 
  ;
CREATE INDEX "PIBICSDM2"."DVOA_VOALSEQNO_IDX" ON "PIBICSDM2"."VOA_DOCS" ("VOAL_SEQNO") 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."VOA_DOCS_PK" ON "PIBICSDM2"."VOA_DOCS" ("DOCS_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."VOA_DOCS" TO "BIOSAADM";
