CREATE TABLE "PIBICSDM2"."VOALIST_ONLINE_LOG" 
   (	"VOALO_LOG_SEQNO" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USRUPD" VARCHAR2(60 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"VOALO_SEQNO" NUMBER, 
	"PASSPORT_PLACE" VARCHAR2(60 CHAR), 
	"PASSPORT_EXPDATE" DATE, 
	"PASSPORT_ISSUEDATE" DATE, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"RPJSEQNO" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"VERIFY_BLACKLIST" CHAR(1 CHAR), 
	"STS" CHAR(1 CHAR), 
	"VOAO_SEQNO" NUMBER, 
	"VOAR_SEQNO" NUMBER, 
	"PERADD" VARCHAR2(1500 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"VERSION" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE_LOG" ADD CONSTRAINT "VOALIST_ONLINE_LOG_PK" PRIMARY KEY ("VOALO_LOG_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE_LOG" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE_LOG" ADD FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE;
  CREATE INDEX "PIBICSDM2"."VOALIST_ONLINE_LOG_CREATEDTE1" ON "PIBICSDM2"."VOALIST_ONLINE_LOG" (TO_CHAR("CREATE_DATE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."VOALIST_ONLINE_LOG_CREATEDTE2" ON "PIBICSDM2"."VOALIST_ONLINE_LOG" (TO_CHAR("CREATE_DATE",'yyyymm')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."VOALIST_ONLINE_LOG_PK" ON "PIBICSDM2"."VOALIST_ONLINE_LOG" ("VOALO_LOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."VOALIST_ONLINE_LOG" TO "BIOSAADM";
