CREATE TABLE "PIBICSDM2"."VOALIST_ONLINE" 
   (	"VOALO_SEQNO" NUMBER, 
	"PASSPORT_PLACE" VARCHAR2(60 CHAR), 
	"PASSPORT_EXPDATE" DATE, 
	"PASSPORT_ISSUEDATE" DATE, 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"BIRTH_DATE" VARCHAR2(10 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"RPJSEQNO" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"VERIFY_BLACKLIST" CHAR(1 CHAR), 
	"STS" CHAR(1 CHAR), 
	"VOAO_SEQNO" NUMBER, 
	"VOAR_SEQNO" NUMBER, 
	"PERADD" VARCHAR2(1500 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"VERSION" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6)
   ) ;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE" ADD CONSTRAINT "VOALIST_ONLINE_PK" PRIMARY KEY ("VOALO_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE" ADD FOREIGN KEY ("NATION_SEQNO")
	  REFERENCES "PIBICSDM2"."COUNTRY" ("COUNT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE" ADD FOREIGN KEY ("OCC_SEQNO")
	  REFERENCES "PIBICSDM2"."OCCUPATION" ("OCC_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."VOALIST_ONLINE" ADD CONSTRAINT "VOALIST_ONLINE_R01" FOREIGN KEY ("VOAO_SEQNO")
	  REFERENCES "PIBICSDM2"."VOA_ONLINE" ("VOAO_SEQNO") ENABLE;
  CREATE INDEX "PIBICSDM2"."VOALIST_ONLINE_CREATEDTE1" ON "PIBICSDM2"."VOALIST_ONLINE" (TO_CHAR("CREATE_DATE",'yyyymmdd')) 
  ;
CREATE INDEX "PIBICSDM2"."VOALIST_ONLINE_CREATEDTE2" ON "PIBICSDM2"."VOALIST_ONLINE" (TO_CHAR("CREATE_DATE",'yyyymm')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."VOALIST_ONLINE_PK" ON "PIBICSDM2"."VOALIST_ONLINE" ("VOALO_SEQNO") 
  ;
