CREATE TABLE "PIBICSDM2"."VWWANTED_POLISDEL" 
   (	"WARRANT_NO" VARCHAR2(20 CHAR), 
	"WARRANT_YEAR" VARCHAR2(4 CHAR), 
	"WARRANT_ORG" VARCHAR2(10 CHAR), 
	"CRIME_NO" VARCHAR2(10 CHAR), 
	"CRIME_YEAR" VARCHAR2(10 CHAR), 
	"ORG_CODE" VARCHAR2(10 CHAR), 
	"OFFENDER_NO" VARCHAR2(10 CHAR), 
	"RELEASE_FLAG" CHAR(1 CHAR), 
	"RELEASE_DATE" VARCHAR2(10 CHAR), 
	"CAUSE" VARCHAR2(1000 CHAR), 
	"LOGIN_ID" VARCHAR2(20 CHAR), 
	"KEY_DATE" DATE
   ) ;
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."VWWANTED_POLISDEL" TO "BIOSAADM";
