CREATE TABLE "PIBICSDM2"."WATCHLISTLOG_HIST" 
   (	"WATCHLISTHISTID" NUMBER, 
	"WATCHLISTLOGID" NUMBER, 
	"DELREMARK" VARCHAR2(1000 CHAR), 
	"LOGUSERID" VARCHAR2(20 CHAR), 
	"LOGFLAG" VARCHAR2(1 CHAR), 
	"LOGDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."WATCHLISTLOG_HIST" ADD PRIMARY KEY ("WATCHLISTHISTID")
  USING INDEX  ENABLE;
  ;
