CREATE TABLE "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" 
   (	"WLCD" VARCHAR2(20 CHAR), 
	"SEQ" NUMBER, 
	"PERMIT_DATE" DATE, 
	"OVERSTAY_DATE" DATE, 
	"PRESENT_TYPE" VARCHAR2(1 CHAR), 
	"PROHIBIT_AMT" VARCHAR2(20 CHAR), 
	"OVERSTAY_DAY" NUMBER, 
	"REMARK" VARCHAR2(1000 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" ADD CONSTRAINT "WATCHLIST_OVERSTAY_EX_PK" PRIMARY KEY ("WLCD", "SEQ")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WATCHLIST_OVERSTAY_EX_PK" ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" ("WLCD", "SEQ") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WATCHLIST_OVERSTAY_EX" TO "BIOSAADM";
