CREATE TABLE "PIBICSDM2"."WATCHLISTPIC" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"WLPIC" BLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."WATCHLISTPIC" ADD CONSTRAINT "WATCHLISTPIC_PK" PRIMARY KEY ("SEQNO", "WLCD")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000420509C00003$$" ON "PIBICSDM2"."WATCHLISTPIC" (
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."WATCHLISTPIC_PK" ON "PIBICSDM2"."WATCHLISTPIC" ("SEQNO", "WLCD") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WATCHLISTPIC" TO "BIOSAADM";
