CREATE TABLE "PIBICSDM2"."WELFARE_EDRQTDOCMT" 
   (	"DEPTCD" CHAR(4 CHAR), 
	"FSCYEAR" CHAR(4 CHAR), 
	"RQTDOCNO" CHAR(20 CHAR), 
	"RQTDOCDTE" DATE, 
	"RQTDOCSTS" CHAR(1 CHAR), 
	"CITIZENID" CHAR(13 CHAR), 
	"RANKNM" VARCHAR2(60 CHAR), 
	"FIRSTNM" VARCHAR2(60 CHAR), 
	"LASTNM" VARCHAR2(60 CHAR), 
	"DEPTNM" VARCHAR2(60 CHAR), 
	"RCTTOTAL" NUMBER, 
	"PMTTOTAL" NUMBER(10,2), 
	"RQTTOTAL" NUMBER(10,2), 
	"ACTFLAG" CHAR(1 CHAR), 
	"CVRDOCNO" DATE, 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WELFARE_EDRQTDOCMT" TO "BIOSAADM";
