CREATE TABLE "PIBICSDM2"."WELFARE_FNFEE" 
   (	"FSCYEAR" CHAR(4 CHAR), 
	"MONTH" CHAR(4 CHAR), 
	"FNMBRFEENML" CHAR(1 CHAR), 
	"FNMBRFEEJN" CHAR(1 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
