CREATE TABLE "PIBICSDM2"."WF_BUILDING" 
   (	"BD_ID" NUMBER, 
	"BD_NAME" VARCHAR2(200 CHAR), 
	"VERSION" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"ACTFLAG" CHAR(1 CHAR), 
	"BD_ADDR" VARCHAR2(300 CHAR), 
	"PV_SEQNO" NUMBER, 
	"AMP_SEQNO" NUMBER, 
	"TMB_SEQNO" NUMBER, 
	"BD_PHONENO" VARCHAR2(100 CHAR), 
	"BD_POSTNO" CHAR(5 CHAR)
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_BUILDING_PK" ON "PIBICSDM2"."WF_BUILDING" ("BD_ID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_BUILDING" TO "BIOSAADM";
