CREATE TABLE "PIBICSDM2"."WF_BILL" 
   (	"BILL_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"TENANT_SEQNO" NUMBER, 
	"APT_SEQNO" NUMBER, 
	"MON_SEQNO" NUMBER, 
	"BILL_WATERAMT" NUMBER, 
	"BILL_CLEANAMP" NUMBER, 
	"BILL_PROPERTYAMT" NUMBER, 
	"BILL_OTHERAMT" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"BILL_MONTH" NUMBER, 
	"BILL_YEAR" VARCHAR2(4 CHAR), 
	"WAT_SEQNO" NUMBER, 
	"BILL_SUMAMT" NUMBER, 
	"BD_ID" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_BILL" ADD CONSTRAINT "WF_FACILITYUSAGE_PK" PRIMARY KEY ("BILL_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_BILL" ADD CONSTRAINT "WF_BILL_R01" FOREIGN KEY ("APT_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_APARTMENT" ("APT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_BILL" ADD CONSTRAINT "WF_FACILITYUSAGE_R04" FOREIGN KEY ("MON_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_MONTHLYBILL" ("MON_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_BILL" ADD CONSTRAINT "WF_FACILITYUSAGE_R03" FOREIGN KEY ("TENANT_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_TENANT" ("TENANT_SEQNO") ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_BILL" ADD CONSTRAINT "WF_BILL_R02" FOREIGN KEY ("WAT_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_WATERUSAGE" ("WAT_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_FACILITYUSAGE_PK" ON "PIBICSDM2"."WF_BILL" ("BILL_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_BILL" TO "BIOSAADM";
