CREATE TABLE "PIBICSDM2"."WF_CREMATION_LOG" 
   (	"CMLOG_SEQNO" NUMBER, 
	"LOG_FLAG" VARCHAR2(1 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_USERID" VARCHAR2(30 CHAR), 
	"CM_SEQNO" NUMBER, 
	"CM_APPLYDATE" DATE, 
	"CM_QUITDATE" DATE, 
	"CM_CREMATIONSTS" CHAR(1 CHAR), 
	"CM_FUNDMOMDATE" DATE, 
	"PROFILE_SEQNO" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"CM_REMARK" VARCHAR2(600 CHAR), 
	"VERSION" NUMBER, 
	"CM_FUNDDADDATE" DATE, 
	"CM_FUNDWFDATE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_CREMATION_LOG" ADD CONSTRAINT "WF_CREMATION_LOG_PK" PRIMARY KEY ("CMLOG_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_CREMATION_LOG_PK" ON "PIBICSDM2"."WF_CREMATION_LOG" ("CMLOG_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_CREMATION_LOG" TO "BIOSAADM";
