CREATE TABLE "PIBICSDM2"."WF_COVERDOCHEADER" 
   (	"CH_SEQNO" NUMBER, 
	"CH_DATE" DATE, 
	"CH_FISCALYEAR" CHAR(4 CHAR), 
	"CH_TOTALAMT" NUMBER(22,2), 
	"CH_TYPE" VARCHAR2(20 CHAR), 
	"CH_STATUS" CHAR(6 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CH_RUNNING" VARCHAR2(5 CHAR), 
	"CH_YEAR" VARCHAR2(4 CHAR), 
	"USER_DEPT_SEQNO" NUMBER, 
	"USER_DEPTCD" CHAR(3 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_COVERDOCHEADER" ADD CONSTRAINT "WF_COVERDOCHEADER_PK" PRIMARY KEY ("CH_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_COVERDOCHEADER_PK" ON "PIBICSDM2"."WF_COVERDOCHEADER" ("CH_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_COVERDOCHEADER" TO "BIOSAADM";
