CREATE TABLE "PIBICSDM2"."WF_EDUDETAIL_LOG" 
   (	"ED_SEQNO_LOG" NUMBER, 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_USERID" VARCHAR2(30 CHAR), 
	"ED_SEQNO" NUMBER, 
	"EH_SEQNO" NUMBER, 
	"CH_SEQNO" NUMBER, 
	"ED_INSTITUTE" VARCHAR2(60 CHAR), 
	"ED_EDUYEAR" CHAR(4 CHAR), 
	"ED_SEMESTER" NUMBER, 
	"ED_EDULEVEL" VARCHAR2(60 CHAR), 
	"ED_AMOUNT" NUMBER(10,2), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"CH_ORDERNO" NUMBER, 
	"CH_NAME" VARCHAR2(100 CHAR), 
	"CH_CARDID" VARCHAR2(13 CHAR), 
	"CH_BIRTHDATE" DATE, 
	"ED_RECEIPTDATE" DATE, 
	"ED_AGE_YEAR" NUMBER, 
	"ED_AGE_MONTH" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"ED_REMARK" VARCHAR2(605 CHAR), 
	"EL_SEQNO" NUMBER, 
	"EH_SEQNO_LOG" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_EDUDETAIL_LOG" ADD CONSTRAINT "WF_STUDYDETAIL_LOG_PK" PRIMARY KEY ("ED_SEQNO_LOG")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_EDUDETAIL_LOG" ADD CONSTRAINT "WF_EDUDETAIL_LOG_R01" FOREIGN KEY ("EH_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_EDUHEADER" ("EH_SEQNO") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_STUDYDETAIL_LOG_PK" ON "PIBICSDM2"."WF_EDUDETAIL_LOG" ("ED_SEQNO_LOG") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_EDUDETAIL_LOG" TO "BIOSAADM";
