CREATE TABLE "PIBICSDM2"."WF_EDUHEADER" 
   (	"EH_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"EH_DOCDATE" DATE, 
	"EH_FISCALYEAR" CHAR(4 CHAR), 
	"EH_TOTALAMT" NUMBER(10,2), 
	"EH_TOTALITEM" NUMBER, 
	"EH_COVERDOCSTATUS" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"EH_RUNNINGNO" VARCHAR2(5 CHAR), 
	"EH_YEAR" VARCHAR2(4 CHAR), 
	"NAME" VARCHAR2(30 CHAR), 
	"SNAME" VARCHAR2(30 CHAR), 
	"RANK_SEQNO" VARCHAR2(3 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"POS_SEQNO" VARCHAR2(6 CHAR), 
	"ACTFLAG" CHAR(1 CHAR), 
	"USER_DEPT_SEQNO" NUMBER, 
	"USER_DEPTCD" CHAR(3 CHAR), 
	"PAID_STATUS" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_EDUHEADER" ADD CONSTRAINT "WF_STUDYHEADER_PK" PRIMARY KEY ("EH_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_STUDYHEADER_PK" ON "PIBICSDM2"."WF_EDUHEADER" ("EH_SEQNO") 
  ;
