CREATE TABLE "PIBICSDM2"."WF_HEALTHDETAIL_LOG" 
   (	"HD_SEQNO_LOG" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_USERID" VARCHAR2(30 CHAR), 
	"HD_SEQNO" NUMBER, 
	"HH_SEQNO" NUMBER, 
	"RELATIVE_SEQNO" NUMBER, 
	"HD_PATIENCETYPE" VARCHAR2(3 CHAR), 
	"HD_AMOUNT" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"HD_NAME" VARCHAR2(100 CHAR), 
	"HD_CARDID" VARCHAR2(13 CHAR), 
	"CH_ORDERNO" NUMBER, 
	"HD_BIRTHDATE" DATE, 
	"HD_RECEIPTDATE" DATE, 
	"HD_AGE_YEAR" NUMBER, 
	"HD_AGE_MONTH" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR), 
	"HD_REMARK" VARCHAR2(600 CHAR), 
	"RELATIVETYPE" CHAR(1 CHAR), 
	"HH_SEQNO_LOG" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_HEALTHDETAIL_LOG" ADD CONSTRAINT "WF_HEALTDETAIL_LOG_PK" PRIMARY KEY ("HD_SEQNO_LOG")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."WF_HEALTHDETAIL_LOG" ADD CONSTRAINT "WF_HEALTHDETAIL_LOG_R01" FOREIGN KEY ("HH_SEQNO")
	  REFERENCES "PIBICSDM2"."WF_HEALTHHEADER_LOG" ("HH_SEQNO_LOG") DISABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_HEALTDETAIL_LOG_PK" ON "PIBICSDM2"."WF_HEALTHDETAIL_LOG" ("HD_SEQNO_LOG") 
  ;
