CREATE TABLE "PIBICSDM2"."WF_HEALTHHEADER_LOG" 
   (	"HH_SEQNO_LOG" NUMBER, 
	"LOG_FLAG" CHAR(1 CHAR), 
	"LOG_DATE" TIMESTAMP (6), 
	"LOG_USERID" VARCHAR2(30 CHAR), 
	"HH_SEQNO" NUMBER, 
	"PROFILE_SEQNO" NUMBER, 
	"HH_DOCDATE" DATE, 
	"HH_FISCALYEAR" CHAR(4 CHAR), 
	"HH_TOTALAMT" NUMBER, 
	"HH_TOTALITEM" NUMBER, 
	"HH_COVERDOCSTATUS" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"HH_RUNNINGNO" VARCHAR2(5 CHAR), 
	"HH_YEAR" VARCHAR2(4 CHAR), 
	"NAME" VARCHAR2(30 CHAR), 
	"SNAME" VARCHAR2(30 CHAR), 
	"RANK_SEQNO" VARCHAR2(3 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"POS_SEQNO" VARCHAR2(8 CHAR), 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"USER_DEPT_SEQNO" NUMBER, 
	"USER_DEPTCD" CHAR(3 CHAR), 
	"PAID_STATUS" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_HEALTHHEADER_LOG" ADD CONSTRAINT "WF_HEALTHHEADER_LOG_PK" PRIMARY KEY ("HH_SEQNO_LOG")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_HEALTHHEADER_LOG_PK" ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" ("HH_SEQNO_LOG") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_HEALTHHEADER_LOG" TO "BIOSAADM";
