CREATE TABLE "PIBICSDM2"."WF_PROCESS_CONTROL" 
   (	"PC_SEQNO" NUMBER, 
	"PC_MONTH" NUMBER, 
	"PC_YEAR" VARCHAR2(4 CHAR), 
	"PC_METERINPUT" CHAR(1 CHAR), 
	"PC_CALBILL" CHAR(1 CHAR), 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"VERSION" NUMBER DEFAULT 1, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"PC_TENANT" CHAR(1 CHAR), 
	"BD_ID" NUMBER
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_PROCESS_CONTROL" ADD CONSTRAINT "WF_PROCESS_CONTROL_PK" PRIMARY KEY ("PC_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_PROCESS_CONTROL_PK" ON "PIBICSDM2"."WF_PROCESS_CONTROL" ("PC_SEQNO") 
  ;
