CREATE TABLE "PIBICSDM2"."WF_WATERUSAGE" 
   (	"WAT_SEQNO" NUMBER, 
	"APT_SEQNO" NUMBER, 
	"WAT_MONTH" NUMBER, 
	"WAT_YEAR" CHAR(4 CHAR), 
	"WAT_METERVALUE" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"WAT_USAGE" NUMBER, 
	"PROCESS" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WF_WATERUSAGE" ADD CONSTRAINT "WF_WATERUSAGE_PK" PRIMARY KEY ("WAT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WF_WATERUSAGE_PK" ON "PIBICSDM2"."WF_WATERUSAGE" ("WAT_SEQNO") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WF_WATERUSAGE" TO "BIOSAADM";
