CREATE TABLE "PIBICSDM2"."WINOUTPERSON" 
   (	"SEQNO" VARCHAR2(100 CHAR), 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" CHAR(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" CHAR(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"AGE" NUMBER, 
	"NATIONCD" CHAR(3 CHAR), 
	"DEPTCD" VARCHAR2(5 CHAR), 
	"CONVCD" CHAR(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"CREDTE" DATE, 
	"PERSONID" VARCHAR2(20 CHAR), 
	"IMGINOUT" BLOB, 
	"WANTEDSEQNO" NUMBER
   ) ;
  CREATE UNIQUE INDEX "PIBICSDM2"."SYS_IL0000302374C00023$$" ON "PIBICSDM2"."WINOUTPERSON" (
  ;
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WINOUTPERSON" TO "BIOSAADM";
