CREATE TABLE "PIBICSDM2"."WKLOG" 
   (	"WKLOGID" NUMBER(38,0), 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"APPCD" VARCHAR2(20 CHAR), 
	"USERID" CHAR(6 CHAR), 
	"TTLREC" NUMBER, 
	"STARTDTE" DATE, 
	"ENDDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."WKLOG" ADD CONSTRAINT "PK_WKLOGID" PRIMARY KEY ("WKLOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_WKLOGID" ON "PIBICSDM2"."WKLOG" ("WKLOGID") 
  ;
