CREATE TABLE "PIBICSDM2"."WLCHARGE" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"CHARGE_CODE" VARCHAR2(5 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WLCHARGE" ADD CONSTRAINT "WLCHARGE_PK" PRIMARY KEY ("WLCD", "SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WLCHARGE_PK" ON "PIBICSDM2"."WLCHARGE" ("WLCD", "SEQNO") 
  ;
