CREATE TABLE "PIBICSDM2"."WLINDICATECARD" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"IDCCD" CHAR(4 CHAR), 
	"DOCNO" VARCHAR2(20 CHAR), 
	"ISUDTE" DATE, 
	"ISUPLACE" VARCHAR2(60 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WLINDICATECARD" ADD CONSTRAINT "PK_WLINDICATECARD" PRIMARY KEY ("SEQNO", "WLCD")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."WLCARD_DOCNO_IDX" ON "PIBICSDM2"."WLINDICATECARD" ("DOCNO") 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_I1" ON "PIBICSDM2"."WLINDICATECARD" ("WLCD") 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_RP_DOCNO_IDX" ON "PIBICSDM2"."WLINDICATECARD" (REPLACE("DOCNO",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_RP_DOCNO_IDX2" ON "PIBICSDM2"."WLINDICATECARD" (REPLACE("DOCNO",'-','')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PK_WLINDICATECARD" ON "PIBICSDM2"."WLINDICATECARD" ("SEQNO", "WLCD") 
  ;
