CREATE TABLE "PIBICSDM2"."WLINDICATECARD" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"IDCCD" CHAR(4 CHAR), 
	"DOCNO" VARCHAR2(20 CHAR), 
	"ISUDTE" DATE, 
	"ISUPLACE" VARCHAR2(60 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WLINDICATECARD" ADD CONSTRAINT "PK_WLINDICATECARD" PRIMARY KEY ("SEQNO", "WLCD")
  USING INDEX  ENABLE;
  CREATE INDEX "PIBICSDM2"."WLCARD_DOCNO_IDX" ON "PIBICSDM2"."WLINDICATECARD" ("DOCNO") 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_I1" ON "PIBICSDM2"."WLINDICATECARD" ("WLCD") 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_RP_DOCNO_IDX" ON "PIBICSDM2"."WLINDICATECARD" (REPLACE("DOCNO",' ','')) 
  ;
CREATE INDEX "PIBICSDM2"."WLINDICATECARD_RP_DOCNO_IDX2" ON "PIBICSDM2"."WLINDICATECARD" (REPLACE("DOCNO",'-','')) 
  ;
CREATE UNIQUE INDEX "PIBICSDM2"."PK_WLINDICATECARD" ON "PIBICSDM2"."WLINDICATECARD" ("SEQNO", "WLCD") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WLINDICATECARD" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "DL_BORDERCONTROL";
  GRANT SELECT ON "PIBICSDM2"."WLINDICATECARD" TO "APPSUSR";
