CREATE TABLE "PIBICSDM2"."WLREMARK" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"REMK" CLOB
   ) ;
  ALTER TABLE "PIBICSDM2"."WLREMARK" ADD CONSTRAINT "PK_WLREMARK" PRIMARY KEY ("SEQNO", "WLCD")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."PK_WLREMARK" ON "PIBICSDM2"."WLREMARK" ("SEQNO", "WLCD") 
  ;
  ;
