CREATE TABLE "PIBICSDM2"."WORKGROUP" 
   (	"WKGCD" VARCHAR2(20 CHAR), 
	"WKGNM" VARCHAR2(60 CHAR), 
	"WKGDESC" VARCHAR2(250 CHAR), 
	"UPDUSR" CHAR(6 CHAR), 
	"UPDDTE" DATE
   ) ;
  ALTER TABLE "PIBICSDM2"."WORKGROUP" ADD CONSTRAINT "WKGCD_PK" PRIMARY KEY ("WKGCD")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WKGCD_PK" ON "PIBICSDM2"."WORKGROUP" ("WKGCD") 
  ;
