CREATE TABLE "PIBICSDM2"."WORKPERMISSION" 
   (	"WORKPERID" NUMBER(10,0), 
	"FAID" NUMBER(10,0), 
	"WKGCD" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "PIBICSDM2"."WORKPERMISSION" ADD CONSTRAINT "WORKPERID_PK" PRIMARY KEY ("WORKPERID")
  USING INDEX  ENABLE;
  ALTER TABLE "PIBICSDM2"."WORKPERMISSION" ADD CONSTRAINT "WKGCD_FK2" FOREIGN KEY ("WKGCD")
	  REFERENCES "PIBICSDM2"."WORKGROUP" ("WKGCD") ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WORKPERID_PK" ON "PIBICSDM2"."WORKPERMISSION" ("WORKPERID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WORKPERMISSION" TO "BIOSAADM";
