CREATE TABLE "PIBICSDM2"."WORKPERMISSIONLOG" 
   (	"WORKPERID" NUMBER(10,0), 
	"FAID" NUMBER(10,0), 
	"WKGCD" VARCHAR2(20 CHAR), 
	"LOGUSERID" CHAR(6 CHAR), 
	"LOGFLAG" CHAR(1 CHAR), 
	"LOGDTE" DATE, 
	"CHKPOINTNO" CHAR(3 CHAR), 
	"WORKPERMISSIONLOGID" NUMBER(5,0)
   ) ;
  ALTER TABLE "PIBICSDM2"."WORKPERMISSIONLOG" ADD CONSTRAINT "WORKPERMISSIONLOG_PK" PRIMARY KEY ("WORKPERMISSIONLOGID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "PIBICSDM2"."WORKPERMISSIONLOG_PK" ON "PIBICSDM2"."WORKPERMISSIONLOG" ("WORKPERMISSIONLOGID") 
  ;
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "ROLE_SERVAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "ROLE_PIBICSAPP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "ROLE_PIBICSDM2_RO";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "ROLE_DL_STAGING4PIBICS";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIO_BD";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "APPSUP";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOAPPREPORT";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSUPPORT";
  GRANT ALTER ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT DELETE ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT INDEX ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT INSERT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT SELECT ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT UPDATE ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT REFERENCES ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT READ ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT DEBUG ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
  GRANT FLASHBACK ON "PIBICSDM2"."WORKPERMISSIONLOG" TO "BIOSAADM";
