CREATE TABLE "DL_COMMON"."DYNAMIC_SQLS$HIS" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"APP_ALIAS" VARCHAR2(255 CHAR), 
	"PAGE_ID" NUMBER(10,0), 
	"SQL_TEXT" CLOB, 
	"SQL_TYPE" VARCHAR2(255 CHAR), 
	"COMMENTS" VARCHAR2(4000 CHAR), 
	"OWNER" VARCHAR2(128 CHAR), 
	"INS_AT" DATE, 
	"INS_BY" VARCHAR2(255 CHAR), 
	"DML_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "DL_COMMON"."SYS_IL0000722951C00005$$" ON "DL_COMMON"."DYNAMIC_SQLS$HIS" (
  ;
