CREATE TABLE "DL_BORDERCONTROL"."XXFMENN_BLOBS" 
   (	"ID" NUMBER, 
	"XDATA" BLOB
   ) ;
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IL0000500672C00002$$" ON "DL_BORDERCONTROL"."XXFMENN_BLOBS" (
  ;
