CREATE TABLE "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL SYSDATE NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"SENDER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SENDER_OBJECT" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"SENDER_OBJECT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"SENDER_MESSAGE" CLOB, 
	"SENDER_RESPONSE_CODE" VARCHAR2(50 CHAR), 
	"SENDER_RESPONSE_MESSAGE" CLOB, 
	"RECEIVER_RESPONSE_ID" VARCHAR2(100 CHAR), 
	"RECEIVER_RESPONSE" CLOB, 
	"PROCESS_TIME" NUMBER
   ) ;
  ALTER TABLE "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" ADD CONSTRAINT "LOG_SYNC_WEBSERVICES$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."KEY_VALUE" IS 'Primary Key';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."DML_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."DML_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."DML_TYPE" IS 'Audit (I.nsert, U.pdate, D.elete)';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."INS_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."INS_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER" IS 'Name of application, schema or identifier who send this message';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER_OBJECT" IS 'Name of Object that should be transfered (e.g. MOVEMENTS)';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER_OBJECT_ID" IS 'PK of Object that should be transfered';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER_MESSAGE" IS 'PK of Object that should be transfered';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER_RESPONSE_CODE" IS 'Response code of step 1 (asynchronous)';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."SENDER_RESPONSE_MESSAGE" IS 'Error message of step 1 (asynchronous)';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."RECEIVER_RESPONSE_ID" IS 'Response ID or message of the database that came from another system';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."RECEIVER_RESPONSE" IS 'JSON Response that came from another system';
   COMMENT ON COLUMN "DL_INTERFACE"."LOG_SYNC_WEBSERVICES"."PROCESS_TIME" IS 'The time in seconds that the Request took to get a Response.';
  CREATE INDEX "DL_INTERFACE"."LOG_SYNC_WEBSERVICES_IDX1" ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" ("SENDER_OBJECT_ID", TO_NUMBER("SENDER_RESPONSE_CODE")) 
  ;
CREATE UNIQUE INDEX "DL_INTERFACE"."LOG_SYNC_WEBSERVICES$PK" ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_INTERFACE"."SYS_IL0000313571C00010$$" ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" (
  ;
CREATE UNIQUE INDEX "DL_INTERFACE"."SYS_IL0000313571C00012$$" ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" (
  ;
CREATE UNIQUE INDEX "DL_INTERFACE"."SYS_IL0000313571C00014$$" ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" (
  ;
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "DL_BORDERCONTROL";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "SERVAPP";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "BIO_BD";
  GRANT DELETE ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "APPSUP";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "PIBICSAPP";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_INTERFACE"."LOG_SYNC_WEBSERVICES" TO "BIOSUPPORT";
