CREATE TABLE "DL_USER_MANAGEMENT"."LOOKUPS" 
   (	"KEY_CATEGORY" VARCHAR2(64 CHAR) NOT NULL ENABLE, 
	"KEY_VALUE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"PARENT_KEY_CATEGORY" VARCHAR2(64 CHAR), 
	"PARENT_KEY_VALUE" VARCHAR2(32 CHAR), 
	"DISPLAY_VALUE" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER(*,0), 
	"IS_ACTIVE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'Y' NOT NULL ENABLE, 
	"NOTICE" VARCHAR2(4000 CHAR), 
	"NUM_VALUE" NUMBER(32,0), 
	"LOCALE" VARCHAR2(5 CHAR) DEFAULT ON NULL 'en_US' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"ROW_FLAG_MASK" NUMBER(6,0) DEFAULT ON NULL 0 NOT NULL ENABLE, 
	"TAG" VARCHAR2(255 CHAR), 
	"DISPLAY_VALUE_SHORT" VARCHAR2(30 CHAR), 
	"DISPLAY_VALUE_ALTERNATIVE" VARCHAR2(200 CHAR), 
	"VALUE_LARGE_DATA_ID" NUMBER(*,0)
   ) ;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$PK" PRIMARY KEY ("KEY_CATEGORY", "KEY_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$UQ00" UNIQUE ("KEY_CATEGORY", "NUM_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$CHK00" CHECK (LOCALE = 'en_US') ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$CHK01" CHECK (DML_TYPE in ('I'
                                                                                      ,'U')) ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$CHK02" CHECK (IS_ACTIVE in ('Y'
                                                                                       ,'N')) ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."LOOKUPS" ADD CONSTRAINT "LOOKUPS$FK00" FOREIGN KEY ("PARENT_KEY_CATEGORY", "PARENT_KEY_VALUE")
	  REFERENCES "DL_USER_MANAGEMENT"."LOOKUPS" ("KEY_CATEGORY", "KEY_VALUE") ON DELETE CASCADE ENABLE;
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."KEY_CATEGORY" IS 'Lookup category,e.g. "gender","country"';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."KEY_VALUE" IS 'Key of the lookup. Within a category this key is unique if only the active lookups are considered.';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."PARENT_KEY_CATEGORY" IS 'Lookup category of the parent lookup if there is a hierarchy (e.g. district < country)';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."PARENT_KEY_VALUE" IS 'Lookup key of the parent lookup if there is a hierarchy (e.g. district < country)';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."DISPLAY_VALUE" IS 'Long version of the lookup value (e.g. country name)';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."IS_ACTIVE" IS '"Y" if the lookup is currently active, "N" if not.';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."NOTICE" IS 'Description on the lookup value';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."NUM_VALUE" IS 'Numeric lookup value';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."LOCALE" IS 'Locale for multilanguage candidates';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."ROW_FLAG_MASK" IS 'Bitmask: 1 => delivered by Dermalog, 2 => reserved, 4 => reserved, 8 => reserved, 16 => prevent update, 32 => prevent delete, 64 .. 524288 => reserved !';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."LOOKUPS"."TAG" IS 'Tag for the row, for example for better identifying the datasets by any DML-Statements.';
   COMMENT ON TABLE "DL_USER_MANAGEMENT"."LOOKUPS"  IS 'Global lookup table';
  CREATE INDEX "DL_USER_MANAGEMENT"."LOOKUPS$IX00" ON "DL_USER_MANAGEMENT"."LOOKUPS" ("DISPLAY_VALUE", "DISPLAY_ORDER") 
  ;
CREATE INDEX "DL_USER_MANAGEMENT"."LOOKUPS$IX01" ON "DL_USER_MANAGEMENT"."LOOKUPS" ("DML_AT", "DML_BY") 
  ;
CREATE INDEX "DL_USER_MANAGEMENT"."LOOKUPS$IX02" ON "DL_USER_MANAGEMENT"."LOOKUPS" ("PARENT_KEY_CATEGORY", "PARENT_KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_USER_MANAGEMENT"."LOOKUPS$PK" ON "DL_USER_MANAGEMENT"."LOOKUPS" ("KEY_CATEGORY", "KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_USER_MANAGEMENT"."LOOKUPS$UQ00" ON "DL_USER_MANAGEMENT"."LOOKUPS" ("KEY_CATEGORY", "NUM_VALUE") 
  ;
  GRANT DELETE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "APEX_USER_MANAGEMENT";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "APEX_USER_MANAGEMENT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "APEX_USER_MANAGEMENT";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "APEX_USER_MANAGEMENT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "SERVAPP";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "DL_BORDERCONTROL";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIO_BD";
  GRANT DELETE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "APPSUP";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT DELETE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT INDEX ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT READ ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "BIOSAADM";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "PUNYAWII_D";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "WORAGON_T";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "PISAN_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "CHAYA_W";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "THANASET_N";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "THASAYA_M";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "PORNRUKSA_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."LOOKUPS" TO "SANTIPATN_P";
