CREATE TABLE "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" 
   (	"ID" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"OBJECT_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"APP_NAME" VARCHAR2(100 CHAR), 
	"PAGE_ID" NUMBER NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"ROW_FLAG_MASK" NUMBER(6,0) DEFAULT ON NULL 0 NOT NULL ENABLE, 
	"TAG" VARCHAR2(255 CHAR)
   ) ;
  ALTER TABLE "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ADD CONSTRAINT "OBJECT_PAGE_REL$PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ADD CONSTRAINT "OBJECT_PAGE_REL$CHK01" CHECK (DML_TYPE in ('I'
                                                                                                      ,'U')) ENABLE;
  ALTER TABLE "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ADD CONSTRAINT "OBJECT_PAGE_REL$FK00" FOREIGN KEY ("OBJECT_ID")
	  REFERENCES "DL_USER_MANAGEMENT"."OBJECTS" ("ID") ON DELETE CASCADE ENABLE;
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."ID" IS 'Artificial primary key';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."OBJECT_ID" IS 'Foreign key to table OBJECTS';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."APP_NAME" IS 'APEX-App-Name who is parent of PAGE_ID';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."PAGE_ID" IS 'Page ID (as in APEX_[999999].APEX_APPLICATION_PAGES)';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."ROW_FLAG_MASK" IS 'Bitmask: 1 => delivered by Dermalog, 2 => reserved, 4 => reserved, 8 => reserved, 16 => prevent update, 32 => prevent delete, 64 .. 524288 => reserved !';
   COMMENT ON COLUMN "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"."TAG" IS 'Tag for the row, for example for better identifying the datasets by any DML-Statements.';
   COMMENT ON TABLE "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL"  IS 'Relations between Objects and apex application pages (assignment of apex aplication pages to objects)';
  CREATE INDEX "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL$IX00" ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ("OBJECT_ID", "PAGE_ID", "APP_NAME") 
  ;
CREATE INDEX "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL$IX01" ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ("DML_AT", "DML_BY") 
  ;
CREATE UNIQUE INDEX "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL$PK" ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" ("ID") 
  ;
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "SERVAPP";
  GRANT DELETE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "APEX_USER_MANAGEMENT";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "APEX_USER_MANAGEMENT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "APEX_USER_MANAGEMENT";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "APEX_USER_MANAGEMENT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "DL_BORDERCONTROL";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIO_BD";
  GRANT DELETE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "APPSUP";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT DELETE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT INDEX ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT INSERT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT UPDATE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT READ ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT DEBUG ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "BIOSAADM";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "PUNYAWII_D";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "SOMPORN_K";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "WORAGON_T";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "PISAN_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "CHAYA_W";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "THANASET_N";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "THASAYA_M";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "PORNRUKSA_S";
  GRANT SELECT ON "DL_USER_MANAGEMENT"."OBJECT_PAGE_REL" TO "SANTIPATN_P";
