CREATE TABLE "DL_STAGING4PIBICS"."MLOG$_TMINOUT" 
   (	"SEQNO" VARCHAR2(100 CHAR), 
	"M_ROW$$" VARCHAR2(255 CHAR), 
	"SEQUENCE$$" NUMBER, 
	"DMLTYPE$$" VARCHAR2(1 CHAR), 
	"OLD_NEW$$" VARCHAR2(1 CHAR), 
	"CHANGE_VECTOR$$" RAW(255), 
	"XID$$" NUMBER
   ) ;
   COMMENT ON TABLE "DL_STAGING4PIBICS"."MLOG$_TMINOUT"  IS 'snapshot log for master table DL_STAGING4PIBICS.TMINOUT';
  CREATE INDEX "DL_STAGING4PIBICS"."I_MLOG$_TMINOUT" ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" ("XID$$") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "SERVAPP";
  GRANT DELETE ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_TMINOUT" TO "TESTADM";
