CREATE TABLE "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" 
   (	"PROCESS_NAME" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"KIND" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"PROCESS_CLUSTER" VARCHAR2(500 CHAR), 
	"SHALL_BE_SYNCED" VARCHAR2(1 CHAR), 
	"PROCESS_CLUSTER_SEQUENCE" NUMBER
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" ADD CONSTRAINT "PIBICS_LOAD_PROCESSES_PK" PRIMARY KEY ("PROCESS_NAME")
  USING INDEX (CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES_PK" ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" ("PROCESS_NAME") 
  )  ENABLE;
  ALTER TABLE "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" ADD CONSTRAINT "PIBICS_LOAD_PROCESSES_KIND" CHECK (KIND in ('M', 'B','A')) ENABLE;
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES"."PROCESS_NAME" IS 'mostly the name of the table in staging';
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES"."KIND" IS '(M) ranscode (B) usiness-transaction';
   COMMENT ON TABLE "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES"  IS 'Metatable for the different LOAD-processes in the system';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES_PK" ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" ("PROCESS_NAME") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OPS_PIBICS_LOAD_PROCESSES" TO "TESTADM";
