CREATE TABLE "DL_STAGING4PIBICS"."THAIPASSPORT" 
   (	"UPDATE_YYYYMM" NUMBER INVISIBLE GENERATED ALWAYS AS (CAST(TO_CHAR(TRUNC("UPDATE_DATE",'fmmm'),'YYYYMM') AS NUMBER)) VIRTUAL , 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"PASSPORTNO" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"PASSNO" VARCHAR2(4 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"SEX" VARCHAR2(1 CHAR), 
	"NATIONCD" VARCHAR2(3 CHAR), 
	"HEIGHT" NUMBER, 
	"WEIGHT" NUMBER, 
	"ADDR" VARCHAR2(60 CHAR), 
	"DISTRICT" VARCHAR2(60 CHAR), 
	"CITYCD" VARCHAR2(3 CHAR), 
	"STATECD" VARCHAR2(2 CHAR), 
	"ZIPCODE" VARCHAR2(5 CHAR), 
	"TELNO" VARCHAR2(60 CHAR), 
	"PASSPORTDTE" DATE, 
	"PASSPORTEXPDTE" DATE, 
	"MICROROLLNO" VARCHAR2(4 CHAR), 
	"MICROPICNO" VARCHAR2(10 CHAR), 
	"MICROPICNOL" VARCHAR2(4 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"BIRTHPLACE" VARCHAR2(50 CHAR), 
	"DOMICILE" VARCHAR2(50 CHAR), 
	"PPS_SEQNO" NUMBER, 
	"PASS_SEQNO" NUMBER, 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"TYPEDPASSPORT" VARCHAR2(1 CHAR), 
	"PASSPORTSTS" VARCHAR2(1 CHAR), 
	"TMPPASS_SEQNO" NUMBER, 
	"IMGPASS" BLOB
   ) 
  PARTITION BY RANGE ("CREATE_DATE") INTERVAL (NUMTOYMINTERVAL(1,'MONTH')) STORE IN ("DATASTORE_LOB_01", "DATASTORE_LOB_02", "DATASTORE_LOB_03", "DATASTORE_LOB_04", "DATASTORE_LOB_05", "DATASTORE_LOB_06", "DATASTORE_LOB_07", "DATASTORE_LOB_08", "DATASTORE_LOB_09") 
 (PARTITION "PART_01"  VALUES LESS THAN (TIMESTAMP' 1918-02-01 00:00:00') ) ;
  ALTER TABLE "DL_STAGING4PIBICS"."THAIPASSPORT" ADD CONSTRAINT "THAIPASSPORT_PK" PRIMARY KEY ("CITIZENID", "PASSPORTNO")
  USING INDEX  ENABLE;
  CREATE INDEX "DL_STAGING4PIBICS"."THAIPASSPORT_CREATE_IDX1" ON "DL_STAGING4PIBICS"."THAIPASSPORT" ("DL_STAGING4PIBICS"."PKG_UTILS"."GET_YYYYMMDD"("CREATE_DATE")) 
   LOCAL
 (PARTITION "PART_01" ) ;
CREATE INDEX "DL_STAGING4PIBICS"."THAIPASSPORT_I2" ON "DL_STAGING4PIBICS"."THAIPASSPORT" ("UPDATE_YYYYMM") 
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."SYS_IL0000313006C00036$$" ON "DL_STAGING4PIBICS"."THAIPASSPORT" (
   LOCAL
 (PARTITION "SYS_IL_P7325" ) ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."THAIPASSPORT_PK" ON "DL_STAGING4PIBICS"."THAIPASSPORT" ("CITIZENID", "PASSPORTNO") 
  ;
  GRANT DELETE ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."THAIPASSPORT" TO "TESTADM";
