CREATE TABLE "DL_STAGING4PIBICS"."TMINOUT" 
   (	"UPDATE_YYYYMM" NUMBER INVISIBLE GENERATED ALWAYS AS (CAST(TO_CHAR(TRUNC("UPDATE_DATE",'fmmm'),'YYYYMM') AS NUMBER)) VIRTUAL , 
	"SEQNO" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"TM6NO" VARCHAR2(20 CHAR), 
	"INOUTDTE" DATE, 
	"CARDTYPE" VARCHAR2(1 CHAR), 
	"TFIRSTNM" VARCHAR2(60 CHAR), 
	"TMIDDLENM" VARCHAR2(60 CHAR), 
	"TFAMILYNM" VARCHAR2(60 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"SEX" VARCHAR2(1 CHAR), 
	"BIRTHDTE" VARCHAR2(10 CHAR), 
	"NATIONCD" VARCHAR2(3 CHAR), 
	"DEPTCD" VARCHAR2(5 CHAR), 
	"TRAVCD" VARCHAR2(4 CHAR), 
	"CONVCD" VARCHAR2(4 CHAR), 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"TDTCD" VARCHAR2(4 CHAR), 
	"TDTNO" VARCHAR2(20 CHAR), 
	"VISATYPECD" VARCHAR2(4 CHAR), 
	"VISAEXPDTE" DATE, 
	"PASSPORTDTE" DATE, 
	"PASSPORTISU" VARCHAR2(60 CHAR), 
	"PASSPORTEXPDTE" DATE, 
	"TARGETNO" VARCHAR2(7 CHAR), 
	"INTYPE" VARCHAR2(1 CHAR), 
	"CHKPOINTNO" VARCHAR2(3 CHAR), 
	"CREUSR" VARCHAR2(20 CHAR), 
	"CREDTE" DATE, 
	"CREDTERM" VARCHAR2(30 CHAR), 
	"UPDUSR" VARCHAR2(20 CHAR), 
	"UPDDTE" DATE, 
	"UPDTERM" VARCHAR2(30 CHAR), 
	"ISPROCESS" VARCHAR2(1 CHAR), 
	"PERSONID" VARCHAR2(20 CHAR), 
	"TFSNDXNM" VARCHAR2(60 CHAR), 
	"TLSNDXNM" VARCHAR2(60 CHAR), 
	"TMSNDXNM" VARCHAR2(60 CHAR), 
	"EFSNDXNM" VARCHAR2(60 CHAR), 
	"ELSNDXNM" VARCHAR2(60 CHAR), 
	"EMSNDXNM" VARCHAR2(60 CHAR), 
	"REMARK" VARCHAR2(1500 CHAR), 
	"RESCERTNO" VARCHAR2(20 CHAR), 
	"PM_RE_ENTRY" VARCHAR2(20 CHAR), 
	"PM_REEXPDTE" DATE, 
	"PM_EXTENSION" VARCHAR2(20 CHAR), 
	"PM_EXEXPDTE" DATE, 
	"PM_NON_QUOTA" VARCHAR2(20 CHAR), 
	"PM_NONEXPDTE" DATE, 
	"STATUS" VARCHAR2(1 CHAR), 
	"TM5_SEQNO" NUMBER, 
	"TM2INOUT_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER DEFAULT 0, 
	"RPJSEQNO" NUMBER, 
	"PERMITCD" VARCHAR2(4 CHAR), 
	"NEWPERMIT" DATE, 
	"CONV_SEQNO" NUMBER, 
	"VISATYPE_SEQNO" NUMBER, 
	"DEPT_SEQNO" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"PERMIT_SEQNO" NUMBER, 
	"CITIZENID" VARCHAR2(13 CHAR), 
	"PASS_SEQNO" NUMBER, 
	"FLIGHTPREFIX" VARCHAR2(20 CHAR), 
	"FLIGHTNUMBER" VARCHAR2(20 CHAR), 
	"TYPEDATA" VARCHAR2(20 CHAR), 
	"DEPTCDORG" VARCHAR2(5 CHAR), 
	"FLAGJOINPASS" VARCHAR2(1 CHAR), 
	"FLAGFINES" VARCHAR2(1 CHAR), 
	"RESCERTTYPE" VARCHAR2(4 CHAR), 
	"RESPVCD" VARCHAR2(3 CHAR), 
	"RESNOYEAR" VARCHAR2(20 CHAR), 
	"PV_SEQNO" NUMBER, 
	"PD_SEQNO" NUMBER, 
	"ZONE_SEQNO" NUMBER, 
	"SHIFT_SEQNO" NUMBER, 
	"IMGINOUT" BLOB
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS"."TMINOUT" ADD CONSTRAINT "TMINOUT_PK" PRIMARY KEY ("SEQNO")
  USING INDEX  ENABLE;
  CREATE INDEX "DL_STAGING4PIBICS"."TMINOUT_I1" ON "DL_STAGING4PIBICS"."TMINOUT" ("UPDATE_YYYYMM") 
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."SYS_IL0000313014C00081$$" ON "DL_STAGING4PIBICS"."TMINOUT" (
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."TMINOUT_PK" ON "DL_STAGING4PIBICS"."TMINOUT" ("SEQNO") 
  ;
  GRANT DELETE ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."TMINOUT" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."TMINOUT" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."TMINOUT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."TMINOUT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."TMINOUT" TO "TESTADM";
