CREATE TABLE "SERVAPP"."AMAPPSTATUS" 
   (	"APP_ID" VARCHAR2(18) NOT NULL ENABLE, 
	"APP_DESC" VARCHAR2(500), 
	"APP_DESC_EN" VARCHAR2(500), 
	"APP_HEAD_DESC" VARCHAR2(500), 
	"APP_HEAD_DESC_EN" VARCHAR2(500), 
	"APP_STATUS" NUMBER(*,0), 
	"APP_PATH" VARCHAR2(500), 
	"APP_IMG" VARCHAR2(500), 
	"APP_PARENT" VARCHAR2(18), 
	"APP_ORDER" NUMBER(*,0), 
	"LASTCHILD_STATUS" NUMBER(*,0), 
	"MODULE_ID" VARCHAR2(18), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50), 
	"OPENLINK_FLAG" NUMBER
   ) ;
  ALTER TABLE "SERVAPP"."AMAPPSTATUS" ADD PRIMARY KEY ("APP_ID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."XPKAMAPPSTATUS" ON "SERVAPP"."AMAPPSTATUS" ("APP_ID") 
  ;
  GRANT SELECT ON "SERVAPP"."AMAPPSTATUS" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."AMAPPSTATUS" TO "BIOSAADM";
