CREATE TABLE "SERVAPP"."AMSECPERMISSMODULE" 
   (	"MEMBER_TYPE" VARCHAR2(18) NOT NULL ENABLE, 
	"MODULE_ID" VARCHAR2(18) NOT NULL ENABLE, 
	"STATUS" NUMBER(*,0), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."AMSECPERMISSMODULE" ADD PRIMARY KEY ("MEMBER_TYPE", "MODULE_ID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."XPKAMSECPERMISSMODULE" ON "SERVAPP"."AMSECPERMISSMODULE" ("MEMBER_TYPE", "MODULE_ID") 
  ;
