CREATE TABLE "SERVAPP"."ERRORCODEMASTER" 
   (	"ERROR_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(500), 
	"CREATE_DATE" DATE, 
	"CREATE_BY" VARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"UPDATE_BY" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."ERRORCODEMASTER" ADD PRIMARY KEY ("ERROR_CODE")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."XPKERRORCODEMASTER" ON "SERVAPP"."ERRORCODEMASTER" ("ERROR_CODE") 
  ;
