CREATE TABLE "SERVAPP"."LINEITEM" 
   (	"PONO" NUMBER(5,0), 
	"ITEMNUMBER" NUMBER(10,0), 
	"PARTDESCRIPTION" VARCHAR2(50), 
	"PARTUNITPRICE" NUMBER(10,0), 
	"PARTUPCCODE" NUMBER(10,0), 
	"QUANTITY" NUMBER(10,0)
   ) ;
  ALTER TABLE "SERVAPP"."LINEITEM" ADD PRIMARY KEY ("PONO", "ITEMNUMBER")
  USING INDEX  ENABLE;
  ;
