CREATE TABLE "SERVAPP"."MBDEPARTMENT" 
   (	"DEPARTMENT_CODE" VARCHAR2(18) NOT NULL ENABLE, 
	"DEPARTMENT_DESC" VARCHAR2(500), 
	"DEPARTMENT_DESC_EN" VARCHAR2(500), 
	"STATUS" NUMBER(*,0), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."MBDEPARTMENT" ADD PRIMARY KEY ("DEPARTMENT_CODE")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."XPKMBDEPARTMENT" ON "SERVAPP"."MBDEPARTMENT" ("DEPARTMENT_CODE") 
  ;
  GRANT SELECT ON "SERVAPP"."MBDEPARTMENT" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MBDEPARTMENT" TO "BIOSAADM";
