CREATE TABLE "SERVAPP"."MBPOSITION" 
   (	"POSITION_CODE" VARCHAR2(18) NOT NULL ENABLE, 
	"POSITION_DESC" VARCHAR2(500), 
	"POSITION_DESC_EN" VARCHAR2(500), 
	"STATUS" NUMBER(*,0), 
	"CREATE_DATE" DATE, 
	"CREATE_USER" VARCHAR2(50), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."MBPOSITION" ADD PRIMARY KEY ("POSITION_CODE")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."XPKMBPOSITION" ON "SERVAPP"."MBPOSITION" ("POSITION_CODE") 
  ;
  GRANT SELECT ON "SERVAPP"."MBPOSITION" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MBPOSITION" TO "BIOSAADM";
