CREATE TABLE "SERVAPP"."MSCS_EXT_COMMITTEE" 
   (	"COMMITTEE_SEQNO" NUMBER NOT NULL ENABLE, 
	"PROC_SEQNO" NUMBER, 
	"CMEETING_NO" VARCHAR2(20 CHAR), 
	"CMEETING_DATE" DATE, 
	"CREMARK" VARCHAR2(1000 CHAR), 
	"CRESOLVE" CHAR(1 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"CR_DETAIL" VARCHAR2(200 CHAR), 
	"CDATE" DATE
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_EXT_COMMITTEE" ADD CONSTRAINT "EXT_COMMITEE_PK" PRIMARY KEY ("COMMITTEE_SEQNO")
  USING INDEX (CREATE UNIQUE INDEX "SERVAPP"."MSCS_EXT_COMMITEE_PK" ON "SERVAPP"."MSCS_EXT_COMMITTEE" ("COMMITTEE_SEQNO") 
  )  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."MSCS_EXT_COMMITEE_PK" ON "SERVAPP"."MSCS_EXT_COMMITTEE" ("COMMITTEE_SEQNO") 
  ;
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_EXT_COMMITTEE" TO "BIOSAADM";
