CREATE TABLE "SERVAPP"."MSCS_TM2MAIN" 
   (	"TM2MAIN_SEQNO" NUMBER NOT NULL ENABLE, 
	"CONV_SEQNO" NUMBER, 
	"CONVNATIONCD" NUMBER, 
	"CONVREGNO" VARCHAR2(50 CHAR), 
	"TM2_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"CARDTYPE" CHAR(1 CHAR), 
	"DEPT_SEQNO" NUMBER
   ) ;
  GRANT SELECT ON "SERVAPP"."MSCS_TM2MAIN" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_TM2MAIN" TO "BIOSAADM";
