CREATE TABLE "SERVAPP"."MSCS_VOA_VOA15LIST" 
   (	"VOAL_SEQNO" NUMBER NOT NULL ENABLE, 
	"PERSON_SEQNO" NUMBER, 
	"VOA_SEQNO" NUMBER, 
	"CP_SEQNO" NUMBER, 
	"TM6NO" VARCHAR2(20 CHAR), 
	"VISANO" VARCHAR2(50 CHAR), 
	"EFIRSTNM" VARCHAR2(60 CHAR), 
	"EMIDDLENM" VARCHAR2(60 CHAR), 
	"EFAMILYNM" VARCHAR2(60 CHAR), 
	"BIRTH_DATE" DATE, 
	"SEX" CHAR(1 CHAR), 
	"NATION_SEQNO" NUMBER, 
	"STS" CHAR(1 CHAR), 
	"IPADDRESS" VARCHAR2(20 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"PASSPORT_ISSUEDATE" DATE, 
	"PASSPORT_EXPDATE" DATE, 
	"PASSPORT_PLACE" VARCHAR2(60 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"COUNT_SEQNO" NUMBER, 
	"FEES_SEQNO" NUMBER, 
	"OCC_SEQNO" NUMBER, 
	"CHILD_RELATIONSHIP" VARCHAR2(100 CHAR), 
	"SUFFIX_SEQNO" NUMBER, 
	"IMGINOUT" BLOB, 
	"IMGPASS" BLOB, 
	"RPJSEQNO" NUMBER, 
	"TMINOUT_SEQNO" NUMBER, 
	"STATUSVOA" CHAR(1 CHAR), 
	"STATUSVOADTE" DATE, 
	"STATUSONLINE" CHAR(1 CHAR), 
	"CRE_PROGRAMID" VARCHAR2(25 CHAR)
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_VOA_VOA15LIST" ADD CONSTRAINT "VOA_VOA15LIST_PK" PRIMARY KEY ("VOAL_SEQNO")
  USING INDEX  ENABLE;
  ;
  ;
CREATE UNIQUE INDEX "SERVAPP"."VOA_VOA15LIST_PK" ON "SERVAPP"."MSCS_VOA_VOA15LIST" ("VOAL_SEQNO") 
  ;
