CREATE TABLE "SERVAPP"."MSCS_FOREIGNPRO" 
   (	"FOREIGN_SEQNO" NUMBER NOT NULL ENABLE, 
	"DPT_SEQNO" NUMBER, 
	"CONV_SEQNO" NUMBER, 
	"CONVREGNO" VARCHAR2(20 CHAR), 
	"COUNT_SEQNO" NUMBER, 
	"NOTE" VARCHAR2(250 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_FOREIGNPRO" ADD CONSTRAINT "MSCS_FOREIGNPRO_PK" PRIMARY KEY ("FOREIGN_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."MSCS_FOREIGNPRO_PK" ON "SERVAPP"."MSCS_FOREIGNPRO" ("FOREIGN_SEQNO") 
  ;
