CREATE TABLE "SERVAPP"."MSCS_INSDEPT" 
   (	"INSDEPT_SEQNO" NUMBER NOT NULL ENABLE, 
	"TM5_SEQNO" NUMBER, 
	"GUART_SEQNO" NUMBER, 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
