CREATE TABLE "SERVAPP"."MSCS_EXT_PRO_232" 
   (	"PRO_SEQNO" NUMBER NOT NULL ENABLE, 
	"PROC_SEQNO" NUMBER, 
	"DOCDATE" DATE, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"AGENCY" VARCHAR2(50 CHAR), 
	"BOOK" VARCHAR2(1000 CHAR), 
	"SPORT_BOOK" VARCHAR2(2000 CHAR), 
	"COMMAND_FROM" VARCHAR2(150 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"LOCATION" VARCHAR2(1000 CHAR)
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_EXT_PRO_232" ADD CONSTRAINT "MSCS_EXT_PRO_232_PK" PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."MSCS_EXT_PRO_232_PK" ON "SERVAPP"."MSCS_EXT_PRO_232" ("PRO_SEQNO") 
  ;
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_232" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_EXT_PRO_232" TO "BIOSAADM";
