CREATE TABLE "SERVAPP"."MSCS_EXT_PRO_230" 
   (	"PRO_SEQNO" NUMBER NOT NULL ENABLE, 
	"PROC_SEQNO" NUMBER, 
	"LOCATION" VARCHAR2(1000 CHAR), 
	"INCOME_PERSON" NUMBER(15,2), 
	"CONTRACT_DATE" DATE, 
	"CONTRACT" VARCHAR2(300 CHAR), 
	"OTHER" VARCHAR2(2000 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_230" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_EXT_PRO_230" TO "BIOSAADM";
