CREATE TABLE "SERVAPP"."MSCS_INSAIR" 
   (	"INSAIR_SEQNO" NUMBER NOT NULL ENABLE, 
	"TM5_SEQNO" NUMBER, 
	"DEPT_AIR" NUMBER, 
	"FLIGHTNO" VARCHAR2(15 CHAR), 
	"CREATE_BY" VARCHAR2(30 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(30 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"ACTFLAG" CHAR(1 CHAR)
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_INSAIR" ADD CONSTRAINT "INSAIR_PK" PRIMARY KEY ("INSAIR_SEQNO")
  USING INDEX (CREATE UNIQUE INDEX "SERVAPP"."MSCS_INSAIR_PK" ON "SERVAPP"."MSCS_INSAIR" ("INSAIR_SEQNO") 
  )  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."MSCS_INSAIR_PK" ON "SERVAPP"."MSCS_INSAIR" ("INSAIR_SEQNO") 
  ;
  GRANT SELECT ON "SERVAPP"."MSCS_INSAIR" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_INSAIR" TO "BIOSAADM";
