CREATE TABLE "SERVAPP"."MSCS_REPORTPRO" 
   (	"RPT_SEQNO" NUMBER NOT NULL ENABLE, 
	"DPT_SEQNO" NUMBER, 
	"PRODTE" DATE, 
	"PROUSRID" VARCHAR2(60 CHAR), 
	"REASON" VARCHAR2(100 CHAR), 
	"DEPT_SEQNO" NUMBER, 
	"DUEDTE" DATE, 
	"CASE1" CHAR(1), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
