CREATE TABLE "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT 'I' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT user NOT NULL ENABLE, 
	"SENDER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SENDER_OBJECT" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"SENDER_OBJECT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"SENDER_MESSAGE" CLOB, 
	"SENDER_RESPONSE_CODE" VARCHAR2(50 CHAR), 
	"SENDER_RESPONSE_MESSAGE" CLOB, 
	"RECEIVER_RESPONSE_ID" VARCHAR2(100 CHAR), 
	"RECEIVER_RESPONSE" CLOB, 
	"PROCESS_TIME" NUMBER, 
	"REQUEST_URL" VARCHAR2(500 CHAR)
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" ADD CONSTRAINT "LOG_SYNC_WEBSERVICES$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX (CREATE UNIQUE INDEX "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES$PK" ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" ("KEY_VALUE") 
  )  ENABLE;
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."KEY_VALUE" IS 'Primary Key';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."DML_AT" IS 'Audit';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."DML_BY" IS 'Audit';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."DML_TYPE" IS 'Audit (I.nsert, U.pdate, D.elete)';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."INS_AT" IS 'Audit';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."INS_BY" IS 'Audit';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER" IS 'Name of application, schema or identifier who send this message';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER_OBJECT" IS 'Name of Object that should be transfered (e.g. MOVEMENTS)';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER_OBJECT_ID" IS 'PK of Object that should be transfered';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER_MESSAGE" IS 'PK of Object that should be transfered';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER_RESPONSE_CODE" IS 'Response code of step 1 (asynchronous)';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."SENDER_RESPONSE_MESSAGE" IS 'Error message of step 1 (asynchronous)';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."RECEIVER_RESPONSE_ID" IS 'Response ID or message of the database that came from another system';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."RECEIVER_RESPONSE" IS 'JSON Response that came from another system';
   COMMENT ON COLUMN "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES"."PROCESS_TIME" IS 'The time in seconds that the Request took to get a Response.';
  CREATE UNIQUE INDEX "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES$PK" ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "SERVAPP"."SYS_IL0000357577C00010$$" ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" (
  ;
CREATE UNIQUE INDEX "SERVAPP"."SYS_IL0000357577C00012$$" ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" (
  ;
CREATE UNIQUE INDEX "SERVAPP"."SYS_IL0000357577C00014$$" ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" (
  ;
  GRANT SELECT ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_LOG_SYNC_WEBSERVICES" TO "BIOSAADM";
