CREATE TABLE "SERVAPP"."MSCS_EXT_PRO_225" 
   (	"PRO_SEQNO" NUMBER, 
	"PROC_SEQNO" NUMBER, 
	"REF_REASON" VARCHAR2(300 CHAR), 
	"SICKNESS" VARCHAR2(100 CHAR), 
	"CER_FROM" VARCHAR2(200 CHAR), 
	"OTH" VARCHAR2(1500 CHAR), 
	"FACT1" CHAR(1 CHAR), 
	"FACT2" CHAR(1 CHAR), 
	"FACT3" CHAR(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "SERVAPP"."MSCS_EXT_PRO_225" ADD PRIMARY KEY ("PRO_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."SYS_C0022505" ON "SERVAPP"."MSCS_EXT_PRO_225" ("PRO_SEQNO") 
  ;
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_225" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."MSCS_EXT_PRO_225" TO "BIOSAADM";
