CREATE TABLE "SERVAPP"."PURCHASEORDER" 
   (	"PONO" NUMBER(5,0), 
	"REQUESTOR" VARCHAR2(50), 
	"COSTCENTER" VARCHAR2(5), 
	"ADDRESSSTREET" VARCHAR2(50), 
	"ADDRESSCITY" VARCHAR2(50), 
	"ADDRESSSTATE" VARCHAR2(2), 
	"ADDRESSZIP" VARCHAR2(10), 
	"ADDRESSCOUNTRY" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."PURCHASEORDER" ADD PRIMARY KEY ("PONO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SERVAPP"."SYS_C0018547" ON "SERVAPP"."PURCHASEORDER" ("PONO") 
  ;
  GRANT SELECT ON "SERVAPP"."PURCHASEORDER" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."PURCHASEORDER" TO "BIOSAADM";
