CREATE TABLE "SERVAPP"."PURCHASEORDER" 
   (	"PONO" NUMBER(5,0), 
	"REQUESTOR" VARCHAR2(50), 
	"COSTCENTER" VARCHAR2(5), 
	"ADDRESSSTREET" VARCHAR2(50), 
	"ADDRESSCITY" VARCHAR2(50), 
	"ADDRESSSTATE" VARCHAR2(2), 
	"ADDRESSZIP" VARCHAR2(10), 
	"ADDRESSCOUNTRY" VARCHAR2(50)
   ) ;
  ALTER TABLE "SERVAPP"."PURCHASEORDER" ADD PRIMARY KEY ("PONO")
  USING INDEX  ENABLE;
  ;
