CREATE TABLE "SERVAPP"."REASON_CODES" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR), 
	"LOCALE" VARCHAR2(5 CHAR) DEFAULT ON NULL 'en_US' NOT NULL ENABLE, 
	"DISPLAY_VALUE" VARCHAR2(128 CHAR), 
	"DISPLAY_ORDER" NUMBER(*,0), 
	"IS_ACTIVE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'Y' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"NOTICE" VARCHAR2(4000 CHAR), 
	"NUM_VALUE" NUMBER(32,0), 
	"ROW_FLAG_MASK" NUMBER(6,0) DEFAULT 0, 
	"OWNER" VARCHAR2(128 CHAR)
   ) ;
  CREATE INDEX "SERVAPP"."REASON_CODES$IX00" ON "SERVAPP"."REASON_CODES" ("DISPLAY_VALUE", "DISPLAY_ORDER") 
  ;
CREATE INDEX "SERVAPP"."REASON_CODES$IX01" ON "SERVAPP"."REASON_CODES" ("OWNER") 
  ;
CREATE UNIQUE INDEX "SERVAPP"."REASON_CODES$PK" ON "SERVAPP"."REASON_CODES" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "SERVAPP"."REASON_CODES$UQ00" ON "SERVAPP"."REASON_CODES" ("NUM_VALUE") 
  ;
