CREATE TABLE "SERVAPP"."VISAS" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"VISA_TYPE" VARCHAR2(32 CHAR), 
	"VISA_NUMBER" VARCHAR2(32 CHAR), 
	"ISSUING_DATE" DATE, 
	"ISSUING_PLACE" VARCHAR2(255 CHAR), 
	"ADDITIONAL_INFO" VARCHAR2(255 CHAR), 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"INS_TERMINAL" VARCHAR2(32 CHAR), 
	"INS_BORDERPOST" VARCHAR2(32 CHAR), 
	"BORDERDOCUMENT" VARCHAR2(32 CHAR), 
	"VISA_IMAGE" BLOB, 
	"EXPIRY_DATE" DATE, 
	"PERSON" VARCHAR2(32 CHAR), 
	"APPLICANT_DATE" DATE, 
	"FROM_COUNTRY" VARCHAR2(32 CHAR), 
	"TRANS_VEHICLE" VARCHAR2(32 CHAR), 
	"TRANS_NUMBER" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(32 CHAR) DEFAULT ON NULL 'APPROVED' NOT NULL ENABLE, 
	"RELEASE_NOTE" VARCHAR2(2500 CHAR), 
	"CANCEL_NOTE" VARCHAR2(2500 CHAR), 
	"PAYMENT_STATUS" VARCHAR2(32 CHAR) DEFAULT ON NULL 'DONT_PAY' NOT NULL ENABLE, 
	"RECEIPT" VARCHAR2(32 CHAR), 
	"PERMIT_TYPE" VARCHAR2(255 CHAR), 
	"PERMIT_EXPIRY_DATE" DATE, 
	"INS_OFFICER" VARCHAR2(255 CHAR), 
	"STATUS_FEE_EXCEPTION" VARCHAR2(255 CHAR) DEFAULT ON NULL 'N' NOT NULL ENABLE, 
	"STATUS_NO_RECEIPT" VARCHAR2(255 CHAR) DEFAULT ON NULL 'N' NOT NULL ENABLE, 
	"STATUS_PRINT_FORM" VARCHAR2(255 CHAR) DEFAULT ON NULL 'N' NOT NULL ENABLE, 
	"BLACKLIST_RECORD" VARCHAR2(32 CHAR)
   ) ;
  CREATE UNIQUE INDEX "SERVAPP"."SYS_IL0000377655C00015$$" ON "SERVAPP"."VISAS" (
  ;
  GRANT SELECT ON "SERVAPP"."VISAS" TO "PIBICSAPP";
  GRANT ALTER ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT DELETE ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT INDEX ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT INSERT ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT SELECT ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT UPDATE ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT REFERENCES ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT READ ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT DEBUG ON "SERVAPP"."VISAS" TO "BIOSAADM";
  GRANT FLASHBACK ON "SERVAPP"."VISAS" TO "BIOSAADM";
