CREATE TABLE "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" 
   (	"MSGID" RAW(16), 
	"SUBSCRIBER#" NUMBER, 
	"NAME" VARCHAR2(512 CHAR), 
	"ADDRESS#" NUMBER, 
	"DEQUEUE_TIME" TIMESTAMP (6) WITH TIME ZONE, 
	"TRANSACTION_ID" VARCHAR2(30 CHAR), 
	"DEQUEUE_USER" VARCHAR2(128 CHAR), 
	"FLAGS" RAW(1)
   ) USAGE QUEUE ;
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_L" TO "APPSUP";
