CREATE TABLE "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" 
   (	"SUBSCRIBER#" NUMBER, 
	"NAME" VARCHAR2(512 CHAR), 
	"QUEUE#" NUMBER, 
	"MSG_ENQ_TIME" TIMESTAMP (6), 
	"MSG_STEP_NO" NUMBER, 
	"MSG_CHAIN_NO" NUMBER, 
	"MSG_LOCAL_ORDER_NO" NUMBER, 
	"MSGID" RAW(16), 
	"HINT" ROWID, 
	"SPARE" RAW(16), 
	 PRIMARY KEY ("SUBSCRIBER#", "NAME", "QUEUE#", "MSG_ENQ_TIME", "MSG_STEP_NO", "MSG_CHAIN_NO", "MSG_LOCAL_ORDER_NO", "MSGID") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IOT_TOP_311850" ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" ("SUBSCRIBER#", "NAME", "QUEUE#", "MSG_ENQ_TIME", "MSG_STEP_NO", "MSG_CHAIN_NO", "MSG_LOCAL_ORDER_NO", "MSGID") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB_I" TO "APPSUP";
