CREATE TABLE "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" 
   (	"MSGID" RAW(16), 
	"SUBSCRIBER#" NUMBER, 
	"NAME" VARCHAR2(512), 
	"ADDRESS#" NUMBER, 
	"DEQUEUE_TIME" TIMESTAMP (6), 
	"TRANSACTION_ID" VARCHAR2(30), 
	"DEQUEUE_USER" VARCHAR2(128), 
	"PROPAGATED_MSGID" RAW(16), 
	"RETRY_COUNT" NUMBER, 
	"HINT" ROWID, 
	"SPARE" RAW(16), 
	 PRIMARY KEY ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IOT_TOP_698350" ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_H" TO "PORNRUKSA_S";
