CREATE TABLE "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" 
   (	"NEXT_DATE" TIMESTAMP (6), 
	"TXN_ID" VARCHAR2(30), 
	"MSGID" RAW(16), 
	"ACTION" NUMBER, 
	 PRIMARY KEY ("NEXT_DATE", "TXN_ID", "MSGID") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IOT_TOP_698348" ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" ("NEXT_DATE", "TXN_ID", "MSGID") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."AQ$_AQ_EVOA_HOOKS_TAB_T" TO "PORNRUKSA_S";
