CREATE TABLE "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB2_H" 
   (	"MSGID" RAW(16), 
	"SUBSCRIBER#" NUMBER, 
	"NAME" VARCHAR2(512), 
	"ADDRESS#" NUMBER, 
	"DEQUEUE_TIME" TIMESTAMP (6), 
	"TRANSACTION_ID" VARCHAR2(30), 
	"DEQUEUE_USER" VARCHAR2(128), 
	"PROPAGATED_MSGID" RAW(16), 
	"RETRY_COUNT" NUMBER, 
	"HINT" ROWID, 
	"SPARE" RAW(16), 
	 PRIMARY KEY ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") ENABLE
   ) USAGE QUEUE ORGANIZATION INDEX NOCOMPRESS ;
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IOT_TOP_639272" ON "DL_BORDERCONTROL"."AQ$_AQ_BORDERCONTROL_HOOKS_TAB2_H" ("MSGID", "SUBSCRIBER#", "NAME", "ADDRESS#") 
  ;
