CREATE TABLE "DL_BORDERCONTROL"."BORDERPOSTS" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT SYS_GUID(), 
	"BORDER_TYPE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"IS_ACTIVE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'Y' NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"BORDER_TO_COUNTRY" VARCHAR2(32 CHAR), 
	"LOCALE" VARCHAR2(5 CHAR) DEFAULT ON NULL 'en_US' NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER(*,0), 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"PROVINCEID" VARCHAR2(32 CHAR), 
	"CODE" VARCHAR2(20 CHAR)
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$CHK$C00" CHECK (upper(KEY_VALUE) = KEY_VALUE) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$CHK$C03" CHECK (IS_ACTIVE in ('Y'
                                                                                               ,'N')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$CHK$C06" CHECK (DML_TYPE in ('I'
                                                                                              ,'U')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$CHK$C08" CHECK (LOCALE = 'en_US') ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "DISPLAY_OBJECTS$CHK$C00" CHECK (DML_TYPE in ('I', 'U')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$FK00" FOREIGN KEY ("BORDER_TYPE")
	  REFERENCES "DL_COMMON"."BORDER_TYPES" ("KEY_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$FK01" FOREIGN KEY ("BORDER_TO_COUNTRY")
	  REFERENCES "DL_COMMON"."COUNTRIES" ("KEY_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."BORDERPOSTS" ADD CONSTRAINT "BORDERPOSTS$FK02" FOREIGN KEY ("LOCALE")
	  REFERENCES "DL_COMMON"."LOCALES" ("KEY_VALUE") ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."KEY_VALUE" IS 'Unique Identifier';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."BORDER_TYPE" IS 'Column for Border Type (Land, Air, Sea)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."NAME" IS 'Name of Borderpost';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."IS_ACTIVE" IS 'Value is active and will be shown in frontend (Y.es, N.o)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."DML_AT" IS 'Date of last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."DML_BY" IS 'User who did the last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."DML_TYPE" IS 'DML Type: I = Insert, U = Update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."BORDER_TO_COUNTRY" IS 'Country Code of Border to Contry';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."LOCALE" IS 'Language definition of display_value column';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."DISPLAY_ORDER" IS 'Numeric value that provides the correct sorting';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."INS_AT" IS 'Date of Insert';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."INS_BY" IS 'User who insert the data';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."BORDERPOSTS"."PROVINCEID" IS 'Province of Bordepost';
   COMMENT ON TABLE "DL_BORDERCONTROL"."BORDERPOSTS"  IS 'Is used for BmBS';
  CREATE INDEX "DL_BORDERCONTROL"."BORDERPOSTS$IX00" ON "DL_BORDERCONTROL"."BORDERPOSTS" ("BORDER_TYPE") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."BORDERPOSTS$IX01" ON "DL_BORDERCONTROL"."BORDERPOSTS" ("BORDER_TO_COUNTRY") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."BORDERPOSTS$IX02" ON "DL_BORDERCONTROL"."BORDERPOSTS" ("LOCALE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."BORDERPOSTS$PK" ON "DL_BORDERCONTROL"."BORDERPOSTS" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."BORDERPOSTS$UX00" ON "DL_BORDERCONTROL"."BORDERPOSTS" (UPPER("NAME")) 
  ;
  GRANT DELETE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT INSERT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT UPDATE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DL_BORDERCONTROL_DATAMART";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "APPSUP";
  GRANT INSERT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PIBICSDM2";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOAPPREPORT";
  GRANT INSERT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOAPPREPORT";
  GRANT UPDATE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PORNRUKSA_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "SANTIPATN_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."BORDERPOSTS" TO "PUNYAWII_D";
