CREATE TABLE "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"INS_AT" DATE NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"NOTICE" VARCHAR2(4000 CHAR), 
	"ROW_FLAG_MASK" NUMBER(6,0) NOT NULL ENABLE, 
	"POSITION" NUMBER(3,0) NOT NULL ENABLE, 
	"PAYMENT_RATE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"FEES_AND_FINES" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"COSTS" NUMBER NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" ADD CONSTRAINT "FAF_FEES_AND_FINES_DETAILS$HIS$CK00" CHECK (DML_TYPE in ('I','U','D')) ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."KEY_VALUE" IS 'Primary Key';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."INS_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."INS_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."DML_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."DML_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."DML_TYPE" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."NOTICE" IS 'Column for Notes';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."ROW_FLAG_MASK" IS 'Bitmask: 1 => delivered by Dermalog, 2 => reserved, 4 => reserved, 8 .. 524288 => reserved !';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."POSITION" IS 'Number of the position (defines the order of the different positions for a fees and fines)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."PAYMENT_RATE" IS 'FK dl_bordercontrol.faf_payment_rate (defines the type of the position / detail entry)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."FEES_AND_FINES" IS 'FK dl_bordercontrol.faf_fees_and_fines (connects the detail position to a receipt)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS"."COSTS" IS 'Cost of the detail position';
  CREATE INDEX "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS$IX00" ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" ("KEY_VALUE", "DML_AT") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."FAF_FEES_AND_FINES_DETAILS$HIS" TO "BIOSAADM";
