CREATE TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"LOCALE" VARCHAR2(5 CHAR) DEFAULT ON NULL 'en_US' NOT NULL ENABLE, 
	"DISPLAY_VALUE" VARCHAR2(128 CHAR) NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER(*,0), 
	"DISPLAY_CODE" VARCHAR2(4 CHAR), 
	"IS_ACTIVE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'Y' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"NOTICE" VARCHAR2(4000 CHAR), 
	"NUM_VALUE" NUMBER(32,0), 
	"ROW_FLAG_MASK" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$UQ00" UNIQUE ("NUM_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$CK00" CHECK (KEY_VALUE = upper(KEY_VALUE) and length(KEY_VALUE) >= 3) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$CK01" CHECK (LOCALE = 'en_US') ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$CK02" CHECK (IS_ACTIVE in ('Y','N')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ADD CONSTRAINT "FAF_PERMIT_TYPE$CK03" CHECK (DML_TYPE in ('I','U')) ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."KEY_VALUE" IS 'Primary Key';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."LOCALE" IS 'Language definition of display_value column';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DISPLAY_VALUE" IS 'Name of the permission type (Fee and Fine)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DISPLAY_ORDER" IS 'Numeric value that provides the correct sorting';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DISPLAY_CODE" IS 'Four characters to describe the Permission entries; will be used by the customer';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."IS_ACTIVE" IS 'Value is active and will be shown in frontend (Y.es, N.o)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."INS_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."INS_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DML_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DML_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."DML_TYPE" IS 'Audit (I.nsert, U.pdate)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."NOTICE" IS 'Column for Notes';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."NUM_VALUE" IS 'Numeric version of primary key';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"."ROW_FLAG_MASK" IS 'Bitmask: 1 => delivered by Dermalog, 2 => reserved, 4 => reserved, 8 .. 524288 => reserved !';
   COMMENT ON TABLE "DL_BORDERCONTROL"."FAF_PERMIT_TYPE"  IS 'Table for Permit Types (Fee and Fine)';
  CREATE INDEX "DL_BORDERCONTROL"."FAF_PERMIT_TYPE$IX00" ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ("DISPLAY_VALUE", "DISPLAY_ORDER") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."FAF_PERMIT_TYPE$PK" ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."FAF_PERMIT_TYPE$UQ00" ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" ("NUM_VALUE") 
  ;
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."FAF_PERMIT_TYPE" TO "PORNRUKSA_S";
