CREATE TABLE "DL_BORDERCONTROL"."FLIGHTS" 
   (	"FLGHTID" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"FLIGHTNUM" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ORIGINAIRPORTID" NUMBER(10,0), 
	"DESTINAIRPORTID" NUMBER(10,0), 
	"TIMEDEPARTURE" DATE, 
	"TIMEARRIVAL" DATE, 
	"ACTIVE" NUMBER(1,0) DEFAULT ON NULL 1 NOT NULL ENABLE, 
	"DIRECTIONFLG" NUMBER(1,0), 
	"PAIREDFLGHTID" VARCHAR2(32 CHAR), 
	"AGENTID" NUMBER(4,0), 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"INS_TERMINAL" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"INS_BORDERPOST" VARCHAR2(32 CHAR) NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_PK" PRIMARY KEY ("FLGHTID")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS_UK1" UNIQUE ("FLIGHTNUM", "DIRECTIONFLG") DISABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS$CHK00" CHECK (DML_TYPE in ('I'
                                                                                    ,'U')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS$FK00" FOREIGN KEY ("ORIGINAIRPORTID")
	  REFERENCES "DL_COMMON"."PORTS" ("NUM_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS$FK01" FOREIGN KEY ("DESTINAIRPORTID")
	  REFERENCES "DL_COMMON"."PORTS" ("NUM_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS$FK02" FOREIGN KEY ("PAIREDFLGHTID")
	  REFERENCES "DL_BORDERCONTROL"."FLIGHTS" ("FLGHTID") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."FLIGHTS" ADD CONSTRAINT "FLIGHTS$FK03" FOREIGN KEY ("AGENTID")
	  REFERENCES "DL_COMMON"."CARRIERS" ("NUM_VALUE") ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."FLGHTID" IS 'Unique Identifier';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."FLIGHTNUM" IS 'Column for Flight Number';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."ORIGINAIRPORTID" IS 'Column for original airport';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."DESTINAIRPORTID" IS 'Column for destination airport';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."TIMEDEPARTURE" IS 'Column for departure time';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."TIMEARRIVAL" IS 'Column for arrival time';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."ACTIVE" IS 'Value is active and will be shown in frontend (Y.es, N.o)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."DIRECTIONFLG" IS 'Direction Flag (arrival or departure)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."PAIREDFLGHTID" IS 'Column for PAIRED FLGHT ID';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."AGENTID" IS 'Column for AGENT ID';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."INS_AT" IS 'Date of Insert';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."INS_BY" IS 'User who insert the data';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."DML_AT" IS 'Date of last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."DML_BY" IS 'User who did the last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."DML_TYPE" IS 'DML Type: I = Insert, U = Update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."INS_TERMINAL" IS 'Terminal, where data was inserted (Foreign Key)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."FLIGHTS"."INS_BORDERPOST" IS 'Borderpost, where data was inserted (Foreign Key)';
   COMMENT ON TABLE "DL_BORDERCONTROL"."FLIGHTS"  IS 'Used in BmBS';
  CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX00" ON "DL_BORDERCONTROL"."FLIGHTS" ("ORIGINAIRPORTID") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX01" ON "DL_BORDERCONTROL"."FLIGHTS" ("DESTINAIRPORTID") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX02" ON "DL_BORDERCONTROL"."FLIGHTS" ("PAIREDFLGHTID") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX03" ON "DL_BORDERCONTROL"."FLIGHTS" ("AGENTID") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX04" ON "DL_BORDERCONTROL"."FLIGHTS" ("INS_BORDERPOST") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS$IX05" ON "DL_BORDERCONTROL"."FLIGHTS" ("INS_TERMINAL") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."FLIGHTS_IDX1" ON "DL_BORDERCONTROL"."FLIGHTS" ("FLIGHTNUM", "DIRECTIONFLG") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."FLIGHTS_PK" ON "DL_BORDERCONTROL"."FLIGHTS" ("FLGHTID") 
  ;
  GRANT INSERT ON "DL_BORDERCONTROL"."FLIGHTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."FLIGHTS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FLIGHTS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "APPSUP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOAPPREPORT";
  GRANT INSERT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOAPPREPORT";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOAPPREPORT";
  GRANT DELETE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSUPPORT";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."FLIGHTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."FLIGHTS" TO "PORNRUKSA_S";
