CREATE TABLE "DL_BORDERCONTROL"."IDENTITIES_BK" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"IDENTITY" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"BRDDOCID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"INS_AT" DATE NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE
   ) ;
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."IDENTITIES_BK" TO "PORNRUKSA_S";
