CREATE TABLE "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"SENDER_SYSTEM" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SENDER_USER" VARCHAR2(255 CHAR), 
	"SENDER_OBJECT" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"SENDER_OBJECT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"REQUEST_TYPE" VARCHAR2(50 CHAR) DEFAULT ON NULL 'SEARCH' NOT NULL ENABLE, 
	"REQUEST" CLOB, 
	"RESPONSE" CLOB, 
	"RESPONSE_CODE" VARCHAR2(50 CHAR), 
	"ELAPSED_TIME_SECONDS" NUMBER DEFAULT ON NULL 0 NOT NULL ENABLE, 
	"NUMBER_OF_HITS" NUMBER, 
	"INS_AT" DATE DEFAULT ON NULL SYSDATE NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL SYSTIMESTAMP NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" ADD CONSTRAINT "LOG_WARRANT_SEARCH$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."KEY_VALUE" IS 'Primary Key';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."SENDER_SYSTEM" IS 'System what sent the request (e.g. BMBS)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."SENDER_USER" IS 'Username of the user who sent the request';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."SENDER_OBJECT_ID" IS 'ID of the object that raising the request';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."REQUEST_TYPE" IS 'Type of request';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."REQUEST" IS 'JSON code of the request that was send';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."RESPONSE" IS 'Response of the service';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."RESPONSE_CODE" IS 'Response code';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."ELAPSED_TIME_SECONDS" IS 'Elapsed time in seconds it took to send a resoonse';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."NUMBER_OF_HITS" IS 'Number of hits the response got';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."INS_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."INS_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."DML_AT" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."DML_BY" IS 'Audit';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH"."DML_TYPE" IS 'Audit (I.nsert, U.pdate, D.elete)';
  CREATE INDEX "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH$IX00" ON "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" ("SENDER_OBJECT_ID") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH$PK" ON "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IL0000691416C00007$$" ON "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" (
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IL0000691416C00008$$" ON "DL_BORDERCONTROL"."LOG_WARRANT_SEARCH" (
  ;
