CREATE TABLE "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" 
   (	"MVMNTID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT 0 NOT NULL ENABLE, 
	"PERMIT_DATE" DATE, 
	"EXTLIST_SEQNO" NUMBER, 
	"TM8_SEQNO" NUMBER, 
	"DOCTYPE" CHAR(1), 
	"RQSPERSON_SEQNO" NUMBER, 
	"RCNO_PVCD" VARCHAR2(3), 
	"RCNO_RUNNINGNO" NUMBER, 
	"RCNO_YEAR" CHAR(4), 
	"RESCERTTYPE_SEQNO" NUMBER, 
	"TFIRSTNM" VARCHAR2(60), 
	"TFAMILYNM" VARCHAR2(60), 
	"TMIDDLENM" VARCHAR2(60), 
	"SEX" CHAR(1), 
	"BIRTH_DATE" VARCHAR2(10), 
	"NATION_SEQNO" NUMBER, 
	"CONTROLBOOK_NO" VARCHAR2(10), 
	"TM13NO" NUMBER, 
	"TM13YEAR" CHAR(4), 
	"RCISSUE_BY" VARCHAR2(60)
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" ADD CONSTRAINT "MSCS_MOVEMENTS_PERMIT_PK" PRIMARY KEY ("MVMNTID")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT"."MVMNTID" IS 'MOVEMENTS.MVMNTID';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT"."KEY_VALUE" IS 'PERMIT_TYPE.KEY_VALUE';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT"."EXTLIST_SEQNO" IS 'SeqNo. Extend Stay';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT"."TM8_SEQNO" IS 'SeqNo. ReEntry';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT"."RQSPERSON_SEQNO" IS 'SeqNo. Request Residence';
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT_PK" ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" ("MVMNTID") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."MSCS_MOVEMENTS_PERMIT" TO "BIOSAADM";
