CREATE TABLE "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" 
   (	"DATES" DATE, 
	"DAY_MOVEMENTS" NUMBER, 
	"TOTAL_MOVEMENTS" NUMBER, 
	"DAY_ABIS" NUMBER, 
	"TOTAL_ABIS" NUMBER, 
	"DAY_BORDERDOCUMENTS" NUMBER, 
	"TOTAL_BORDERDOCUMENTS" NUMBER, 
	"REMAINING_FACE" NUMBER
   ) ;
   COMMENT ON MATERIALIZED VIEW "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS"  IS 'snapshot table for snapshot DL_BORDERCONTROL.MV_TRANSACTION_DATA_ANALYSIS';
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."MV_TRANSACTION_DATA_ANALYSIS" TO "PORNRUKSA_S";
