CREATE TABLE "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"PAYLOAD" CLOB, 
	"ERROR_MESSAGE" CLOB, 
	"URL" VARCHAR2(255 CHAR), 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR" ADD CONSTRAINT "OFFLINE_SYNC_ERROR$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."KEY_VALUE" IS 'Key value default on sys_guid()';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."PAYLOAD" IS 'Payload that has been send';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."ERROR_MESSAGE" IS 'Error message that came back';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."URL" IS 'URL that the error occured on';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."INS_AT" IS 'Inserted date';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."INS_BY" IS 'Inserted user';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."DML_AT" IS 'Modified date';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"."DML_BY" IS 'Modified user';
   COMMENT ON TABLE "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR"  IS 'Table to store sync errors that occured';
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR$PK" ON "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR" ("KEY_VALUE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IL0000539720C00002$$" ON "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR" (
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."SYS_IL0000539720C00003$$" ON "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR" (
  ;
  CREATE OR REPLACE EDITIONABLE TRIGGER "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR$TIUD0" 
	before update on DL_BORDERCONTROL.OFFLINE_SYNC_ERROR for each row
--
/*******************************************************************************
* Author    Date        Description                                            *
* --------  ----------  -------------------------------------------------------
* MStahl    24.04.2019  Added
*******************************************************************************/
--
begin
	:new.dml_at := systimestamp;
	:new.dml_by := dl_common.pkg_session.get_audit_user();
end;
/
ALTER TRIGGER "DL_BORDERCONTROL"."OFFLINE_SYNC_ERROR$TIUD0" ENABLE;
