CREATE TABLE "DL_BORDERCONTROL"."T_LOGGER_GROWTH" 
   (	"OWNER" VARCHAR2(128), 
	"SIZE_GB" NUMBER, 
	"CHK_DATE" DATE
   ) ;
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."T_LOGGER_GROWTH" TO "PORNRUKSA_S";
