CREATE TABLE "DL_BORDERCONTROL"."TERMINALS" 
   (	"ID" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"IPADDRESS" VARCHAR2(15 CHAR), 
	"DEFAULTEXITFLG" NUMBER(1,0) NOT NULL ENABLE, 
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"TRNSPRTMODEID" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"ISGATE" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"POS_X" NUMBER DEFAULT 1, 
	"POS_Y" NUMBER DEFAULT 1, 
	"WIDTH" NUMBER DEFAULT 1, 
	"HEIGHT" NUMBER DEFAULT 1, 
	"FLOOR_ID" NUMBER, 
	"BIO_CAPTURING" NUMBER DEFAULT ON NULL 1 NOT NULL ENABLE, 
	"NAME" VARCHAR2(128 CHAR) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"BORDER_POST" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"LOCALE" VARCHAR2(5 CHAR) DEFAULT ON NULL 'en_US' NOT NULL ENABLE, 
	"INS_AT" DATE DEFAULT ON NULL sysdate NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE, 
	"INS_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DEFAULT_TRAVELER_TYPE" NUMBER(32,0), 
	"DEFAULT_CAMERA_DIRECTION" CHAR(1 CHAR), 
	"IS_EVOA" NUMBER DEFAULT ON NULL 0 NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS_UK1" UNIQUE ("IPADDRESS")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$CHK$C14" CHECK (LOCALE = 'en_US') ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$CHK00" CHECK (DML_TYPE in ('I'
                                                                                        ,'U')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$CHK01" CHECK (DEFAULT_CAMERA_DIRECTION is null or DEFAULT_CAMERA_DIRECTION in ('L', 'R')) ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$FK00" FOREIGN KEY ("TRNSPRTMODEID")
	  REFERENCES "DL_COMMON"."TRANS_MODES" ("NUM_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$FK01" FOREIGN KEY ("DEFAULTEXITFLG")
	  REFERENCES "DL_COMMON"."PORT_MOVEMENTS" ("NUM_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$FK03" FOREIGN KEY ("LOCALE")
	  REFERENCES "DL_COMMON"."LOCALES" ("KEY_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$FK04" FOREIGN KEY ("DEFAULT_TRAVELER_TYPE")
	  REFERENCES "DL_COMMON"."BC_PERSON_TYPES" ("NUM_VALUE") ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."TERMINALS" ADD CONSTRAINT "TERMINALS$FK02" FOREIGN KEY ("BORDER_POST")
	  REFERENCES "DL_BORDERCONTROL"."BORDERPOSTS" ("KEY_VALUE") ON DELETE CASCADE ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."ID" IS 'Unique Identifier';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."IPADDRESS" IS 'Column for IP Address';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DEFAULTEXITFLG" IS 'Default Text Flag';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."ACTIVE" IS 'Value is active and will be shown in frontend (Y.es, N.o)';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."TRNSPRTMODEID" IS 'Default Value for Transportmode ID';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."ISGATE" IS 'Flag for is gate?';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."POS_X" IS 'Column for position X';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."POS_Y" IS 'Column for position Y';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."WIDTH" IS 'Column for width';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."HEIGHT" IS 'Column height';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."FLOOR_ID" IS 'Column for floor id';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."BIO_CAPTURING" IS 'Column for Bio Capturing';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."NAME" IS 'Name of Terminal';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."BORDER_POST" IS 'Foreign Key to Table DL_BORDERCONTROL.BORDERPOSTS';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."LOCALE" IS 'Language definition of display_value column';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."INS_AT" IS 'Date of Insert';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DML_AT" IS 'Date of last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DML_BY" IS 'User who did the last update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DML_TYPE" IS 'DML Type: I = Insert, U = Update';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."INS_BY" IS 'User who insert the data';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DEFAULT_TRAVELER_TYPE" IS 'The default value  for person type for this terminal';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."TERMINALS"."DEFAULT_CAMERA_DIRECTION" IS 'The default direction for the camera to look at. May be (null), ''L'', ''R''';
   COMMENT ON TABLE "DL_BORDERCONTROL"."TERMINALS"  IS 'Used in BmBS';
  CREATE INDEX "DL_BORDERCONTROL"."TERMINALS$IX00" ON "DL_BORDERCONTROL"."TERMINALS" ("TRNSPRTMODEID") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."TERMINALS$IX01" ON "DL_BORDERCONTROL"."TERMINALS" ("DEFAULTEXITFLG") 
  ;
CREATE INDEX "DL_BORDERCONTROL"."TERMINALS$IX03" ON "DL_BORDERCONTROL"."TERMINALS" ("LOCALE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."TERMINALS$UX00" ON "DL_BORDERCONTROL"."TERMINALS" ("BORDER_POST", UPPER("NAME")) 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."TERMINALS_PK" ON "DL_BORDERCONTROL"."TERMINALS" ("ID") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."TERMINALS_UK1" ON "DL_BORDERCONTROL"."TERMINALS" ("IPADDRESS") 
  ;
  GRANT DELETE ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_STAGING4PIBICS_INTF";
  GRANT INSERT ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_STAGING4PIBICS_INTF";
  GRANT UPDATE ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "DL_BORDERCONTROL_DATAMART";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."TERMINALS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."TERMINALS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."TERMINALS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."TERMINALS" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."TERMINALS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PIBICSDM2";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."TERMINALS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PORNRUKSA_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "SANTIPATN_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."TERMINALS" TO "PUNYAWII_D";
