CREATE TABLE "DL_BORDERCONTROL"."X_VISARUN_RULES" 
   (	"VISARUNID" VARCHAR2(32 CHAR) DEFAULT sys_guid() NOT NULL ENABLE, 
	"VISA_KEYVALUE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"MAX_USE_PER_YEAR" NUMBER, 
	"MAX_DAYS_EACH" NUMBER, 
	"INCLUDE_EXTSTAY_EACH" NUMBER, 
	"MAX_DAYS_TOTAL" NUMBER, 
	"INCLUDE_EXTSTAY_TOTAL" NUMBER
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."X_VISARUN_RULES" ADD CONSTRAINT "X_VISARUN_RULES_PK" PRIMARY KEY ("VISARUNID")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."VISARUNID" IS 'Unique Identifier';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."VISA_KEYVALUE" IS 'Column Visa Key Value';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."MAX_USE_PER_YEAR" IS 'Max Number to use per year';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."MAX_DAYS_EACH" IS 'Max Number of Days';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."INCLUDE_EXTSTAY_EACH" IS 'Include Extendstay Each';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."MAX_DAYS_TOTAL" IS 'Max Number of Days total';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."X_VISARUN_RULES"."INCLUDE_EXTSTAY_TOTAL" IS 'Include Extendstay total';
   COMMENT ON TABLE "DL_BORDERCONTROL"."X_VISARUN_RULES"  IS 'Used in BmBS';
  CREATE INDEX "DL_BORDERCONTROL"."X_VISARUN_RULES$IX00" ON "DL_BORDERCONTROL"."X_VISARUN_RULES" ("VISA_KEYVALUE") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."X_VISARUN_RULES_PK" ON "DL_BORDERCONTROL"."X_VISARUN_RULES" ("VISARUNID") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."X_VISARUN_RULES" TO "PORNRUKSA_S";
