CREATE TABLE "DL_BORDERCONTROL"."XLIB_COMPONENTS" 
   (	"COMP_ID" NUMBER NOT NULL ENABLE, 
	"COMP_NAME" VARCHAR2(100 CHAR), 
	"COMP_VERSION" VARCHAR2(50 CHAR), 
	"COMP_VERSION_LABEL" VARCHAR2(50 CHAR), 
	"COMP_DEPENDS_ON" VARCHAR2(4000 CHAR)
   ) ;
  ALTER TABLE "DL_BORDERCONTROL"."XLIB_COMPONENTS" ADD CONSTRAINT "XLIB_COMPONENTS_PK" PRIMARY KEY ("COMP_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_BORDERCONTROL"."XLIB_COMPONENTS" ADD CONSTRAINT "XLIB_COMPONENTS_U01" UNIQUE ("COMP_NAME")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_BORDERCONTROL"."XLIB_COMPONENTS"."COMP_ID" IS 'Unique Identifier';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."XLIB_COMPONENTS"."COMP_NAME" IS 'Name of Component';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."XLIB_COMPONENTS"."COMP_VERSION" IS 'Version of Component';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."XLIB_COMPONENTS"."COMP_VERSION_LABEL" IS 'Version Lable of Component';
   COMMENT ON COLUMN "DL_BORDERCONTROL"."XLIB_COMPONENTS"."COMP_DEPENDS_ON" IS 'Dependencies of Component';
   COMMENT ON TABLE "DL_BORDERCONTROL"."XLIB_COMPONENTS"  IS 'Not in use';
  CREATE UNIQUE INDEX "DL_BORDERCONTROL"."XLIB_COMPONENTS_PK" ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" ("COMP_ID") 
  ;
CREATE UNIQUE INDEX "DL_BORDERCONTROL"."XLIB_COMPONENTS_U01" ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" ("COMP_NAME") 
  ;
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "SERVAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIO_BD";
  GRANT DELETE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PIBICSAPP";
  GRANT UPDATE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "APPSUP";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PONGPICHET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."XLIB_COMPONENTS" TO "PORNRUKSA_S";
