CREATE TABLE "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" 
   (	"OWNER" VARCHAR2(128), 
	"OBJECT_TYPE" VARCHAR2(23), 
	"OBJECT_NAME" VARCHAR2(128)
   ) ;
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT DELETE ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT INDEX ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT INSERT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT READ ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSAADM";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "SOMPORN_K";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "KIATTIPAT_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "WORAGON_T";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "PISAN_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "PRAMUALSOOK_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "CHAYA_W";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "CHAYAWEE_O";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "THANASET_N";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "THASAYA_M";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "PORNRUKSA_S";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "SANTIPATN_P";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "PUNYAWII_D";
