CREATE TABLE "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" 
   (	"OWNER" VARCHAR2(128), 
	"OBJECT_TYPE" VARCHAR2(23), 
	"OBJECT_NAME" VARCHAR2(128)
   ) ;
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BORDERCONTROL"."XXTMP_INVALID_OBJECTS" TO "BIOSUPPORT";
