---------------------
-- user --
-- DL_COMMON/user
@DL_COMMON/user/create_DL_COMMON.sql
-- LOGGER/user
@LOGGER/user/create_LOGGER.sql
-- DL_DBA/user
@DL_DBA/user/create_DL_DBA.sql
-- DL_USER_MANAGEMENT/user
@DL_USER_MANAGEMENT/user/create_DL_USER_MANAGEMENT.sql
-- APEX_USER_MANAGEMENT/user
@APEX_USER_MANAGEMENT/user/create_APEX_USER_MANAGEMENT.sql
-- USER_MANAGEMENT/user
@USER_MANAGEMENT/user/create_USER_MANAGEMENT.sql
-- DL_BIOSTORE_BLACKLIST/user
@DL_BIOSTORE_BLACKLIST/user/create_DL_BIOSTORE_BLACKLIST.sql
-- DL_BIOSTORE_MOVEMENTS/user
@DL_BIOSTORE_MOVEMENTS/user/create_DL_BIOSTORE_MOVEMENTS.sql
-- DL_BORDERCONTROL/user
@DL_BORDERCONTROL/user/create_DL_BORDERCONTROL.sql
-- DL_BLACKLIST/user
@DL_BLACKLIST/user/create_DL_BLACKLIST.sql
-- DL_BORDERCONTROL_DATAMART/user
@DL_BORDERCONTROL_DATAMART/user/create_DL_BORDERCONTROL_DATAMART.sql
-- DL_STAGING4PIBICS/user
@DL_STAGING4PIBICS/user/create_DL_STAGING4PIBICS.sql
-- DL_STAGING4PIBICS_INTF/user
@DL_STAGING4PIBICS_INTF/user/create_DL_STAGING4PIBICS_INTF.sql
-- DL_INTERFACE/user
@DL_INTERFACE/user/create_DL_INTERFACE.sql
-- PIBICSDM2_RO/user
@PIBICSDM2_RO/user/create_PIBICSDM2_RO.sql
-- BIO_BD/user
@BIO_BD/user/create_BIO_BD.sql
-- SYSTEM/user
@SYSTEM/user/create_SYSTEM.sql
