---------------------
-- types --
-- DL_COMMON/types
@DL_COMMON/types/ot_10vcc_10cl.tps
@DL_COMMON/types/ot_bin_file.tps
@DL_COMMON/types/ot_char_file.tps
@DL_COMMON/types/ot_db_exce_code.tps
@DL_COMMON/types/ot_db_object_tblspc.tps
@DL_COMMON/types/ot_db_object.tps
@DL_COMMON/types/ot_db_owner.tps
@DL_COMMON/types/ot_db_tab_col_tblspc.tps
@DL_COMMON/types/ot_db_tab_col.tps
@DL_COMMON/types/ot_db_tblspc.tps
@DL_COMMON/types/ot_file.tps
@DL_COMMON/types/ot_search_definition.tps
@DL_COMMON/types/pljson_element.tps
@DL_COMMON/types/pljson_list.tps
@DL_COMMON/types/pljson_narray.tps
@DL_COMMON/types/pljson_table_impl.tps
@DL_COMMON/types/pljson.tps
@DL_COMMON/types/pljson_value_array.tps
@DL_COMMON/types/pljson_value.tps
@DL_COMMON/types/pljson_varray.tps
@DL_COMMON/types/pljson_vtab.tps
@DL_COMMON/types/tt_10vcc_10cl.tps
@DL_COMMON/types/tt_bin_file.tps
@DL_COMMON/types/tt_bl.tps
@DL_COMMON/types/tt_char_file.tps
@DL_COMMON/types/tt_cl.tps
@DL_COMMON/types/tt_db_exce_code.tps
@DL_COMMON/types/tt_db_object_tblspc.tps
@DL_COMMON/types/tt_db_object.tps
@DL_COMMON/types/tt_db_owner.tps
@DL_COMMON/types/tt_db_tab_col_tblspc.tps
@DL_COMMON/types/tt_db_tab_col.tps
@DL_COMMON/types/tt_db_tblspc.tps
@DL_COMMON/types/tt_file.tps
@DL_COMMON/types/tt_n5.tps
@DL_COMMON/types/tt_n.tps
@DL_COMMON/types/tt_search_definition.tps
@DL_COMMON/types/tt_vc128.tps
@DL_COMMON/types/tt_vc30.tps
@DL_COMMON/types/tt_vcc.tps
@DL_COMMON/types/tt_vc.tps
@DL_COMMON/types/vt_10vcc_10cl.tps
@DL_COMMON/types/vt_bin_file.tps
@DL_COMMON/types/vt_bl.tps
@DL_COMMON/types/vt_char_file.tps
@DL_COMMON/types/vt_cl.tps
@DL_COMMON/types/vt_db_exce_code.tps
@DL_COMMON/types/vt_db_object_tblspc.tps
@DL_COMMON/types/vt_db_object.tps
@DL_COMMON/types/vt_db_owner.tps
@DL_COMMON/types/vt_db_tab_col_tblspc.tps
@DL_COMMON/types/vt_db_tab_col.tps
@DL_COMMON/types/vt_db_tblspc.tps
@DL_COMMON/types/vt_file.tps
@DL_COMMON/types/vt_n5.tps
@DL_COMMON/types/vt_n.tps
@DL_COMMON/types/vt_search_definition.tps
@DL_COMMON/types/vt_vc128.tps
@DL_COMMON/types/vt_vc30.tps
@DL_COMMON/types/vt_vcc.tps
@DL_COMMON/types/vt_vc.tps
-- DL_USER_MANAGEMENT/types
@DL_USER_MANAGEMENT/types/ot_ldap_role.tps
@DL_USER_MANAGEMENT/types/tt_ldap_role.tps
@DL_USER_MANAGEMENT/types/vt_ldap_role.tps
-- DL_BORDERCONTROL/types
@DL_BORDERCONTROL/types/ct_partial_date_type.tps
@DL_BORDERCONTROL/types/t_hook_payload.tps
@DL_BORDERCONTROL/types/xlib_vc2_array_t.tps
-- DL_BLACKLIST/types
@DL_BLACKLIST/types/ct_partial_date.tps
@DL_BLACKLIST/types/ot_blt_search_result_ext.tps
@DL_BLACKLIST/types/ot_blt_search_result.tps
@DL_BLACKLIST/types/tt_blt_search_result_ext.tps
@DL_BLACKLIST/types/tt_blt_search_result.tps
@DL_BLACKLIST/types/tt_varchar2.tps
-- DL_MAINTENANCE/types
@DL_MAINTENANCE/types/trig_data.tps
-- SYSTEM/types
@SYSTEM/types/ct_partial_date.tps
@SYSTEM/types/logmnr$col_gg_recs.tps
@SYSTEM/types/logmnr$col_gg_rec.tps
@SYSTEM/types/logmnr$gsba_gg_recs.tps
@SYSTEM/types/logmnr$gsba_gg_rec.tps
@SYSTEM/types/logmnr$key_gg_recs.tps
@SYSTEM/types/logmnr$key_gg_rec.tps
@SYSTEM/types/logmnr$seq_gg_recs.tps
@SYSTEM/types/logmnr$seq_gg_rec.tps
@SYSTEM/types/logmnr$tab_gg_recs.tps
@SYSTEM/types/logmnr$tab_gg_rec.tps
