---------------------
-- triggers --
-- DL_COMMON/triggers
@DL_COMMON/triggers/action_codes$i18n$tiud0.trg
@DL_COMMON/triggers/action_codes$tag$tiud0.trg
@DL_COMMON/triggers/action_codes$tiud0.trg
@DL_COMMON/triggers/airports$i18n$tiud0.trg
@DL_COMMON/triggers/airports$tiud0.trg
@DL_COMMON/triggers/apex_lists$tiud0.trg
@DL_COMMON/triggers/apex_menu$i18n$tiud0.trg
@DL_COMMON/triggers/apex_menu$tiud0.trg
@DL_COMMON/triggers/arrested_statuses$i18n$tiud0.trg
@DL_COMMON/triggers/arrested_statuses$tag$tiud0.trg
@DL_COMMON/triggers/arrested_statuses$tiud0.trg
@DL_COMMON/triggers/arrested_types$i18n$tiud0.trg
@DL_COMMON/triggers/arrested_types$tag$tiud0.trg
@DL_COMMON/triggers/arrested_types$tiud0.trg
@DL_COMMON/triggers/bc_doc_class$i18n$tiud0.trg
@DL_COMMON/triggers/bc_doc_class$tiud0.trg
@DL_COMMON/triggers/bc_person_types$i18n$tiud0.trg
@DL_COMMON/triggers/bc_person_types$tiud0.trg
@DL_COMMON/triggers/b_list_reasons$i18n$tiud0.trg
@DL_COMMON/triggers/b_list_reasons$tiud0.trg
@DL_COMMON/triggers/bools$i18n$tiud0.trg
@DL_COMMON/triggers/bools$tiud0.trg
@DL_COMMON/triggers/border_types$i18n$tiud0.trg
@DL_COMMON/triggers/border_types$tiud0.trg
@DL_COMMON/triggers/bs_relationships$i18n$tiud0.trg
@DL_COMMON/triggers/bs_relationships$tag$tiud0.trg
@DL_COMMON/triggers/bs_relationships$tiud0.trg
@DL_COMMON/triggers/card_types$i18n$tiud0.trg
@DL_COMMON/triggers/card_types$tag$tiud0.trg
@DL_COMMON/triggers/card_types$tiud0.trg
@DL_COMMON/triggers/carriers$i18n$tiud0.trg
@DL_COMMON/triggers/carriers$tiud0.trg
@DL_COMMON/triggers/case_types$i18n$tiud0.trg
@DL_COMMON/triggers/case_types$tag$tiud0.trg
@DL_COMMON/triggers/case_types$tiud0.trg
@DL_COMMON/triggers/countries$i18n$tiud0.trg
@DL_COMMON/triggers/countries$tiud0.trg
@DL_COMMON/triggers/device_types$i18n$tiud0.trg
@DL_COMMON/triggers/device_types$tiud0.trg
@DL_COMMON/triggers/entry_exits$i18n$tiud0.trg
@DL_COMMON/triggers/entry_exits$tiud0.trg
@DL_COMMON/triggers/finger_miss_reasons$i18n$tiud0.trg
@DL_COMMON/triggers/finger_miss_reasons$tiud0.trg
@DL_COMMON/triggers/finger_status$i18n$tiud0.trg
@DL_COMMON/triggers/finger_status$tiud0.trg
@DL_COMMON/triggers/human_fingers$i18n$tiud0.trg
@DL_COMMON/triggers/human_fingers$tiud0.trg
@DL_COMMON/triggers/human_sexes$i18n$tiud0.trg
@DL_COMMON/triggers/human_sexes$tiud0.trg
@DL_COMMON/triggers/icao_dc_list_itms$tiud0.trg
@DL_COMMON/triggers/icao_dc_lists$i18n$tiud0.trg
@DL_COMMON/triggers/icao_dc_lists$tiud0.trg
@DL_COMMON/triggers/icao_doc_codes$i18n$tiud0.trg
@DL_COMMON/triggers/icao_doc_codes$tiud0.trg
@DL_COMMON/triggers/icao_doc_code$visa_type$tag$tiud0.trg
@DL_COMMON/triggers/icao_doc_code$visa_type$tiud0.trg
@DL_COMMON/triggers/incident_types$i18n$tiud0.trg
@DL_COMMON/triggers/incident_types$tiud0.trg
@DL_COMMON/triggers/languages$i18n$tiud0.trg
@DL_COMMON/triggers/languages$tiud0.trg
@DL_COMMON/triggers/locales$tiud0.trg
@DL_COMMON/triggers/messages$i18n$tiud0.trg
@DL_COMMON/triggers/messages$tiud0.trg
@DL_COMMON/triggers/module_versions$tiud0.trg
@DL_COMMON/triggers/movement_reasons$i18n$tiud0.trg
@DL_COMMON/triggers/movement_reasons$tag$tiud0.trg
@DL_COMMON/triggers/movement_reasons$tiud0.trg
@DL_COMMON/triggers/owners$i18n$tiud0.trg
@DL_COMMON/triggers/owners$tag$tiud0.trg
@DL_COMMON/triggers/owners$tiud0.trg
@DL_COMMON/triggers/permit_types$i18n$tiud0.trg
@DL_COMMON/triggers/permit_types$tiud0.trg
@DL_COMMON/triggers/port_movements$i18n$tiud0.trg
@DL_COMMON/triggers/port_movements$tag$tiud0.trg
@DL_COMMON/triggers/port_movements$tiud0.trg
@DL_COMMON/triggers/ports$i18n$tiud0.trg
@DL_COMMON/triggers/ports$tiud0.trg
@DL_COMMON/triggers/reason_codes$i18n$tiud0.trg
@DL_COMMON/triggers/reason_codes$tag$tiud0.trg
@DL_COMMON/triggers/reason_codes$tiud0.trg
@DL_COMMON/triggers/relations$i18n$tiud0.trg
@DL_COMMON/triggers/secret_levels$i18n$tiud0.trg
@DL_COMMON/triggers/secret_levels$tag$tiud0.trg
@DL_COMMON/triggers/secret_levels$tiud0.trg
@DL_COMMON/triggers/statuses$i18n$tiud0.trg
@DL_COMMON/triggers/statuses$tag$tiud0.trg
@DL_COMMON/triggers/statuses$tiud0.trg
@DL_COMMON/triggers/sub_nationalities$i18n$tiud0.trg
@DL_COMMON/triggers/sub_nationalities$tiud0.trg
@DL_COMMON/triggers/trans_grp_states$i18n$tiud0.trg
@DL_COMMON/triggers/trans_grp_states$tiud0.trg
@DL_COMMON/triggers/trans_modes$i18n$tiud0.trg
@DL_COMMON/triggers/trans_modes$tiud0.trg
@DL_COMMON/triggers/trans_vehicles$i18n$tiud0.trg
@DL_COMMON/triggers/trans_vehicles$tiud0.trg
@DL_COMMON/triggers/visa_types$i18n$tiud0.trg
@DL_COMMON/triggers/visa_types$tiud0.trg
@DL_COMMON/triggers/yes_nos$i18n$tiud0.trg
@DL_COMMON/triggers/yes_nos$tiud0.trg
-- LOGGER/triggers
@LOGGER/triggers/biu_logger_apex_items.trg
@LOGGER/triggers/biu_logger_prefs.trg
-- DL_DBA/triggers
@DL_DBA/triggers/module_curr_installs$tiud0.trg
@DL_DBA/triggers/module_curr_inst_args$tiud0.trg
@DL_DBA/triggers/module_installs$tiud0.trg
@DL_DBA/triggers/templates$i18n$tiud0.trg
@DL_DBA/triggers/templates$tag$tiud0.trg
@DL_DBA/triggers/templates$tiud0.trg
-- DL_USER_MANAGEMENT/triggers
@DL_USER_MANAGEMENT/triggers/activities$tiud0.trg
@DL_USER_MANAGEMENT/triggers/after_db_logon_set_custom_ctx.trg
@DL_USER_MANAGEMENT/triggers/computer_org_unit_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/computer_role_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/computers$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/computers$tiud0.trg
@DL_USER_MANAGEMENT/triggers/grants$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/grants$tiud0.trg
@DL_USER_MANAGEMENT/triggers/lookups$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/lookups$tiud0.trg
@DL_USER_MANAGEMENT/triggers/object_grant_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/object_grant_rel.trg
@DL_USER_MANAGEMENT/triggers/object_page_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/object_page_rel.trg
@DL_USER_MANAGEMENT/triggers/objects$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/objects$tiud0.trg
@DL_USER_MANAGEMENT/triggers/org_unit_org_unit_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/org_units$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/org_units$tiud0.trg
@DL_USER_MANAGEMENT/triggers/parameter_settings$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/parameter_settings$tiud0.trg
@DL_USER_MANAGEMENT/triggers/role_object_grant_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/role_object_grant_rel.trg
@DL_USER_MANAGEMENT/triggers/role_role_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/roles$i18n$tiud0.trg
@DL_USER_MANAGEMENT/triggers/roles$tiud0.trg
@DL_USER_MANAGEMENT/triggers/user_org_unit_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/user_role_rel$tiud0.trg
@DL_USER_MANAGEMENT/triggers/user_role_rel.trg
@DL_USER_MANAGEMENT/triggers/users#sgd$tiud0.trg
@DL_USER_MANAGEMENT/triggers/users$tiud0.trg
@DL_USER_MANAGEMENT/triggers/users.trg
-- DL_BORDERCONTROL/triggers
@DL_BORDERCONTROL/triggers/borderdocimages$tiud0.trg
@DL_BORDERCONTROL/triggers/borderdocuments$tiud0.trg
@DL_BORDERCONTROL/triggers/borderposts$tiud0.trg
@DL_BORDERCONTROL/triggers/country_management$tiud0.trg
@DL_BORDERCONTROL/triggers/display_objects$tiud0.trg
@DL_BORDERCONTROL/triggers/entry_forms$tiud0.trg
@DL_BORDERCONTROL/triggers/faf_payment_rate$tag$tiud0.trg
@DL_BORDERCONTROL/triggers/faf_permit_type$tag$tiud0.trg
@DL_BORDERCONTROL/triggers/fellow_passenger$tiud0.trg
@DL_BORDERCONTROL/triggers/flight_health_check$tiud0.trg
@DL_BORDERCONTROL/triggers/flights$tiud0.trg
@DL_BORDERCONTROL/triggers/flighttypes$tiud0.trg
@DL_BORDERCONTROL/triggers/incidents$tiud0.trg
@DL_BORDERCONTROL/triggers/movement_attr$tiud0.trg
@DL_BORDERCONTROL/triggers/movements_blob$tiud0.trg
@DL_BORDERCONTROL/triggers/movements_manual_update$tiud0.trg
@DL_BORDERCONTROL/triggers/movements$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_insair$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_insbank$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_inscash$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_insdept$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_movements_overstay$tiud0.trg
@DL_BORDERCONTROL/triggers/mscs_tm5$tiud0.trg
@DL_BORDERCONTROL/triggers/offline_mode$tiud0.trg
@DL_BORDERCONTROL/triggers/offline_sync_error$tiud0.trg
@DL_BORDERCONTROL/triggers/parameters$tiud0.trg
@DL_BORDERCONTROL/triggers/residence$tiud0.trg
@DL_BORDERCONTROL/triggers/terminals$tiud0.trg
@DL_BORDERCONTROL/triggers/thaipassport$tiud0.trg
@DL_BORDERCONTROL/triggers/tm8_application$tiud0.trg
@DL_BORDERCONTROL/triggers/travel_abis_insert_error$tiud0.trg
@DL_BORDERCONTROL/triggers/visas$tiud0.trg
@DL_BORDERCONTROL/triggers/xlib_logs_bi_trg.trg
-- DL_BLACKLIST/triggers
@DL_BLACKLIST/triggers/biometrics$biur.trg
@DL_BLACKLIST/triggers/blacklist_cases$biur_o.trg
@DL_BLACKLIST/triggers/blacklist_cases$biur.trg
@DL_BLACKLIST/triggers/blacklist_cases$tiud0.trg
@DL_BLACKLIST/triggers/compression_algorithms$biur.trg
@DL_BLACKLIST/triggers/device_types$biur.trg
@DL_BLACKLIST/triggers/face_missing_reasons$biur.trg
@DL_BLACKLIST/triggers/face_missing_reasons$i18n$biur.trg
@DL_BLACKLIST/triggers/face_positions$biur.trg
@DL_BLACKLIST/triggers/face_positions$i18n$biur.trg
@DL_BLACKLIST/triggers/face_quality_types$biur.trg
@DL_BLACKLIST/triggers/face_quality_types$i18n$biur.trg
@DL_BLACKLIST/triggers/face_resolutions$biur.trg
@DL_BLACKLIST/triggers/faces$biur.trg
@DL_BLACKLIST/triggers/finger_impression_types$biur.trg
@DL_BLACKLIST/triggers/finger_impression_types$i18n$biur.trg
@DL_BLACKLIST/triggers/finger_missing_reasons$biur.trg
@DL_BLACKLIST/triggers/finger_missing_reasons$i18n$biur.trg
@DL_BLACKLIST/triggers/finger_positions$biur.trg
@DL_BLACKLIST/triggers/finger_positions$i18n$biur.trg
@DL_BLACKLIST/triggers/fingerprints$biur.trg
@DL_BLACKLIST/triggers/identities$tag$tiud0.trg
@DL_BLACKLIST/triggers/identities$tiud0_o.trg
@DL_BLACKLIST/triggers/identities$tiud0.trg
@DL_BLACKLIST/triggers/images$biur.trg
@DL_BLACKLIST/triggers/travel_docs$tag$tiud0.trg
@DL_BLACKLIST/triggers/travel_docs$tiud0.trg
@DL_BLACKLIST/triggers/trg_iou_v_blacklist_cases.trg
