CREATE TABLE "DL_STAGING4PIBICS"."CNT_TMMAIN" 
   (	"LOWEST_TMRUNNO_TO_COPY" VARCHAR2(100 CHAR), 
	"HIGHEST_TMRUNNO_TO_COPY" VARCHAR2(100 CHAR), 
	"LOWEST_TMRUNNO_INOUT_DATE_FOUND" DATE, 
	"HIGEHST_TMRUNNO_INOUT_DATE_FOUND" DATE, 
	"COPIED_CNT_STAGING" NUMBER, 
	"COPIED_AT_STAGING" DATE, 
	"COPIED_CNT_SYNC" NUMBER, 
	"COPIED_AT_SYNC" DATE, 
	"COPIED_CNT_TARGET" NUMBER, 
	"COPIED_AT_TARGET" DATE
   ) ;
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."CNT_TMMAIN"."LOWEST_TMRUNNO_TO_COPY" IS 'data including this number shall be copied';
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."CNT_TMMAIN"."HIGHEST_TMRUNNO_TO_COPY" IS 'data including this number shall be copied';
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."CNT_TMMAIN"."LOWEST_TMRUNNO_INOUT_DATE_FOUND" IS 'indte or outdte at the lowest_tmrunno_to_copy';
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."CNT_TMMAIN"."HIGEHST_TMRUNNO_INOUT_DATE_FOUND" IS 'indte or outdte at the highest_tmrunno_to_copy';
   COMMENT ON TABLE "DL_STAGING4PIBICS"."CNT_TMMAIN"  IS 'Counters for the PIBICS source tables, maintained by program';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."CNT_TMMAIN_UK" ON "DL_STAGING4PIBICS"."CNT_TMMAIN" ("LOWEST_TMRUNNO_TO_COPY") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DL_STAGING4PIBICS_INTF";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS"."CNT_TMMAIN" TO "BIOSAADM";
