CREATE TABLE "DL_STAGING4PIBICS"."FS_FINESDETAIL" 
   (	"FINESDETAIL_SEQNO" NUMBER NOT NULL ENABLE, 
	"FINES_SEQNO" NUMBER, 
	"PRATE_SEQNO" NUMBER, 
	"FINESLIPAMOUNT" NUMBER(10,2), 
	"OVERSTAYDAY" NUMBER, 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_IP" VARCHAR2(20 CHAR), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_IP" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "DL_STAGING4PIBICS"."FS_FINESDETAIL" ADD CONSTRAINT "FS_FINESDETAIL_PK" PRIMARY KEY ("FINESDETAIL_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."FS_FINESDETAIL_PK" ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" ("FINESDETAIL_SEQNO") 
  ;
  GRANT DELETE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS"."FS_FINESDETAIL" TO "BIOSAADM";
