CREATE TABLE "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"M_ROW$$" VARCHAR2(255 CHAR), 
	"SEQUENCE$$" NUMBER, 
	"DMLTYPE$$" VARCHAR2(1 CHAR), 
	"OLD_NEW$$" VARCHAR2(1 CHAR), 
	"CHANGE_VECTOR$$" RAW(255), 
	"XID$$" NUMBER
   ) ;
   COMMENT ON TABLE "DL_STAGING4PIBICS"."MLOG$_WATCHLIST"  IS 'snapshot log for master table DL_STAGING4PIBICS.WATCHLIST';
  CREATE INDEX "DL_STAGING4PIBICS"."I_MLOG$_WATCHLIST" ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" ("XID$$") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "SERVAPP";
  GRANT DELETE ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DL_STAGING4PIBICS_INTF";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."MLOG$_WATCHLIST" TO "APPSUP";
