CREATE TABLE "DL_STAGING4PIBICS"."OCCUPATION" 
   (	"OCC_SEQNO" NUMBER NOT NULL ENABLE, 
	"OCCCD" VARCHAR2(4 CHAR) NOT NULL ENABLE, 
	"OCCTNM" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"OCCENM" VARCHAR2(60 CHAR), 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS"."OCCUPATION" ADD CONSTRAINT "OCCUPATION_PK" PRIMARY KEY ("OCC_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."OCCUPATION_PK" ON "DL_STAGING4PIBICS"."OCCUPATION" ("OCC_SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS"."OCCUPATION" TO "BIOSAADM";
