CREATE TABLE "DL_STAGING4PIBICS"."PERMITTYPE" 
   (	"PERMIT_SEQNO" NUMBER NOT NULL ENABLE, 
	"PERMITCD" VARCHAR2(4 CHAR), 
	"PERMITNM" VARCHAR2(60 CHAR), 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER
   ) ;
  ALTER TABLE "DL_STAGING4PIBICS"."PERMITTYPE" ADD CONSTRAINT "PERMITTYPE_PK" PRIMARY KEY ("PERMIT_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."PERMITTYPE_PK" ON "DL_STAGING4PIBICS"."PERMITTYPE" ("PERMIT_SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS"."PERMITTYPE" TO "BIOSAADM";
