CREATE TABLE "DL_STAGING4PIBICS"."SUFFIX" 
   (	"SUFFIX_SEQNO" NUMBER NOT NULL ENABLE, 
	"SUFFIX_DESC" VARCHAR2(50 CHAR), 
	"ACTFLAG" VARCHAR2(1 CHAR), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"VERSION" NUMBER, 
	"SUFFIX_TYPE" VARCHAR2(1 CHAR), 
	"SUFFIXORDER" NUMBER
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS"."SUFFIX" ADD CONSTRAINT "SUFFIX_PK" PRIMARY KEY ("SUFFIX_SEQNO")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."SUFFIX_PK" ON "DL_STAGING4PIBICS"."SUFFIX" ("SUFFIX_SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."SUFFIX" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."SUFFIX" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."SUFFIX" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."SUFFIX" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS"."SUFFIX" TO "BIOSAADM";
