CREATE TABLE "DL_STAGING4PIBICS"."VISATYPE" 
   (	"VISATYPE_SEQNO" NUMBER NOT NULL ENABLE, 
	"VISATYPECD" CHAR(4 CHAR), 
	"VISATYPETNM" VARCHAR2(120 CHAR), 
	"VISATYPEENM" VARCHAR2(60 CHAR), 
	"PERMITTDAYS" NUMBER(*,0) DEFAULT 0, 
	"ACTFLAG" CHAR(1 CHAR), 
	"CREATE_DATE" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(20 CHAR), 
	"UPDATE_DATE" TIMESTAMP (6), 
	"UPDATE_BY" VARCHAR2(20 CHAR), 
	"VERSION" NUMBER, 
	"VISATYPE_EXT" VARCHAR2(60 CHAR), 
	"OLD_VISATYPE" CHAR(4 CHAR)
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS"."VISATYPE" ADD CONSTRAINT "VISATYPE_PK" PRIMARY KEY ("VISATYPE_SEQNO")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_STAGING4PIBICS"."VISATYPE"."VISATYPE_SEQNO" IS 'Surrogate key ';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS"."VISATYPE_PK" ON "DL_STAGING4PIBICS"."VISATYPE" ("VISATYPE_SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT REFERENCES ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_STAGING4PIBICS_INTF";
  GRANT DELETE ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_COMMON";
  GRANT INSERT ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_COMMON";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."VISATYPE" TO "DL_COMMON";
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS"."VISATYPE" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS"."VISATYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS"."VISATYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS"."VISATYPE" TO "APPSUP";
