CREATE TABLE "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" 
   (	"STAGING_TABLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"SYNC_TABLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ERROR_TABLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"PIBICS_TABLE_CD" VARCHAR2(1 CHAR), 
	"SHALL_BE_PROCESSED" VARCHAR2(1 CHAR) NOT NULL ENABLE
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" ADD CONSTRAINT "OPS_SYNC_PROCESSES_PK" PRIMARY KEY ("STAGING_TABLE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" ADD CONSTRAINT "OPS_SYNC_PROCESSES_UK1" UNIQUE ("SYNC_TABLE_NAME", "PIBICS_TABLE_CD")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES"."STAGING_TABLE_NAME" IS 'This table drives the process ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES"."ERROR_TABLE_NAME" IS 'Error table, several processes might use the same error table ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES"."PIBICS_TABLE_CD" IS 'When the synctable is used  in several backend processed. This column mus exist in the sync_able with the same name and value ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES"."SHALL_BE_PROCESSED" IS '(Y)ey, (N)o, No for processes in development and similar situations';
   COMMENT ON TABLE "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES"  IS 'Metatable for the dofferent sync-processes in the system';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES_PK" ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" ("STAGING_TABLE_NAME") 
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES_UK1" ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" ("SYNC_TABLE_NAME", "PIBICS_TABLE_CD") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "PIBICSAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."OPS_SYNC_PROCESSES" TO "APPSUP";
