CREATE TABLE "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" 
   (	"SEQNO" NUMBER, 
	"CODE" VARCHAR2(20 CHAR), 
	"KEY_VALUE" VARCHAR2(32 CHAR)
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" ADD CONSTRAINT "TRCD_PERMITTYPE_UK1" UNIQUE ("SEQNO")
  USING INDEX  ENABLE;
   COMMENT ON TABLE "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE"  IS 'Transcode Table for DL_STAGING4PIBICS.PERMITTYPE to DL_BORDERCONTROL.FAF_PERMITTYPE';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE_UK1" ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" ("SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "DL_BORDERCONTROL";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "PIBICSAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS_INTF"."TRCD_PERMITTYPE" TO "BIOSAADM";
