CREATE TABLE "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" 
   (	"RANKCRW_SEQNO" NUMBER, 
	"RANKNM" VARCHAR2(30 CHAR), 
	"KEY_VALUE" VARCHAR2(32 CHAR)
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" ADD CONSTRAINT "TRCD_RANKCRW_UK1" UNIQUE ("RANKCRW_SEQNO")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" ADD CONSTRAINT "TRCD_RANKCRW_UK2" UNIQUE ("RANKNM")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW_UK1" ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" ("RANKCRW_SEQNO") 
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW_UK2" ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" ("RANKNM") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "PIBICSAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_RANKCRW" TO "BIOSUPPORT";
