CREATE TABLE "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" 
   (	"SEQNO" NUMBER, 
	"FLIGHTNUM" VARCHAR2(50 CHAR), 
	"KEY_VALUE" VARCHAR2(32 CHAR), 
	"DIRECTION" NUMBER
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" ADD CONSTRAINT "TRCD_FLIGHTNUMBERS_UK1" UNIQUE ("SEQNO")
  USING INDEX  ENABLE;
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS"."FLIGHTNUM" IS 'concatinated from PIBICS FLIGHTPREFIX and FLIGHTNUMBER  ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS"."KEY_VALUE" IS 'Not unique here';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS"."DIRECTION" IS 'Already converted to Bordercontrol keys';
  CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS_UK1" ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" ("SEQNO") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "PIBICSAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "APPSUP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSUPPORT";
  GRANT ALTER ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT INDEX ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT REFERENCES ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT READ ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT ON COMMIT REFRESH ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT QUERY REWRITE ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT DEBUG ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
  GRANT FLASHBACK ON "DL_STAGING4PIBICS_INTF"."TRCD_FLIGHTNUMBERS" TO "BIOSAADM";
