
REM INSERTING into DL_COMMON.LANGUAGES
SET DEFINE OFF;
Insert into DL_COMMON.LANGUAGES (KEY_VALUE,LOCALE,DISPLAY_VALUE,DISPLAY_ORDER,IS_ACTIVE,DML_AT,DML_BY,DML_TYPE,NOTICE,ISO639_2_T,ISO639_1,NUM_VALUE,ROW_FLAG_MASK,INS_AT,INS_BY,OWNER) values ('hrv','en_US','Croatian',null,'Y',to_timestamp('23-NOV-18 10.07.36.471020000 PM','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001','I',null,'hrv','hr',null,1,to_timestamp('23-NOV-18','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001',null);
Insert into DL_COMMON.LANGUAGES (KEY_VALUE,LOCALE,DISPLAY_VALUE,DISPLAY_ORDER,IS_ACTIVE,DML_AT,DML_BY,DML_TYPE,NOTICE,ISO639_2_T,ISO639_1,NUM_VALUE,ROW_FLAG_MASK,INS_AT,INS_BY,OWNER) values ('tha','en_US','Thai',null,'Y',to_timestamp('23-NOV-18 10.07.36.471685000 PM','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001','I',null,'tha','th',null,1,to_timestamp('23-NOV-18','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001',null);
Insert into DL_COMMON.LANGUAGES (KEY_VALUE,LOCALE,DISPLAY_VALUE,DISPLAY_ORDER,IS_ACTIVE,DML_AT,DML_BY,DML_TYPE,NOTICE,ISO639_2_T,ISO639_1,NUM_VALUE,ROW_FLAG_MASK,INS_AT,INS_BY,OWNER) values ('deu','en_US','German',null,'Y',to_timestamp('23-NOV-18 10.07.36.471737000 PM','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001','I',null,'deu','de',null,1,to_timestamp('23-NOV-18','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001',null);
Insert into DL_COMMON.LANGUAGES (KEY_VALUE,LOCALE,DISPLAY_VALUE,DISPLAY_ORDER,IS_ACTIVE,DML_AT,DML_BY,DML_TYPE,NOTICE,ISO639_2_T,ISO639_1,NUM_VALUE,ROW_FLAG_MASK,INS_AT,INS_BY,OWNER) values ('eng','en_US','English',null,'Y',to_timestamp('23-NOV-18 10.07.36.471783000 PM','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001','I',null,'eng','en',null,1,to_timestamp('23-NOV-18','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001',null);
Insert into DL_COMMON.LANGUAGES (KEY_VALUE,LOCALE,DISPLAY_VALUE,DISPLAY_ORDER,IS_ACTIVE,DML_AT,DML_BY,DML_TYPE,NOTICE,ISO639_2_T,ISO639_1,NUM_VALUE,ROW_FLAG_MASK,INS_AT,INS_BY,OWNER) values ('fra','en_US','French',null,'Y',to_timestamp('23-NOV-18 10.07.36.471834000 PM','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001','I',null,'fra','fr',null,1,to_timestamp('23-NOV-18','DD-MON-RR HH.MI.SSXFF AM'),'oracle @sqlplus@tibpbio-db001 (TNS V1-V3) - tibpbio-db001',null);

