
REM INSERTING into DL_STAGING4PIBICS.OPS_PIBICS_TABLE
SET DEFINE OFF;
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('AMPUR','AMPUR');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('AMPUR_LOG','AMPUR');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('CONTINENT','CONTINENT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('CONVEYANCE','CONVEYANCE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('CONVEYANCELOG','CONVEYANCE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('COUNTRY','COUNTRY');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('COUNTRY_LOG','COUNTRY');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('CREW','CREW');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('CREWLOG','CREW');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('DEPARTMENT','DEPARTMENT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('DEPARTMENT_LOG','DEPARTMENT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FLIGHTNUMBERS','FLIGHTNUMBERS');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FLIGHTNUMBERS_LOG','FLIGHTNUMBERS');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FEES','FS_FEES');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FEES_LOG','FS_FEES');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FEESDETAIL','FS_FEESDETAIL');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FEESDETAIL_LOG','FS_FEESDETAIL');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FINES','FS_FINES');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FINES_LOG','FS_FINES');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FINESDETAIL','FS_FINESDETAIL');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_FINESDETAIL_LOG','FS_FINESDETAIL');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('FS_SLIPSYSTEM','FS_SLIPSYSTEM');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('LOSTPASSPORT','LOSTPASSPORT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('OCCUPATION','OCCUPATION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('OCCUPATION_LOG','OCCUPATION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PAYMENTRATE','PAYMENTRATE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PAYMENTRATE_LOG','PAYMENTRATE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PERMITTYPE','PERMITTYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PERMITTYPE_LOG','PERMITTYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PROVINCE','PROVINCE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('PROVINCE_LOG','PROVINCE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('RANKCRW','RANKCRW');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('RANKCRW_LOG','RANKCRW');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('REGION','REGION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('REGION_LOG','REGION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('SUFFIX','SUFFIX');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('SUFFIX_LOG','SUFFIX');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('TAMBON','TAMBON');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('TAMBON_LOG','TAMBON');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('THAIPASSPORT','THAIPASSPORT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('TMINOUT','TMINOUT');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('TRAVELDOCTYPE','TRAVELDOCTYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('TRAVELDOCTYPE_LOG','TRAVELDOCTYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISABYNATION','VISABYNATION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISABYNATIONLOG','VISABYNATION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISABYNATION_LOG','VISABYNATION');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISATYPE','VISATYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISATYPELOG','VISATYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('VISATYPE_LOG','VISATYPE');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WATCHLIST','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WATCHLISTLOG','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WATCHLISTNM','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WATCHLISTNMLOG','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WLRELATION','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WLRELATIONLOG','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WLREMARK','WATCHLIST');
Insert into DL_STAGING4PIBICS.OPS_PIBICS_TABLE (TABLE_NAME,PROCESS_NAME) values ('WLREMARKLOG','WATCHLIST');

57 rows selected. 

