CREATE TABLE "DL_MAINTENANCE"."HM_SETTINGS" 
   (	"KEY" VARCHAR2(100), 
	"VALUE" VARCHAR2(4000), 
	"VALUE_BLOB" BLOB, 
	"VALUE_CLOB" CLOB
   ) ;
  CREATE UNIQUE INDEX "DL_MAINTENANCE"."SYS_IL0000572881C00003$$" ON "DL_MAINTENANCE"."HM_SETTINGS" (
  ;
CREATE UNIQUE INDEX "DL_MAINTENANCE"."SYS_IL0000572881C00004$$" ON "DL_MAINTENANCE"."HM_SETTINGS" (
  ;
  GRANT SELECT ON "DL_MAINTENANCE"."HM_SETTINGS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_MAINTENANCE"."HM_SETTINGS" TO "BIOSUPPORT";
  GRANT SELECT ON "DL_MAINTENANCE"."HM_SETTINGS" TO "BIOSAADM";
