CREATE TABLE "SYSTEM"."LOGMNR_SPILL$" SHARING=METADATA 
   (	"SESSION#" NUMBER, 
	"XIDUSN" NUMBER, 
	"XIDSLT" NUMBER, 
	"XIDSQN" NUMBER, 
	"CHUNK" NUMBER, 
	"STARTIDX" NUMBER, 
	"ENDIDX" NUMBER, 
	"FLAG" NUMBER, 
	"SEQUENCE#" NUMBER, 
	"SPILL_DATA" BLOB, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"PDBID" NUMBER
   ) ;
  ALTER TABLE "SYSTEM"."LOGMNR_SPILL$" ADD CONSTRAINT "LOGMNR_SPILL$_PK" PRIMARY KEY ("SESSION#", "PDBID", "XIDUSN", "XIDSLT", "XIDSQN", "CHUNK", "STARTIDX", "ENDIDX", "FLAG", "SEQUENCE#")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SYSTEM"."LOGMNR_SPILL$_PK" ON "SYSTEM"."LOGMNR_SPILL$" ("SESSION#", "PDBID", "XIDUSN", "XIDSLT", "XIDSQN", "CHUNK", "STARTIDX", "ENDIDX", "FLAG", "SEQUENCE#") 
  ;
CREATE UNIQUE INDEX "SYSTEM"."SYS_IL0000001435C00010$$" ON "SYSTEM"."LOGMNR_SPILL$" (
  ;
