CREATE TABLE "SYSTEM"."LOGMNR_CON$" SHARING=METADATA 
   (	"OWNER#" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(384) NOT NULL ENABLE, 
	"CON#" NUMBER NOT NULL ENABLE, 
	"LOGMNR_UID" NUMBER(22,0), 
	"LOGMNR_FLAGS" NUMBER(22,0), 
	"START_SCNBAS" NUMBER, 
	"START_SCNWRP" NUMBER
   ) 
  PARTITION BY RANGE ("LOGMNR_UID") 
 (PARTITION "P_LESSTHAN100"  VALUES LESS THAN (100) ) ;
  ALTER TABLE "SYSTEM"."LOGMNR_CON$" ADD CONSTRAINT "LOGMNR_CON$_PK" PRIMARY KEY ("LOGMNR_UID", "CON#") DISABLE;
  CREATE INDEX "SYSTEM"."LOGMNR_I1CON$" ON "SYSTEM"."LOGMNR_CON$" ("LOGMNR_UID", "CON#") 
   LOCAL
 (PARTITION "P_LESSTHAN100" ) ;
