CREATE TABLE "SYSTEM"."LOGMNR_PDB_INFO$" SHARING=METADATA 
   (	"LOGMNR_DID" NUMBER NOT NULL ENABLE, 
	"LOGMNR_MDH" NUMBER NOT NULL ENABLE, 
	"PDB_NAME" VARCHAR2(384), 
	"PDB_ID" NUMBER, 
	"PDB_UID" NUMBER, 
	"PLUGIN_SCN" NUMBER NOT NULL ENABLE, 
	"UNPLUG_SCN" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000), 
	"SPARE4" TIMESTAMP (6), 
	"PDB_GLOBAL_NAME" VARCHAR2(384)
   ) ;
  ALTER TABLE "SYSTEM"."LOGMNR_PDB_INFO$" ADD CONSTRAINT "LOGMNR_PDB_INFO$_PK" PRIMARY KEY ("LOGMNR_DID", "LOGMNR_MDH", "PLUGIN_SCN")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SYSTEM"."LOGMNR_PDB_INFO$_PK" ON "SYSTEM"."LOGMNR_PDB_INFO$" ("LOGMNR_DID", "LOGMNR_MDH", "PLUGIN_SCN") 
  ;
