CREATE TABLE "SYSTEM"."LOGMNR_FILTER$" SHARING=METADATA 
   (	"SESSION#" NUMBER, 
	"FILTER_TYPE" VARCHAR2(30), 
	"ATTR1" NUMBER, 
	"ATTR2" NUMBER, 
	"ATTR3" NUMBER, 
	"ATTR4" NUMBER, 
	"ATTR5" NUMBER, 
	"ATTR6" NUMBER, 
	"FILTER_SCN" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" DATE
   ) ;
