CREATE TABLE "SYSTEM"."LOGSTDBY$SKIP" SHARING=METADATA 
   (	"ERROR" NUMBER, 
	"STATEMENT_OPT" VARCHAR2(128), 
	"SCHEMA" VARCHAR2(128), 
	"NAME" VARCHAR2(261), 
	"USE_LIKE" NUMBER, 
	"ESC" VARCHAR2(1), 
	"PROC" VARCHAR2(392), 
	"ACTIVE" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(2000)
   ) ;
  CREATE INDEX "SYSTEM"."LOGSTDBY$SKIP_IDX1" ON "SYSTEM"."LOGSTDBY$SKIP" ("USE_LIKE", "SCHEMA", "NAME") 
  ;
CREATE INDEX "SYSTEM"."LOGSTDBY$SKIP_IDX2" ON "SYSTEM"."LOGSTDBY$SKIP" ("STATEMENT_OPT") 
  ;
