CREATE TABLE "SYSTEM"."MVIEW$_ADV_EXCEPTIONS" SHARING=METADATA 
   (	"RUNID#" NUMBER, 
	"OWNER" VARCHAR2(128), 
	"TABLE_NAME" VARCHAR2(128), 
	"DIMENSION_NAME" VARCHAR2(128), 
	"RELATIONSHIP" VARCHAR2(11), 
	"BAD_ROWID" ROWID
   ) ;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_EXCEPTIONS" ADD CONSTRAINT "MVIEW$_ADV_EXCEPTION_FK" FOREIGN KEY ("RUNID#")
	  REFERENCES "SYSTEM"."MVIEW$_ADV_LOG" ("RUNID#") ENABLE;
   COMMENT ON TABLE "SYSTEM"."MVIEW$_ADV_EXCEPTIONS"  IS 'Output table for dimension validations';
