CREATE TABLE "SYSTEM"."SCHEDULER_JOB_ARGS_TBL" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128), 
	"JOB_NAME" VARCHAR2(128), 
	"ARGUMENT_NAME" VARCHAR2(128), 
	"ARGUMENT_POSITION" NUMBER, 
	"ARGUMENT_TYPE" VARCHAR2(257), 
	"VALUE" VARCHAR2(4000), 
	"ANYDATA_VALUE" "SYS"."ANYDATA" , 
	"OUT_ARGUMENT" VARCHAR2(5)
   ) ;
  CREATE UNIQUE INDEX "SYSTEM"."SYS_IL0000012615C00007$$" ON "SYSTEM"."SCHEDULER_JOB_ARGS_TBL" (
  ;
  GRANT SELECT ON "SYSTEM"."SCHEDULER_JOB_ARGS_TBL" TO "SELECT_CATALOG_ROLE";
