CREATE TABLE "DL_DBA"."MODULE_CURR_INST_ARGS" 
   (	"MODULE_TITLE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ARG_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ARG_VALUE" VARCHAR2(4000 CHAR), 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_DBA"."MODULE_CURR_INST_ARGS" ADD CONSTRAINT "MODULE_CURR_INST_ARGS$PK" PRIMARY KEY ("MODULE_TITLE", "ARG_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_DBA"."MODULE_CURR_INST_ARGS" ADD CONSTRAINT "MODULE_CURR_INST_ARGS$CHK00" CHECK (DML_TYPE in ('I'
                                                                                                       ,'U')) ENABLE;
  ALTER TABLE "DL_DBA"."MODULE_CURR_INST_ARGS" ADD CONSTRAINT "MODULE_CURR_INST_ARGS$FK00" FOREIGN KEY ("MODULE_TITLE")
	  REFERENCES "DL_DBA"."MODULE_CURR_INSTALLS" ("MODULE_TITLE") ON DELETE CASCADE ENABLE;
  CREATE UNIQUE INDEX "DL_DBA"."MODULE_CURR_INST_ARGS$PK" ON "DL_DBA"."MODULE_CURR_INST_ARGS" ("MODULE_TITLE", "ARG_NAME") 
  ;
  GRANT INSERT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "DBA";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO PUBLIC;
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "SERVAPP";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "BIO_BD";
  GRANT DELETE ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "APPSUP";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_DBA"."MODULE_CURR_INST_ARGS" TO "BIOSUPPORT";
