CREATE TABLE "DL_DBA"."MODULE_INSTALLS" 
   (	"KEY_VALUE" VARCHAR2(32 CHAR) DEFAULT ON NULL SYS_GUID() NOT NULL ENABLE, 
	"TITLE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"REMARK" VARCHAR2(4000 CHAR), 
	"MAJOR" NUMBER(5,0) NOT NULL ENABLE, 
	"MINOR" NUMBER(5,0) NOT NULL ENABLE, 
	"PATCH" NUMBER(5,0) NOT NULL ENABLE, 
	"ADDITIONAL_VERSION_NUMBER" NUMBER, 
	"START_INVALID_DB_OBJECTS" NUMBER(18,0) NOT NULL ENABLE, 
	"END_INVALID_DB_OBJECTS" NUMBER(18,0) NOT NULL ENABLE, 
	"END_EXIT_CODE" NUMBER(5,0) NOT NULL ENABLE, 
	"DML_AT" TIMESTAMP (6) DEFAULT ON NULL systimestamp NOT NULL ENABLE, 
	"DML_BY" VARCHAR2(255 CHAR) DEFAULT ON NULL user NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT ON NULL 'I' NOT NULL ENABLE
   ) ;
  ALTER TABLE "DL_DBA"."MODULE_INSTALLS" ADD CONSTRAINT "MODULE_INSTALLS$PK" PRIMARY KEY ("KEY_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DL_DBA"."MODULE_INSTALLS" ADD CONSTRAINT "MODULE_INSTALLS$CK00" CHECK (KEY_VALUE = upper(KEY_VALUE)) ENABLE;
  ALTER TABLE "DL_DBA"."MODULE_INSTALLS" ADD CONSTRAINT "MODULE_INSTALLS$CK01" CHECK (DML_TYPE in ('I'
                                                                                         ,'U')) ENABLE;
  CREATE INDEX "DL_DBA"."MODULE_INSTALLS$IX00" ON "DL_DBA"."MODULE_INSTALLS" ("TITLE", "MAJOR", "MINOR", "PATCH") 
  ;
CREATE INDEX "DL_DBA"."MODULE_INSTALLS$IX01" ON "DL_DBA"."MODULE_INSTALLS" ("TITLE", "ADDITIONAL_VERSION_NUMBER") 
  ;
CREATE UNIQUE INDEX "DL_DBA"."MODULE_INSTALLS$PK" ON "DL_DBA"."MODULE_INSTALLS" ("KEY_VALUE") 
  ;
  GRANT INSERT ON "DL_DBA"."MODULE_INSTALLS" TO "DBA";
  GRANT DELETE ON "DL_DBA"."MODULE_INSTALLS" TO "DL_COMMON";
  GRANT INSERT ON "DL_DBA"."MODULE_INSTALLS" TO "DL_COMMON";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "DL_COMMON";
  GRANT UPDATE ON "DL_DBA"."MODULE_INSTALLS" TO "DL_COMMON";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO PUBLIC;
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "SERVAPP";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "BIO_BD";
  GRANT DELETE ON "DL_DBA"."MODULE_INSTALLS" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_DBA"."MODULE_INSTALLS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_DBA"."MODULE_INSTALLS" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "APPSUP";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_DBA"."MODULE_INSTALLS" TO "BIOSUPPORT";
