CREATE TABLE "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" 
   (	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER, 
	"OWNERAGE" VARCHAR2(4 CHAR), 
	"EXPIRYDATE" DATE, 
	"NATIONCD" VARCHAR2(3 CHAR), 
	"PASSPORTNO" VARCHAR2(20 CHAR), 
	"CASE_ID" VARCHAR2(32 CHAR), 
	"IDENTITY_ID" VARCHAR2(32 CHAR), 
	"ADDRESS_ID" VARCHAR2(32 CHAR), 
	"TRAVEL_DOCS_ID" VARCHAR2(32 CHAR), 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"PIBICS_TABLE_CD" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"IS_ACTIVE_IN_MVLOG" VARCHAR2(1 CHAR) DEFAULT 'Y' NOT NULL ENABLE, 
	"DML_TYPE" VARCHAR2(1 CHAR) DEFAULT 'I' NOT NULL ENABLE, 
	"DML_START_TS" TIMESTAMP (6) DEFAULT systimestamp NOT NULL ENABLE, 
	"CURRENTNESS_IN_PIBICS" DATE NOT NULL ENABLE, 
	"CURRENTNESS_IN_BC" DATE, 
	"ROW_SHALL_BE_IGNORED" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE
   )   NO INMEMORY ;
  ALTER TABLE "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" ADD CONSTRAINT "SYNC_BLACKLIST_CASES_CHK_PIBICS_CD" CHECK (PIBICS_TABLE_CD in ('W', 'L')) ENABLE;
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."WLCD" IS 'PK of PIBICS table WATCHLIST ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."SEQNO" IS 'PK of PIBICS table WATCHLISTNM';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."EXPIRYDATE" IS 'PK of PIBICS table LOSTPASSPORT ';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."NATIONCD" IS 'PK of PIBICS table LOSTPASSPORT';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."PASSPORTNO" IS 'PK of PIBICS table LOSTPASSPORT';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."CASE_ID" IS 'PK of BLACKLIST_CASES';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."IDENTITY_ID" IS 'PK of IDENTITIES';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."TRAVEL_DOCS_ID" IS 'PK of TRAVEL_DOCS';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."DML_TYPE" IS 'Type of last logical DML I,U,D';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."DML_START_TS" IS 'Start of last run which touched this row';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."CURRENTNESS_IN_PIBICS" IS 'The update or create date in the source';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."CURRENTNESS_IN_BC" IS 'The update or create date in the target (movement)';
   COMMENT ON COLUMN "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"."ROW_SHALL_BE_IGNORED" IS 'This data is garbage and cannot be processed';
   COMMENT ON TABLE "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES"  IS 'sync table of DL_BLACKLIST.BLACKLIST_CASES, IDENTITIES, ADDRESS and TRAVEL_DOCS ';
  CREATE INDEX "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES_CD" ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" ("CREATE_DATE") 
  ;
CREATE UNIQUE INDEX "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES_UK" ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" ("WLCD", "OWNERAGE", "SEQNO", "PIBICS_TABLE_CD") 
  ;
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "SERVAPP";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "BIO_BD";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "PIBICSAPP";
  GRANT DELETE ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DL_BLACKLIST";
  GRANT INSERT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DL_BLACKLIST";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DL_BLACKLIST";
  GRANT UPDATE ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "DL_BLACKLIST";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "TESTADM";
  GRANT SELECT ON "DL_STAGING4PIBICS_INTF"."SYNC_BLACKLIST_CASES" TO "TRAINEE";
