@application/init.sql
@application/set_environment.sql
@application/delete_application.sql
@application/ui_types.sql
@application/create_application.sql
@application/shared_components/navigation/lists.sql
@application/shared_components/files.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs.sql
@application/shared_components/navigation/trees.sql
@application/pages/page_groups.sql
@application/comments.sql
@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@application/shared_components/user_interface/templates/page.sql
@application/shared_components/user_interface/templates/button.sql
@application/shared_components/user_interface/templates/region.sql
@application/shared_components/user_interface/templates/list.sql
@application/shared_components/user_interface/templates/report.sql
@application/shared_components/user_interface/templates/label.sql
@application/shared_components/user_interface/templates/breadcrumb.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/translations.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts.sql
@application/shared_components/security/authentications.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_faceitem_update.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_fingercapture_state.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_passportcapture_reset.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_passportcapture_releasedevice.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_fingercapture_releasedevice.sql
@application/shared_components/plugins/region_type/com_dermalog_fingercapture.sql
@application/shared_components/plugins/item_type/com_dermalog_faceitem.sql
@application/shared_components/plugins/region_type/com_dermalog_nist.sql
@application/shared_components/plugins/item_type/com_dermalog_fingeritem.sql
@application/shared_components/plugins/region_type/com_dermalog_facecapture.sql
@application/shared_components/plugins/dynamic_action/com_dermalog_fingeritem_update.sql
@application/shared_components/plugins/region_type/com_dermalog_passportcapture.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00001.sql
@application/pages/page_00003.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00010.sql
@application/pages/page_00020.sql
@application/pages/page_00030.sql
@application/pages/page_00032.sql
@application/pages/page_00040.sql
@application/pages/page_00050.sql
@application/pages/page_00060.sql
@application/pages/page_00065.sql
@application/pages/page_00070.sql
@application/pages/page_00074.sql
@application/pages/page_00075.sql
@application/pages/page_00080.sql
@application/pages/page_00090.sql
@application/pages/page_00099.sql
@application/pages/page_00101.sql
@application/deployment/definition.sql
@application/deployment/install.sql
@application/deployment/checks.sql
@application/deployment/buildoptions.sql
@application/end_environment.sql
