CREATE OR REPLACE FORCE EDITIONABLE VIEW "PIBICSDM2"."V_MBC_IP" ("IPADDRESS", "CHECKPOINTNO", "APPCD", "MAPPINGID", "ZONE", "ORGCD", "DEPTCD", "MODULECD", "DEPT_SEQNO", "PASSPROFILE", "CREATE_BY", "CREATE_DATE", "UPDATE_BY", "UPDATE_DATE", "VERSION", "ZONE_SEQNO", "REPSZONE_SEQNO", "FNZONE_SEQNO", "LAZONE_SEQNO", "QTM8ZONE_SEQNO", "QTM7ZONE_SEQNO", "QFN90ZONE_SEQNO", "INOUTZONE_SEQNO", "TERMINAL", "CARDTYPE") AS 
  SELECT 
    "IPADDRESS","CHECKPOINTNO","APPCD","MAPPINGID","ZONE","ORGCD","DEPTCD","MODULECD","DEPT_SEQNO","PASSPROFILE","CREATE_BY","CREATE_DATE","UPDATE_BY","UPDATE_DATE","VERSION","ZONE_SEQNO","REPSZONE_SEQNO","FNZONE_SEQNO","LAZONE_SEQNO","QTM8ZONE_SEQNO","QTM7ZONE_SEQNO","QFN90ZONE_SEQNO","INOUTZONE_SEQNO","TERMINAL","CARDTYPE"
FROM 
    MAPPINGIP
WHERE
    MBC_FLAG = 'Y' or IPADDRESS like '192.169.254%';
