CREATE OR REPLACE FORCE EDITIONABLE VIEW "PIBICSDM2"."VWOTCOUNTLEVEL_HRPROFILE" ("NUMPOSITION") AS 
  SELECT   COUNT (LEVEL_SEQNO) NUMPOSITION
     FROM   HR_PROFILE
    WHERE   LEVEL_SEQNO IN (SELECT   POSLEVEL_SEQNO FROM OT_RATE) ;
