prompt --application/user_interfaces
begin
wwv_flow_api.create_user_interface(
 p_id=>wwv_flow_api.id(45965479290928181)
,p_ui_type_name=>'DESKTOP'
,p_display_name=>'Desktop'
,p_display_seq=>10
,p_use_auto_detect=>false
,p_is_default=>true
,p_theme_id=>42
,p_home_url=>'f?p=&APP_ID.:1:&SESSION.'
,p_login_url=>'f?p=GLOBAL_DIALOGS:LOGIN_DESKTOP:&SESSION.::NO:RP,111:P111_REFERING_APP:&APP_ID.'
,p_theme_style_by_user_pref=>false
,p_navigation_list_id=>wwv_flow_api.id(45913306685927841)
,p_navigation_list_position=>'SIDE'
,p_navigation_list_template_id=>wwv_flow_api.id(45952642851928062)
,p_nav_list_template_options=>'#DEFAULT#'
,p_css_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'#WORKSPACE_IMAGES#roboto.css',
'#WORKSPACE_IMAGES#vita_style_fixes.css'))
,p_javascript_file_urls=>wwv_flow_string.join(wwv_flow_t_varchar2(
'#WORKSPACE_IMAGES#shortcut.js',
'#WORKSPACE_IMAGES#GenericFunctions.js',
'#APP_IMAGES#blacklist_light.js',
'https://localhost:2013/js/Dermalog.Plugins.js',
'#WORKSPACE_IMAGES#nav_logo.js'))
,p_nav_bar_type=>'LIST'
,p_nav_bar_list_id=>wwv_flow_api.id(45965395992928178)
,p_nav_bar_list_template_id=>wwv_flow_api.id(67816886034506971)
,p_nav_bar_template_options=>'#DEFAULT#'
);
end;
/
