CREATE OR REPLACE FORCE EDITIONABLE VIEW "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" ("DISPLAY_VALUE", "RETURN_VALUE", "ADM_CLASS_DISTRICT") AS 
  SELECT "DISPLAY_VALUE","RETURN_VALUE","ADM_CLASS_DISTRICT" FROM dl_bordercontrol.lov_adm_class_subdistrict;
   COMMENT ON TABLE "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT"  IS 'LoV Available subdistricts from dl_bordercontrol';
  GRANT SELECT ON "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" TO "BIO_BD";
  GRANT DELETE ON "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" TO "DERMALOG_PROXY";
  GRANT INSERT ON "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" TO "DERMALOG_PROXY";
  GRANT SELECT ON "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" TO "DERMALOG_PROXY";
  GRANT UPDATE ON "DL_BLACKLIST"."LOV_ADM_CLASS_SUBDISTRICT" TO "DERMALOG_PROXY";
