CREATE TABLE "DL_BLACKLIST"."BLACKLIST_CASE_IDENTITIES2BK" 
   (	"ID" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"BLACKLIST_CASE" VARCHAR2(32 CHAR) NOT NULL ENABLE, 
	"IDENTITY" VARCHAR2(32 CHAR) NOT NULL ENABLE
   ) ;
