CREATE TABLE "DL_BLACKLIST"."KEEP_BLACKLIST_DATA_BUFFER" 
   (	"CASE_NUMBER" VARCHAR2(100 CHAR), 
	"WLCD" VARCHAR2(7 CHAR), 
	"SEQNO" NUMBER(2,0), 
	"WLTFIRSTNM" VARCHAR2(60 CHAR), 
	"GIVENNAME_THAI" VARCHAR2(100 CHAR), 
	"CREDTE" DATE
   ) ;
  GRANT SELECT ON "DL_BLACKLIST"."KEEP_BLACKLIST_DATA_BUFFER" TO "APPSUP";
  GRANT SELECT ON "DL_BLACKLIST"."KEEP_BLACKLIST_DATA_BUFFER" TO "BIOAPPREPORT";
  GRANT SELECT ON "DL_BLACKLIST"."KEEP_BLACKLIST_DATA_BUFFER" TO "BIOSUPPORT";
