CREATE TABLE "SYSTEM"."LOGMNR_UID$" SHARING=METADATA 
   (	"LOGMNR_UID" NUMBER(22,0), 
	"LOGMNR_DID" NUMBER, 
	"LOGMNR_MDH" NUMBER, 
	"PDB_NAME" VARCHAR2(384), 
	"PDB_ID" NUMBER, 
	"PDB_UID" NUMBER, 
	"START_SCN" NUMBER, 
	"END_SCN" NUMBER, 
	"FLAGS" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(4000), 
	"SPARE4" TIMESTAMP (6)
   ) ;
  ALTER TABLE "SYSTEM"."LOGMNR_UID$" ADD CONSTRAINT "LOGMNR_UID$_PK" PRIMARY KEY ("LOGMNR_UID")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SYSTEM"."LOGMNR_UID$_PK" ON "SYSTEM"."LOGMNR_UID$" ("LOGMNR_UID") 
  ;
