CREATE TABLE "SYSTEM"."LOGMNR_PROPS$" SHARING=METADATA 
   (	"VALUE$" VARCHAR2(4000), 
	"COMMENT$" VARCHAR2(4000), 
	"NAME" VARCHAR2(384) NOT NULL ENABLE, 
	"LOGMNR_UID" NUMBER(22,0), 
	"LOGMNR_FLAGS" NUMBER(22,0)
   ) 
  PARTITION BY RANGE ("LOGMNR_UID") 
 (PARTITION "P_LESSTHAN100"  VALUES LESS THAN (100) ) ;
  ALTER TABLE "SYSTEM"."LOGMNR_PROPS$" ADD CONSTRAINT "LOGMNR_PROPS$_PK" PRIMARY KEY ("LOGMNR_UID", "NAME") DISABLE;
  CREATE INDEX "SYSTEM"."LOGMNR_I1PROPS$" ON "SYSTEM"."LOGMNR_PROPS$" ("LOGMNR_UID", "NAME") 
   LOCAL
 (PARTITION "P_LESSTHAN100" ) ;
