CREATE TABLE "SYSTEM"."LOGSTDBY$EVENTS" SHARING=METADATA 
   (	"EVENT_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"CURRENT_SCN" NUMBER, 
	"COMMIT_SCN" NUMBER, 
	"XIDUSN" NUMBER, 
	"XIDSLT" NUMBER, 
	"XIDSQN" NUMBER, 
	"ERRVAL" NUMBER, 
	"EVENT" VARCHAR2(2000), 
	"FULL_EVENT" CLOB, 
	"ERROR" VARCHAR2(2000), 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(2000), 
	"CON_NAME" VARCHAR2(30), 
	"CON_ID" NUMBER
   ) ;
  CREATE INDEX "SYSTEM"."LOGSTDBY$EVENTS_IND" ON "SYSTEM"."LOGSTDBY$EVENTS" ("EVENT_TIME") 
  ;
CREATE INDEX "SYSTEM"."LOGSTDBY$EVENTS_IND_SCN" ON "SYSTEM"."LOGSTDBY$EVENTS" ("COMMIT_SCN") 
  ;
CREATE INDEX "SYSTEM"."LOGSTDBY$EVENTS_IND_XID" ON "SYSTEM"."LOGSTDBY$EVENTS" ("XIDUSN", "XIDSLT", "XIDSQN") 
  ;
CREATE UNIQUE INDEX "SYSTEM"."SYS_IL0000015280C00009$$" ON "SYSTEM"."LOGSTDBY$EVENTS" (
  ;
