CREATE TABLE "SYSTEM"."LOGSTDBY$EDS_TABLES" SHARING=METADATA 
   (	"OWNER" VARCHAR2(128), 
	"TABLE_NAME" VARCHAR2(128), 
	"SHADOW_TABLE_NAME" VARCHAR2(128), 
	"BASE_TRIGGER_NAME" VARCHAR2(128), 
	"SHADOW_TRIGGER_NAME" VARCHAR2(128), 
	"DBLINK" VARCHAR2(255), 
	"FLAGS" NUMBER, 
	"STATE" VARCHAR2(255), 
	"OBJV" NUMBER, 
	"OBJ#" NUMBER, 
	"SOBJ#" NUMBER, 
	"CTIME" TIMESTAMP (6), 
	"SPARE1" NUMBER, 
	"SPARE2" VARCHAR2(255), 
	"SPARE3" NUMBER, 
	"MVIEW_NAME" VARCHAR2(128), 
	"MVIEW_LOG_NAME" VARCHAR2(128), 
	"MVIEW_TRIGGER_NAME" VARCHAR2(128)
   ) ;
  ALTER TABLE "SYSTEM"."LOGSTDBY$EDS_TABLES" ADD CONSTRAINT "LOGSTDBY$EDS_TABLES_PKEY" PRIMARY KEY ("OWNER", "TABLE_NAME")
  USING INDEX  ENABLE;
  CREATE UNIQUE INDEX "SYSTEM"."LOGSTDBY$EDS_TABLES_PKEY" ON "SYSTEM"."LOGSTDBY$EDS_TABLES" ("OWNER", "TABLE_NAME") 
  ;
