CREATE TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT" SHARING=METADATA 
   (	"RUNID#" NUMBER NOT NULL ENABLE, 
	"OUTPUT_TYPE" NUMBER NOT NULL ENABLE, 
	"RANK#" NUMBER, 
	"ACTION_TYPE" VARCHAR2(6), 
	"SUMMARY_OWNER" VARCHAR2(128), 
	"SUMMARY_NAME" VARCHAR2(128), 
	"GROUP_BY_COLUMNS" VARCHAR2(2000), 
	"WHERE_CLAUSE" VARCHAR2(2000), 
	"FROM_CLAUSE" VARCHAR2(2000), 
	"MEASURES_LIST" VARCHAR2(2000), 
	"FACT_TABLES" VARCHAR2(1000), 
	"GROUPING_LEVELS" VARCHAR2(2000), 
	"QUERYLEN" NUMBER, 
	"QUERY_TEXT" LONG, 
	"STORAGE_IN_BYTES" NUMBER, 
	"PCT_PERFORMANCE_GAIN" NUMBER, 
	"FREQUENCY" NUMBER, 
	"CUMULATIVE_BENEFIT" NUMBER, 
	"BENEFIT_TO_COST_RATIO" NUMBER NOT NULL ENABLE, 
	"VALIDATED" NUMBER
   ) ;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT" ADD CONSTRAINT "MVIEW$_ADV_OUTPUT_PK" PRIMARY KEY ("RUNID#", "RANK#")
  USING INDEX  ENABLE;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT" ADD CONSTRAINT "MVIEW$_ADV_OUTPUT_FK" FOREIGN KEY ("RUNID#")
	  REFERENCES "SYSTEM"."MVIEW$_ADV_LOG" ("RUNID#") ENABLE;
   COMMENT ON TABLE "SYSTEM"."MVIEW$_ADV_OUTPUT"  IS 'Output table for summary recommendations and evaluations';
  CREATE UNIQUE INDEX "SYSTEM"."MVIEW$_ADV_OUTPUT_PK" ON "SYSTEM"."MVIEW$_ADV_OUTPUT" ("RUNID#", "RANK#") 
  ;
