CREATE TABLE "SYSTEM"."MVIEW$_ADV_GC" SHARING=METADATA 
   (	"GCID#" NUMBER NOT NULL ENABLE, 
	"FJGID#" NUMBER NOT NULL ENABLE, 
	"GCDESLEN" NUMBER NOT NULL ENABLE, 
	"GCDES" LONG RAW NOT NULL ENABLE, 
	"HASHVALUE" NUMBER NOT NULL ENABLE, 
	"FREQUENCY" NUMBER
   ) ;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_GC" ADD CONSTRAINT "MVIEW$_ADV_GC_PK" PRIMARY KEY ("GCID#")
  USING INDEX  ENABLE;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_GC" ADD CONSTRAINT "MVIEW$_ADV_GC_FK" FOREIGN KEY ("FJGID#")
	  REFERENCES "SYSTEM"."MVIEW$_ADV_FJG" ("FJGID#") ENABLE;
   COMMENT ON TABLE "SYSTEM"."MVIEW$_ADV_GC"  IS 'Group-by columns of a query';
  CREATE UNIQUE INDEX "SYSTEM"."MVIEW$_ADV_GC_PK" ON "SYSTEM"."MVIEW$_ADV_GC" ("GCID#") 
  ;
