CREATE TABLE "SYSTEM"."MVIEW$_ADV_PARAMETERS" SHARING=METADATA 
   (	"PARAMETER_NAME" VARCHAR2(128), 
	"PARAMETER_TYPE" NUMBER NOT NULL ENABLE, 
	"STRING_VALUE" VARCHAR2(30), 
	"DATE_VALUE" DATE, 
	"NUMERICAL_VALUE" NUMBER
   ) ;
  ALTER TABLE "SYSTEM"."MVIEW$_ADV_PARAMETERS" ADD CONSTRAINT "MVIEW$_ADV_PARAMETERS_PK" PRIMARY KEY ("PARAMETER_NAME")
  USING INDEX  ENABLE;
   COMMENT ON TABLE "SYSTEM"."MVIEW$_ADV_PARAMETERS"  IS 'Summary advisor tuning parameters';
  CREATE UNIQUE INDEX "SYSTEM"."MVIEW$_ADV_PARAMETERS_PK" ON "SYSTEM"."MVIEW$_ADV_PARAMETERS" ("PARAMETER_NAME") 
  ;
