CREATE TABLE "SYSTEM"."ROLLING$PARAMETERS" SHARING=METADATA 
   (	"SCOPE" NUMBER, 
	"NAME" VARCHAR2(32), 
	"ID" NUMBER, 
	"DESCRIP" VARCHAR2(256), 
	"TYPE" NUMBER, 
	"DATATYPE" NUMBER, 
	"ATTRIBUTES" NUMBER, 
	"CURVAL" VARCHAR2(1024), 
	"LSTVAL" VARCHAR2(1024), 
	"DEFVAL" VARCHAR2(1024), 
	"MINVAL" NUMBER, 
	"MAXVAL" NUMBER, 
	"SPARE1" NUMBER, 
	"SPARE2" NUMBER, 
	"SPARE3" VARCHAR2(128)
   ) ;
